### ISSUE TITLE
Support for Games with Continuous Action-Spaces

### ISSUE THREAD

**Issue by heidekrueger** [deepmind/open_spiel#10]
Thanks for open sourcing open_spiel. I love the aim for completeness in this space!

One thing that I noticed is missing is games with continuous action-spaces and related algorithms (such as Deterministic Policy Gradient). Are there any plans to add support for those?

I'm especially interested in MARL and equilibrium learning in auction games.
As an example, I looked at the included implementation of the discretized first-price sealed-bid auction with integer valuations and actions. On the one hand, continuous-actions are necessary when studying emergent MARL-behavior: While a discrete implementation is pretty straight-forward for symmetric-uniform valuation-distributions, it become a lot less meaningful in settings with asymmetric or non-uniform (e.g. Gaussian) priors, where equilibria are nonlinear.
On the other hand, more involved auction games, that are being studied in economics, simply become all but intractable in a discrete implementation: Take, e.g. combinatorial FPSB auctions, where bundles of multiple items are sold to bidders at the same time. Even in a continuous-action implementation, the representation size of the action space already grows exponentially in the number of items; but in a discrete implementation it grows double-exponentially.

I'm sure there's many other use cases, e.g. in optimal control.

**Comment by locked-deepmind** [comment]
Thanks for the suggestion! I think continuous action-space games would be a great addition, but we don't have immediate plans to that ourselves. If you are interested in doing it, I'd be very happy to discuss the API design with you.

**Comment by lihuiknight** [comment]
I agree with @heidekrueger . I think many applications in real-world contains continuous action space. It's also an important research area in multi-agent reinforcement learning.

**Comment by lanctot** [comment]
I agree continuous actions would be great to support. But this issur has remained open for a long time without activity so I will close it for now and we can reopen if we want to discuss further.
