### ISSUE TITLE
[RNaD] Not using activation function in one layer in the network

### ISSUE THREAD

**Issue by kubicon** [deepmind/open_spiel#1002]
Hi, I am working with RNaD  and I noticed that when the network is constructed, the torso uses MLP from haiku. From the [Haiku MLP implementation](https://github.com/deepmind/dm-haiku/blob/main/haiku/_src/nets/mlp.py#L38#L168)) it can be seen that the last layer of the MLP does not use activation function as default (`activate_final: bool = False`). Is this somehow intended in RNaD not to use activation on the last torso layer? It should not really matter if the activation function is used there or not, but it is not standard to have some middle hidden layer without activation.

I am attaching the [RNaD part](https://github.com/deepmind/open_spiel/blob/39f77e3748d42113a609ffaf6b8bc878c4ef783a/open_spiel/python/algorithms/rnad/rnad.py#L739) which corresponds to this issue.

     def network(env_step: EnvStep) -> Tuple[chex.Array, chex.Array, chex.Array, chex.Array]:
        mlp_torso = hk.nets.MLP(self.config.policy_network_layers)
        torso = mlp_torso(env_step.obs)
        mlp_policy_head = hk.nets.MLP([self._game.num_distinct_actions()])
        logit = mlp_policy_head(torso)
        mlp_policy_value = hk.nets.MLP([1])
        v = mlp_policy_value(torso)

Thank you in advance for answer

**Comment by lanctot** [comment]
@perolat , any idea?  (Maybe this is normal, like MLPs that estimate values?)

**Comment by baskuit** [comment]
typically state values are bounded [-1, 1] or [0, 1]. With R-NaD, the reward shaping means that values no longer have that guarantee, even though our original game does. I believe this is the reason for no tanh or sigmoid activation

**Comment by perolat** [comment]
Thanks for spotting this! This is indeed a mistake.
