### ISSUE TITLE
Is there a built in Open spiel expected value calculation?

### ISSUE THREAD

**Issue by Henry-E** [deepmind/open_spiel#1003]
Just wondering if there was any built in way to calculate the expected value of a game to particular agent playing it, given a trained policy. I know it's relatively trivial to just iterate through all of the chance + actions nodes, multiply the probabilities and the payoffs at the end and then sum across all starting actions but I thought maybe there might be some built in way to do this kind of calculation or some similar calculation? I had a look around policy.py but couldn't see anything that might fit the bill.

**Comment by kubicon** [comment]
I think you are looking for [expected_returns.h](https://github.com/deepmind/open_spiel/blob/39f77e3748d42113a609ffaf6b8bc878c4ef783a/open_spiel/algorithms/expected_returns.h#L44) in C++ or [expected_game_score.py](https://github.com/deepmind/open_spiel/blob/39f77e3748d42113a609ffaf6b8bc878c4ef783a/open_spiel/python/algorithms/expected_game_score.py#L35) for Python

**Comment by Henry-E** [comment]
Cool, that definitely looks like it. Thanks!
