### ISSUE TITLE
RNAD with LSTM

### ISSUE THREAD

**Issue by spktrm** [deepmind/open_spiel#1023]
Since an LSTM executes sequentially over time steps, how does the mixed hidden state affect the learning step where the learner takes a mixed sequence of player observations?

**Comment by lanctot** [comment]
@perolat, do you want to weigh in?

(my understanding was that there was no LSTM used in R-NaD.. in the original paper nor in this implementation)

**Comment by perolat** [comment]
Hi,
We indeed didn't use any LSTM in the R-NaD work.

**Comment by lanctot** [comment]
I think the answer to the original question would be in a way that is analogous to how LSTMs are implemented in other RL methods like IMPALA? @spktrm do you have any reason to believe it would be any different?
