### ISSUE TITLE
Possible typo in Windows installation instructions

### ISSUE THREAD

**Issue by vladmashk** [deepmind/open_spiel#1028]
In line https://github.com/deepmind/open_spiel/blob/master/docs/windows.md?plain=1#L177,
is `ddd` supposed to be `add`?

**Comment by lanctot** [comment]
Yes, good spot! Can you submit a PR fix? If not we will fix it in the next update

**Comment by lanctot** [comment]
Fixed by https://github.com/deepmind/open_spiel/pull/1029. Thanks!
