### ISSUE TITLE
 Instantiate Tiny Hanabi with different parameters

### ISSUE THREAD

**Issue by RevanMacQueen** [deepmind/open_spiel#1037]
Hello,

I'd like to instantiate tiny hanabi with different parameters (i.e. num_players, num_actions, num_chance). My first question is what do each of these parameters represent? Is this in a paper somewhere?

Second, when I use `g = pyspiel.load_game('tiny_hanabi',  {"num_players": 3 })` I get an error: 

`SpielError: payoff_.size() == expected_payoff_size 
payoff_.size() = 36, expected_payoff_size = 216`

It seems like I need to specify a payoff string of appropriate size. I'm wondering how to specify this string if I want to play around with the parameters I mentioned above. 

Thanks in advance :)

**Comment by lanctot** [comment]
Normally the parameters are explained in the header of the implementation. In this case, here:

https://github.com/deepmind/open_spiel/blob/master/open_spiel/games/tiny_hanabi.h

I've noticed this one does not have it though (but it does link the paper it's taken from), so you have to look into the source:

https://github.com/deepmind/open_spiel/blob/master/open_spiel/games/tiny_hanabi.cc

The default string is on line 28, and the default values are in the game type (lines 70 - 73). So if you instantiate tiny_hanabi with no parameters, it will use this default game. 

I'm not 100% sure but I believe from the code if you want to use a different one, then you have to specify all the parameters (num_players, num_chance, num_actions, and payoff) for the game to make sense. @elkhrt can you confirm?
