### ISSUE TITLE
ModuleNotFoundError: No module named 'open_spiel.python'

### ISSUE THREAD

**Issue by glgjss960** [deepmind/open_spiel#1045]
Hi,@lanctot ,When I execute rnad.py in Unbuntu20.04,I meet the Error:

(rnad) jzx@DESKTOP-Q3HNUP9:~$ python rnad.py
Traceback (most recent call last):
  File "rnad.py", line 29, in <module>
    from open_spiel.python import policy as policy_lib
ModuleNotFoundError: No module named 'open_spiel.python'

I just installed open_spiel and set PYTHONPATH as OPTIN2 under wsl.I wonder what's the problem??

**Comment by lanctot** [comment]
Can you confirm that pyspiel built properly? E.g. what are the contents of the `build/python`

Also can you give the output of:
```
echo $PYTHONPATH
```

**Comment by glgjss960** [comment]
Thanks for your help.
Now I can run rnad.py without error afer I executed pip install open_spiel and successfully installed open-spiel1.2. in home\jzx\anaconda3\envs\rnad\lib\python3.8\site-packages
I think pyspiel is built,
for there is a pyspiel.io in my build/python.
and output of echo $PYTHONPATH is :/home/jzx/open_spiel:/home/jzx/open_spiel/build/python in my conda env.
However,when I run rnad_test.py,there is an error:
(rnad) jzx@DESKTOP-Q3HNUP9:~$ python rnad.py
(rnad) jzx@DESKTOP-Q3HNUP9:~$ python rnad_test.py
Traceback (most recent call last):
  File "rnad_test.py", line 22, in <module>
    from open_spiel.python.algorithms.rnad import rnad
ModuleNotFoundError: No module named 'open_spiel.python.algorithms.rnad'
I checked open_spiel in home\jzx\anaconda3\envs\rnad\lib\python3.8\site-packages and I found that 
there was no rnad.py in open_spiel\python\algorithms,which I thought had led to the import failure.
I can't understand the error,it's bit of strange,how could rnad.py required not in open_spiel?

**Comment by glgjss960** [comment]
root@DESKTOP-Q3HNUP9:/home/jzx# echo $PYTHONPATH
:/home/jzx/anaconda3/envs/rnad/lib/python3.8/site-packages:
/home/jzx/open_spiel:
/home/jzx/open_spiel/build/python

**Comment by lanctot** [comment]
Oh you are using conda.. we have never tested OpenSpiel within Conda. Why not install directly as stated in the instructions?

What is the output of:
```
ls -l /home/jzx/open_spiel/build/python
```

**Comment by glgjss960** [comment]
(rnad) jzx@DESKTOP-Q3HNUP9:~$ ls -l /home/jzx/open_spiel/build/python
total 12876
drwxrwxr-x 3 jzx jzx     4096 Mar 23 16:19 CMakeFiles
-rw-rw-r-- 1 jzx jzx    37874 Mar 23 16:19 CTestTestfile.cmake
-rw-rw-r-- 1 jzx jzx    31021 Mar 23 16:19 Makefile
-rw-rw-r-- 1 jzx jzx     1252 Mar 23 16:19 cmake_install.cmake
-rwxrwxr-x 1 jzx jzx 13100328 Mar 23 16:28 pyspiel.so

**Comment by lanctot** [comment]
Yeah, I don't understand because you have all the correct paths and in the PYTHONPATH, as far as I can trll it sould be working..

**Comment by glgjss960** [comment]
Oh right,I can surely run rnad.py without error now.

But when I tried rnad_test.py:

(rnad) jzx@DESKTOP-Q3HNUP9:$ python rnad.py
(rnad) jzx@DESKTOP-Q3HNUP9:$ python rnad_test.py
Traceback (most recent call last):
File "rnad_test.py", line 22, in
from open_spiel.python.algorithms.rnad import rnad
ModuleNotFoundError: No module named 'open_spiel.python.algorithms.rnad'

I checked open_spiel in home\jzx\anaconda3\envs\rnad\lib\python3.8\site-packages and I found that
there was no rnad.py in open_spiel\python\algorithms,I wonder if I failed to pip install open_spiel1.2 correctly?

**Comment by glgjss960** [comment]
Hi,@lanctot.
I think I can deal with this error.
I can excute rnad_test.py smoothly now.
There are still some errors then:

(rnad) jzx@DESKTOP-Q3HNUP9:~$ python rnad_test.py
Running tests under Python 3.8.16: /home/jzx/anaconda3/envs/rnad/bin/python
[ RUN      ] RNADTest.test_run_kuhn
I0326 18:37:26.929167 140011520037248 xla_bridge.py:166] Remote TPU is not linked into jax; skipping remote TPU.
I0326 18:37:26.929352 140011520037248 xla_bridge.py:413] Unable to initialize backend 'tpu_driver': Could not initialize backend 'tpu_driver'
I0326 18:37:26.929512 140011520037248 xla_bridge.py:413] Unable to initialize backend 'cuda': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
I0326 18:37:26.929599 140011520037248 xla_bridge.py:413] Unable to initialize backend 'rocm': module 'jaxlib.xla_extension' has no attribute 'GpuAllocatorConfig'
I0326 18:37:26.934912 140011520037248 xla_bridge.py:413] Unable to initialize backend 'tpu': INVALID_ARGUMENT: TpuPlatform is not available.
I0326 18:37:26.935119 140011520037248 xla_bridge.py:413] Unable to initialize backend 'plugin': xla_extension has no attributes named get_plugin_device_client. Compile TensorFlow with //tensorflow/compiler/xla/python:enable_plugin_device set to true (defaults to false) to enable this.
W0326 18:37:26.935262 140011520037248 xla_bridge.py:420] No GPU/TPU found, falling back to CPU. (Set TF_CPP_MIN_LOG_LEVEL=0 and rerun for more info.)
/home/jzx/anaconda3/envs/rnad/lib/python3.8/site-packages/haiku/_src/base.py:515: UserWarning: Explicitly requested dtype float64 requested in zeros is not available, and will be truncated to dtype float32. To enable more dtypes, set the jax_enable_x64 configuration option or the JAX_ENABLE_X64 shell environment variable. See https://github.com/google/jax#current-gotchas for more.
  param = init(shape, dtype)
[       OK ] RNADTest.test_run_kuhn
[ RUN      ] RNADTest.test_serialization
[       OK ] RNADTest.test_serialization
----------------------------------------------------------------------
Ran 2 tests in 8.853s

OK

I wonder what does the information mean?What's should the output be like if the rnad_test.py run properly?

**Comment by lanctot** [comment]
Yes, this is correct because of the `[OK]` next to each test. Happy that you were able to get it to work!
