### ISSUE TITLE
[RNaD] a questions of the performance

### ISSUE THREAD

**Issue by Nineyears-task** [deepmind/open_spiel#1048]
Hello, I am currently learning RNaD. I noticed that in Figure 3 of [Perolat et al., 2021], the x-axis is labeled as "iterations", while in the rnad_nashconv_leduc.png provided by RNaD, the x-axis is labeled as "learner_step". After converting the provided RNaD code to plot against "episode" as the x-axis, I found that the algorithm plateaus at around 0.56 after about 7 million episodes, which is still a considerable distance from the result of 0.02 reported in Figure 4 of [Perolat et al., 2021] for NeuRD, the base version of RNaD. Does this suggest that RNaD requires more samples to converge?

Thank you in advance for answer

![image](https://user-images.githubusercontent.com/62831153/229341748-c8690b51-4cf3-4e0c-bc90-5235630aff1b.png)

![image](https://user-images.githubusercontent.com/62831153/229341983-3024f842-a557-4a48-987f-276437e583f6.png)

Perolat, Julien, et al. (2021) "From Poincaré recurrence to convergence in imperfect information games: Finding equilibrium via regularization." *International Conference on Machine Learning*.

**Comment by lanctot** [comment]
Hmm.. @perolat, any ideas?

**Comment by perolat** [comment]
Hi,
The 2021 result is not the same algorithm (it uses a different critic based on a Q-function). That may explain the difference.
