### ISSUE TITLE
issue when installing in windows

### ISSUE THREAD

**Issue by Chersophyte** [deepmind/open_spiel#1059]
I have followed all steps in windows.md, and the cmake build successful, but when I build all, it meets a strange error in visual studio.
My os: windows 10, and I have set my python in env variales to 3.8, Visual studio 2022

The error occurs in the final step to build pyspiel.pyd:

[672/695] Linking CXX shared module python\pyspiel.pyd
   FAILED: python/pyspiel.pyd
   cmd.exe /C "cd . && "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" -E vs_link_dll --intdir=python \CMakeFiles\pyspiel.dir --rc=C:\PROGRA~2\WI3CF2~1\10\bin\100220~1.0\x64\rc.exe --mt=C:\PROGRA~2\WI3CF2~1\10 \bin\100220~1.0\x64\mt.exe --manifests -- C:\PROGRA~1\MICROS~2\2022\COMMUN~1\VC\Tools\MSVC\1435~1.322\bin\Hostx64\x64\ link.exe /nologo @CMakeFiles\pyspiel.rsp /out:python\pyspiel.pyd /implib:python\pyspiel.lib /pdb:python\pyspiel.pdb /dll /version:0.0 /machine:x64 /debug /INCREMENTAL && cmd.exe /C "cd /D D:\open_spiel\open_spiel\out\build\x64-Debug\python && C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -noprofile -executionpolicy Bypass -file C: /Users/11/vcpkg/scripts/buildsystems/msbuild/applocal.ps1 -targetBinary D:/open_spiel/open_spiel/out/build/x64-Debug/python/pyspiel.pyd -installedDir C:/Users/11/vcpkg/installed /x64-windows/debug/bin -OutVariable out""
   LINK Pass 1: command "C:\PROGRA~1\MICROS~2\2022\COMMUN~1\VC\Tools\MSVC\1435~1.322\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\pyspiel.rsp /out:python\pyspiel.pyd /implib:python\pyspiel.lib /pdb:python\pyspiel.pdb /dll /version:0.0 /machine:x64 /debug /INCREMENTAL /MANIFEST /MANIFESTFILE:python\CMakeFiles\pyspiel.dir /intermediate.manifest python\CMakeFiles\pyspiel.dir/manifest.res" failed (exit code 1120) with the following output:
     Creating library python\pyspiel.lib and object python\pyspiel.exp
D:\open_spiel\open_spiel\out\build\x64-Debug\bots.cc.obj : error LNK2019: unresolved external symbol "class std::unique_ptr<class open_spiel::Bot,struct std::default_delete<class open_spiel ::Bot> > __cdecl open_spiel::uci::MakeUCIBot(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,int,bool,class std: :map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char>>,class std::basic_string<char,struct std::char_traits<char>,class std: :allocator<char> >, struct std::less<class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char> > >, class std::allocator<struct std: :pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class std::basic_string<char,struct std::char_traits<char>,class std ::allocator<char> > > > > const &)" (?MakeUCIBot@uci@open_spiel@@YA?AV?$unique_ptr@VBot@open_spiel@@U?$default_delete@VBot@open_spiel@@@std@@@ std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@4@H_NAEBV?$map@V?$basic_string@DU?$char_traits@D@std@@ V?$allocator@D@2@@std@@V12@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2 @V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V12@@std@@@2@ @4@@Z), the symbol is referenced in the function "void __cdecl open_spiel::init_pyspiel_bots(class pybind11::module_ &)" (?init_pyspiel_bots@open_spiel@@YAXAEAVmodule_@pybind11@@@Z)
  
D:\open_spiel\open_spiel\out\build\x64-Debug\python\pyspiel.pyd : fatal error LNK1120: 1 unresolved external command
  
   [673/695] Linking CXX executable game_transforms\misere_test.exe
   [674/695] Linking CXX executable game_transforms\add_noise_test.exe
   [675/695] Linking CXX executable game_transforms\efg_writer_test.exe
   [676/695] Linking CXX executable game_transforms\normal_form_extensive_game_test.exe
   [677/695] Linking CXX executable game_transforms\coop_to_1p_test.exe
   [678/695] Linking CXX executable game_transforms\start_at_test.exe
   [679/695] Linking CXX executable game_transforms\repeated_game_test.exe
   [680/695] Linking CXX executable game_transforms\zerosum_test.exe
   [681/695] Linking CXX executable utils\circular_buffer_test.exe
   [682/695] Linking CXX executable utils\data_logger_test.exe
   [683/695] Linking CXX executable utils\combinatorics_test.exe
   [684/695] Linking CXX executable utils\file_test.exe
   [685/695] Linking CXX executable utils\functional_test.exe
   ninja: build stopped: subcommand failed.

Why such a fatal error LNK1120: 1 unresolved external command happen? I have tried to solve this problem for more than two days, if anyone can help me, I will thank you so much!!!

**Comment by Chersophyte** [comment]
In the error log, it tells me:
Severity Code Description Item File Line Suppressed Status
error LNK2019 unresolved external symbol "class std::unique_ptr<class open_spiel::Bot,struct std::default_delete<class open_spiel::Bot> > __cdecl open_spiel::uci::MakeUCIBot(class std::basic_string<char, struct std::char_traits<char>, class std::allocator<char> > const &, int, bool, class std::map<class std::basic_string<char, struct std::char_traits<char>, class std ::allocator<char>>,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char>>,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std ::allocator<char> > const ,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > > > const &)" (?MakeUCIBot@uci@open_spiel@ @YA?AV?$unique_ptr@VBot@open_spiel@@U?$default_delete@VBot@open_spiel@@@std@@@std@@AEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator @D@2@@4@H_NAEBV?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@V12@U?$less@V? $basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits @D@std@@V?$allocator@D@2@@std@@V12@@std@@@2@@4@@Z), function "void __cdecl open_spiel::init_pyspiel_bots(class pybind11::module_ & )" (?init_pyspiel_bots@open_spiel@@YAXAEAVmodule_@pybind11@@@Z) referenced in D:\open_spiel\open_spiel\out\build\x64-Debug\open_spiel D:\open_spiel\open_spiel\out\build\x64 -Debug\bots.cc.obj 1

looks like some problems in bots.cc.obj when building the pyspiel.pyd

**Comment by lanctot** [comment]
Yep this seems to be linker error due to a missing function. Doesn't seem to happen on the Linux side. I _vaguely_ remember changing the signature of that function recently -- probably the cause. We'll look into it, thanks!

**Comment by lanctot** [comment]
Found the cause: https://github.com/deepmind/open_spiel/blob/4c96de2383cd7d93cef549e67ef8ab91707775b1/open_spiel/bots/CMakeLists.txt#L8

Yeah I had forgotten the UCI bot is not supported in Windows. But the python bindings are still trying to include it (because added it to them recently).

Quick and dirty solution, just comment out these two lines: https://github.com/deepmind/open_spiel/blob/4c96de2383cd7d93cef549e67ef8ab91707775b1/open_spiel/python/pybind11/bots.cc#L292

Longer, more elegant, solution -- feel free to submit a PR :) -- change those three lines to:

```
#ifndef _WIN32
  m.def("make_uci_bot", open_spiel::uci::MakeUCIBot, py::arg("bot_binary_path"),
      py::arg("move_time"), py::arg("ponder"), py::arg("options"),
      "Bot that can play chess using UCI chess engine.");
#endif 
```

**Comment by Chersophyte** [comment]
Oh thank you for your quick and efficient reply so much!!!! I have built successfully now on my windows.
I will submit a PR for this problem. Thank you again!
