### ISSUE TITLE
Slightly change the utilities of an implemented game

### ISSUE THREAD

**Issue by masoumian** [deepmind/open_spiel#1073]
Hello,

I was wondering about how I can change the final utilities of an implemented game. I mean is there any way to construct a new game that is completely identical to Kuhn poker for example, except in the utilities of one leaf?
How can I address that leaf and change its utilities?

I searched for it and
load_game(game_string: str, parameters: Dict[str, Any])
looks promising, but I did not end up with a solution.

Thanks a lot

**Comment by lanctot** [comment]
Hmm, there are several options, but the easiest would be to do something like the "add noise wrapper". 

See `open_spiel/game_transforms/add_noise.*`

This wrapper adds epsilon noise to the all leaves, but you can just change the implementation of the `Returns` function [here](https://github.com/deepmind/open_spiel/blob/db0f4a78b1fd0bee0263d46d62fb4d693897329e/open_spiel/game_transforms/add_noise.cc#L99) if you only want to change one specific leaf. 

The other options:

- Make a new game that subclasses Kuhn and overrides the Returns method
- If you're only looking at something of Kuhn size, then you can design the game in the .efg format ([here is the real game in .efg](https://github.com/deepmind/open_spiel/blob/master/open_spiel/games/efg/kuhn_poker.efg)), then you can construct the game you want via a string and load it via EFGGame (see `games/efg_game*`).

**Comment by masoumian** [comment]
Thanks for the fast reply (not like mine!)

**Comment by lanctot** [comment]
No problem! ;-)
