### ISSUE TITLE
Mean Episode Rewards Question

### ISSUE THREAD

**Issue by jamesdfrost** [deepmind/open_spiel#108]
I've got a question on the mean episode rewards returned whilst running the DQN algorithm (and probably other algorithms) when playing against random bots, e.g.:

[1000] Mean episode rewards [0.542 0.336]

As far as I can tell the DQN algorithm implements two agents, which play against each other, and then both agents are tested against the random bot. The first score above is the performance of agent1, whilst the second score is agent2.

I let this run for 400 episodes of Connect4 and got the following results:

Agent 1
--
Max : 0.986
Min : 0.542
Average : 0.8883675
StdDev : 0.0811125295114757

Agent 2
--
Max : 0.9
Min : 0.174
Average : 0.72085
StdDev : 0.110491594702945

There's quite a difference between these, and Agent 1 has a better score than Agent 2 in 95% of episodes.

Am I reading this right, and is this because Agent 1 is always playing first or is there another reason for this behavior?

**Comment by lanctot** [comment]
Hi @jamesdfrost , quick response (I will follow up when I have more time to thoroughly dig through the code)

You are almost surely right. I believe the agents will each hold a specific seat and Connect Four is a proven win for the first player hence unbalanced in that we can expect more first player wins in general
