### ISSUE TITLE
RNaD policy fine-tunning

### ISSUE THREAD

**Issue by sergiu-turlea** [deepmind/open_spiel#1084]
In the paper it's noted that there is a post-processing/fine-tunning aplied to the policy during learning and evaluation in order to remove small but non-zero probabilities assigned to blunder moves. This is also obvious from the code.

However, shouldn't this also be applied in the acting phase, before sampling, to ensure trajectories also don't contain these blunders?

**Comment by perolat** [comment]
Hi @sergiu-turlea,

Great question!

One does not necessarily need to act without blunders as long as one corrects for the discrepancy between the post-processed policy and the acting policy in the critic of the learning algorithm.

That is why we use a variant of v-trace in the critic of R-NaD.
