### ISSUE TITLE
The Observation String give more information than the Observation Tensor in Backgammon

### ISSUE THREAD

**Issue by mariohevia** [deepmind/open_spiel#1086]
The Observation string gives the dice values while the observation tensor does not. 

This is because the observation tensor uses a format defined in an early paper (1994) where the algorithm gets a board and assigns a probability of white or black winning. In that way the authors would choose a move that resulted in the higher probability of winning for the current player. 

I think this should be homogenised and the observation tensor should give the dice values as the last two values of the array. This are my arguments to implement this:

In a normal game of Backgammon a player (human/computer) would know what are the dice before selecting a move. This is true for at least one well known algorithm: the gnubg.

If an algorithm needs to decide what moves to do by itself (without knowing the legal moves) i.e. learn the rules of the game, this becomes impossible without the knowledge of the dice values.

Why give the dice in the last two values? This is the place where the snowie standard backgammon format puts the values of the dice. In the case of no dice being rolled, e.g. before a chance action, the value should be 0, 0 (as the snowie standard)

**Comment by lanctot** [comment]
Hi @mariohevia,

Good find. Yeah, that is totally an oversight. The observation tensor should absolutely include the current dice outcomes.. 100% :) 

I'm happy to put that at the end.

Have you done this already. If not, could I ask you to submit a PR?

**Comment by mariohevia** [comment]
Hi I have submitted a PR with the changes. I also have signed the CLA, but I don't see it updated, I don't know if I need to do another PR for it to update.

**Comment by mariohevia** [comment]
I managed to update the CLA checks with an empty commit.

**Comment by lanctot** [comment]
Great, thanks!
