### ISSUE TITLE
ctest error on #206

### ISSUE THREAD

**Issue by toxifly** [deepmind/open_spiel#1097]
I'm getting an erorr on one of the tests:

ctest --rerun-failed --output-on-failure
Test project /home/user/open_spiel/open_spiel/build
    Start 206: run_python_test
1/1 Test #206: run_python_test ..................***Failed    0.05 sec
sh: 1: -m: not found
Spiel Fatal Error: /home/user/open_spiel/open_spiel/utils/run_python_test.cc:35 CHECK_TRUE(RunPython(python_command, test_module, {"--return_value", "0"}))

0% tests passed, 1 tests failed out of 1

Total Test time (real) =   0.05 sec

The following tests FAILED:
        206 - run_python_test (Failed)
Errors while running CTest

My python version is Python 3.10.6

**Comment by lanctot** [comment]
That test often fails for various reasons. If it's the only test failing, it is fine -- nothing is wrong. Sometimes the python binary is not found or fails to run for reasons specific to the environment setup. We should probably remove this test.

**Comment by toxifly** [comment]
Yes, it was only that one that has failed.
