### ISSUE TITLE
Issue when restoring breakpoints with DQN using player_id=1

### ISSUE THREAD

**Issue by giogix2** [deepmind/open_spiel#1104]
Hi,

I created a DQN_Bot in my open_spiel fork. It wraps the TF implementation of open_spiel's [dqn](https://github.com/deepmind/open_spiel/blob/master/open_spiel/python/algorithms/dqn.py). Sometimes I have an issue when restoring breakpoints previously trained using [breakthrough_dqn.py](https://github.com/deepmind/open_spiel/blob/master/open_spiel/python/examples/breakthrough_dqn.py). More precisely, I get an error when creating a DQN object with player=1, and restoring the weights using the [restore](https://github.com/deepmind/open_spiel/blob/master/open_spiel/python/algorithms/dqn.py#L371) method. If I set player_id=0, it works fine. Quite interestingly, if I create two DQN objects one after the other with player id 0 and 1, I don't get errors.

Here's a snippet to reproduce the error:
* NOTE: the weigths were creating using [breakthrough_dqn.py](https://github.com/deepmind/open_spiel/blob/master/open_spiel/python/examples/breakthrough_dqn.py) with default parameters (board size: 5x5). I can share them if necessary.

```python
from open_spiel.python.algorithms.dqn import DQN

import tensorflow.compat.v1 as tf

def main():
    session = tf.Session()

    checkpoint_dir = 'data/breakthrough_weights/'

    info_state_size = 75
    num_actions = 300
    hidden_layer_sizes = [64, 64]
    hidden_layers_sizes = [int(l) for l in hidden_layer_sizes]
    replay_buffer_capacity = 100000
    batch_size = 32

    agent0 = DQN(session=session,
                player_id=1,
                state_representation_size=info_state_size,
                num_actions=num_actions,
                hidden_layers_sizes=hidden_layers_sizes,
                replay_buffer_capacity=replay_buffer_capacity,
                batch_size=batch_size)
    
    agent0.restore(checkpoint_dir)
    
if __name__ == "__main__":
    main()
```

The error seems to suggest that the restored weights do not comply with the model format, however it's strange considering that it works if I initially load the weights with player_id=0. Also, when saving the model, there is not difference between the model architecture between player_id=0 and player_id=1. I was wondering whether you've encountered this issue before.

Here's the error:
<details>
  <summary>Error</summary>

> WARNING:tensorflow:From /Users/giovanniortolani/projects/open_spiel_fork/open_spiel/venv/lib/python3.10/site-packages/tensorflow/python/compat/v2_compat.py:107: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
> Instructions for updating:
> non-resource variables are not supported in the long term
> 2023-08-06 19:03:05.518932: I tensorflow/compiler/mlir/mlir_graph_optimization_pass.cc:375] MLIR V1 optimization pass is not enabled
> 2023-08-06 19:03:05.540081: W tensorflow/core/framework/op_kernel.cc:1828] OP_REQUIRES failed at save_restore_v2_ops.cc:230 : NOT_FOUND: Key mlp/bias not found in checkpoint
> Traceback (most recent call last):
>   File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/venv/lib/python3.10/site-packages/tensorflow/python/client/session.py", line 1379, in _do_call
>     return fn(*args)
>   File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/venv/lib/python3.10/site-packages/tensorflow/python/client/session.py", line 1362, in _run_fn
>     return self._call_tf_sessionrun(options, feed_dict, fetch_list,
>   File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/venv/lib/python3.10/site-packages/tensorflow/python/client/session.py", line 1455, in _call_tf_sessionrun
>     return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
> tensorflow.python.framework.errors_impl.NotFoundError: Key mlp/bias not found in checkpoint
>          [[{{node save/RestoreV2}}]]
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/venv/lib/python3.10/site-packages/tensorflow/python/training/saver.py", line 1418, in restore
>     sess.run(self.saver_def.restore_op_name,
>   File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/venv/lib/python3.10/site-packages/tensorflow/python/client/session.py", line 969, in run
>     result = self._run(None, fetches, feed_dict, options_ptr,
>   File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/venv/lib/python3.10/site-packages/tensorflow/python/client/session.py", line 1192, in _run
>     results = self._do_run(handle, final_targets, final_fetches,
>   File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/venv/lib/python3.10/site-packages/tensorflow/python/client/session.py", line 1372, in _do_run
>     return self._do_call(_run_fn, feeds, fetches, targets, options,
>   File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/venv/lib/python3.10/site-packages/tensorflow/python/client/session.py", line 1398, in _do_call
>     raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter
> tensorflow.python.framework.errors_impl.NotFoundError: Graph execution error:
> 
> Detected at node 'save/RestoreV2' defined at (most recent call last):
>     File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/open_spiel/python/examples/breakthrough_restore_example.py", line 28, in <module>
>       main()
>     File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/open_spiel/python/examples/breakthrough_restore_example.py", line 17, in main
>       agent0 = DQN(session=session,
>     File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/open_spiel/python/algorithms/dqn.py", line 147, in __init__
>       self._savers = [("q_network", tf.train.Saver(self._q_network.variables)),
> Node: 'save/RestoreV2'
> Key mlp/bias not found in checkpoint
>          [[{{node save/RestoreV2}}]]
> 
> Original stack trace for 'save/RestoreV2':
>   File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/open_spiel/python/examples/breakthrough_restore_example.py", line 28, in <module>
>     main()
>   File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/open_spiel/python/examples/breakthrough_restore_example.py", line 17, in main
>     agent0 = DQN(session=session,
>   File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/open_spiel/python/algorithms/dqn.py", line 147, in __init__
>     self._savers = [("q_network", tf.train.Saver(self._q_network.variables)),
>   File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/venv/lib/python3.10/site-packages/tensorflow/python/training/saver.py", line 934, in __init__
>     self.build()
>   File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/venv/lib/python3.10/site-packages/tensorflow/python/training/saver.py", line 946, in build
>     self._build(self._filename, build_save=True, build_restore=True)
>   File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/venv/lib/python3.10/site-packages/tensorflow/python/training/saver.py", line 974, in _build
>     self.saver_def = self._builder._build_internal(  # pylint: disable=protected-access
>   File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/venv/lib/python3.10/site-packages/tensorflow/python/training/saver.py", line 543, in _build_internal
>     restore_op = self._AddRestoreOps(filename_tensor, saveables,
>   File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/venv/lib/python3.10/site-packages/tensorflow/python/training/saver.py", line 360, in _AddRestoreOps
>     all_tensors = self.bulk_restore(filename_tensor, saveables, preferred_shard,
>   File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/venv/lib/python3.10/site-packages/tensorflow/python/training/saver.py", line 611, in bulk_restore
>     return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
>   File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/venv/lib/python3.10/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1517, in restore_v2
>     _, _, _op, _outputs = _op_def_library._apply_op_helper(
>   File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/venv/lib/python3.10/site-packages/tensorflow/python/framework/op_def_library.py", line 795, in _apply_op_helper
>     op = g._create_op_internal(op_type_name, inputs, dtypes=None,
>   File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/venv/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 3381, in _create_op_internal
>     ret = Operation.from_node_def(
> 
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/venv/lib/python3.10/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 66, in get_tensor
>     return CheckpointReader.CheckpointReader_GetTensor(
> RuntimeError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/venv/lib/python3.10/site-packages/tensorflow/python/training/saver.py", line 1429, in restore
>     names_to_keys = object_graph_key_mapping(save_path)
>   File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/venv/lib/python3.10/site-packages/tensorflow/python/training/saver.py", line 1751, in object_graph_key_mapping
>     object_graph_string = reader.get_tensor(trackable.OBJECT_GRAPH_PROTO_KEY)
>   File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/venv/lib/python3.10/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 71, in get_tensor
>     error_translator(e)
>   File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/venv/lib/python3.10/site-packages/tensorflow/python/training/py_checkpoint_reader.py", line 31, in error_translator
>     raise errors_impl.NotFoundError(None, None, error_message)
> tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/open_spiel/python/examples/breakthrough_restore_example.py", line 28, in <module>
>     main()
>   File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/open_spiel/python/examples/breakthrough_restore_example.py", line 25, in main
>     agent0.restore(checkpoint_dir)
>   File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/open_spiel/python/algorithms/dqn.py", line 383, in restore
>     saver.restore(self._session, full_checkpoint_dir)
>   File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/venv/lib/python3.10/site-packages/tensorflow/python/training/saver.py", line 1434, in restore
>     raise _wrap_restore_error_with_msg(
> tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:
> 
> Graph execution error:
> 
> Detected at node 'save/RestoreV2' defined at (most recent call last):
>     File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/open_spiel/python/examples/breakthrough_restore_example.py", line 28, in <module>
>       main()
>     File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/open_spiel/python/examples/breakthrough_restore_example.py", line 17, in main
>       agent0 = DQN(session=session,
>     File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/open_spiel/python/algorithms/dqn.py", line 147, in __init__
>       self._savers = [("q_network", tf.train.Saver(self._q_network.variables)),
> Node: 'save/RestoreV2'
> Key mlp/bias not found in checkpoint
>          [[{{node save/RestoreV2}}]]
> 
> Original stack trace for 'save/RestoreV2':
>   File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/open_spiel/python/examples/breakthrough_restore_example.py", line 28, in <module>
>     main()
>   File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/open_spiel/python/examples/breakthrough_restore_example.py", line 17, in main
>     agent0 = DQN(session=session,
>   File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/open_spiel/python/algorithms/dqn.py", line 147, in __init__
>     self._savers = [("q_network", tf.train.Saver(self._q_network.variables)),
>   File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/venv/lib/python3.10/site-packages/tensorflow/python/training/saver.py", line 934, in __init__
>     self.build()
>   File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/venv/lib/python3.10/site-packages/tensorflow/python/training/saver.py", line 946, in build
>     self._build(self._filename, build_save=True, build_restore=True)
>   File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/venv/lib/python3.10/site-packages/tensorflow/python/training/saver.py", line 974, in _build
>     self.saver_def = self._builder._build_internal(  # pylint: disable=protected-access
>   File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/venv/lib/python3.10/site-packages/tensorflow/python/training/saver.py", line 543, in _build_internal
>     restore_op = self._AddRestoreOps(filename_tensor, saveables,
>   File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/venv/lib/python3.10/site-packages/tensorflow/python/training/saver.py", line 360, in _AddRestoreOps
>     all_tensors = self.bulk_restore(filename_tensor, saveables, preferred_shard,
>   File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/venv/lib/python3.10/site-packages/tensorflow/python/training/saver.py", line 611, in bulk_restore
>     return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
>   File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/venv/lib/python3.10/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1517, in restore_v2
>     _, _, _op, _outputs = _op_def_library._apply_op_helper(
>   File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/venv/lib/python3.10/site-packages/tensorflow/python/framework/op_def_library.py", line 795, in _apply_op_helper
>     op = g._create_op_internal(op_type_name, inputs, dtypes=None,
>   File "/Users/giovanniortolani/projects/open_spiel_fork/open_spiel/venv/lib/python3.10/site-packages/tensorflow/python/framework/ops.py", line 3381, in _create_op_internal
>     ret = Operation.from_node_def(

</details>

**Comment by lanctot** [comment]
I suspect it's because the environment you are trying to load the agent back into does not match the one it was saved in.

E.g. when TF creates the DQN agent, it assigns variable names to the ops that are created. But there is a naming overlap when there are multiple agents so it puts each op into its own nested (auto generated?) variable scope.

If you do not reload it the exact way you saved it, the variable names don't match.

Just a theory.

Did you save that agent as part of a set of agents?

**Comment by giogix2** [comment]
> Did you save that agent as part of a set of agents?

Yes. I used the script [breakthrough_dqn.py](https://github.com/deepmind/open_spiel/blob/master/open_spiel/python/examples/breakthrough_dqn.py), which creates two agents, and saves the weights for the two models one after the other.
You're absolutely right. The two DQN agents share the same session (see [here](https://github.com/deepmind/open_spiel/blob/master/open_spiel/python/examples/breakthrough_dqn.py#L97)), and this is why the graphs op names get incrementally updated.

I was wondering if I should have invested time changing this behaviour, but it's actually expected, because it depends on how the script breakthrough_dqn.py is implemented. So as long as I structure my training script differently that's fine.

I think we can close this issue.
