### ISSUE TITLE
Any games or algorithms in open-spiel on cooperative MARL

### ISSUE THREAD

**Issue by lihuiknight** [deepmind/open_spiel#111]
Dear Authors,

Just want to ask whether there are some games and benchmark algorithms to support the research on  cooperative MARL.

Thanks.
Hui

**Comment by locked-deepmind** [comment]
We have both full-sized games and smaller games for research purposes. Of course, it's possible to use independent RL approaches (which are implemented), but we don't have any other algorithms implemented in OpenSpiel. What did you have in mind?

Full-size games:

- Hanabi (we wrap the Hanabi Learning Environment to conform to the OpenSpiel interface)
- Bridge uncontested bidding (a sub-game of contract bridge, used by experts for training / practice)

Small games:

- TinyHanabi - a variety of very small cooperative games; see paper reference in the source code
- TinyBridge2p - a tiny version of bridge uncontested bidding
- CoopBoxPushing
- MatrixCoordination

**Comment by lihuiknight** [comment]
In this paper [A Survey and Critique of Multiagent Deep Reinforcement Learning], there are many methods addressing MARL on cooperative games, however, there is no available open source codes. So it's very different to reproduce these algorithms for a fair comparison. Does you plan to implement some of them?

**Comment by lanctot** [comment]
We could certainly use more cooperative games. We don't have any planned at the moment, but this is why we released it open source: so anybody (such as yourself) can add games! So, I invite you to do add the ones you are most interested in and then everyone can benefit from it.

**Comment by lihuiknight** [comment]
That's great. I am very happy to merge my new algorithm into open spiel.  I think open spiel is very helpful and influential in MARL communities.
