### ISSUE TITLE
ValueError when training a2c agent for bridge environment

### ISSUE THREAD

**Issue by ai-gamer** [deepmind/open_spiel#127]
I am trying to train a2c agent for the full contract bridge environment by modifying breakthrough_dpn.py. While running, the following error happens:

  File "/Users/sunshuo/Desktop/open_spiel/open_spiel/python/algorithms/policy_gradient.py", line 261, in _act
    action = np.random.choice(len(probs), p=probs)
  File "mtrand.pyx", line 1144, in mtrand.RandomState.choice
ValueError: probabilities contain NaN

It happens when the policy_probs of all legal_actions is 0, which means sum(probs)=0
# 
    probs = np.zeros(self._num_actions)
    probs[legal_actions] = policy_probs[0][legal_actions]
    probs /= sum(probs)
    action = np.random.choice(len(probs), p=probs)
    return action, probs

print out:
legal_actions:
[52, 54]
probs[legal_actions]:
[0. 0.]
sum 0, Nan will happen
Actions 52,54 should correspond to PASS and REDOUBLE. I got exactly the same error in my own implementation. I am confused how the prediction value of neural networks could be exactly 0 (I assume it will be very tiny value but not 0). This error does not happen when I use DQN agent, the internal reason for this is not clear for me also.

**Comment by locked-deepmind** [comment]
I suspect the problem is that we are removing illegal actions after converting logits to probabilities. It would be more robust to do the illegal action removal first and then softmax the remaining logits. The DQN agent doesn't have this issue.

**Comment by ai-gamer** [comment]
Great! you are correct. It works after I do the illegal action removal first. Should I make a pull request to add this?

**Comment by locked-deepmind** [comment]
Good to hear. Yes, please do submit a PR - bug fixes are always welcome!

**Comment by ai-gamer** [comment]
Sorry, please ignore the PR. I get confused again. how can value after softmax be 0? The original implementation should work because the output of softmax should be always positive.

**Comment by locked-deepmind** [comment]
float32 has limited range. The smallest positive number it can represent is
about exp(-100). So any action with a raw logit at least 100 smaller than
the highest logit will get zero probability.

An alternative is just to not worry about this and use a uniform
distribution when all probabilities are zero. Getting all zeros should be a
rare occurrence which happens only at the start of training before the
network has learned which actions are legal.

**Comment by lanctot** [comment]
This has been recently fixed from this PR: https://github.com/deepmind/open_spiel/pull/128

Thanks @ai-gamer!
