### ISSUE TITLE
Unable to build and run test.(Solved)

### ISSUE THREAD

**Issue by Alioth10086** [deepmind/open_spiel#13]
The Problem is solved.Thanks to rejuvyesh.

(lost) hyh@amax2080-1:~/Downloads/open_spiel-master/build$ CXX=g++ cmake 
-DPython_TARGET_VERSION=3.6 -DCMAKE_CXX_COMPILER=${CXX} ../open_spiel
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/g++
-- Check for working CXX compiler: /usr/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:45 (add_subdirectory):
  add_subdirectory given source "abseil-cpp" which is not an existing
  directory.

-- Found Python3: /home/hyh/anaconda3/lib/libpython3.7m.so (found version "3.7.0") found components:  Development 
-- Configuring incomplete, errors occurred!
See also "/home/hyh/Downloads/open_spiel-master/build/CMakeFiles/CMakeOutput.log".

**Comment by rejuvyesh** [comment]
You need to run `./install.sh` first to get the dependencies.

**Comment by Alioth10086** [comment]
> 
> 
> You need to run `./install.sh` first to get the dependencies.

Thank you very much!
