### ISSUE TITLE
failed test in rl_environment_test.py

### ISSUE THREAD

**Issue by peter-de-boer** [deepmind/open_spiel#136]
Running python rl_environment_test.py (python/tests) shows a failed test:

```
[  FAILED  ] RLEnvironmentTest.test_set_and_get_state
[ RUN      ] RLEnvironmentTest.test_spec_fields
I0120 17:58:02.550096 139867464664896 rl_environment.py:164] Using game string: tic_tac_toe
[       OK ] RLEnvironmentTest.test_spec_fields
======================================================================
ERROR: test_set_and_get_state (__main__.RLEnvironmentTest)
test_set_and_get_state (__main__.RLEnvironmentTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "rl_environment_test.py", line 128, in test_set_and_get_state
    env_ttt1.set_state(env_ttt2.get_state)
  File "/home/peter/open_spiel/open_spiel/python/rl_environment.py", line 360, in set_state
    assert new_state.get_game() == self.game, (
AttributeError: 'pyspiel.State' object has no attribute 'get_game'
```

**Comment by locked-deepmind** [comment]
Thanks for the bug report. State.get_game() was added in:
https://github.com/deepmind/open_spiel/commit/3cc2713413b79591b790319e6464bff43c357428

Can you check that you have that version of the code (or later) and that
you've built the C++ library since?

**Comment by peter-de-boer** [comment]
Oh, this is embarrassing, I did not rebuild.  That happens if you usually only work with interpreted languages! Am rebuilding now, hitting other issues though.

**Comment by peter-de-boer** [comment]
Ok, test ran fine now. Thanks for the help, and sorry for the confusion.

**Comment by carlosgmartin** [comment]
@elkhrt I don't see `get_game` in the [docs](https://openspiel.readthedocs.io/en/latest/api_reference.html). Should it be?
