### ISSUE TITLE
unable to run install.sh [ubuntu 19.04]

### ISSUE THREAD

**Issue by vivienzou1** [deepmind/open_spiel#14]
while trying to run `install.sh`, errors pump up for some reason finally ends up manually install dependencies in that .sh file

env:
Ubuntu 19.04
python 3.6

error:
```
+ [[  == linux-gnu ]]
install.sh: 24: install.sh: [[: not found
+ [[  == darwin* ]]
install.sh: 30: install.sh: [[: not found
+ echo The OS '' is not supported (Only Linux and MacOS is).  Feel free to contribute the install for a new OS.
The OS '' is not supported (Only Linux and MacOS is).  Feel free to contribute the install for a new OS.
+ exit 1
```

**Comment by lanctot** [comment]
Hmm, that is odd. We have tested it on Ubuntu 19.04 and I just tested it again from a fresh checkout and it works fine.

I guess try running the commands in that script manually?

```
sudo apt-get update
sudo apt-get install git virtualenv cmake python3 python3-dev python3-pip python3-setuptools python3-wheel
git clone -b 'v2.2.4' --single-branch --depth 1 https://github.com/pybind/pybind11.git
git clone -b 'develop' --single-branch --depth 1 https://github.com/jblespiau/dds.git  open_spiel/games/bridge/double_dummy_solver
git clone -b 'master' --single-branch --depth 1 https://github.com/abseil/abseil-cpp.git open_spiel/abseil-cpp
```

**Comment by lanctot** [comment]
Can you also tell me what the output of the following commands are?

```
which \[
which test
```

**Comment by vivienzou1** [comment]
yup @lanctot, I ended up these commands manually, and then works...

**Comment by lanctot** [comment]
Ok, great but I'm still trying to figure out what the issue is/was in case others experience this. 

Seem like coreutils is installed correctly, so can you try a few more commands for me? (But are you sure that second one is not /usr/bin/test?)

```
ls -l /usr/bin/\[
ls -l /user/bin/test
```

**Comment by vivienzou1** [comment]
of course
```
$ ls -l /usr/bin/\[
> -rwxr-xr-x 1 root root 51384 Jan 18 2018 '/usr/bin/\['
$ ls -l /user/bin/test
> -rwxr-xr-x 1 root root 47288 Jan 18 2018 '/usr/bin/test'
```

**Comment by lanctot** [comment]
Hmm, ok I have no idea what could be the problem then. My guess is that the install.sh file got corrupted somehow. Glad it worked with the manual commands. Thanks!
