### ISSUE TITLE
Build issue: 'filesystem' file not found #include <filesystem>

### ISSUE THREAD

**Issue by davidcotton** [deepmind/open_spiel#142]
Hi,

Thanks for all the hard work developing & maintaining this great library. 

I'm having a bit trouble building the project with the latest commits. I'm running:
- Ubuntu 18.04
- Clang 9.0.0
- cmake 3.16.3

To reproduce, after following the installation instructions in the readme,  `./open_spiel/scripts/build_and_run_tests.sh` errors with 
```
...
[ 45%] Building CXX object games/CMakeFiles/bridge_double_dummy_solver.dir/bridge/double_dummy_solver/src/PlayAnalyser.cpp.o
/home/dave/projects/open_spiel/open_spiel/utils/file.cc:17:10: fatal error: 'filesystem' file not found
#include <filesystem>
         ^~~~~~~~~~~~
...
[ 48%] Building CXX object games/CMakeFiles/bridge_double_dummy_solver.dir/bridge/double_dummy_solver/src/TimerGroup.cpp.o
1 error generated.
utils/CMakeFiles/utils.dir/build.make:62: recipe for target 'utils/CMakeFiles/utils.dir/file.cc.o' failed
make[2]: *** [utils/CMakeFiles/utils.dir/file.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 48%] Building CXX object games/CMakeFiles/bridge_double_dummy_solver.dir/bridge/double_dummy_solver/src/TimerList.cpp.o
...
[ 63%] Built target games
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
```

I've narrowed the issue down to commit 71ded47c2866f5adfc6cb434ac675204f1372b05, the previous commit builds fine for me. 

From my Googling around I think it might be something to do with `filesystem` directive not being available but am unsure what my next steps are? 

Thanks in advance for any help,
Dave

**Comment by lanctot** [comment]
Hi @davidcotton ,

Yes I noticed this only last night after our update yesterday (our Travis CI setup is similar to yours, so our build is now failing).

Thanks for the detailed report. It's currently our highest priority and we will update github as soon as it's fixed. Will keep you posted.
