### ISSUE TITLE
Question about how to run nfsp?

### ISSUE THREAD

**Issue by wangzhuangcd** [deepmind/open_spiel#146]
I noticed that there is "See open_spiel/python/examples/nfsp.py for an usage example." in open_spiel/python/algorithms/nfsp.py. 
But I can't find this example.
Is there an example of using nfsp, or how can I quickly create one based on the existing content?

**Comment by lanctot** [comment]
Wow it is the second time in two days that examples that were there before suddenly vanished. 

We will catch this example thief and bring them to justice!

(I will look into it and follow-up.)

**Comment by lanctot** [comment]
Found it! https://github.com/deepmind/open_spiel/blob/master/open_spiel/python/examples/kuhn_nfsp.py

But we should indeed fix that comment to point to the correct file name :) So please leave this issue open, I will submit a fix to correct the comment and it will be closed when merged.

**Comment by wangzhuangcd** [comment]
@lanctot thanks~I found it. It was not stolen, just changed the name.
