### ISSUE TITLE
a problem about  CXX=clang++ cmake -DPython_TARGET_VERSION=3.6 -DCMAKE_CXX_COMPILER=${CXX} ../open_spiel

### ISSUE THREAD

**Issue by chenxli** [deepmind/open_spiel#153]
when I execute CXX=clang++ cmake -DPython_TARGET_VERSION=3.6 -DCMAKE_CXX_COMPILER=${CXX} ../open_spiel ,is it normal to print the following info?

I notice that   "CMake Error at games/CMakeLists.txt:112 (add_library):
  Cannot find source file:

    bridge/double_dummy_solver/include/dll.h
"
does it have an effect on the next step? how can I handle it?

BUILD_WITH_HANABI not set. Defaults to OFF
BUILD_WITH_HANABI: OFF 
BUILD_WITH_ACPC not set. Defaults to OFF
BUILD_WITH_ACPC: OFF 
BUILD_WITH_JULIA not set. Defaults to OFF
BUILD_WITH_JULIA: OFF 
-- Configuring done
You have changed variables that require your cache to be deleted.
Configure will be re-run and you may have to reset some variables.
The following variables have changed:
CMAKE_CXX_COMPILER= 
CMAKE_CXX_COMPILER= 

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is Clang 8.0.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/bin/clang++
-- Check for working CXX compiler: /usr/local/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
BUILD_WITH_HANABI: OFF 
BUILD_WITH_ACPC: OFF 
BUILD_WITH_JULIA: OFF 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found Python: /home/chenxli123/anaconda3/lib/libpython3.7m.so (found version "3.7.1") found components:  Development 
-- Configuring done
CMake Error at games/CMakeLists.txt:112 (add_library):
  Cannot find source file:

    bridge/double_dummy_solver/include/dll.h

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx

-- Generating done
-- Build files have been written to: /home/chenxli123/open_spiel/build

**Comment by lanctot** [comment]
Did you run `./install.sh` in the installation instructions? Seems like you're missing a dependency that should have been brought in by running that scripts.

**Comment by chenxli** [comment]
yes, and the results are these:
3-wheel'
++ which apt-get
+ APT_GET=/usr/bin/apt-get
+ '[' /usr/bin/apt-get = '' ']'
+ already_installed=0
+ /usr/bin/dpkg-query --show '--showformat=${db:Status-Status}\n' virtualenv clang cmake python3 python3-dev python3-pip python3-setuptools python3-wheel
installed
installed
installed
installed
installed
installed
installed
not-installed
+ '[' 0 -eq 0 ']'
+ echo -e '\e[33mSystem wide packages already installed, skipping their installation.\e[0m'
System wide packages already installed, skipping their installation.

and I don't know what is not installed。。。。

**Comment by lanctot** [comment]
`sudo apt-get install python3-wheel` 

And then try building again.

**Comment by chenxli** [comment]
I have tried, but the same. 
+ EXT_DEPS='virtualenv clang cmake python3 python3-dev python3-pip python3-setuptools python3-wheel'
++ which apt-get
+ APT_GET=/usr/bin/apt-get
+ '[' /usr/bin/apt-get = '' ']'
+ already_installed=0
+ /usr/bin/dpkg-query --show '--showformat=${db:Status-Status}\n' virtualenv clang cmake python3 python3-dev python3-pip python3-setuptools python3-wheel
installed
installed
installed
installed
installed
installed
installed
not-installed
+ '[' 0 -eq 0 ']'
+ echo -e '\e[33mSystem wide packages already installed, skipping their installation.\e[0m'
System wide packages already installed, skipping their installation.
+ [[ -n '' ]]

**Comment by lanctot** [comment]
Ok but did you try building again after running `./install.sh` ?

**Comment by chenxli** [comment]
well, do you means to execute this:
        ./build_and_run_tests.sh  # Run this every-time you need to rebuild. ??
I try it just now, but it seems still not work.

**Comment by lanctot** [comment]
I meant the command hat you posted at the tart of this thread. `./install.sh` should get the files that you are missing.

**Comment by lanctot** [comment]
Are the files actually there? Do you see a `double_dummy_solver` when you run `ls open_spiel/games/bridge` from the top-level directory?

**Comment by chenxli** [comment]
Yes,  double_dummy_solver  is there.
and now the info is showed as following, it seems normal?
>LER=${CXX} ../open_spiel
BUILD_WITH_HANABI not set. Defaults to OFF
BUILD_WITH_HANABI: OFF
BUILD_WITH_ACPC not set. Defaults to OFF
BUILD_WITH_ACPC: OFF
BUILD_WITH_JULIA not set. Defaults to OFF
BUILD_WITH_JULIA: OFF
-- Found Python3: /home/cxl/open_spiel/ven/bin/python3.7 (found version "3.7.1") found components:  Interpreter Development
-- Configuring done
You have changed variables that require your cache to be deleted.
Configure will be re-run and you may have to reset some variables.
The following variables have changed:
CMAKE_CXX_COMPILER=
CMAKE_CXX_COMPILER=

-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is Clang 8.0.1
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/local/bin/clang++
-- Check for working CXX compiler: /usr/local/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
BUILD_WITH_HANABI: OFF
BUILD_WITH_ACPC: OFF
BUILD_WITH_JULIA: OFF
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found Python: /home/cxl/anaconda3/lib/libpython3.7m.so (found version "3.7.1") found components:  Development
-- Configuring done
-- Generating done
-- Build files have been written to: /home/cxl/open_spiel/build

But then I execute the command: make -j$(nproc) , new problem appears..... I  notice that other people have met similar problem, and I see that you had added "#include <optional>" to the spiel.h and I  have also updated my clang to v8.0.1, but seems not work..

> In file included from /home/cxl/open_spiel/open_spiel/matrix_game.cc:15:
In file included from /home/cxl/open_spiel/open_spiel/../open_spiel/matrix_game.h:25:
In file included from /home/cxl/open_spiel/open_spiel/../open_spiel/normal_form_game.h:24:
In file included from /home/cxl/open_spiel/open_spiel/../open_spiel/simultaneous_move_game.h:22:
/home/cxl/open_spiel/open_spiel/../open_spiel/spiel.h:24:10: fatal error: 'optional' file
      not found
#include <optional>
         ^~~~~~~~~~
1 error generated.
CMakeFiles/open_spiel_core.dir/build.make:75: recipe for target 'CMakeFiles/open_spiel_core.dir/spiel.cc.o' failed
make[2]: *** [CMakeFiles/open_spiel_core.dir/spiel.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 36%] Linking CXX static library libabsl_flags.a
[ 36%] Built target absl_flags
Scanning dependencies of target absl_flags_usage_internal
[ 37%] Building CXX object abseil-cpp/absl/flags/CMakeFiles/absl_flags_usage_internal.dir/internal/usage.cc.o
1 error generated.
CMakeFiles/open_spiel_core.dir/build.make:127: recipe for target 'CMakeFiles/open_spiel_core.dir/simultaneous_move_game.cc.o' failed
make[2]: *** [CMakeFiles/open_spiel_core.dir/simultaneous_move_game.cc.o] Error 1
1 error generated.
CMakeFiles/open_spiel_core.dir/build.make:88: recipe for target 'CMakeFiles/open_spiel_core.dir/spiel_bots.cc.o' failed
make[2]: *** [CMakeFiles/open_spiel_core.dir/spiel_bots.cc.o] Error 1
1 error generated.
CMakeFiles/open_spiel_core.dir/build.make:153: recipe for target 'CMakeFiles/open_spiel_core.dir/tensor_game.cc.o' failed
make[2]: *** [CMakeFiles/open_spiel_core.dir/tensor_game.cc.o] Error 1
1 error generated.
CMakeFiles/open_spiel_core.dir/build.make:114: recipe for target 'CMakeFiles/open_spiel_core.dir/policy.cc.o' failed
make[2]: *** [CMakeFiles/open_spiel_core.dir/policy.cc.o] Error 1
1 error generated.
CMakeFiles/open_spiel_core.dir/build.make:101: recipe for target 'CMakeFiles/open_spiel_core.dir/matrix_game.cc.o' failed
make[2]: *** [CMakeFiles/open_spiel_core.dir/matrix_game.cc.o] Error 1
CMakeFiles/Makefile2:72: recipe for target 'CMakeFiles/open_spiel_core.dir/all' failed
make[1]: *** [CMakeFiles/open_spiel_core.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 37%] Linking CXX static library libabsl_flags_usage_internal.a
[ 37%] Built target absl_flags_usage_internal
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by lanctot** [comment]
What is the output of the following commands:

```
which clang++
clang++ --version
```

My guess is the older version of clang is the one still being found in your PATH.

**Comment by chenxli** [comment]
>(ven) cxl@ccnt-lab:~/open_spiel/open_spiel$ which clang++
/usr/local/bin/clang++
(ven) cxl@ccnt-lab:~/open_spiel/open_spiel$ clang++ --version
clang version 8.0.1 (tags/RELEASE_801/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin

**Comment by chenxli** [comment]
(ven) cxl@ccnt-lab:~/open_spiel/open_spiel$ which clang++
/usr/local/bin/clang++
(ven) cxl@ccnt-lab:~/open_spiel/open_spiel$ clang++ --version
clang version 8.0.1 (tags/RELEASE_801/final)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/local/bin

**Comment by lanctot** [comment]
Ok so my last guess is that CMake has cached the location of your older clang and make is still using that one. Can you remove the entire build directory (`rm -rf build`) and start again?

**Comment by lanctot** [comment]
May also be useful: https://stackoverflow.com/questions/47396959/does-clang6-implement-stdoptional

**Comment by chenxli** [comment]
I remove the build directory and start again, but still the same error>_<
I am trying the method in the link, thank you!

**Comment by lanctot** [comment]
Any eventual luck with this @chenxli ?

**Comment by chenxli** [comment]
still not.....since I updated the gcc and g++

**Comment by lanctot** [comment]
@chenxli we recently removed all instances of std::optional and replaced them with absl::optional. Can you try to see if this fixes the problem?
