### ISSUE TITLE
issue with top-level directory when installing via docker

### ISSUE THREAD

**Issue by hejujie** [deepmind/open_spiel#162]
I found dockerfile is added in yesterday commit: #158 , while it was placed in open_spiel/open_spiel/Dockerfile.
In the document, installing via docker
```
In the top-level directory:
```bash
docker build -t openspiel .
docker run openspiel python3 python/examples/matrix_game_example.py
```
If we use this command in top-level directory, the dockerfile will not be found.
If use this command in open_spiel/open_spiel, many commands in dockerfile will not be found, as they should be in the same directory with dockerfile.
```
RUN ./install.sh

RUN pip3 install --upgrade setuptools testresources 
RUN pip3 install --upgrade -r requirements.txt
RUN pip3 install --upgrade cmake

Output:
Step 3/11 : RUN ./install.sh
 ---> Running in 06c1f93031b3
/bin/sh: 1: ./install.sh: not found ( failed in this step)
```
Whether the Dockerfile should be placed in the top-level of the repo, just like in this [link](https://github.com/hejujie/open_spiel)?

**Comment by hejujie** [comment]
In the merge request of dockerfile #158, in [origin branch](https://github.com/yarncraft/open_spiel/tree/patch-1) Dockerfile is also set in top-level directory

**Comment by lanctot** [comment]
Whoops! Good catch. Ok I think this should be fixed by https://github.com/deepmind/open_spiel/pull/164

**Comment by lanctot** [comment]
> Whoops! Good catch. Ok I think this should be fixed by #164

Which I expect will be merged on Monday.

**Comment by yarncraft** [comment]
> I found dockerfile is added in yesterday commit: #158 , while it was placed in open_spiel/open_spiel/Dockerfile.
> In the document, installing via docker
> 
> ```
> In the top-level directory:
> ```bash
> docker build -t openspiel .
> docker run openspiel python3 python/examples/matrix_game_example.py
> ```
> 
> If we use this command in top-level directory, the dockerfile will not be found.
> If use this command in open_spiel/open_spiel, many commands in dockerfile will not be found, as they should be in the same directory with dockerfile.
> 
> ```
> RUN ./install.sh
> 
> RUN pip3 install --upgrade setuptools testresources 
> RUN pip3 install --upgrade -r requirements.txt
> RUN pip3 install --upgrade cmake
> 
> Output:
> Step 3/11 : RUN ./install.sh
>  ---> Running in 06c1f93031b3
> /bin/sh: 1: ./install.sh: not found ( failed in this step)
> ```
> 
> Whether the Dockerfile should be placed in the top-level of the repo, just like in this [link](https://github.com/hejujie/open_spiel)?

Thanks for the heads up, the relocation in the last PR was not on purpose indeed 👍

**Comment by lanctot** [comment]
I will fix this by moving the Dockerfile up one directory (you can currently do this yourself by just moving it: `mv Dockerfile ..`). I messed up the paths accidentally when importing the PR by @yarncraft . Code will be updated Monday. Apologies. 

Please leave this issue open as it will automatically be fixed when code is updated.

**Comment by hejujie** [comment]
> > I found dockerfile is added in yesterday commit: #158 , while it was placed in open_spiel/open_spiel/Dockerfile.
> > In the document, installing via docker
> > ```
> > In the top-level directory:
> > ```bash
> > docker build -t openspiel .
> > docker run openspiel python3 python/examples/matrix_game_example.py
> > ```
> > 
> > 
> > If we use this command in top-level directory, the dockerfile will not be found.
> > If use this command in open_spiel/open_spiel, many commands in dockerfile will not be found, as they should be in the same directory with dockerfile.
> > ```
> > RUN ./install.sh
> > 
> > RUN pip3 install --upgrade setuptools testresources 
> > RUN pip3 install --upgrade -r requirements.txt
> > RUN pip3 install --upgrade cmake
> > 
> > Output:
> > Step 3/11 : RUN ./install.sh
> >  ---> Running in 06c1f93031b3
> > /bin/sh: 1: ./install.sh: not found ( failed in this step)
> > ```
> > 
> > 
> > Whether the Dockerfile should be placed in the top-level of the repo, just like in this [link](https://github.com/hejujie/open_spiel)?
> 
> Thanks for the heads up, the relocation in the last PR was not on purpose indeed 👍

By moving Dockerfile to the top-level directory, build and run the image.  I find the root path is messy, the file and directory in the top-level directory of this repo are mixed with system file:
![image](https://user-images.githubusercontent.com/29149911/76146631-517f1080-60cf-11ea-9978-2b4957c96d86.png)
I am not familiar with docker, but I think it can be cleaned by changing some command in 
the Dockerfile, maybe it can be improved? @yarncraft

**Comment by yarncraft** [comment]
Feel free to add a .dockerignore is that is what you are aiming for! I follow the convention of having the Dockerfile and other configs in the root directory as explained in https://12factor.net/.

**Comment by yarncraft** [comment]
I would first move it to the root at least so that we can set up the CICD Docker pipeline, further reducing the image size and altering some steps in the Dockerfile can be done from then onwards!

**Comment by yarncraft** [comment]
Ah I see what you mean @hejujie, once the Dockerfile is moved, I will alter the COPY step so that the files are placed in a directory instead of the root of the container.

**Comment by lanctot** [comment]
> I would first move it to the root at least so that we can set up the CICD Docker pipeline, further reducing the image size and altering some steps in the Dockerfile can be done from then onwards!

That is the plan. I will get to it as soon as I can.

**Comment by lanctot** [comment]
Ok I have move the Dockerfile to the right place, closing this for now. @yarncraft if you would like to change the Dockerfile you can do that now.

**Comment by yarncraft** [comment]
@hejujie I've submitted a PR ( #171 ) that solves your issue!
