### ISSUE TITLE
how to fix seed to reproduce the results.

### ISSUE THREAD

**Issue by lihuiknight** [deepmind/open_spiel#167]
how to set environment seed so that I can achieve the exact the same results every time.

**Comment by lanctot** [comment]
Hi @lihuiknight , depends on the algorithm and which random number generators are used. You should be able to set the seed in the usual way? What algorithms are you using? If they are using numpy for random numbers then `numpy.random.seed`.

**Comment by lihuiknight** [comment]
I have set the seed for all the key package as follows.

def set_device_seed(args):
    torch.set_num_threads(1)
    device = torch.device("cuda:0" if torch.cuda.is_available() and args.cuda else "cpu")
    random.seed(args.seed)
    np.random.seed(args.seed)
    torch.manual_seed(args.seed)
    torch.cuda.manual_seed_all(args.seed)
    # if args.cuda and torch.cuda.is_available():
    #     torch.backends.cudnn.benchmark = False
    #     torch.backends.cudnn.deterministic = True

    return device

When I use gym, I also add `env.seed(args.seed)`, so that I can reproduce the exact the same results every time. When I use open_spiel, I don't know whether there is a similar function to fix the seed.

**Comment by lanctot** [comment]
I don't think we have the equivalent function yet, but it would certainly be a good thing to add.

I need more information. You're mentioning torch and gym.. is this not for one of our algorithms? Are you using our RL environment? 

Hmm, I just checked and our RL environment has an internal component called a `ChanceEventSampler` that supports a seed but there's no way to set it externally (see here: https://github.com/deepmind/open_spiel/blob/5c7c38d696052262080a3e4dca96cbeebce55cbc/open_spiel/python/rl_environment.py#L162)

Easy fix: all we need to do is to add a `seed` parameter to the RL environment's constructor and then pass it to the ChanceEventSampler. We can also add a  gym-like`seed` method as you suggested. 

Thanks for pointing this out. I will make this change and it will be included in our next Monday update. Please don't close this issue as it will get closed when the fix goes in.

**Comment by lihuiknight** [comment]
I write my algorithm in pytorch and test the algorithm on multiple environments includes gym and open_spiel.

**Comment by lanctot** [comment]
Ah, I just noticed that we do have a way to send in a seeded chance event sampler. This is the way it should be done:

```
chance_even_sampler = rl_environment.ChanceEventSampler(seed=129738)
env = rl_environment.Environment(game, discount=1.0, chance_event_sampler=chance_event_sampler)
```

So I won't add a seed parameter as we already support custom chance samplers which is more general anyway.

**Comment by lanctot** [comment]
On second thought, I will still add a seed method for consistency with gym environments.

**Comment by lihuiknight** [comment]
Yes. Your method works (I have tried one minute ago). Great job. Thanks.

**Comment by lanctot** [comment]
Great! 

(Please leave this open, as it will be closed when the fix goes in.)
