### ISSUE TITLE
Google Colab build issue

### ISSUE THREAD

**Issue by oslumbers** [deepmind/open_spiel#170]
Hi,
I'm having an issue building the open spiel environment this morning that wasn't an issue yesterday, happens at 63% of build. Here's the error:
 ``` Makefile :94: recipe for target 'all' failed make: *** [all] Error 2```
Happy to give more info if needed

**Comment by sullins2** [comment]
I have the same issue as well.

**Comment by lanctot** [comment]
Hmm.. last time we did an update was Monday so might be that the systems running the colabs changed configurations.

I will look into it, thanks.

**Comment by lanctot** [comment]
Noticed a few other things that need attention in the colab:

1. This line `!pip3 install --upgrade mock==3.0.5` also fails.
2. It's still using g++, which we switched away from a while back (we're using clang++ now).

**Comment by lanctot** [comment]
I've reproduced the error on our side (even internally, on my workstation), which is odd. Wasn't happening on Monday either. Must be due to a global change in compiler / linker on Google systems. Looks like it should be an easy problem to fix.

**Comment by sullins2** [comment]
Thanks

**Comment by lanctot** [comment]
I just noticed we're not fixing the version of absl; it's possibly due to a new change in absl. I'll try with an older commit.

**Comment by lanctot** [comment]
> I just noticed we're not fixing the version or commit of absl; it's possibly due to a new change in absl. I'll try with an older commit.

Confirming it's a recent change in abseil. Fix coming soon.

**Comment by lanctot** [comment]
Should work now, but you _might_ have to clear your old build directory by adding

```
% rm -rf open_spiel
``` 

after the `% cd /usr/local`.

**Comment by sullins2** [comment]
Working again. Thanks @lanctot
