### ISSUE TITLE
Issue about the python implementation of AlphaZero

### ISSUE THREAD

**Issue by hejujie** [deepmind/open_spiel#176]
When I compare our implementation of AlphaZero with the pseudocode of paper, I find two different, maybe it will have a slight influence on the performance.
The first is the Dirichlet noise:
- In the pseudocode of AlphaZero, the noise is added before MCTS simulations, so it will have the same noise in different simulations.
```python
def run_mcts(config: AlphaZeroConfig, game: Game, network: Network):
    root = Node(0)
    evaluate(root, game, network)
    add_exploration_noise(config, root)

    for _ in range(config.num_simulations):
        node = root
        scratch_game = game.clone()
        search_path = [node]

        while node.expanded():
            action, node = select_child(config, node)
            scratch_game.apply(action)
            search_path.append(node)

        value = evaluate(node, scratch_game, network)
        backpropagate(search_path, value, scratch_game.to_play())
    return select_action(config, game, root), root
```
- In our MCTS,  different noise is added in every simulations.
https://github.com/deepmind/open_spiel/blob/master/open_spiel/python/algorithms/mcts.py#L399
https://github.com/deepmind/open_spiel/blob/master/open_spiel/python/algorithms/mcts.py#L314
```python
   root_player = state.current_player()
    root = SearchNode(None, state.current_player(), 1)
    for _ in range(self.max_simulations):
      visit_path, working_state = self._apply_tree_policy(root, state)
```
```python
  def _apply_tree_policy(self, root, state):
    visit_path = [root]
    working_state = state.clone()
    current_node = root
    while not working_state.is_terminal() and current_node.explore_count > 0:
      if not current_node.children:
        # For a new node, initialize its state, then choose a child as normal.
        legal_actions = self.evaluator.prior(working_state)
        if current_node is root and self._dirichlet_noise:
          epsilon, alpha = self._dirichlet_noise
          noise = self._random_state.dirichlet([alpha] * len(legal_actions))
          legal_actions = [(a, (1 - epsilon) * p + epsilon * n)
                           for (a, p), n in zip(legal_actions, noise)]
```
different noise between simulations may have better exploration, but I don't know whether it will make it unstable?

(Edit after review: I find the sample batch of the games in pseudocode is sampled with the probability according to the length of the game, the second one is just different in implementation detail.)
The second one is the sample batch for training. 
- In pseudocode of AlphaZero, games are saved as the sample, when sampling from replay buffer, it sample num_batch of game, and random choice a game_pos in every game.
```python
    def sample_batch(self):
        # Sample uniformly across positions.
        move_sum = float(sum(len(g.history) for g in self.buffer))
        games = numpy.random.choice(
            self.buffer,
            size=self.batch_size,
            p=[len(g.history) / move_sum for g in self.buffer])
        game_pos = [(g, numpy.random.randint(len(g.history))) for g in games]
        return [(g.make_image(i), g.make_target(i)) for (g, i) in game_pos]
```
- In our implementation, we save every game position as the sample, and we just random sample from game position
https://github.com/deepmind/open_spiel/blob/master/open_spiel/python/algorithms/alpha_zero/alpha_zero.py#L164
```python
  self.replay_buffer = dqn.ReplayBuffer(replay_buffer_capacity)
  def _self_play_single(self):
    """Play a single game and add it to the replay buffer."""
    state = self.game.new_initial_state()
    trajectory = []

    while not state.is_terminal():
      root = self.bot.mcts_search(state)
      target_policy = np.zeros(self.game.num_distinct_actions(),
                               dtype=np.float32)
      for child in root.children:
        target_policy[child.action] = child.explore_count
      target_policy /= sum(target_policy)

      trajectory.append(model_lib.TrainInput(
          state.observation_tensor(), state.legal_actions_mask(),
          target_policy, root.total_reward / root.explore_count))

      action = self._select_action(root.children, len(trajectory))
      state.apply_action(action)

    terminal_rewards = state.rewards()
    for state in trajectory:
      self.replay_buffer.add(
          model_lib.TrainInput(state.observation, state.legals_mask,
                               state.policy, terminal_rewards[0]))
```
In the implementation of pseudocode, sampling from games will make it fair for the games which have different length, and our implementation is fair for every data point.

Maybe the different implementation can all work well, but I think we should have careful consideration or it may also need to have some experiments.

@sbodenstein @lanctot

**Comment by hejujie** [comment]
OK, I find the sample batch of the games in pseudocode is sampled with the probability according to the length of the game, the second one is not a difference.

**Comment by lanctot** [comment]
Going to loop in @elkhrt and @tewalds to this conversation.

Good catch! Based on those two lines, I'm inclined to agree: I think you are right, we should probably only be noisifying the root once before the simulations. @tewalds, can we try moving that the noise to before the simulations and see if we can easily reproduce internal results? 

Also, btw, there will be some upcoming changes to the AlphaZero code structure (in next Monday's update) that might affect you. Tagging @tewalds in case you have any questions, but please keep an eye on the commits. In case there is anything that breaks your code, maybe save it somewhere before pulling from master.

**Comment by lanctot** [comment]
Tagging also @TWAnthony who might have experience with this from [ExIT](https://arxiv.org/abs/1705.08439).

**Comment by elkhrt** [comment]
Yes, this looks like a bug - well spotted!

**Comment by tewalds** [comment]
Isn't it only noisifying the root once? It only happens when the current node has no children and is the root, which should only happen the first time. It then saves that noise in the tree. The second time the root will have children, so it'll use the noise saved in the tree.

**Comment by tewalds** [comment]
Btw, your second point is slightly different, in that it samples without replacement, as compared to with replacement in the pseudocode. I asked the author of AZ whether it was important that it was with replacement. He said it was simpler with replacement but shouldn't make a difference. It may well be true in that without replacement is harder in their code layout, but it's much easier without replacement here, so I left it.

**Comment by lanctot** [comment]
Ahh, yes I missed this: https://github.com/deepmind/open_spiel/blob/f5eabb654690081991a212cc6c2e8cbd46cefaa6/open_spiel/python/algorithms/mcts.py#L311 

Ok, I think I agree @tewalds, seems like this case will only be hit once. Thanks.

**Comment by hejujie** [comment]
I run the code and it just hit once, sorry for the mistake.
btw, whether place the exploration noise before the simulations loop will make the code easier to understand? 
I will close this issue soon.

**Comment by tewalds** [comment]
That would require duplicating some code for node expansion, but feel free to raise a PR to suggest it. If you manage to make it clean enough it could be worth integrating.

**Comment by hejujie** [comment]
ok, got it.
