### ISSUE TITLE
universal_poker not registered in colabs

### ISSUE THREAD

**Issue by VogtAI** [deepmind/open_spiel#189]
I simply concatenated "install_open_spiel.ipynb" and "test_universal_poker.ipynb" from open_spiel/open_spiel/colabs/ in Google Colab. 
However I get the error:
"RuntimeError: Unknown game 'universal_poker'. Available games are:"

**Comment by lanctot** [comment]
Hi @VogtAI, this is because that game requires an optional dependency (the ACPC code base) as a dependency which we have disabled by default.

To enable it, you will need to clone the ACPC code into the proper directory (see `install.sh`) and then prepend the build command with `BUILD_WITH_ACPC="ON" `

**Comment by lanctot** [comment]
Thinking more: having the appropriate commands in the colab commented out would be good. That way people can enable poker just by deleting a few characters. I will suggest it to the team, will probably go into next Monday's update.

**Comment by krfgbhoiaeuzr** [comment]
There seems to be a regression here as the same problem is happening again with the latest versions of "install_open_spiel.ipynb" and "test_universal_poker.ipynb". Also, it's not immediatly clear to new users how to build with `BUILD_WITH_ACPC="ON"`.

**Comment by lanctot** [comment]
Arghh... a test case I forgot to check, sorry!

The release did not include the optional dependencies for the pip package for some reason. My bad, sorry, will fix tonight.. should be done in 4-5 hours.

**Comment by lanctot** [comment]
Hi @krfgbhoiaeuzr , ok it's fixed again... apologies!
