### ISSUE TITLE
Suspicious implementation of UCB formula in MCTS algorithm

### ISSUE THREAD

**Issue by marcinbogdanski** [deepmind/open_spiel#19]
Hi All

Firstly, thanks for this fantastic repo!

Looking at the `python/algorithms/mcts.py` function `SearchNode.child_value` it seems UCB is implemented as follows:

```python
return (
        self.player_sign * child.total_reward / child.explore_count +
        uct_c * math.sqrt(math.log(child.explore_count) / child.explore_count))
```

In the usual UCB formula ([wiki](https://en.wikipedia.org/wiki/Monte_Carlo_tree_search) or [link](http://www.moderndescartes.com/essays/deep_dive_mcts/)) the second term contains `log(parentN) / childN`, while above is `log(childN)/childN`.

I tested both formulas on different implementation of MCTS and both work, but `log(childN)/childN` seems to degrade performance.

There seems to be equivalent issue in C++ version in `mcts.cc`

Is this a potential bug, or am I missing something?

**Comment by locked-deepmind** [comment]
Thanks for reporting! Yes, I agree this is an error; we will fix it.
