### ISSUE TITLE
deepcfr algorithm yields error in colab

### ISSUE THREAD

**Issue by VogtAI** [deepmind/open_spiel#190]
I'm trying to get deepcfr to work in colab:
https://colab.research.google.com/drive/1hnsPNjcQnxtpvyO3l2-Aa8zcGvAomnPT?authuser=1&pli=1#scrollTo=CYfgDd7H9iK1

I get the following error:

/usr/local/open_spiel/open_spiel/python/algorithms/deep_cfr.py in reinitialize_advantage_networks(self)
    241   def reinitialize_advantage_networks(self):
    242     for p in range(self._num_players):
--> 243       for key in self._advantage_networks[p].initializers:
    244         self._advantage_networks[p].initializers[key]()
    245 

AttributeError: 'MLP' object has no attribute 'initializers'

**Comment by lanctot** [comment]
I can't load the colab for some reason; can you copy the code here? 

What are you doing beyond `test_deep_cfr_runs` from this: https://github.com/deepmind/open_spiel/blob/master/open_spiel/python/algorithms/deep_cfr_test.py (that test is passing so I guess it must be something custom)

**Comment by VogtAI** [comment]
This link should hopefully work:
https://drive.google.com/open?id=1r4Ge5-g8Y9NUQUSSLhGsKKUP65TVNRJb

I just copied the code of the test_deep_cfr_runs from the file you posted method.

**Comment by sullins2** [comment]
I had a problem similar to this a week or so ago, I think they updated Sonnet to a version 2.0 a few weeks ago and that broke what you are using. I had to manually install a lower version of 1.x of Sonnet. You can get the older 1.x versions with something like 'pip install sonnet=' and it will error and list the versions and just install the highest 1.x version.

**Comment by sullins2** [comment]
Also, to run neurd.py on colab, I always have to change line 67 of rcfr.py to

num_columns = 1 if rank == 0 else tensor.shape[0] #.value

Note the ".value" is commented out, that's what I had to remove.

**Comment by lanctot** [comment]
Pretty sure we haven't upgraded to Sonnet 2; in fact we're looking into that because we're considering moving a few algorithms to TF2 and it's non-trivial. Sonnet version still listed as 1.32 in https://github.com/deepmind/open_spiel/blob/master/requirements.txt . @sullins2 , can you point me to where you see references to Sonnet 2?

Something I'm missing: why would the tests all still run without any problems if these changes were necessary? And why would it only happen on colab? Could it be that your source is out of sync with master because you have not git-updated or rebuilt in a while? This seems mysterious to me.

**Comment by lanctot** [comment]
> I had a problem similar to this a week or so ago, I think they updated Sonnet to a version 2.0

A ha! By 'they' I think you meant the colab providers, not us. Sorry! 

Hmmmm... that is going to make this a bit tricky indeed!

**Comment by sullins2** [comment]
Yeah, it was colab I think. One day, a bunch of stuff just stopped working, like what I mentioned. It was easy enough to fix so I didn't end up posting about it on here.

**Comment by lanctot** [comment]
Hi @VogtAI @sullins2 : I am closing this bug in favor of the overall one with colab being broken here: https://github.com/deepmind/open_spiel/issues/191

If you have any updates for us on getting it to work, please follow-up on that thread. Thanks!
