### ISSUE TITLE
Any reasons for limiting nox tests to python 3.6?

### ISSUE THREAD

**Issue by mrdaliri** [deepmind/open_spiel#206]
Hi,

I tried to run nox tests within my Python 3.7 virtual environment, but it requires python **3.6**:
https://github.com/deepmind/open_spiel/blob/4c02fe8c74ced5d448e98c68520c7394e241051d/noxfile.py#L30-L32

I found that the `python` argument has been added in a893c45b to mitigate build problems with TravisCI. However, it breaks things when running nox inside a venv.

I think if we remove python version specifier, it uses parent environment version and works perfectly. (parent env in case of TravisCI will be Python 3.6, and in a local venv, such as mine, it will be Python 3.7)

I'm relatively new to this repository and still looking around to understand how things work. If there is a specific reason for using Python 3.6 only and not newer versions, I believe it should be noted in the README file.

**Comment by mrdaliri** [comment]
Well, I just noticed that nox tests are not included in TravisCI. It only checks building from source method. Is it intentional?

**Comment by lanctot** [comment]
There was a cryptic error that I couldn't figure out, but I don't remember what it was.

The nox tests are included in Travis when the flag is set (which we do set: https://travis-ci.org/github/deepmind/open_spiel).

Could be good to reinvestigate this now. Does it work for you with Python 3.7?

**Comment by lanctot** [comment]
> I'm relatively new to this repository and still looking around to understand how things work. If there is a specific reason for using Python 3.6 only and not newer versions, I believe it should be noted in the README file.

Python 3.7 is supported everywhere, it was just the nox tests which have have only been using on Travis (we don't use it for testing internally).

**Comment by lanctot** [comment]
Oh yes now I think I remember that it was indeed related to Travis not having python 3.7 installed. I thought I had put a comment to that effect in the nox file but I will add it if not.

**Comment by lanctot** [comment]
> https://github.com/deepmind/open_spiel/blob/4c02fe8c74ced5d448e98c68520c7394e241051d/noxfile.py#L30-L32
> 
> I found that the `python` argument has been added in [a893c45](https://github.com/deepmind/open_spiel/commit/a893c45bce16383878381ea95de2a54bfb91e425) to mitigate build problems with TravisCI. However, it breaks things when running nox inside a venv.
> 
> I think if we remove python version specifier, it uses parent environment version and works 
> I found that the `python` argument has been added in [a893c45](https://github.com/deepmind/open_spiel/commit/a893c45bce16383878381ea95de2a54bfb91e425) to mitigate build problems with TravisCI. However, it breaks things when running nox inside a venv.
> 
> I think if we remove python version specifier, it uses parent environment version and works perfectly. (parent env in case of TravisCI will be Python 3.6, and in a local venv, such as mine, it will be Python 3.7)
> 

Ah! I believe that I didn't try that. I assume you are trying it? If it works, could you submit a PR? That will trigger a Travis build and we can see what happens.

**Comment by mrdaliri** [comment]
Well, I removed version specifier from Nox session definition and was able to pass all Nox tests with Python 3.7 (after setting `PYTHONPATH` #207).

I'll submit a PR to confirm it with Travis.

**Comment by mrdaliri** [comment]
Pull request #208 created. Hope it passes Travis build.

**Comment by lanctot** [comment]
Closing this now that this PR was imported and will be merged soon: https://github.com/deepmind/open_spiel/pull/208
