### ISSUE TITLE
`run_python_test_file` fails on Nox

### ISSUE THREAD

**Issue by mrdaliri** [deepmind/open_spiel#207]
Hi,

When running tests with Nox, test #141 (`run_python_test`) fails with the following `ModuleNotFoundError` exception.

Any suggestions? I thought it could be wrong package name, since `open_spiel` is installed as `pyspiel` so replaced `open_spiel.utils.run_python_test_file` with `pyspiel.utils.run_python_test_file` but it didn't solve the issue. 

```
127/145 Test #141: run_python_test ...................................***Failed    1.27 sec
~/openspiel/.nox/tests/bin/python3: Error while finding module specification for 'open_spiel.utils.run_python_test_file' (ModuleNotFoundError: No module named 'open_spiel')
Spiel Fatal Error: ~/openspiel/open_spiel/utils/run_python_test.cc:25 CHECK_TRUE(RunPython(test_module, {"--return_value", "0"}))
```

**Comment by lanctot** [comment]
Yes I ran into the same problem when we added that test. You need to setup the PYTHONPATH appropriately before running nox. See here for how we do it on Travis: https://github.com/deepmind/open_spiel/blob/master/open_spiel/scripts/travis_script.sh

**Comment by mrdaliri** [comment]
Thank you. I set `PYTHONPATH` as you said, and was able to pass all tests with Python 3.7. Here is the commands (for reference only):

  ```
PWD=`pwd`  # normally defined, but just in case!
PYTHONPATH="$PYTHONPATH:$PWD:$PWD/build:$PWD/build/python" nox -s tests
```
