### ISSUE TITLE
Python AlphaZero: division by zero exception

### ISSUE THREAD

**Issue by mrdaliri** [deepmind/open_spiel#218]
Hi,

I'm trying to run `tic_tac_toe_alpha_zero.py` but it fails with an **ZeroDivisionError: division by zero** exception. Here is the stack trace: 

> ===================== Exception caught =====================
> Traceback (most recent call last):
>   File "\~/openspiel/open_spiel/python/algorithms/alpha_zero/alpha_zero.py", line 166, in _watcher
>     return fn(config=config, logger=logger, **kwargs)
>   File "\~/openspiel/open_spiel/python/algorithms/alpha_zero/alpha_zero.py", line 452, in learner
>     "results": [sum(e.data) / len(e) for e in evals],
>   File "\~/openspiel/open_spiel/python/algorithms/alpha_zero/alpha_zero.py", line 452, in <listcomp>
>     "results": [sum(e.data) / len(e) for e in evals],
> ZeroDivisionError: division by zero
> 

I tried it on a Mac and Ubuntu 18.04 machine, both failed with same error.

**Comment by mrdaliri** [comment]
I could mitigate this issue by adding a guard in this line. But I think it's more like a workaround and probably the root of the problem is somewhere else.
 https://github.com/deepmind/open_spiel/blob/4c02fe8c74ced5d448e98c68520c7394e241051d/open_spiel/python/algorithms/alpha_zero/alpha_zero.py#L452 

Changed to:
`
            "results": [sum(e.data) / len(e) if len(e) > 0 else None for e in evals],
`

**Comment by lanctot** [comment]
Thanks for reporting this, @tewalds has submitted a fix. It will be merged in Monday's update.
