### ISSUE TITLE
Breakthrough Swift implementation is slow

### ISSUE THREAD

**Issue by sbodenstein** [deepmind/open_spiel#228]
Playing random games with Swift environments is generally faster than the combination of Python/C++. But Breakthrough is significantly slower for some reason. Times below are in μs:
|  | **Swift** | **Python** |
| :---         |     :---:      |          ---: |
| TicTacToe  | 87     | 255    |
| Breakthrough     | 9340      | 2506      |
| Kuhn Poker     | 15       | 149      |

These numbers were generated on a 2019 15' Macbook Pro, and the Swift implementation was built with `-O` and `Whole Module` optimization flags:
```swift
import Dispatch
import Foundation
import OpenSpiel

func playRandomGame<T: GameProtocol>(_ game: T) {
  var state = game.initialState
  while !state.isTerminal {
    state.apply(state.legalActions.randomElement()!)
  }
}

let game = Breakthrough()
let n: Int = 1000
let start = DispatchTime.now()
for _ in 1...n {
    playRandomGame(game)
}
let timeDiff = Double(DispatchTime.now().uptimeNanoseconds - start.uptimeNanoseconds) / Double(n)
print("Mean Random Game Time (μs): \(timeDiff / 1e3)")
```
and 
```python
import numpy as np
import pyspiel
import time

def play_random_game(game):
    game_state = game.new_initial_state()
    while not game_state.is_terminal():
        random_action = np.random.choice(game_state.legal_actions())
        game_state.apply_action(random_action)

game = pyspiel.load_game("breakthrough")
n = 1000
start = time.time()
for _ in range(n):
    play_random_game(game)
time_diff = (time.time() - start) / n

print("Mean Random Game Time (μs): ", 1e6 * time_diff)
```

**Comment by lanctot** [comment]
Hi @sbodenstein,

I'm not too surprised by this, but I don't know much about Swift. @elkhrt or @dan-zheng , any ideas?

The reason for my thinking: the python games are all wrappers around C++ implementations, not actual Python implementations. So, the constant overhead you pay for the round trip from python to C++ and back should eventually be less of a problem as the game gets larger because the time spent executing the logic of the rules dominates the running time. 

Now, I'm not sure that's what is happening here-- I actually have no idea what the relative latencies are like-- but it is one theory.

**Comment by sbodenstein** [comment]
@lanctot: sorry, I should have titled this as 'possible slow implementation issue', as you are right that this could well be that C++ is much faster than Swift in this case and the C++/Python round-trip overhead is no longer relevant for this more complex game.

But: if Swift is really is at least 3.7x slower than C++ here, then doesn't that potentially invalidate the motivation for Swift OpenSpiel ("*Swift OpenSpiel explores using a single programming language for the entire OpenSpiel environment, from game implementations to algorithms and deep learning models.*") as complex environments will definitely still need to be written in C++?

**Comment by lanctot** [comment]
> @lanctot: sorry, I should have titled this as 'possible slow implementation issue', as you are right that this could well be that C++ is much faster than Swift in this case and the C++/Python round-trip overhead is no longer relevant for this more complex game.

Keep in mind that I have only epsilon knowledge of Swift, hence tagging the experts :)

> But: if Swift is really is at least 3.7x slower than C++ here, then doesn't that potentially invalidate the motivation for Swift OpenSpiel ("_Swift OpenSpiel explores using a single programming language for the entire OpenSpiel environment, from game implementations to algorithms and deep learning models._") as complex environments will definitely still need to be written in C++?

_If_ it is indeed 3.7x slower than C++ then yes, we should be asking some questions. I'm happy (and quite likely!) to be wrong about this. 

I actually have not looked at the Swift Breakthrough implementation-- I don't know Swift at all. Is there anything in it that strikes you as inefficient that could be causing an artificial slowdown (compared to e.g. the C++ impl)? I wrote the C++ implementation; IIRC it didn't do anything fancy to save time, but it was a long time ago. I will gladly take a look to be sure, but maybe will wait for someone else who might have a better idea first.

**Comment by saeta** [comment]
Thanks @sbodenstein for noticing and inquiring about this! I've put together https://github.com/deepmind/open_spiel/pull/230 which helps a bit. I suspect there's a fair bit more that's possible to improve Breakthrough's performance.

Please do let me know if you'd be interested in further optimizations!

**Comment by sbodenstein** [comment]
@saeta: thanks for such a rapid response and fix! Don't directly require more speedup. 

It would be interesting to know just how close you can get to C++ performance in Swift to answer the question 'is solving the two-language problem in RL viable with Swift', but that is beyond the scope of this issue 😉
