### ISSUE TITLE
Preferred priority for PyTorch example contributions?

### ISSUE THREAD

**Issue by seungjaeryanlee** [deepmind/open_spiel#23]
I read [contributing.md](https://github.com/deepmind/open_spiel/blob/master/docs/contributing.md) and saw that one of them was adding examples and supports for PyTorch. I wanted to contribute, but was wondering if you had particular algorithms or examples in mind to start with.

If there is no particular preference, I would like to start with DQN, imitating the style of the existing TensorFlow example in [`open_spiel/python/algorithms/dqn.py`](https://github.com/deepmind/open_spiel/blob/master/open_spiel/python/algorithms/dqn.py).

Thank you!

**Comment by lanctot** [comment]
I don't think we have any preferences on that. DQN seems like a great place to start!

**Comment by lanctot** [comment]
If you do implement anything using pytorch maybe put it in a subdirectory for now so we can more easily separate the pytorch and TF algorithms?

**Comment by seungjaeryanlee** [comment]
@lanctot I think that's a good good idea! Just to clarify, would it be a subdirectory in `algorithms` folder, or would it be another folder like `pytorch_algorithms` ?

In other words,
`open_spiel/open_spiel/python/algorithms/pytorch/`
vs
`open_spiel/open_spiel/python/pytorch_algorithms/`

**Comment by lanctot** [comment]
I was thinking a pytorch subdir directly under python/ for now. If we get enough pytorch contributions, we can do some re-organization later. How does that sound?

**Comment by lanctot** [comment]
@seungjaeryanlee going to close this one as it seems resolved, thanks!

**Comment by seungjaeryanlee** [comment]
Sounds good. Thank you!
