### ISSUE TITLE
make process error...

### ISSUE THREAD

**Issue by hanyun2019** [deepmind/open_spiel#24]
When I use "make -j$(nproc)" to make, some errors display as the follows:

In file included from /Users/user/documents/deeplearning/open_spiel/open_spiel/abseil-cpp/absl/random/internal/randen_slow.cc:21:
/Users/user/documents/deeplearning/open_spiel/open_spiel/abseil-cpp/absl/random/internal/platform.h:165:48: error: 
      'TARGET_OS_IPHONE_SIMULATOR' is not defined, evaluates to 0 [-Werror,-Wundef]
#if defined(__APPLE__) && (TARGET_OS_IPHONE || TARGET_OS_IPHONE_SIMULATOR)

[  8%] Built target absl_leak_check_disable
In file included from /Users/user/documents/deeplearning/open_spiel/open_spiel/abseil-cpp/absl/random/internal/randen_hwaes.cc:26:
/Users/user/documents/deeplearning/open_spiel/open_spiel/abseil-cpp/absl/random/internal/platform.h:165:48: error: 
      'TARGET_OS_IPHONE_SIMULATOR' is not defined, evaluates to 0 [-Werror,-Wundef]
#if defined(__APPLE__) && (TARGET_OS_IPHONE || TARGET_OS_IPHONE_SIMULATOR)
...

Please give some help. Thanks a lot.

**Comment by lanctot** [comment]
What platform are you building on?

If MacOS it might be because nproc is not defined in MacOS, and maybe try the fixes discussed in https://github.com/deepmind/open_spiel/issues/2

**Comment by hanyun2019** [comment]
It's MacOS.

lanctot <notifications@github.com> 于2019年9月4日周三 上午7:50写道：

**Comment by lanctot** [comment]
Did you try read the discussion in the link I posted to fix the issue with nproc not being defined on MacOS?

**Comment by hanyun2019** [comment]
Sorry. I cannot find the "build_and_run_tests.sh" file in the scripts directory:
![image](https://user-images.githubusercontent.com/51042844/64217727-179b3a80-cef1-11e9-80fd-24da5534ba6c.png)

I just follow these steps:
1.  Run ./install.sh
2. virtualenv -p python3 venv
    source venv/bin/activate
    pip3 install -r requirements.txt
3. mkdir build
    cd build
4. CXX=g++ cmake -DPython_TARGET_VERSION=3.6 -DCMAKE_CXX_COMPILER=${CXX} ../open_spiel
5. make -j$(nproc)
...

When I input the step 5 "make -j$(nproc)", the mistake happens...

**Comment by hanyun2019** [comment]
Sorry, re-open it for help. thanks~

**Comment by lanctot** [comment]
Did you look at the link I posted in my first reply? nproc is not defined in MacOS.

Can you try:

```
make -j12
```

**Comment by hanyun2019** [comment]
When I try:

    make -j12

Some error occurs:
In file included from /Users/user/documents/deeplearning/open_spiel/open_spiel/abseil-cpp/absl/random/internal/randen_hwaes.cc:26:
/Users/user/documents/deeplearning/open_spiel/open_spiel/abseil-cpp/absl/random/internal/platform.h:165:48: error: In file included from /Users/user/documents/deeplearning/open_spiel/open_spiel/abseil-cpp/absl/random/internal/randen_slow.cc:21:
/Users/user/documents/deeplearning/open_spiel/open_spiel/abseil-cpp/absl/random/internal/platform.h:165:48: error: 
      'TARGET_OS_IPHONE_SIMULATOR' is not defined, evaluates to 0 [-Werror,-Wundef]
...

**Comment by lanctot** [comment]
I see. Unfortunately we are unable to officially support MacOS at the moment, but maybe someone else will have the same issue and post a fix.

Meanwhile, I suggest you take a look at this pull request which has some fixes for MacOS and links to several comments on building in MacOS: https://github.com/deepmind/open_spiel/pull/6

**Comment by hanyun2019** [comment]
OK. Thanks a lot~

**Comment by OpenSpiel** [comment]
Hi. Thanks for your report.

I merged https://github.com/deepmind/open_spiel/pull/6 which was suggesting a Fix to build on MacOS.

Can you check if it works for you? If not, I would encourage you to send a contribution, as no developer is using Mac (so we it is low priority for DeepMind developers).

I will mark the bug as fixed, assuming the PR was enough, given 2 persons build on macOS, but feel free to reopen with the new kind of errors you have.

**Comment by hanyun2019** [comment]
It's OK now. Thanks~
