### ISSUE TITLE
terminal state detection connect_four not working correctly

### ISSUE THREAD

**Issue by danielwillemsen** [deepmind/open_spiel#25]
It seems that the terminal state detection of connect_four does not detect all winning states. 
See the following example for a minimal reproduction:
```
import pyspiel
game = pyspiel.load_game("connect_four")
state = game.new_initial_state()
state.apply_action(3)
state.apply_action(2)
state.apply_action(3)
state.apply_action(2)
state.apply_action(3)
state.apply_action(2)
state.apply_action(3)
print(state)
print(state.is_terminal())
```

results in:
```
.......
.......
...x...
..ox...
..ox...
..ox...

False

```

This should be a winning state for x and thus print True, right? Or do I just understand the functionalities of state and is_terminal() incorrectly?

**Comment by OpenSpiel** [comment]
Fixed thanks to your PR! (https://github.com/deepmind/open_spiel/pull/26)

Thanks again, it is really helpful.
