### ISSUE TITLE
DeepCFR with Reservoir sampling 

### ISSUE THREAD

**Issue by bakanaouji** [deepmind/open_spiel#264]
Dear authors.

I have been reading the code of DeepCFR and was wondering why a reservoir sampling is not chosen?
https://github.com/deepmind/open_spiel/blob/021f3585efed8bb9eb4173e36f65c65263996c69/open_spiel/python/algorithms/deep_cfr.py#L62-L76

According to the following paper, the performance with a reservoir sampling is better than one with a sliding window memory.
https://arxiv.org/pdf/1811.00164.pdf
From this point of view, I think it is better to choose a reservoir sampling memory.

**Comment by lanctot** [comment]
Hi @bakanaouji yes I think that is a bug... or, rather, something the author did not realize about the algorithm on reading the paper.

Do you feel like contributing a fix? There is reservoir sampling code you can take directly from NFSP. Maybe we should make that data structure more accessible generally, a lot of algorithms in this class are starting to use them now. But I'd be happy with an implementation local to this file.

If you don't, I will fix this, but I've got several higher-priority items on the list, so it might be a few weeks.

**Comment by bakanaouji** [comment]
Hi @lanctot , thanks for your polite response.

I would like to contribute to the fix this bug. Since I have already confirmed that the performance with the fixed code will improve in my local environment, I can send the pull request immediately.

**Comment by lanctot** [comment]
Ok great. Can you make sure it's the most reason version using our simple_nets not sonnet?

Also can you try the example to see if you get close to the proper values in Kuhn? I had to introduce a flag to toggle reinitializing the networks and had to set it to false to get good values. Curious if that is still true with the reservoir buffers.

Details here: https://github.com/deepmind/open_spiel/pull/248

**Comment by bakanaouji** [comment]
I have checked with both versions using simple_nets and sonnet.
The results of trying the example are shown in the following PR.
#268

**Comment by lanctot** [comment]
Great thanks. @aliyakamercan tagging you since you were also looking into this code.

**Comment by lanctot** [comment]
Fixed now by https://github.com/deepmind/open_spiel/commit/f67f3e65b1c66fe3a2291cf555957e9378a29456
