### ISSUE TITLE
Page not found when clicked on Contributing.md

### ISSUE THREAD

**Issue by MetalDent** [deepmind/open_spiel#27]
In README under [Guidlines and Contributing](https://github.com/deepmind/open_spiel/blob/master/docs/contributing.md) when we click on CONTRIBUTING.md under "Roadmap and Call for Contributions" it says Not Found.

Apparently, the link address is incorrect. I'm willing to open a PR to fix this.

**Comment by locked-deepmind** [comment]
Thanks for the PR!

**Comment by OpenSpiel** [comment]
Fixed by merging the PR.
