### ISSUE TITLE
Make Python code PEP8 compliant

### ISSUE THREAD

**Issue by inejc** [deepmind/open_spiel#275]
The PEP8 style guide is available here: https://www.python.org/dev/peps/pep-0008. It is possible to use auto formatters, e.g. https://github.com/hhatto/autopep8 is a good choice.

**Comment by elkhrt** [comment]
Thanks for suggesting! We us `YAPF` with the `google` style. The main difference is the use of two spaces rather than four for indentation. I'll kick off a run now.

**Comment by lanctot** [comment]
Closing as I feel it is resolved, please reopen if necessary.
