### ISSUE TITLE
Better de/serialization for stateful game objects

### ISSUE THREAD

**Issue by inejc** [deepmind/open_spiel#276]
Strictly speaking, I believe stateful game objects are currently not serialized correctly. For example, `NegotiationGame` which holds an internal RNG loses the state of the RNG after serialization and deserialization (using `ToString` and `LoadGame`). I guess this issue is mostly relevant for sampled stochastic implementations, e.g. I have the same problem in https://github.com/deepmind/open_spiel/pull/274.

While there is the ability to override `Serialize` and `Deserialize` for state objects, the same should probably be true for game objects. The default implementation would assume stateless game objects and would simply be identical to the current implementation.

The issue occurs in cases where the `rng_seed` parameter is set by a user and then the game and state objects are de/serialized. While the state object is deserialized correctly, a `NewInitialState` call on the deserialized game object, would essentially result in the same sequence of RNG samples and thus the same sequence of new initial states (compared to prior to serialization).

**Comment by lanctot** [comment]
Hi @inejc , ah yes I understand the issue. 

But, I think we should probably not encourage stateful objects generally, could be error-prone. We can allow it for this specific exceptional case of `kSampledStochastic` chance mode and the RNG state. 

I think there is a simple fix which is to include the current seed (or whatever is needed to reconstruct the RNG state) in the game's parameters and invlude it in game's ToString so it gets deserialized properly.

We should also add a test for all the games using that chance mode to ensure that the produce the same sequence of random numbers after serialization.

What do you think?

**Comment by inejc** [comment]
Agree with not encouraging stateful game objects in general. Yeah, I think that fix would work, I will give it a try later in the day.

**Comment by lanctot** [comment]
Closing this since it's actively being working on in https://github.com/deepmind/open_spiel/pull/279
