### ISSUE TITLE
Inconsistent length of `LegalActions` and `LegalActionsMask` for chance nodes

### ISSUE THREAD

**Issue by findmyway** [deepmind/open_spiel#283]
For example, in the game `kuhn_poker`, the `LegalActions` of the first chance node is `[0,1,2]`, while the `LegalActionsMask` fallbacks to the default implementation and returns `[1,1]`. Is this expected? (If so, does it mean that I should always rely on `LegalActions` instead of `LegalActiosnMask` for chance nodes?)

**Comment by lanctot** [comment]
Hi @findmyway , no this is not expected, pretty sure is a bug. Can you confirm, @jblespiau ?Thanks for finding. 

We introduced that function as a helper for neural net experiments so we likely only thought about it at decision nodes and mistakenly did not support it properly at chance nodes.

Can I ask you to submit a fix?
