### ISSUE TITLE
[Request] Guide that explain how to create a new game.

### ISSUE THREAD

**Issue by lorrp1** [deepmind/open_spiel#296]
hello, im trying to understand how to modify an existing game, but from the spiel.h i cant figure out how many functions works and the requirement for the different gameType (whats is needed for a kSimultaneous vs kSequential for example).
could you provide a simple guide at least to explain in detail how to create a game?  

from spiel.h: 

  // Which type of information state representations are supported?
  // The information state is a perfect-recall state-of-the-game from the
  // perspective of one player.
  bool provides_information_state_string;
  bool provides_information_state_tensor;

the comments above do not explain in detail whats the meaning of each xString and xTensor, but it gives only a general explanation of the "provides_information_"

**Comment by findmyway** [comment]
1. Determine the [`GameType`](https://github.com/deepmind/open_spiel/blob/a651ce7fbea858b0be2db98afabb49f7c830d904/open_spiel/spiel.h#L72-L116) and [`StateType`](https://github.com/deepmind/open_spiel/blob/a651ce7fbea858b0be2db98afabb49f7c830d904/open_spiel/spiel.h#L153-L158) of the environment you want to implement.
    - The `provides_*` usually mean that the related function is optional and you should use the returned flag to tell users whether it is implemented in your game or not. For example, `provides_information_state_string` ->`InformationStateString`. Generally speaking, you're suggested to implement these functions as much as possible to cover the potential usages by different kinds of algorithms.
 2. Find an existing game of the same `GameType` or `StateType`. If there exists one and then you are lucky. Start from modifying that example and add test cases.
    - You can use some functions to filter out games of specific types like this:
    - https://github.com/deepmind/open_spiel/blob/a651ce7fbea858b0be2db98afabb49f7c830d904/open_spiel/python/tests/games_sim_test.py#L34-L60

3. Make sure that your game is registered and then make a PR.
    - https://github.com/deepmind/open_spiel/blob/c2be1951587b2879b04ef986706652275256081a/open_spiel/games/tic_tac_toe.cc#L51

**Comment by lanctot** [comment]
Hi @lorrp1 , best thing to do is read the paper: https://arxiv.org/abs/1908.09453. Then read comments, then if you're still not sure, just ask! We don't bite. :)

On first pass, you can omit all `InformationStateString`, `InformationStateTensor`, `ObservationString`, `ObservationTensor` (and set all their respective `provides_` in the game type to be false). These are really the last things you need to implement, and depending what you want to do, you may not even have to implement them. 

You can run tests and check correctness without having these functions, and they are both the most boring and easiest to get wrong, so just best to leave them until the end.

Also: please identify any pieces of documentation you feel is missing, noting down some pain points along the way. And then feel free to submit a fix to the current guide :)

**Comment by lanctot** [comment]
BTW I replied assuming you've seen the "Adding a Game" section of this page: https://github.com/deepmind/open_spiel/blob/master/docs/developer_guide.md

If not, that's a great place to start!

**Comment by lanctot** [comment]
Hi @lorrp1 , did you find what you needed? Any more questions for us?
