### ISSUE TITLE
Unable to find the "example" program in the  In the "examples" directory

### ISSUE THREAD

**Issue by hanyun2019** [deepmind/open_spiel#30]
I have successful run the following steps on MacOS:
1) ./install.sh 
2) 
virtualenv -p python3 venv
source venv/bin/activate
pip3 install -r requirements.txt
3) ./open_spiel/scripts/build_and_run_tests.sh

But when I try to run my first example, like:
examples/example --game=tic_tac_toe

I can not find the "example" program in the  "examples" directory:
![image](https://user-images.githubusercontent.com/51042844/64332996-38a27f00-d008-11e9-8d80-2f54bc81a059.png)

Anyone knows what happens here? Thanks!

**Comment by lanctot** [comment]
The `build_and_run_examples.sh` script creates a build directory to put everything it compiles into. You need to run the example from within that build directory.

You can also do it manually as step 3 like explained here: https://github.com/deepmind/open_spiel/blob/master/docs/install.md#building-and-running-tests

**Comment by hanyun2019** [comment]
The build_and_run_examples.sh can not be found.
You means ./open_spiel/scripts/build_and_run_tests.sh ?

**Comment by lanctot** [comment]
Oh yes I was referring to your step 3.

**Comment by lanctot** [comment]
@hanyun2019, were you able to run the example from within the build directory?

**Comment by hanyun2019** [comment]
If I use:  ./open_spiel/scripts/build_and_run_tests.sh, I can pass all the test:
![image](https://user-images.githubusercontent.com/51042844/64482025-04071100-d21c-11e9-9fd0-d5de911620ec.png)

I can not find the "example" program in the "examples" directory:
![image](https://user-images.githubusercontent.com/51042844/64482071-dff7ff80-d21c-11e9-9ac4-19b895e701c4.png)

![image](https://user-images.githubusercontent.com/51042844/64482076-f1d9a280-d21c-11e9-9f3b-df776b3a1653.png)

May I enter a wrong directory?
@lanctot

**Comment by lanctot** [comment]
It is great that the tests pass. This means that it is working.

As I said in a previous comment, this script creates a build subdirectory where all the binaries are placed (see lines 44-46 of the `build_and_run_tests.sh` script). You need to run the example from within that directory, or prepend the build directory to the command.

(If you do the build manually like the instructions I linked above, then you create this build directory yourself, so you lnow the name of it. Otherwise you can find it by running `ls` after running the build script.)

**Comment by hanyun2019** [comment]
And if I follow the detail steps (I think it's an alternative install way in the document) as:
https://github.com/deepmind/open_spiel/blob/master/docs/install.md#building-and-running-tests

I can not pass the following steps:
make -j$(nproc)
![image](https://user-images.githubusercontent.com/51042844/64482143-67923e00-d21e-11e9-81ec-a659238ebd41.png)
![image](https://user-images.githubusercontent.com/51042844/64482148-70830f80-d21e-11e9-9831-2570e36d21c1.png)

It's my situation now. 
I am stilling fighting for the make ......

**Comment by lanctot** [comment]
You need the fixes for MacOSX from here: https://github.com/deepmind/open_spiel/pull/6

Try `git pull` to update the code or clone a fresh copy.

**Comment by lanctot** [comment]
Also note that nproc is not defined on MacOSX. If you are building manually please use `make -j12` instead of `make -j$(nproc)`. Thanks.

**Comment by hanyun2019** [comment]
I have already git pull the code again:
![image](https://user-images.githubusercontent.com/51042844/64482211-bc828400-d21f-11e9-87ac-55fbc69a7816.png)

But still failed to "make -j12":
![image](https://user-images.githubusercontent.com/51042844/64482222-ea67c880-d21f-11e9-9a14-42fea19901e5.png)

@lanctot

**Comment by lanctot** [comment]
Can you try removing all the code, clone a fresh copy of the repos, and try again? 

I think the CMake is reusing cached makefiles which need to be updated. That is why the test script works but the manual build does not. Because you ran cmake before those MacOS fixes were in.

**Comment by lanctot** [comment]
Alternatively you can remove all the cached cmake files with `rm -rf CMakeCache.txt CMakeFiles` and rerun the cmake command, then run the make command again.

**Comment by hanyun2019** [comment]
I have removed all the cached cmake files with: rm -rf CMakeCache.txt CmakeFiles
![image](https://user-images.githubusercontent.com/51042844/64482316-459aba80-d222-11e9-969d-f33565e8f275.png)

Which parameters should I take with the cmake command?

**Comment by lanctot** [comment]
The same one used in the manual build instructions specified here: https://github.com/deepmind/open_spiel/blob/master/docs/install.md#building-and-running-tests

**Comment by hanyun2019** [comment]
I have successfully pass the cmake again, with the command:
CXX=g++ cmake -DPython_TARGET_VERSION=3.6 -DCMAKE_CXX_COMPILER=${CXX} ../open_spiel

![image](https://user-images.githubusercontent.com/51042844/64482428-682dd300-d224-11e9-918a-3a617f7caf28.png)

But still failed to "make -j12":

![image](https://user-images.githubusercontent.com/51042844/64482442-a0cdac80-d224-11e9-9434-e82acb7dd851.png)

**Comment by lanctot** [comment]
Ok let's abandon the manual build.

Can you rerun the script that works and show me the output of `ls` after the tests run successfully?

**Comment by hanyun2019** [comment]
In this directory, I plan to run the script:
![image](https://user-images.githubusercontent.com/51042844/64482537-30c02600-d226-11e9-894c-d5d5e372eaa5.png)

And after rerun the script:

![image](https://user-images.githubusercontent.com/51042844/64482659-c5c41e80-d228-11e9-88d6-3d699cdaa3b4.png)

![image](https://user-images.githubusercontent.com/51042844/64482664-d4aad100-d228-11e9-9e37-6bbaeb84aa46.png)

**Comment by lanctot** [comment]
Great. Can you now run:

```
cd build_python_3
examples/example --game=tic_tac_toe
```

**Comment by hanyun2019** [comment]
cd build_python_3
examples/example --game=tic_tac_toe

![image](https://user-images.githubusercontent.com/51042844/64482698-8b0eb600-d229-11e9-8489-8c381ef1adb8.png)

![image](https://user-images.githubusercontent.com/51042844/64482706-a11c7680-d229-11e9-9a9a-a8685189c288.png)

Am I right?
Have I successfully run the example game tic_tac_toe?

**Comment by lanctot** [comment]
Yep, it worked! Glad we got to the bottom of this.

**Comment by hanyun2019** [comment]
Cheers! Thanks a lot! @lanctot
