### ISSUE TITLE
The L2-projection operator in projected replicator dynamics

### ISSUE THREAD

**Issue by rezunli96** [deepmind/open_spiel#308]
This might be a minor issue. I found in [projected_replicator_dynamics.py, line 57](https://github.com/deepmind/open_spiel/blob/e87fe7beef3c698e334704ee570eaf09b9159a40/open_spiel/python/algorithms/projected_replicator_dynamics.py), the L2-projection operator is implemented as 
```
def _project_distribution(updated_strategy, gamma):
  """Projects the distribution in updated_x to have minimal probabilities.
  Minimal probabilities are set as gamma, and the probabilities are then
  renormalized to sum to 1.
  Args:
    updated_strategy: New distribution value after being updated by update rule.
    gamma: minimal probability value when divided by number of actions.
  Returns:
    Projected distribution.
  """
  # Epsilon approximation of L2-norm projection onto the Delta_gamma space.
  updated_strategy[updated_strategy < gamma] = gamma
  updated_strategy = updated_strategy / np.sum(updated_strategy)
  return updated_strategy
```

I think this is not quite aligned with the [original definition (Sec 3.1)](https://arxiv.org/pdf/1711.00832.pdf), where the result is supposed to be the closest point in L2 distance on the simplex to updated_strategy. Just by replacing values less than gamma with gamma and renormalizing it doesn't feel right.

Here is my implementation based on [this paper](https://eng.ucmerced.edu/people/wwang5/papers/SimplexProj.pdf):
```
def project_on_clipped_simplex(v, gamma=0):
    """
    v is the vector to be projected on the gamma-simplex
    """
    N = len(v)
    l = np.sort(v)
    lam = (np.sum(l)-1)/N
    for i in range(N-1, 0, -1):
        pho = (1/(N-i)) * (np.sum(l[i:])-1+gamma * i)
        if(l[i-1] - pho < gamma):
            lam = pho
            break
    return np.maximum(v-lam, gamma)
```
In practice I doubt it may differ a little in terms of performance, but hope it is helpful.

**Comment by PaulFMMuller** [comment]
Hi @rezunli96 , thank you very much for the fix ! 
Indeed, I hadn't taken the time to do a proper L2 projection (As mentioned in the comment) ; thank you for taking care of this !

Out of curiosity, I've tried a vectorized version of this code, it must be the first time I see a for loop faster than numpy-vectorized code in Python, well done !
Please don't hesitate to put it in a pull request and add an option in PRD to use the "historical" (And incorrect) solver and the correct one, if only for reproduction purpose.

Thanks again,

Paul

**Comment by rezunli96** [comment]
Hi @PaulFMMuller , please expect a pull request [here](https://github.com/deepmind/open_spiel/pull/309). Thanks.

**Comment by lanctot** [comment]
Fixed by https://github.com/deepmind/open_spiel/pull/309, thanks!
