### ISSUE TITLE
[question] how to save and load trained model?

### ISSUE THREAD

**Issue by gsdt** [deepmind/open_spiel#315]
For example:
In file `open_spiel/python/examples/tic_tac_toe_dqn_vs_tabular.py`
I would like to save trained agents: 
```python
dqn_agent = dqn.DQN(
        sess,
        player_id=0,
        state_representation_size=state_size,
        num_actions=num_actions,
        hidden_layers_sizes=hidden_layers_sizes,
        replay_buffer_capacity=replay_buffer_capacity)
...

```
How to save dqn_agent?

**Comment by lanctot** [comment]
Unfortunately DQN does not support that yet. However, it should be relatively easy to do by using savers similar to NFSP and policy gradients (see `nfsp.py` and `policy_gradient.py`). 

It would make a nice contribution. If you do this, it would be great to submit a PR so everyone benefits!

**Comment by colibri17** [comment]
If the task is still useful, I can have a look at it! It does not seem to be too much complicated.

**Comment by lanctot** [comment]
I think this would still be quite useful. I also think it would be straight-forward since it would be quite similar to what we did in NFSP and policy gradients code.

**Comment by colibri17** [comment]
That's great, will work on that!

**Comment by lanctot** [comment]
Hi @gsdt, thanks to @colibri17 there is now a PR for this: https://github.com/deepmind/open_spiel/pull/437. I'll try to import it by next update.

**Comment by lanctot** [comment]
Fixed by https://github.com/deepmind/open_spiel/pull/437 which was merged today.
