### ISSUE TITLE
Processes Not Joining Properly In Python AlphaZero Implementation

### ISSUE THREAD

**Issue by alextrudeau** [deepmind/open_spiel#318]
I've been trying to perform a parameter sweep for AlphaZero in Connect Four and added some loops to open_spiel/python/examples/alpha_zero.py to do so. However, once AlphaZero is finished training with the first set of parameters, the program stops. I've spent today debugging and it seems like the actor and evaluator processes aren't joining properly. I get the following logging:

learner exiting
actor-0 exiting
.
.
.
evaluator-0 exiting

However, when I add a print statement at the end of alpha_zero() in open_spiel/python/algorithms/alpha_zero/alpha_zero.py:

```python
try:
    learner(game=game, config=config, actors=actors,  # pylint: disable=missing-kwoa
            evaluators=evaluators, broadcast_fn=broadcast)
  except (KeyboardInterrupt, EOFError):
    print("Caught a KeyboardInterrupt, stopping early.")
  finally:
    broadcast("")
    for proc in actors + evaluators:
      proc.join()
      print("Joined")
```

"Joined" is not printed.

I read the multiprocessing documentation: https://docs.python.org/3/library/multiprocessing.html#multiprocessing.Process and found the following:

> As mentioned above, if a child process has put items on a queue (and it has not used JoinableQueue.cancel_join_thread), then that process will not terminate until all buffered items have been flushed to the pipe. This means that if you try joining that process you may get a deadlock unless you are sure that all items which have been put on the queue have been consumed. Similarly, if the child process is non-daemonic then the parent process may hang on exit when it tries to join all its non-daemonic children.

With this in mind, I tried emptying q_in and q_out in spawn.py using get() before join() was called and also tried using Queue.cancel_join_thread() but wasn't able to fix the problem. Do you have any suggestions on how I can run my parameter sweep without running into this Process joining issue?

**Comment by lanctot** [comment]
@tewalds @sbodenstein, any ideas?

**Comment by StochasticEntropy** [comment]
The evaluator process seems to terminate correctly. The problem seems to be that the actor process can't finish while their _q_in is not empty. If I (patiently) empty it with

finally:
    broadcast("")
    for proc in actors + evaluators:
      while proc.queue._q_in.empty()==False:
        while proc.queue._q_in.empty()==False:
          proc.queue._q_in.get(False)
        time.sleep(0.1)
      proc.join()
      print('Joined')

The actor processes join as well

**Comment by lanctot** [comment]
@StochasticEntropy , should we add this to our code? Do you want to submit a PR?

**Comment by StochasticEntropy** [comment]
well, it's a very dirty fix. Better than nothing, but probably not the way a good software engineer would do it. But if nobody else wants to propose a better solution, it would be better than before. I didn't get deep enough into the code to being able to debug it better.

**Comment by lanctot** [comment]
Agree, but if you don't fix it, it will likely go unfixed as we don't have time for this right now-- which is probably worse. You can always put a comment to that effect and cite this discussion. I'll leave the issue open until there's a fix of or it stays open for a few months without any activity.
