### ISSUE TITLE
Cooperative box pushing giving unexpected observations

### ISSUE THREAD

**Issue by hynek-urban** [deepmind/open_spiel#32]
Hello,

according to the [paper](https://arxiv.org/pdf/1206.5295.pdf) referenced in connection to the "Cooperative Box-Pushing" game, the agents are supposed to receive observations that correspond to what they currently see in a given time step:

> After every time step each agent gets one out of 5 possible observations deterministically describing the situation of the environment in front of the agent: empty field,wall, other agent, small box, large box.

However, the game as implemented in OpenSpiel appears to return something else. In `time_step.observations["info_state"]`, each agent receives a field of 704 binary values which seems to correspond to the global state (704 = 64 cells x 11 possible cell states).

Also, the `GameType` flag `provides_information_state` is set to `true`, while `provides_observation` is set to false which also goes contrary to what I would expect after reading the paper.

Is this an oversight or is there a purpose behind this?

**Comment by lanctot** [comment]
Oops, this is my bad. I did not follow the paper closely, but not on purpose :)

We should provide both. The current one should be information state (evrn though it does not abide by perfect recall, though we will note this) and the one from the paper should be the observation.

I am on holiday at the moment so I can fix it next week. Or, also feel free to send us a PR with these changes instead!

**Comment by lanctot** [comment]
Just touching base that I still plan to do this ;-)
