### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by awesomettt** [deepmind/open_spiel#325]
Hello，
When I follow the detailed steps, some errors occured. When I run 'make -j$', the following error occurred.

My environment：
ubuntu 16.04.12
gcc 5.4.0
python 3.6.5

Error message:
In file included from /home/wuqi/wt/open_spiel/open_spiel/../open_spiel/game_parameters.h:23:0,
                 from /home/wuqi/wt/open_spiel/open_spiel/../open_spiel/spiel.h:36,
                 from /home/wuqi/wt/open_spiel/open_spiel/../open_spiel/policy.h:25,
                 from /home/wuqi/wt/open_spiel/open_spiel/../open_spiel/spiel_bots.h:22,
                 from /home/wuqi/wt/open_spiel/open_spiel/spiel_bots.cc:15:
/home/wuqi/wt/open_spiel/open_spiel/../open_spiel/spiel_utils.h: In instantiation of ‘void open_spiel::internal::SpielStrOut(Out&, const T&, Args&& ...) [with Out = std::__cxx11::basic_ostringstream<char>; T = int; Args = {const char (&)[2], const char (&)[57], const char (&)[28], const char (&)[4], std::vector<float, std::allocator<float> >&, const char (&)[32], std::vector<float, std::allocator<float> >&}]’:
/home/wuqi/wt/open_spiel/open_spiel/../open_spiel/spiel_utils.h:119:14:   recursively required from ‘void open_spiel::internal::SpielStrOut(Out&, const T&, Args&& ...) [with Out = std::__cxx11::basic_ostringstream<char>; T = char [2]; Args = {int, const char (&)[2], const char (&)[57], const char (&)[28], const char (&)[4], std::vector<float, std::allocator<float> >&, const char (&)[32], std::vector<float, std::allocator<float> >&}]’
/home/wuqi/wt/open_spiel/open_spiel/../open_spiel/spiel_utils.h:119:14:   required from ‘void open_spiel::internal::SpielStrOut(Out&, const T&, Args&& ...) [with Out = std::__cxx11::basic_ostringstream<char>; T = char [50]; Args = {const char (&)[2], int, const char (&)[2], const char (&)[57], const char (&)[28], const char (&)[4], std::vector<float, std::allocator<float> >&, const char (&)[32], std::vector<float, std::allocator<float> >&}]’
/home/wuqi/wt/open_spiel/open_spiel/../open_spiel/spiel_utils.h:133:14:   required from ‘std::__cxx11::string open_spiel::internal::SpielStrCat(Args&& ...) [with Args = {const char (&)[50], const char (&)[2], int, const char (&)[2], const char (&)[57], const char (&)[28], const char (&)[4], std::vector<float, std::allocator<float> >&, const char (&)[32], std::vector<float, std::allocator<float> >&}; std::__cxx11::string = std::__cxx11::basic_string<char>]’
/home/wuqi/wt/open_spiel/open_spiel/spiel_bots.cc:98:7:   required from here
/home/wuqi/wt/open_spiel/open_spiel/../open_spiel/spiel_utils.h:118:7: error: ambiguous overload for ‘operator<<’ (operand types are ‘std::__cxx11::basic_ostringstream<char>’ and ‘const int’)
   out << arg1;

In file included from /home/wuqi/wt/open_spiel/open_spiel/../open_spiel/game_parameters.h:23:0,
                 from /home/wuqi/wt/open_spiel/open_spiel/../open_spiel/spiel.h:36,
                 from /home/wuqi/wt/open_spiel/open_spiel/../open_spiel/policy.h:25,
                 from /home/wuqi/wt/open_spiel/open_spiel/../open_spiel/spiel_bots.h:22,
                 from /home/wuqi/wt/open_spiel/open_spiel/spiel_bots.cc:15:
/home/wuqi/wt/open_spiel/open_spiel/../open_spiel/spiel_utils.h:65:15: note: candidate: std::ostream& open_spiel::operator<<(std::ostream&, const int&)
 std::ostream& operator<<(std::ostream& stream, const std::nullopt_t& v);
               ^
In file included from /usr/include/c++/5/iterator:64:0,
                 from /home/wuqi/wt/open_spiel/open_spiel/../open_spiel/abseil-cpp/absl/algorithm/container.h:45,
                 from /home/wuqi/wt/open_spiel/open_spiel/../open_spiel/policy.h:24,
                 from /home/wuqi/wt/open_spiel/open_spiel/../open_spiel/spiel_bots.h:22,
                 from /home/wuqi/wt/open_spiel/open_spiel/spiel_bots.cc:15:
/usr/include/c++/5/ostream:519:5: note: candidate: std::basic_ostream<char, _Traits>& std::operator<<(std::basic_ostream<char, _Traits>&, unsigned char) [with _Traits = std::char_traits<char>]
     operator<<(basic_ostream<char, _Traits>& __out, unsigned char __c)
     ^
/usr/include/c++/5/ostream:514:5: note: candidate: std::basic_ostream<char, _Traits>& std::operator<<(std::basic_ostream<char, _Traits>&, signed char) [with _Traits = std::char_traits<char>]
     operator<<(basic_ostream<char, _Traits>& __out, signed char __c)
     ^
/usr/include/c++/5/ostream:508:5: note: candidate: std::basic_ostream<char, _Traits>& std::operator<<(std::basic_ostream<char, _Traits>&, char) [with _Traits = std::char_traits<char>]
     operator<<(basic_ostream<char, _Traits>& __out, char __c)
     ^
/usr/include/c++/5/ostream:502:5: note: candidate: std::basic_ostream<_CharT, _Traits>& std::operator<<(std::basic_ostream<_CharT, _Traits>&, char) [with _CharT = char; _Traits = std::char_traits<char>]
     operator<<(basic_ostream<_CharT, _Traits>& __out, char __c)
     ^
In file included from /home/wuqi/wt/open_spiel/open_spiel/../open_spiel/game_parameters.h:23:0,
                 from /home/wuqi/wt/open_spiel/open_spiel/../open_spiel/spiel.h:36,
                 from /home/wuqi/wt/open_spiel/open_spiel/spiel.cc:15:
/home/wuqi/wt/open_spiel/open_spiel/../open_spiel/spiel_utils.h:117:6: error: ‘void open_spiel::internal::SpielStrOut(Out&, const T&, Args&& ...) [with Out = std::__cxx11::basic_ostringstream<char>; T = char [2]; Args = {const char (&)[24], const char (&)[13], const char (&)[4], open_spiel::DeserializeGameAndState(const string&)::Section&, const char (&)[14], open_spiel::DeserializeGameAndState(const string&)::Section&}]’, declared using local type ‘open_spiel::DeserializeGameAndState(const string&)::Section’, is used but never defined [-fpermissive]
 void SpielStrOut(Out& out, const T& arg1, Args&&... args) {
      ^
/home/wuqi/wt/open_spiel/open_spiel/../open_spiel/spiel_utils.h:117:6: error: ‘void open_spiel::internal::SpielStrOut(Out&, const T&, Args&& ...) [with Out = std::__cxx11::basic_ostringstream<char>; T = char [2]; Args = {const char (&)[21], const char (&)[13], const char (&)[4], open_spiel::DeserializeGameAndState(const string&)::Section&, const char (&)[11], open_spiel::DeserializeGameAndState(const string&)::Section&}]’, declared using local type ‘open_spiel::DeserializeGameAndState(const string&)::Section’, is used but never defined [-fpermissive]
[ 31%] Linking CXX static library libabsl_random_seed_sequences.a
[ 31%] Built target absl_random_seed_sequences
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-everything’
CMakeFiles/open_spiel_core.dir/build.make:146: recipe for target 'CMakeFiles/open_spiel_core.dir/policy.cc.o' failed
make[2]: *** [CMakeFiles/open_spiel_core.dir/policy.cc.o] Error 1
cc1plus: warning: unrecognized command line option ‘-Wno-everything’
At global scope:
cc1plus: warning: unrecognized command line option ‘-Wno-everything’
CMakeFiles/open_spiel_core.dir/build.make:172: recipe for target 'CMakeFiles/open_spiel_core.dir/spiel.cc.o' failed
make[2]: *** [CMakeFiles/open_spiel_core.dir/spiel.cc.o] Error 1
CMakeFiles/open_spiel_core.dir/build.make:185: recipe for target 'CMakeFiles/open_spiel_core.dir/spiel_bots.cc.o' failed
make[2]: *** [CMakeFiles/open_spiel_core.dir/spiel_bots.cc.o] Error 1
CMakeFiles/Makefile2:971: recipe for target 'CMakeFiles/open_spiel_core.dir/all' failed
make[1]: *** [CMakeFiles/open_spiel_core.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 31%] Linking CXX static library libabsl_flags_config.a
[ 31%] Built target absl_flags_config
[ 31%] Linking CXX static library libabsl_raw_hash_set.a
[ 31%] Built target absl_raw_hash_set
Makefile:113: recipe for target 'all' failed
make: *** [all] Error 2

I would appreciate it if you could reply.

**Comment by lanctot** [comment]
Hi @awesomettt, 

I am guessing it's because the compiler is too old. We only officially support clang 9. If possible I would suggest upgrading to Ubuntu 18.04 or 20.04 but you can also install clang 9 on 16.04 by following this guide: https://justiceboi.github.io/blog/install-clang-9-on-ubuntu/

Let us know!

**Comment by lanctot** [comment]
Looking more closely, seems like `-Wno-everything` had just not been invented yet, maybe remove it (from CMakeLists.txt), remove and recreate the build dir, and try again. You might have to disable individual warnings or it might produce a lot of warnings.

**Comment by lanctot** [comment]
@awesomettt , any luck?

**Comment by awesomettt** [comment]
When I modified the CMakeLists.txt, the warning disappeared but the error remained. I will try it with Ubuntu 18.04. Thank you. @lanctot

**Comment by xiaowenwenwen** [comment]
@lanctot I followed your advice, it is very nice. When I used the clang9 in Ubuntu 18.04, It was compiled successfully. Only 4 errors appeared in the ctest stage. The errors are as follows.

98% tests passed, 4 tests failed out of 165

Total Test time (real) = 396.83 sec

The following tests FAILED:
	108 - python_neurd_test (Failed)
	121 - python_rcfr_test (Failed)
	151 - python_examples_bridge_supervised_learning (Failed)
	161 - run_python_test (Failed)
Errors while running CTest

**Comment by awesomettt** [comment]
@lanctot I followed your advice, it is very nice. When I used the clang9 in Ubuntu 18.04, It was compiled successfully. Only 4 errors appeared in the ctest stage. The errors are as follows.

98% tests passed, 4 tests failed out of 165

Total Test time (real) = 396.83 sec

The following tests FAILED:
108 - python_neurd_test (Failed)
121 - python_rcfr_test (Failed)
151 - python_examples_bridge_supervised_learning (Failed)
161 - run_python_test (Failed)
Errors while running CTest

**Comment by lanctot** [comment]
Ok tge first two use some special features of TF. Possibly your version is too old or too new. The third is likely because you did not install jax or dm-haiku. Last on probably PYTHONPATH not setup properly.

Coukd you run the tests manually and post the output? 

If those are the only 4 failing I think you wilo mostly ok but can help more if we could see the errors.

**Comment by lanctot** [comment]
Any update on this @awesomettt  ?
