### ISSUE TITLE
static lib compile

### ISSUE THREAD

**Issue by gkio** [deepmind/open_spiel#326]
how to compile it as static lib?

**Comment by lanctot** [comment]
Hi can you be more specific, are you looking for something that builds e.g. a `libopen_spiel.a` ?

**Comment by lanctot** [comment]
You might be able to achieve this by changing using similar logic to the shared lib here: https://github.com/deepmind/open_spiel/blob/3f79a3c1fb6f39071c48a2fc2e2e7190643094a9/open_spiel/CMakeLists.txt#L267 . You will have to consult the CMake docs but it might be as easy as just replacing `SHARED` with `STATIC`. Then you can build it by prepending the cmake command with `BUILD_WITH_SHARED=ON cmake ...`

**Comment by lanctot** [comment]
Any update @gkio ?
