### ISSUE TITLE
Installation Errors on Windows

### ISSUE THREAD

**Issue by Weihnachtshase** [deepmind/open_spiel#327]
Hi everyone!

I followed the installation instructions on Windows.
My current specifics are Windows 10 Version 2004 Build 19041.450, running WSL 2 and then Ubuntu 20.04.1 LTS

In the installtion instructions I skipped the part of updating make, because it said it's only necessary with Ubuntu Version 18.04 and I already have 20.04.
Besides omitting this step I followed all instructions. My errors arise when I type the 'make -j$' command.
The output is:

In file included from /home/seresheim/open_spiel/open_spiel/../open_spiel/spiel.h:36,
                 from /home/seresheim/open_spiel/open_spiel/spiel.cc:15:
/home/seresheim/open_spiel/open_spiel/../open_spiel/game_parameters.h:116:13: error: explicit specialization in non-namespace scope ‘class open_spiel::GameParameter’
  116 |   template <>
      |                        ^
/home/seresheim/open_spiel/open_spiel/../open_spiel/game_parameters.h:120:13: error: explicit specialization in non-namespace scope ‘class open_spiel::GameParameter’
  120 |   template <>
      |                        ^
/home/seresheim/open_spiel/open_spiel/../open_spiel/game_parameters.h:121:10: error: ‘double open_spiel::GameParameter::value() const’ cannot be overloaded with ‘int open_spiel::GameParameter::value() const’
  121 |   double value() const {
      |          ^~~~~
/home/seresheim/open_spiel/open_spiel/../open_spiel/game_parameters.h:117:7: note: previous declaration ‘int open_spiel::GameParameter::value() const’
  117 |   int value() const {
      |            ^~~~~

This is just part of the output, but it repeats for several other files and functions.
(On the console '>' and 'value()' is highlighted in red)

As far as I understand, this has something to do with c++, but I'm not that fluent in it.

Can somebody guide mit in the right direction on how to fix this?

Kind regards

**Comment by elkhrt** [comment]
This probably means you have an old version of clang. What version do you
have installed?

**Comment by Weihnachtshase** [comment]
Thanks for the fast reply.

I have clang version 10.0.0-4ubuntu1 (the one that comes per default with the Ubuntu App)

**Comment by Weihnachtshase** [comment]
To be honest I just recognized, that I wasn't event using clang, since in the installation instructions there is this line:
CXX=g++ cmake -DPython3_EXECUTABLE=$(which python3) -DCMAKE_CXX_COMPILER=g++ ../open_spiel

I now simply replaced the 'g++' for 'clang' in the above line and ran 'make -j$' again and it runs much longer. But at about 51% it gives mit a ton of output, that ends with:

/usr/bin/ld: ../abseil-cpp/absl/base/libabsl_raw_logging_internal.a(raw_logging.cc.o): in function `absl::lts_2020_02_25::raw_logging_internal::DefaultInternalLog(absl::lts_2020_02_25::LogSeverity, char const*, int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
raw_logging.cc:(.text+0x3a2): undefined reference to `std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >::c_str() const'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [examples/CMakeFiles/matrix_example.dir/build.make:155: examples/matrix_example] Error 1
make[1]: *** [CMakeFiles/Makefile2:4702: examples/CMakeFiles/matrix_example.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

**Comment by elkhrt** [comment]
Ah, sorry - it looks like we haven't updated the Windows installation
instructions.
I suspect you might need to make clean and rebuild everything with clang.

**Comment by lanctot** [comment]
It should be `clang++`. (For the exact command take a look at the manual Linux instructions.)

Can you try `rm -rf build venv` and start everything over with clang++? Some of the build info / filed may have been cached.

**Comment by Weihnachtshase** [comment]
it is working now
Thnak you very much!

**Comment by elkhrt** [comment]
Great! If you have time, it would be much appreciated if you could update
the Windows instructions.

**Comment by lanctot** [comment]
Re-opening to serve as a reminder to fix the Windows installation instructions.

**Comment by lanctot** [comment]
@Weihnachtshase in the end, was it just changing `g++` to `clang++`? Is there any other thing that should be modified in the Windows instructions?

**Comment by Weihnachtshase** [comment]
Yes it was just that.
Sorrry for not changing the instructions myself, I forogt about that

**Comment by lanctot** [comment]
No problem. It's a one-line change easy to do on our side!
