### ISSUE TITLE
Visualize game trees with SpielViz

### ISSUE THREAD

**Issue by michalsustr** [deepmind/open_spiel#329]
Hello, as a small side-kick I made [SpielViz](https://github.com/michalsustr/spielviz). I finally had a free weekend when I could put final things together. Enjoy!

It is based on another open source project which uses LGPL-3, so it cannot be integrated into OpenSpiel. However, if you feel like putting a link to it, I would be happy. :) In the docs there is a mention of publishing pyspiel as a pip package. What is the status on this, since there is an 0.1.0 version out there?

**Comment by lanctot** [comment]
Hi Michal, thanks for the PR!

> In the docs there is a mention of publishing pyspiel as a pip package. What is the status on this, since there is an 0.1.0 version out there?

In the next couple of months we will do another release, where we include prebuilt dynamically linked libraries supported on Linux x86_64 and (maybe) MacOSX. I already have this working on Ubuntu 20.04, we just have to put a release together, and I want to get LP solving in on the C++ side (via OR-Tools / GLPK) and hopefully merge the C++ Libtorch AlphaZero.

Once that's done it is a matter of figuring out how to deploy python-wrapped C++ project via pip / PyPI. Luckily we have someone who has done this internally already and they told me what is involved. Sounds like the trickiest thing is supporting several OSes (like three Ubuntu major versions, latest Debian and Fedora, MacOS, Windows) times several Python subversions (3.6, 3.7, 3.8) which are not backward compatible.

So it sounds straight-forward in theory, but it will take us time and resources for to setup a proper test environment and scaffolding necessary to support it long-term. 

We could possibly use some help from the community for this. I am currently on holiday but will open an issue to describe the plan for upcoming release and hosting on PyPI so we can discuss it there.

**Comment by lanctot** [comment]
Oops I thought it was a PR. Of course we are happy to point to this :) You can submit a PR to link to it whereever you think is most appropriate!

**Comment by michalsustr** [comment]
Thank you! :) Btw I recently made a PR to pybind and it seems their travis setup is pretty advanced. Maybe there is something useful to be learned from that project, as they deal with bunch of python versions / OSes etc.
