### ISSUE TITLE
Question: use case for Observer params?

### ISSUE THREAD

**Issue by michalsustr** [deepmind/open_spiel#335]
Hi @elkhrt , what is the use case for `GameParameters params` in `Game::MakeObserver`? https://github.com/deepmind/open_spiel/blob/master/open_spiel/spiel.h#L792

AFAIK it is currently not used, and these parameters should be accessible via Game::GetParameters(). I think this implies the observer would fill tensors for a different game than is actually played.

**Comment by elkhrt** [comment]
These are params for the observer, not for the game. The type name is
unfortunate.
For example, in bridge one might like to have the option to include
double-dummy results in the observation (or not), which could be controlled
by a flag in here.

**Comment by michalsustr** [comment]
Makes sense. Maybe it should be renamed then to `Parameter`, and we can keep GameParameter as an alias for backwards compatibility? Also I added a better comment.
