### ISSUE TITLE
Question: redundancy of State::*TensorShape methods

### ISSUE THREAD

**Issue by michalsustr** [deepmind/open_spiel#338]
Now that we have an `Observer` and all `State::*String/Tensor` methods are forwarded to `Observer,` custom `State::*TensorShape` seem redundant. @elkhrt is the plan to get rid of them as well? I think it could be implemented in `Game` as a call to `Observation::tensor_info()` (why the snake_case btw?), something like this:

```
virtual std::vector<int> InformationStateTensorShape() const {
    return ComputeShape(Observation(*this, MakeObserver(kInfoStateObsType, {})).tensor_info());
}
```
where `ComputeShape` will return flat shape if there are multiple tensors, and specific shape if there is only one tensor.

**Comment by elkhrt** [comment]
The default Observer implementation relies on
Game::InformationStateTensorShape et al, so we can't remove them yet. Once
all games use the new style, yes.
Snake case because its an accessor:
https://google.github.io/styleguide/cppguide.html#Function_Names

**Comment by michalsustr** [comment]
Makes sense. I added a PR to do this on per-game basis: #346
