### ISSUE TITLE
Question: goofspiel state round-robin encoding of NextPlayer

### ISSUE THREAD

**Issue by michalsustr** [deepmind/open_spiel#339]
The observations in Goofspiel are player relative, i.e. the requested player's observation will be at index 0, and the remaining players will be "modulo wrapped around", as in change:

Add ObservationString, ObservationTensor, and ObservationTensorShape to Goofspiel and make both tensors observing player-relative  PiperOrigin-RevId: 283363694 Change-Id: I205363c9d641a574e2018cb9312672c8b15e8d9f

I can't think of a justification for this. What is the reason?

**Comment by michalsustr** [comment]
Concerns #344

**Comment by elkhrt** [comment]
The idea is that there is no difference between p0 and p1 in goofspiel -
it's just an arbitrary labelling that we give the players. So the
observation should be invariant to swapping the player labels (in the 2p
case).

**Comment by michalsustr** [comment]
Sure, but it is not invariant in >2p case. I kept it the same, but it is a bit awkward.

**Comment by elkhrt** [comment]
Thanks! If you have an idea for a representation which is invariant in the
many-player case, please add it.

**Comment by michalsustr** [comment]
It would have to be permutation invariant, I think this is something that would have to be done by the neural network model, maybe something like this: https://papers.nips.cc/paper/6931-deep-sets.pdf (just skimmed the paper briefly).
