### ISSUE TITLE
Feature: automatic encoding and checks of DimensionedSpan

### ISSUE THREAD

**Issue by michalsustr** [deepmind/open_spiel#348]
The Observer's WriteTensor implementations contain boilerplate code for encoding one-hot vector representations. Instead of looping arrays and setting indices to 1 at some places, `DimensionedSpan` could have new methods to accept, check and appropriately copy vectors from which these observations are made. Wha do you think?

**Comment by lanctot** [comment]
We are now doing some form of this.
