### ISSUE TITLE
ModuleNotFoundError: No module named 'open_spiel'

### ISSUE THREAD

**Issue by hanyun2019** [deepmind/open_spiel#36]
I want to run open_spiel/python/examples/playthrough.py for an richer example generating a playthrough and printing all available information. (MacOS, Python 3.7.3)

The error message is:
ModuleNotFoundError: No module named 'open_spiel'

The snapshot is as the follows:
![image](https://user-images.githubusercontent.com/51042844/64497254-0f6f4080-d2df-11e9-8bec-26fe9512fd5b.png)

How can I import open_spiel.python.algorithms when I run the python program?
Thanks~

@lanctot

**Comment by lanctot** [comment]
Can you show me the output of `pwd` and `ls`?

**Comment by lanctot** [comment]
Can you run them from the same directory that you built fr

**Comment by hanyun2019** [comment]
The output of pwd and ls is as the follows:
![image](https://user-images.githubusercontent.com/51042844/64497422-8fe27100-d2e0-11e9-8115-aa104d610d84.png)

**Comment by hanyun2019** [comment]
Yes. I can run them from the same directory that I built from:
![image](https://user-images.githubusercontent.com/51042844/64497493-2adb4b00-d2e1-11e9-851a-d99fe5ef049d.png)

Thanks~ @lanctot

**Comment by lanctot** [comment]
Ok great. You just have PYTHONPATH set incorrectly (you have an extra open_spiel).

You should be able to run from anywhere with these commands:

```
export OPEN_SPIEL_HOME=/Users/user/documents/deeplearning/open_spiel
export PYTHONPATH=$PYTHONPATH:$OPEN_SPIEL_HOME:$OPEN_SPIEL_HOME/build_python_3/python
```

**Comment by hanyun2019** [comment]
Thanks~
I add your suggested PYTHONPATH in the file: ~/.bash_profile
![image](https://user-images.githubusercontent.com/51042844/64499784-0ab18900-d2ed-11e9-8d17-be43b3c27ed7.png)

![image](https://user-images.githubusercontent.com/51042844/64499876-68de6c00-d2ed-11e9-932e-f264dd4980b3.png)

I works perfect now!
