### ISSUE TITLE
Questions on adding new games

### ISSUE THREAD

**Issue by andrealbh** [deepmind/open_spiel#367]
Hi, I have followed the instructions to copy aa existed game to a new game but when I verified it before modifying, the error message said the newgame i copied is not registered.

**Comment by lanctot** [comment]
My guess is you forgot to change the unique name somewhere. Is it easy for you to show me your fork or create a PR?

(Probably will only reply tomorrow)

**Comment by lanctot** [comment]
Wait: you at least need to modify all the names, otherwise it will try to register the same game twice. Did you do that?

Also what executable or test are you running?

**Comment by andrealbh** [comment]
> Wait: you at least need to modify all the names, otherwise it will try to register the same game twice. Did you do that?
> 
> Also what executable or test are you running?

Thank you for your reply. I have forked the repo and uploaded a new_auction folder containing all related files. To make it more clear I also put the modified CMakeLists.txt and python/tests/pyspiel_test.py in the same folder. The new_auction is modified from first_sealed_auction game. I was doing the step 6, "python3 open_spiel/python/examples/example.py --game=new_auction" and it said it is not registered. Meanwhile I have another issue when installing open_spiel in a server and I will create another issue. thank you.

**Comment by lanctot** [comment]
Hi @andrealbh, you should not put it into a new directory. Just place it with the rest of the games under open_spiel/games. The problem is the rest of the code is not getting compiled with your new game because you have it in a separate dir with a separate CMakeLists.txt so example.cc has no way of knowing about it.

In principle you can do it this way but you need to then make sure it gets built in with the rest of the library if you plan to run it from our examples. So it is just easier if you put it alongside the other games and modify open_spiel/games/CMakeLists.txt directly.

**Comment by andrealbh** [comment]
> Hi @andrealbh, you should not put it into a new directory. Just place it with the rest of the games under open_spiel/games. The problem is the rest of the code is not getting compiled with your new game because you have it in a separate dir with a separate CMakeLists.txt so example.cc has no way of knowing about it.
> 
> In principle you can do it this way but you need to then make sure it gets built in with the rest of the library if you plan to run it from our examples. So it is just easier if you put it alongside the other games and modify open_spiel/games/CMakeLists.txt directly.

Sorry for making you misunderstand. I did put the new game files in the game folder and did not change the location of CMakeList.txt or pyspiel_test.py. I just want to avoid looking for files here and there if you are willing to review my code so I create the new game fold in the fork and copy related files to this folder.

**Comment by lanctot** [comment]
Ah right, I see. What you did seems perfectly fine to me. Can you try rebuilding and then paste the exact command you run and its output?

**Comment by lanctot** [comment]
You might need to redo the whole build process once you modify CMakeLists, i.e. all the way back to the cmake command. This is because CMake generates make files, and at the time you ran it maybe your new additions were not in them?

So I would remove the build dirs: `rm -rd build venv`, rebuild, and try again. And if it still doesn't work please past the command and its output.

**Comment by andrealbh** [comment]
> You might need to redo the whole build process once you modify CMakeLists, i.e. all the way back to the cmake command. This is because CMake generates (and caches) make files, and at the time you ran it maybe your new additions were not in them?
> 
> So I would remove the build dirs: `rm -rf build venv`, rebuild, and try again. And if it still doesn't work please past the command and its output.

Yes it works. Should I do these again every time I add a new game?

**Comment by lanctot** [comment]
I think you don't necessarily need to completely delete the directories, only rerun the CMake command to regenerate / overwrite the cache makefiles every time you touch CMakeLists.txt. So this would save having to rebuild from scratch. I only suggested it this time to rule every possibility out. 

BTW, I'd love to see more auction games.. so I would strongly encourage you to submit the game as a PR when it's finished!

**Comment by andrealbh** [comment]
> I think you don't necessarily need to completely delete the directories, only rerun the CMake command to regenerate / overwrite the cached makefiles every time you touch one of the CMakeLists.txt. So this would save having to rebuild from scratch. I only suggested it this time to rule every possibility out.
> 
> BTW, I'd love to see more auction games.. so I encourage you to submit the game as a PR when it's finished!

Thanks. We would try our best to do some contributions.
