### ISSUE TITLE
Unable to get Observation/StateInformation for the game of go

### ISSUE THREAD

**Issue by Gregory-Eales** [deepmind/open_spiel#37]
there seems to be no way to access the go board using the python API

**Comment by lanctot** [comment]
You are right, it is simply missing.

Should be quite easy to add go::GoGame::Observation and go::GoGame::ObservationAsNormalizedVector (similar to chess::ChessGame::InformationSetAsNormalizedVector).

Feel free to submit a pull request! Otherwise, we will add it in one of the next updates.

**Comment by lanctot** [comment]
BTW this should be relatively straight-forward, only requiring inspecting the underlying go board object declared here: https://github.com/deepmind/open_spiel/blob/26349aeb2c09cbe8f876678007f9543bf51aa28a/open_spiel/games/go.h#L88
