### ISSUE TITLE
Feature: Bot registration API

### ISSUE THREAD

**Issue by michalsustr** [deepmind/open_spiel#373]
It would be great if we could have a bot API similar to the one for games, such as 
```
std::unique_ptr<Bot> bot = LoadBot("xyz");
std::vector<std::string> RegisteredBots();
```

We could also add the following method to the `Bot` interface:
```
bool CanPlayGame(const Game&);
```

The bots right now are disorganized -- Roshambo is in `bots/`, but xinxin is illogically in `games/hearts/`. I can put it together more nicely. This will also provide a structure for adding other external bots in the future, like Stockfish. What do you think?

**Comment by lanctot** [comment]
I think this is a neat idea, would make running tournaments (with customized bot e.g. built outside the lib, i.e. for course projects etc.) easier too.

@elkhrt @jblespiau wdyt?

**Comment by lanctot** [comment]
Will be merged by https://github.com/deepmind/open_spiel/pull/384, so closing for now.
