### ISSUE TITLE
Small usability improvements for Swift

### ISSUE THREAD

**Issue by vojtamolda** [deepmind/open_spiel#375]
Dear DeepMind team,

I'm working on exercises from [_Sutton & Barto '18_](http://incompleteideas.net/book/the-book-2nd.html) book and to make things more fun and learn something new I implemented the games and algorithms in OpenSpiel `GameProtocol`.

I hit a two small bumps along the road, so I figured it would be nice to fix the "virtual potholes" and pay the community back.

1) [`GameInfo`](https://github.com/deepmind/open_spiel/blob/91da643188fcacd7a57bf5a64ee392d6c919dcfc/swift/Sources/OpenSpiel/Spiel.swift#L242) struct doesn't have a _public_ initializer. Swift by default synthesizes a member-wise `init(...)` for every struct but the access level is only _internal_. This internal initializer is called by all Swift games implemented here in the repo.

   The problem happens when you try to implement a game outside of the `OpenSpiel` module in a separate package that only depends on `OpenSpiel` to import the `GameProtocol`. Not having the initializer makes implementing the `GameProtocol` by third party packages more complicated.

   I don't think this is intentional. I think there should be a public member-wise constructor but I'm not 100% sure.

2) Building with latest (0.11) [S4TF](https://github.com/tensorflow/swift/blob/master/Installation.md) toolchain on macOS fails with the following error:
   ```sh
   $> swift build
   ...
   error: compiling for macOS 10.10, but module 'TensorFlow' has a minimum deployment target of macOS 10.13
   ...
   ```
   I [googled the error message](https://github.com/t-ae/swim/issues/10) and it looks like the S4TF toolchain indeed requires at least macOS 10.13. Maybe there is a way to enforce this on the command line but the most fool-proof fix seems to be adding `platforms` section to the `Package.swift` manifest. This will make plain `swift build` work again.
   ```swift
   platforms: [.macOS(.v10_13)],
   ```
   The change sounds simple enough but it opens a whole can of worms - Swift version upgrade. The problem is that the `platforms` argument was introduced in Swift 5. So making the updated`Package.swift` work requires lifting the minimal Swift tools version requirement.

   The decision whether this is okay or not is way above my pay grade of an anonymous volunteer 😉. I've noticed that there's already a `v0.1.0` release. So maybe people that use older Swift versions could still use `v0.1.0`.  And version `v0.2.0` could be Swift 5? I think not having the ability to build with the S4TF toolchain is a big enough bummer to warrant an upgrade.

3) Would you be interested in having games from the exercises in [_Sutton & Barto '18_](http://incompleteideas.net/book/the-book-2nd.html) merged here? I think it could be of some use when one develops and tests a new algorithm. The exercises have well tested solutions so bugs have a better chance of being spotted.

---

I already implemented fixes to 1. and 2. in [my private fork](https://github.com/vojtamolda/open_spiel). Here's [a diff of the changes](https://github.com/deepmind/open_spiel/compare/master...vojtamolda:master) for easier review.

I'll be happy to create a PR with the fixes but I figured it would be better to ask and discuss it first.

Cheers,

  Vojta

**Comment by vojtamolda** [comment]
Just a small remark about point **1**. I was able to figure out two workarounds:

- **A** Use `@testable` modifier. This is a quite ugly hack obviously intended for testing but it allows import of symbols with _internal_ access level.
   ```swift
   @testable import OpenSpiel
   ```

- **B** Member-wise extension of the `GameInfo` struct that calls the internal initilizer. This is cleaner than A. but it's a ton of boilerplate code.
   ```swift
   extension GameInfo {
       /// Workaround for missing public memberwise initializer.
       init(shortName: String, longName: String, dynamics: GameInfo.Dynamics,
            chanceMode: GameInfo.ChanceMode, information: GameInfo.Information,
            utility: GameInfo.Utility, rewardModel: GameInfo.RewardModel,
            maxPlayers: Int, minPlayers: Int,
            providesInformationStateString: Bool, providesInformationStateTensor: Bool) {
           self.init(shortName: shortName, longName: longName, dynamics: dynamics,
                     chanceMode: chanceMode, information: information,
                     utility: utility, rewardModel: rewardModel,
                     maxPlayers: maxPlayers, minPlayers: minPlayers,
                     providesInformationStateString: providesInformationStateString,
                     providesInformationStateTensor: providesInformationStateTensor
           )
       }
   }
   ```

**Comment by elkhrt** [comment]
Thanks; these are all good changes - please do submit a PR. For point 1,
you can just put the (tedious) public unit in the definition of GameInfo if
you prefer.

Thanks!

Ed
