### ISSUE TITLE
GameParameter with string literal is not recognized as string but rather as bool

### ISSUE THREAD

**Issue by gabrfarina** [deepmind/open_spiel#380]
While implementing the Battleship game (#376) I noticed that the following assertion fails, contrary to what I was expecting:

```
SPIEL_CHECK_TRUE(GameParameter("1").has_string_value());    // FAILS
```

On the other hand, this passes:
```
SPIEL_CHECK_TRUE(GameParameter("1").has_bool_value());      // PASS
```

I think this is a serious papercut, due to quirks in the C++ ISO standard (see §13.3.3.1.1 and especially [§13.3.3.2.2](http://www.open-std.org/JTC1/SC22/WG21/docs/papers/2011/n3242.pdf#page=321)).
I'm happy to open a pull request addressing this.

**Comment by elkhrt** [comment]
Thanks for pointing this out!
The easy fix is to add an overload accepting const char". A contribution
would be welcome!

**Comment by gabrfarina** [comment]
Perfect, it's done. I'll rebase my battleship branch once #381 lands.

**Comment by lanctot** [comment]
Wow, that is a nasty one! Thanks for the fix.
