### ISSUE TITLE
Implementation of external sampling mccfr in Python

### ISSUE THREAD

**Issue by colibri17** [deepmind/open_spiel#394]
I was wondering if you planned to develop the external sampling version of MCCFR in Python. 

I noticed that the outcome sampling version is already in place (`outcome_sampling_mccfr.py`) and that it is possible to call the external sampling version by using the C++ version (`mccfr_cpp_example.py`), but for me it would be useful to also have the direct implementation in Python.

Are you open to contributions for this task?

**Comment by lanctot** [comment]
Yes, this sounds like a great thing to have (a bit surprised we don't already!)

I would love it if you mirrored the C++ version that handles the case of more than two players (and, if you want, has a way to specify different ways to do the averaging).

**Comment by colibri17** [comment]
That's great! I will have a deep look at the C++ version then before starting with the implementation. I will keep you updated!

**Comment by lanctot** [comment]
Imported now from https://github.com/deepmind/open_spiel/pull/410, so closing this. Thanks @colibri17 !
