### ISSUE TITLE
Trouble with build_and_run_tests

### ISSUE THREAD

**Issue by amokhvarma** [deepmind/open_spiel#400]
Can someone tell me what the problem is? I am using clang-8 as default and gcc/g++ 7.5.
![image](https://user-images.githubusercontent.com/56398422/95423707-25768700-095f-11eb-88a7-b63f37f1c6cf.png)
Thank you

**Comment by lanctot** [comment]
Hi @amokhvarma, you need clang >= 9. Which version of Ubuntu are you using? It _should_ be as simple as `apt-get install clang-9`, but on some older Ubuntu versions you might need to add a repository.

**Comment by amokhvarma** [comment]
Hi . Thanks, I changed my clang and now clang --version gives 9 by default . But I noticed that while building , it shows "CXX compiler identification is Clang 6.0.0 " . So I think there is some path problem . Can you also tell me how to change that explicitly ?(As it is not taking the default value, I guess maybe there is some assumption about the path) . Thank you !

**Comment by lanctot** [comment]
I think you have to start fresh and rerun CMake to remove the cache (because CMake was run when you had the older compiler, it caches some paths etc.). So run `rm -rf build venv` and start again.

**Comment by lanctot** [comment]
If not, try this maybe? https://askubuntu.com/questions/1198087/how-to-set-clang-9-as-the-default-c-compiler-on-ubuntu-19-10

**Comment by amokhvarma** [comment]
Hi. Thanks. I tried that. All my defaults are at the required level. (I used clang++/g++/c++ -o out trial.cpp, a file which compiles only with c++17) [The error I am getting is because of difference between c++17 and lower version,I think ] .  Is it possible to find out the place in the code where the compiler location is decided. I can edit that maybe?

**Comment by lanctot** [comment]
Did you try removing the build directory to refresh the CMake cache?

**Comment by amokhvarma** [comment]
I deleted the existing directory and cloned a fresh repository from github. After that I confirmed that my default setting in sudo update-alternatives --config c++ is clang-9. Then I installed the requirements and then ran the build command. It is still showing Clang 6.0

**Comment by lanctot** [comment]
can you try prefixing the build command with `CXX=/usr/bin/clang++`  (or whereever your clang-9 binary lives?)

**Comment by amokhvarma** [comment]
See how the CC changes to Clang-9 but not CXX. I have also printed the current environment variables.
![image](https://user-images.githubusercontent.com/56398422/95509897-bf2b4c00-09d2-11eb-8a3d-7744ca882b96.png)
(I had installed clang9 separately as I am using Ubuntu 16, so it is not in usr/bin/foo and is instead in the path shown. Do you think the build file might be looking for it in /usr/bin/clang ? )

**Comment by lanctot** [comment]
Alright could you try the manual build instead?

```
rm -rf build
mkdir build
CXX=/usr/local/clang_9.0.0/bin/clang++ cmake -DPython3_EXECUTABLE=$(which python3) -DCMAKE_CXX_COMPILER=${CXX} ../open_spiel
make -j$(nproc)
ctest -j$(nproc)
```

**Comment by amokhvarma** [comment]
The above method worked. Thanks! I was able to reach till ctest part and only half the tests passed
![image](https://user-images.githubusercontent.com/56398422/95547276-320ee400-0a20-11eb-8a78-e979586b3c11.png)

The venv is python3.7 and all requirements were installed correctly. Does this look like a python problem?

**Comment by lanctot** [comment]
Can you show me the output of `which python3` and `python3`. E.g. this is mine:

```
lanctot@lanctot:~$ which python3
/usr/bin/python3
lanctot@lanctot:~$ python3
Python 3.8.5 (default, Jul 20 2020, 18:32:44) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

**Comment by lanctot** [comment]
Also :Did you run `./install.sh` to get the dependencies, specifically pybind11? Can you also paste the output of `ls -l` in the main directory (the one with `build` and `venv` in it)?

**Comment by amokhvarma** [comment]
Yes I started with  ``` ./install.sh ```
![image](https://user-images.githubusercontent.com/56398422/95568818-524f9a80-0a42-11eb-9487-cf91be4f0db4.png)
I am using venv, so it is showing the python corresponding to it. Is this the output you wanted?

**Comment by lanctot** [comment]
I wanted one directory above that to make sure you have a `pybind11` subdirectory.

Alright, can you try again but delete the venv subdirectory too:

```
rm -rf build venv
mkdir build
# remake the venv manually and get pip dependencies before running the rest, see link below
CXX=/usr/local/clang_9.0.0/bin/clang++ cmake -DPython3_EXECUTABLE=/home/amokh/PycharmProjects/index/last/bin/Python3 -DCMAKE_CXX_COMPILER=${CXX} ../open_spiel
make -j$(nproc)
ctest -j$(nproc)
```

I'm not an expert with venv.. my guess is it's failing due to not setting up venv properly. You might want to take a look through our `build_and_run_tests.sh` script and see how it sets up venv. I would deactive and set it up again, and follow the steps in https://github.com/deepmind/open_spiel/blob/master/docs/install.md  (in particular, the steps about when to be within venv and when not). 

I usually just setup pip locally as my user rather than use venv. Instructions for how to do that are in the OpenSpiel paper: https://arxiv.org/abs/1908.09453.

**Comment by lanctot** [comment]
What might be easier actually is just editing the build script and manually replacing it with the values that finally worked for you, i.e. hardcoding the CXX path to clang 9 in the cmake command.

**Comment by amokhvarma** [comment]
I think the problem was that I did not see the instruction to deactivate virtualenv(now i am using virtualenv ) before upgrading pip. Anyway, I am still failing 1 test. (I have confirmed that I have pybind11)
![image](https://user-images.githubusercontent.com/56398422/95594542-b7b68200-0a68-11eb-8300-b6974d263468.png)
We are almost there :P, I really appreciate your help!!

**Comment by lanctot** [comment]
Yes that test occasionally fails for people because it requires having PYTHONPATH setup in a specific way (it's a super simple test that tries to run one of our python examples by loading python from C++). Unless you plan to do that, I would say it's safe to ignore.. so you _are_ indeed there! :) 

No problem, enjoy!

**Comment by amokhvarma** [comment]
Excellent. Thanks a lot ! :D
