### ISSUE TITLE
tensorflow2.2.1 not found

### ISSUE THREAD

**Issue by pratapram** [deepmind/open_spiel#408]
During fresh install of openspiel, pip install of requirements fails on MacOS.

$ python3 -m pip install .
Processing /Users/swetha/Desktop/OrbitalVelocity/ai/open_spiel
Requirement already satisfied: pip>=20.0.2 in ./venv/lib/python3.8/site-packages (from pyspiel==0.0.1rc2) (20.2.3)
Collecting absl-py==0.9.0
  Using cached absl-py-0.9.0.tar.gz (104 kB)
ERROR: Could not find a version that satisfies the requirement tensorflow==2.2.1 (from pyspiel==0.0.1rc2) (from versions: 2.2.0rc3, 2.2.0rc4, 2.2.0, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.3.0)
ERROR: No matching distribution found for tensorflow==2.2.1 (from pyspiel==0.0.1rc2)

$ pip3 --version
pip 20.2.3 from ~/OrbitalVelocity/ai/open_spiel/venv/lib/python3.8/site-packages/pip (python 3.8)

**Comment by lanctot** [comment]
Hmm.. ok, can you tell me what instructions you have followed? E.g. did you run `./install.sh` ?

We use MacOS in our weekly tests and it's been working since that change to 2.2.1. So I'm guessing this will possibly due to a local setup.

**Comment by pratapram** [comment]
I am following instructions from here https://github.com/deepmind/open_spiel/blob/master/docs/install.md

To be specific, I followed instructions in this section:

https://github.com/deepmind/open_spiel/blob/master/docs/install.md#summary

**Comment by lanctot** [comment]
Can you post a full transcript of the output of those two commands at the start of the summary section (before step 1)

**Comment by pratapram** [comment]
$ ./install.sh
++++ realpath ./install.sh
+++ dirname /Users/swetha/Desktop/OrbitalVelocity/ai/open_spiel/install.sh
++ MYDIR=/Users/swetha/Desktop/OrbitalVelocity/ai/open_spiel
+++ basename /Users/swetha/Desktop/OrbitalVelocity/ai/open_spiel
++ [[ open_spiel == \s\c\r\i\p\t\s ]]
++ source /Users/swetha/Desktop/OrbitalVelocity/ai/open_spiel/open_spiel/scripts/global_variables.sh
+++ export DEFAULT_OPTIONAL_DEPENDENCY=OFF
+++ DEFAULT_OPTIONAL_DEPENDENCY=OFF
+++ export BUILD_WITH_PYTHON=ON
+++ BUILD_WITH_PYTHON=ON
+++ export BUILD_WITH_HANABI=OFF
+++ BUILD_WITH_HANABI=OFF
+++ export BUILD_WITH_ACPC=OFF
+++ BUILD_WITH_ACPC=OFF
+++ export BUILD_WITH_JULIA=OFF
+++ BUILD_WITH_JULIA=OFF
+++ export BUILD_WITH_EIGEN=OFF
+++ BUILD_WITH_EIGEN=OFF
+++ export BUILD_WITH_XINXIN=OFF
+++ BUILD_WITH_XINXIN=OFF
+++ export BUILD_WITH_ROSHAMBO=OFF
+++ BUILD_WITH_ROSHAMBO=OFF
+++ export BUILD_WITH_LIBTORCH=OFF
+++ BUILD_WITH_LIBTORCH=OFF
+++ export BUILD_WITH_PUBLIC_STATES=OFF
+++ BUILD_WITH_PUBLIC_STATES=OFF
+++ export BUILD_WITH_GAMUT=OFF
+++ BUILD_WITH_GAMUT=OFF
+++ export BUILD_WITH_ORTOOLS=OFF
+++ BUILD_WITH_ORTOOLS=OFF
++ DEFAULT_DOWNLOAD_CACHE_DIR=/Users/swetha/Desktop/OrbitalVelocity/ai/open_spiel/download_cache
++ DOWNLOAD_CACHE_DIR=/Users/swetha/Desktop/OrbitalVelocity/ai/open_spiel/download_cache
++ [[ -d /Users/swetha/Desktop/OrbitalVelocity/ai/open_spiel/download_cache ]]
++ git --version
++ GIT_IS_AVAILABLE=0
++ '[' 0 -ne 0 ']'
++ [[ -d ./pybind11 ]]
++ [[ -d open_spiel/games/bridge/double_dummy_solver ]]
++ [[ ! -d open_spiel/abseil-cpp ]]
++ DIR=open_spiel/games/hanabi/hanabi-learning-environment
++ [[ OFF == \O\N ]]
++ DIR=open_spiel/games/universal_poker/acpc
++ [[ OFF == \O\N ]]
++ DIR=open_spiel/eigen/libeigen
++ [[ OFF == \O\N ]]
++ DIR=open_spiel/bots/xinxin/hearts
++ [[ OFF == \O\N ]]
++ DIR=open_spiel/bots/roshambo/roshambo
++ [[ OFF == \O\N ]]
++ DIR=open_spiel/libtorch/libtorch
++ [[ OFF == \O\N ]]
++ [[ OFF == \O\N ]]
++ [[ darwin17 == \l\i\n\u\x\-\g\n\u ]]
++ [[ darwin17 == \d\a\r\w\i\n* ]]
+++ which realpath
++ [[ -x /usr/local/bin/realpath ]]
+++ which cmake
++ [[ -x /usr/local/bin/cmake ]]
+++ which python3
++ [[ -x /Users/swetha/Desktop/OrbitalVelocity/ai/open_spiel/venv/bin/python3 ]]
+++ python3 -c 'import tkinter'
+++ which clang++
++ [[ -x /usr/bin/clang++ ]]
+++ which curl
++ [[ -x /Users/swetha/anaconda3/bin/curl ]]
++ curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1841k  100 1841k    0     0  3529k      0 --:--:-- --:--:-- --:--:-- 3624k
++ python3 get-pip.py
Collecting pip
  Using cached pip-20.2.3-py2.py3-none-any.whl (1.5 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.2.3
    Uninstalling pip-20.2.3:
      Successfully uninstalled pip-20.2.3
Successfully installed pip-20.2.3
++ pip3 install virtualenv
Requirement already satisfied: virtualenv in ./venv/lib/python3.8/site-packages (20.0.35)
Requirement already satisfied: appdirs<2,>=1.4.3 in ./venv/lib/python3.8/site-packages (from virtualenv) (1.4.4)
Requirement already satisfied: filelock<4,>=3.0.0 in ./venv/lib/python3.8/site-packages (from virtualenv) (3.0.12)
Requirement already satisfied: six<2,>=1.9.0 in ./venv/lib/python3.8/site-packages (from virtualenv) (1.15.0)
Requirement already satisfied: distlib<1,>=0.3.1 in ./venv/lib/python3.8/site-packages (from virtualenv) (0.3.1)




$ ./open_spiel/scripts/build_and_run_tests.sh
\e[1m\e[93mVirtualenv already detected. We do not create a new one.\e[0m
\e[33mRunning ./open_spiel/scripts/build_and_run_tests.sh from /Users/swetha/Desktop/OrbitalVelocity/ai/open_spiel\e[0m
\e[33mSkipping installation of requirements.txt.\e[0m
Building and testing in /Users/swetha/Desktop/OrbitalVelocity/ai/open_spiel/build using 'python' (version 3.8.0).
Current build type is: Testing
BUILD_WITH_ACPC: OFF 
BUILD_WITH_EIGEN: OFF 
BUILD_WITH_HANABI: OFF 
BUILD_WITH_JULIA: OFF 
BUILD_WITH_LIBTORCH: OFF 
BUILD_WITH_PUBLIC_STATES: OFF 
BUILD_WITH_PYTHON: ON 
BUILD_WITH_XINXIN: OFF 
BUILD_WITH_ROSHAMBO: OFF 
BUILD_WITH_GAMUT: OFF 
BUILD_WITH_ORTOOLS: OFF 
-- Found Python3: /Users/swetha/Desktop/OrbitalVelocity/ai/open_spiel/venv/bin/python3 (found version "3.8.0") found components: Interpreter Development Development.Module Development.Embed 
Python include dirs: /Users/swetha/.pyenv/versions/3.8.0/include/python3.8
-- Configuring done
You have changed variables that require your cache to be deleted.
Configure will be re-run and you may have to reset some variables.
The following variables have changed:
CMAKE_CXX_COMPILER= /usr/bin/clang++
CMAKE_CXX_COMPILER= /usr/bin/clang++

-- The C compiler identification is AppleClang 10.0.0.10001044
-- The CXX compiler identification is AppleClang 10.0.0.10001044
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Current build type is: Testing
BUILD_WITH_ACPC: OFF 
BUILD_WITH_EIGEN: OFF 
BUILD_WITH_HANABI: OFF 
BUILD_WITH_JULIA: OFF 
BUILD_WITH_LIBTORCH: OFF 
BUILD_WITH_PUBLIC_STATES: OFF 
BUILD_WITH_PYTHON: ON 
BUILD_WITH_XINXIN: OFF 
BUILD_WITH_ROSHAMBO: OFF 
BUILD_WITH_GAMUT: OFF 
BUILD_WITH_ORTOOLS: OFF 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found Python3: /Users/swetha/Desktop/OrbitalVelocity/ai/open_spiel/venv/bin/python3.8 (found version "3.8.0") found components: Interpreter Development Development.Module Development.Embed 
Python include dirs: /Users/swetha/.pyenv/versions/3.8.0/include/python3.8
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/swetha/Desktop/OrbitalVelocity/ai/open_spiel/build
Building project
Scanning dependencies of target open_spiel_core
[  0%] Building CXX object abseil-cpp/absl/base/CMakeFiles/absl_exponential_biased.dir/internal/exponential_biased.cc.o
[  1%] Building CXX object CMakeFiles/open_spiel_core.dir/canonical_game_strings.cc.o
[  1%] Linking CXX static library libabsl_exponential_biased.a
[  1%] Built target absl_exponential_biased
[  1%] Building CXX object CMakeFiles/open_spiel_core.dir/fog/observation_history.cc.o
[  1%] Building CXX object abseil-cpp/absl/base/CMakeFiles/absl_log_severity.dir/log_severity.cc.o
In file included from /Users/swetha/Desktop/OrbitalVelocity/ai/open_spiel/open_spiel/fog/observation_history.cc:15:
In file included from /Users/swetha/Desktop/OrbitalVelocity/ai/open_spiel/open_spiel/../open_spiel/fog/observation_history.h:24:
In file included from /Users/swetha/Desktop/OrbitalVelocity/ai/open_spiel/open_spiel/../open_spiel/spiel.h:36:
/Users/swetha/Desktop/OrbitalVelocity/ai/open_spiel/open_spiel/../open_spiel/game_parameters.h:133:7: error: explicit specialization of 'value' in class scope
  int value() const {
      ^
/Users/swetha/Desktop/OrbitalVelocity/ai/open_spiel/open_spiel/../open_spiel/game_parameters.h:137:10: error: explicit specialization of 'value' in class scope
  double value() const {
         ^
/Users/swetha/Desktop/OrbitalVelocity/ai/open_spiel/open_spiel/../open_spiel/game_parameters.h:141:22: error: explicit specialization of 'value' in class scope
  const std::string& value() const {
                     ^
/Users/swetha/Desktop/OrbitalVelocity/ai/open_spiel/open_spiel/../open_spiel/game_parameters.h:145:15: error: explicit specialization of 'value' in class scope
  std::string value() const {
              ^
/Users/swetha/Desktop/OrbitalVelocity/ai/open_spiel/open_spiel/../open_spiel/game_parameters.h:149:8: error: explicit specialization of 'value' in class scope
  bool value() const {
       ^
/Users/swetha/Desktop/OrbitalVelocity/ai/open_spiel/open_spiel/../open_spiel/game_parameters.h:153:47: error: explicit specialization of 'value' in class scope
  const std::map<std::string, GameParameter>& value() const {
                                              ^
/Users/swetha/Desktop/OrbitalVelocity/ai/open_spiel/open_spiel/../open_spiel/game_parameters.h:157:40: error: explicit [  1%] Linking CXX static library libabsl_log_severity.a
specialization of 'value' in class scope
  std::map<std::string, GameParameter> value() const {
                                       ^
[  1%] Built target absl_log_severity
[  1%] Building CXX object abseil-cpp/absl/base/CMakeFiles/absl_spinlock_wait.dir/internal/spinlock_wait.cc.o
[  1%] Linking CXX static library libabsl_spinlock_wait.a
[  1%] Built target absl_spinlock_wait
[  1%] Building CXX object abseil-cpp/absl/base/CMakeFiles/absl_raw_logging_internal.dir/internal/raw_logging.cc.o
7 errors generated.
make[2]: *** [CMakeFiles/open_spiel_core.dir/fog/observation_history.cc.o] Error 1
make[1]: *** [CMakeFiles/open_spiel_core.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  1%] Linking CXX static library libabsl_raw_logging_internal.a
[  1%] Built target absl_raw_logging_internal
make: *** [all] Error 2

**Comment by lanctot** [comment]
Can you remove the build dir and try prefixing the build command with the following:

```
rm -rf build venv
CXX=/usr/bin/clang++ ./open_spiel/scripts/build_and_run_tests.sh
```

**Comment by pratapram** [comment]
@lanctot 

(venv) $ rm -rf build venv
(venv) $ CXX=/usr/bin/clang++ ./open_spiel/scripts/build_and_run_tests.sh
\e[1m\e[93mVirtualenv already detected. We do not create a new one.\e[0m
\e[33mRunning ./open_spiel/scripts/build_and_run_tests.sh from /Users/swetha/Desktop/OrbitalVelocity/ai/open_spiel\e[0m
\e[33mSkipping installation of requirements.txt.\e[0m
Building and testing in /Users/swetha/Desktop/OrbitalVelocity/ai/open_spiel/build using 'python' (version 3.8.0).
-- The C compiler identification is AppleClang 10.0.0.10001044
-- The CXX compiler identification is AppleClang 10.0.0.10001044
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/clang++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Current build type is: Testing
BUILD_WITH_ACPC: OFF 
BUILD_WITH_EIGEN: OFF 
BUILD_WITH_HANABI: OFF 
BUILD_WITH_JULIA: OFF 
BUILD_WITH_LIBTORCH: OFF 
BUILD_WITH_PUBLIC_STATES: OFF 
BUILD_WITH_PYTHON: ON 
BUILD_WITH_XINXIN: OFF 
BUILD_WITH_ROSHAMBO: OFF 
BUILD_WITH_GAMUT: OFF 
BUILD_WITH_ORTOOLS: OFF 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Success
-- Found Threads: TRUE  
-- Found Python3: /Users/swetha/.pyenv/shims/python3 (found version "3.8.0") found components: Interpreter Development Development.Module Development.Embed 
Python include dirs: /Users/swetha/.pyenv/versions/3.8.0/include/python3.8
-- Configuring done
-- Generating done
-- Build files have been written to: /Users/swetha/Desktop/OrbitalVelocity/ai/open_spiel/build
Building project
Scanning dependencies of target absl_exponential_biased
Scanning dependencies of target open_spiel_core
[  0%] Building CXX object abseil-cpp/absl/base/CMakeFiles/absl_exponential_biased.dir/internal/exponential_biased.cc.o
[  1%] Building CXX object CMakeFiles/open_spiel_core.dir/canonical_game_strings.cc.o
[  1%] Linking CXX static library libabsl_exponential_biased.a
[  1%] Built target absl_exponential_biased
[  1%] Building CXX object CMakeFiles/open_spiel_core.dir/fog/observation_history.cc.o
Scanning dependencies of target absl_log_severity
[  1%] Building CXX object abseil-cpp/absl/base/CMakeFiles/absl_log_severity.dir/log_severity.cc.o
[  1%] Linking CXX static library libabsl_log_severity.a
In file included from /Users/swetha/Desktop/OrbitalVelocity/ai/open_spiel/open_spiel/fog/observation_history.cc:15:
In file included from /Users/swetha/Desktop/OrbitalVelocity/ai/open_spiel/open_spiel/../open_spiel/fog/observation_history.h:24:
In file included from /Users/swetha/Desktop/OrbitalVelocity/ai/open_spiel/open_spiel/../open_spiel/spiel.h:36:
/Users/swetha/Desktop/OrbitalVelocity/ai/open_spiel/open_spiel/../open_spiel/game_parameters.h:133:7: error: explicit specialization of 'value' in class scope
  int value() const {
      ^
/Users/swetha/Desktop/OrbitalVelocity/ai/open_spiel/open_spiel/../open_spiel/game_parameters.h:137:10: error: explicit specialization of 'value' in class scope
  double value() const {
         ^
/Users/swetha/Desktop/OrbitalVelocity/ai/open_spiel/open_spiel/../open_spiel/game_parameters.h:141:22: error: explicit specialization of 'value' in class scope
  const std::string& value() const {
                     ^
/Users/swetha/Desktop/OrbitalVelocity/ai/open_spiel/open_spiel/../open_spiel/game_parameters.h:145:15: error: explicit specialization of 'value' in class scope
  std::string value() const {
              ^
/Users/swetha/Desktop/OrbitalVelocity/ai/open_spiel/open_spiel/../open_spiel/game_parameters.h:149:8: error: explicit specialization of 'value' in class scope
  bool value() const {
       ^
/Users/swetha/Desktop/OrbitalVelocity/ai/open_spiel/open_spiel/../open_spiel/game_parameters.h:153:47: error: explicit specialization of 'value' in class scope
  const std::map<std::string, GameParameter>& value() const {
                                              ^
/Users/swetha/Desktop/OrbitalVelocity/ai/open_spiel/open_spiel/../open_spiel/game_parameters.h:157:40: error: explicit specialization of 'value' in class scope
  std::map<std::string, GameParameter> value() const {
                                       ^
[  1%] Built target absl_log_severity
Scanning dependencies of target absl_spinlock_wait
[  1%] Building CXX object abseil-cpp/absl/base/CMakeFiles/absl_spinlock_wait.dir/internal/spinlock_wait.cc.o
[  1%] Linking CXX static library libabsl_spinlock_wait.a
[  1%] Built target absl_spinlock_wait
Scanning dependencies of target absl_raw_logging_internal
[  1%] Building CXX object abseil-cpp/absl/base/CMakeFiles/absl_raw_logging_internal.dir/internal/raw_logging.cc.o
7 errors generated.
make[2]: *** [CMakeFiles/open_spiel_core.dir/fog/observation_history.cc.o] Error 1
make[1]: *** [CMakeFiles/open_spiel_core.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[  1%] Linking CXX static library libabsl_raw_logging_internal.a
[  1%] Built target absl_raw_logging_internal
make: *** [all] Error 2

**Comment by lanctot** [comment]
You were within virtual env when you ran the commands. You can exit virtualenv by running `deactivate`.

Can you try _entirely_ from scratch again? Remove all of OpenSpiel, reclone it, and then:

```
./install.sh
CXX=/usr/bin/clang++ ./open_spiel/scripts/build_and_run_tests.sh
```

If it still does not work, can you tell me your MacOS version and XCode version? I think it's just a matter of upgrading XCode, that will use a new enough Clang version.

**Comment by lanctot** [comment]
Let's continue using a single issue for this problem, choosing #407 for the title.
