### ISSUE TITLE
Guaranteed order of actions within an infoset

### ISSUE THREAD

**Issue by michalsustr** [deepmind/open_spiel#41]
I just wanted to make sure I understand some things:

`Action` is an int64_t, but it is not guaranteed to have them indexed from `i=0...n-1`, i.e. `State.LegalActions.at(i) == i` does not always hold. (Btw this could be mentioned in comment for `using Action = int64_t;` in `spiel_utils.h`)

However, does it hold that `x.LegalActions.at(i) == y.LegalActions.at(i)` for all states `x,y` within the same infoset `I` and all action indices `i`? Or in other words, are actions of histories within infoset consistent?

If yes, is there a test for that which checks it for all games (maybe up to certain depth of the tree)?

Thanks for great work!

**Comment by lanctot** [comment]
Correct: actions are from the global action set \cal{A}, whereas the list of legal actions \cal{A}(s) is a subset. I think this is clear from the LegalActions comment header, but agree we can add a comment up top too.

The API does not force or require what you wrote to hold, so we do not have a test or check for it. However, it should hold for most or all games. The CFR implementation currently assumes this and I think it is safe to assume. 

I am finding it difficult to find an example of a game and implementation of LegalActions where this would not hold. It is maybe something should enforce, to be safe. I will bring it to the attention of the team. Thanks!

**Comment by locked-deepmind** [comment]
An easy would be to require LegalActions() to be returned sorted. WDYT?

**Comment by lanctot** [comment]
Mmm.. not sure this would necessary. Most of the legal action functions will be always return a deterministic ordering (in fact, this is almost surely true already for all the current games, by virtue of the way people enumerate the internal structures). @michalsustr, @locked-deepmind: do you anticipate any games or implementations where this would not be true?

Whereas sorting the list each time would either add an unnecessary \Omega(|\cal{A}(s)|) overhead or increase the complexity of the legal actions functions. Not convinced that's worth it given that I can't think of any case where this would not be true by construction.

**Comment by locked-deepmind** [comment]
I'm not necessarily advocating sorting the list, but just requiring that it is returned in sorted order. Most games will do this automatically, e.g. in tic-tac-toe if squares are checked in the right order, this will happen with zero extra compute.

But requiring this is a very simple check, whereas verifying that all info states are internally consistent with each other is potentially very computationally expensive.

**Comment by lanctot** [comment]
Yeah but that is what I meant by increasing the complexity of legal actions.

Sure it will be easy for games like Tic Tac Toe and Go. But some games have complex actions that pack several quantities in the integer in custom ways (e.g chess and breakthrough). Forcing them to be added in sorted order seems painful.

But I still don't understand why force an order at all? It makes one test easier but it doesn't feel like something we need extensive testing for. As far as I can tell this will be true by default/construction (still waiting on a counterexample btw :-p) so why complicate the API constraints for something that will almost never matter?

**Comment by lanctot** [comment]
BTW, I am thinking of adding an infoset -> set of states consistent with the infoset function for the imperfect info games (with implementations for all the games). Then that test becomes easier since we can have it in the simulations test.

**Comment by michalsustr** [comment]
> That function would certainly be optional. For games like  Kriegspiel, the list might be too large anyway. I might pair it with  another (optional) method that samples one at random.

How do you want to implement it? By traversing the tree in game-agnostic way? In games like Stratego it would not work -- you have ~ (20!)^2 initial configurations and finding the ones which lead to your target infoset by chance is very unlikely. The situation is similar in Kriegspiel. It's actually a research topic we're looking into now with one student. Maybe we can move this discussion somewhere else.

> the sorting option is the way to go

Interesting. At first glance it seems wasteful, I'd also be interested in hearing the arguments. :)

**Comment by lanctot** [comment]
> How do you want to implement it? By traversing the tree in game-agnostic way? In games like Stratego it would not work -- you have ~ (20!)^2 initial configurations and finding the ones which lead to your target infoset by chance is very unlikely. The situation is similar in Kriegspiel. It's actually a research topic we're looking into now with one student. Maybe we can move this discussion somewhere else.

Well, as I said, this would be optional; games would not be required to override it. Each game would implement it differently. Obviously it would be very complex for large Phantom games and probably not provided. 

> > the sorting option is the way to go
> 
> Interesting. At first glance it seems wasteful, I'd also be interested in hearing the arguments. :)

Yeah it was my first reaction as well. Turns out only 4-5 games currently violate this, and sorting them was cheap. The sort is only done if the game doesn't already return sorted moves, so it's actually it seems ok. We can always undo it if it ends up being too costly, but for now it seems like the easiest solution.
