### ISSUE TITLE
cmake fails for universal_poker game

### ISSUE THREAD

**Issue by cwolffff** [deepmind/open_spiel#411]
Steps to repro:
1. Download the repository
2. Run `export BUILD_WITH_ACPC="ON"`
3. Run `./install.sh`
4. Run `./open_spiel/scripts/build_and_run_tests.sh`

The 4th step yields `CMake generate step failed. Build file cannot be regenerated correctly.` Along with lots of error messages along the lines of
```
Error evaluating generator expression:

    $<TARGET_OBJECTS:universal_poker_clib>

  Objects of target "universal_poker_clib" referenced but no such target
  exists.
```

I'm running Mac OS and python 3.7.9.

Any help would be much appreciated!

**Comment by michalsustr** [comment]
I'm afraid this is a known issue: https://github.com/deepmind/open_spiel/blob/master/.travis.yml#L38 But maybe I'm wrong, and there is a way to make it work ( https://github.com/deepmind/open_spiel/issues/121 ).

**Comment by lanctot** [comment]
As far as I was aware, this was working and that line in Travis should be removed. You can see further below that it is enabled when running with nox (on MacOS) and it's been passing in travis for the recent past. We will look into this, thanks for reporting!

**Comment by lanctot** [comment]
Hi @cwolffff can you send the ouput of `cmake -version`? I remember seeing those before from older CMake versions.

**Comment by cwolffff** [comment]
```
> cmake -version 
cmake version 3.18.2

CMake suite maintained and supported by Kitware (kitware.com/cmake)
```
@lanctot

**Comment by lanctot** [comment]
Seems like CMake isn't finding a target that should be enabled. 

Three things to try:

1. Can you ensure the code got cloned? Show me the output of `ls -l games/universal/poker`. There should be an `acpc` subdirectory in there.
2. If not can you try running the install line as: `BUILD_WITH_ACPC="ON" ./install.sh`
3. If so, can you remove all the build files (`rm -rf build`) and try again with this line: `BUILD_WITH_ACPC="ON" ./open_spiel/scripts/build_and_run_tests.sh`

**Comment by lanctot** [comment]
I just compiled and ran the universal_poker_test on my MacOS laptop and it worked without a problem. My guess is that you ran the export in one terminal and then tried a partial build, and reran the build in a different terminal which did not have the export. Removing the build directory entirely and redoing it with the environment variable prepended should fix it.

**Comment by cwolffff** [comment]
Removing the build files and rebuilding fixed it. Thanks for the help!
