### ISSUE TITLE
build_only arguments are not escaped correctly in print

### ISSUE THREAD

**Issue by pratapram** [deepmind/open_spiel#415]
This is a minor bug.  When I build using arguments build_only, it displays an error at the end.

$./open_spiel/scripts/build_and_run_tests.sh --build_only=true
...
[ 99%] Built target logger_test
[100%] Built target file_test
[100%] Built target tensor_view_test
./open_spiel/scripts/build_and_run_tests.sh: line 226: ARG_build_only: command not found
*** Skipping runing tests as build_only is  
Exiting virtualenv
$

This is the offending line:
echo -e "\033[32m*** Skipping runing tests as build_only is $(ARG_build_only) \e[0m"

It should be
echo -e "\033[32m*** Skipping runing tests as build_only is ${ARG_build_only} \e[0m"

**Comment by lanctot** [comment]
Ok thanks for flagging!

Hmm, am I missing something.. those two lines look exactly the same to me.. (though I do see a typo)

**Comment by pratapram** [comment]
Yes. I will submit my first PR :-)

**Comment by lanctot** [comment]
Fixed by https://github.com/deepmind/open_spiel/pull/418
