### ISSUE TITLE
Adding a game docs is outdated

### ISSUE THREAD

**Issue by michalsustr** [deepmind/open_spiel#42]
The documentation `docs/developer_guide.md` seems outdated - there is no `new_game.h` and the registration seems to be done via `REGISTER_SPIEL_GAME` macro.

**Comment by lanctot** [comment]
Sorry, I don't understand.

new_game.h is not an actual header. If e.g. you're implementing Checkers, new_game.h would refer to `checkers.h` which was created in Step 2.

**Comment by michalsustr** [comment]
Misunderstanding on my part :-)
