### ISSUE TITLE
Bots API - step function does not allow to restrict number of iterations/time

### ISSUE THREAD

**Issue by michalsustr** [deepmind/open_spiel#45]
The Step method
```
std::pair<ActionsAndProbs, Action> Step(const State& state)
```
or respectively `EvaluateBots` does not offer a way to specify for how many iterations or for what time the bots are allowed to update their strategies, so it's not possible for example to compare the performance of two Monte Carlo bots which both receive 5s of time per move.

If there's interest, I can submit a PR (I've developed something similar in GTLib)

**Comment by lanctot** [comment]
You can do this. This should not be part of the step function, that information should be part of the bot. You can make a parameterized bot which takes in the number of seconds or simulation for each search time, and then play e.g. MyBot(search_time=5s) against MyBot(search_time=10s).

**Comment by michalsustr** [comment]
Yes, you can do it this way. I had a competitive approach in mind, where the bots may be implemented somehow externally and you should be able to deny them more computational time.

**Comment by lanctot** [comment]
I see. You should still be able do that by having a mutator method in the bot that sets the search time dynamically.
