### ISSUE TITLE
Would it be wise/possible to include Stratego to Open_spiel

### ISSUE THREAD

**Issue by BluemlJ** [deepmind/open_spiel#459]
Hello, 

I am currently writing my master thesis about (scalable) multi-agent systems for large/complex games with hidden information. Such a large game I want to try is Stratego/Barrage Stratego. 

My question is: would it be wise with the current state of open_spiel to try to include Stratego/Barrage Stratego or is the game simply not feasible/out of scale?

If it is possible, do you have any recommendations (@michalsustr maybe?)

I know that is not an issue with the current state and more a question about a possible extension. Hope it is okay to open an issue for this.

**Comment by michalsustr** [comment]
I would love to have implementation of Stratego! I even had a discussion with @lanctot about this and we both agreed that it would be nice, however there might be copyright issues with publishing the implementation. Since this repository is maintained by Deepmind, they didn't want to get into a potential hassle because of the copyright. However feel free to implement the game in your own fork -- if you want I can give you a code review. 

My limited understanding of the legal problem is that the game mechanics are not copyrightable, but the name is, so either getting an official approval or publishing the implementation under a different name should be fine.

**Comment by lanctot** [comment]
Hi @BluemlJ,

It is totally ok to open an issue for this! I would also love to see an OpenSpiel implementation of Stratego. It certainly is feasible and within "scale" / scope. The only problem is that is that the game is copyrighted.

We had a case like this before: someone contributed an implementation of Catan. We decided the safest route was for the game to be hosted independently by the contributor, and that we could mention the third party implementation on our game list (but without a link). We could certainly offer the same option for Stratego.

However, I do anticipate a growing number of cases like this one, so I am still planning to look into options like we did for Hanabi, which was to contact the publishers and get official permissions. This is not a quick process, though, and you have do this for every publisher. I should say I've also been saying this for some time... :)

The idea of using a different name is interesting -- we never investigated this. I will look into it.

**Comment by michalsustr** [comment]
> The idea of using a different name is interesting -- we never investigated this. I will look into it.

Just quickly searching around it seems to be well established you can't copyright game mechanics:

> Therefore, the systems or processes that make up the core of a game—generally referred to as the “game mechanics”—are not subject to copyright, even though the written rules, game board, card artwork, and other elements—often referred to as the “theme” of the game—may be. Game mechanics can be as simple as “roll dice and move a token along a track,” or far more complex. Regardless of the complexity or originality of a given game’s systems and processes, its game mechanics will likely not be protected by copyright.

From https://www.americanbar.org/groups/intellectual_property_law/publications/landslide/2014-15/march-april/not-playing-around-board-games-intellectual-property-law/

The whole page is quite an interesting read :)

**Comment by michalsustr** [comment]
Game mechanics can't be copyrighted, but they can be _patented_, and the patent can be granted only before the game has been played publicly. Reading through the [wikipedia article](https://en.wikipedia.org/wiki/Stratego) it seems the only potential problem could be a 1908 French patent for L'Attaque, but that should be expired :-P However it seems the trademark for the game is still active, which means the original name shouldn't be used.

**Comment by BluemlJ** [comment]
Hey guys, 

I wrote this little game called "Yorktown" in an own fork [0] . It is quite similar to this old game called "Stratego" (which means the game mechanics are identical) :wink: 

The implementation, especially the game_board is based on the chess_board in Open_spiel.

It is not finished yet but it is at at a point where you can run random_agents against each other. 

Some open ToDos are
- check why tests 91,92 and 154 (python_api, python_playthrough and python_pyspiel) fail
- write own tests for the board and the game itself
- fix the observations -> how to deal with partial information situations better (probability representation in form of planes maybe)
- check for information leakage in any form (especially in tree search methods)
- test some algorithms on the game and see how they work/if they work
- ...

Maybe you want take a look yourself [0].

I am open to changes, if you have any feedback or ideas.

[0] : [my fork](https://github.com/BluemlJ/open_spiel)

**Comment by lanctot** [comment]
Closing this now since there is a PR: https://github.com/deepmind/open_spiel/pull/635
