### ISSUE TITLE
Help with the backgammon action encoding

### ISSUE THREAD

**Issue by RjVicks** [deepmind/open_spiel#461]
Hi there, thanks for this awesome framework. I am using it for my third year project on a backgammon RL agent.

Please can you help me understand the encoding of the agent actions for backgammon. I can't seem to understand it.
![Backgammon-actions](https://user-images.githubusercontent.com/26366162/101677083-0033f100-3a54-11eb-89fb-8ceb36765c3f.png)

Thanks
Robert McVickers

**Comment by lanctot** [comment]
Hi @RjVicks , yes it is explained here: https://github.com/deepmind/open_spiel/blob/b298e9f8b1e36fc3adbc36902181d565ce01f7d4/open_spiel/games/backgammon.h#L64

Each individual checker move is encoded as a two-digit number in base 26. And two numerical ranges are used (to differentiate between the high-roll moving first and the low roll moving first. 

The your example image, let's take action 11. That's in the first set of 676 numbers, so it means the high-roll moves first.  The two digits in base 26 works out to 0 11. Those are the starting points relative to the player's furthest point. In the case of that image it means (from 24 -> move 6, from 13 -> move 6).

Would it be useful to you if there was a function to convert the actions from integer to some meaningful backgammon-specific structure?

**Comment by RjVicks** [comment]
Thank you, that's super helpful.

I had planned to write such a function myself. I am hooking up open_spiel to a Gui I made. I would be honoured to write the function in the API, if that is possible. I have not contributed to an open source project before, I do know C however... If you could assist me through the process that would be super awesome.

I had seen the description in the .h file although I couldn't readily understand it,  that being said I am not familiar with 'modulo' encoding, for lack of a better phrase. May I suggest a slightly more elaborate explanation, perhaps with the example you gave. I think that would certainly be beneficial to people of my level. 

Thanks once again. Really loving the API.

**Comment by RjVicks** [comment]
Hi,

Also, I think I may have found a bug ...
![Open-spiel-bug](https://user-images.githubusercontent.com/26366162/101822332-0cd24b00-3b21-11eb-95ae-7451c518ecf8.png)

Notice that 16 and 11 are < 676, however they move the low roll first. Also note this with 

- 297: 297 - 13/9 13/7 is the same as 973: 973 - 13/9 13/7 (Maybe in this case it doesn't matter)
- 302: 302 - 13/9 8/2 
- 432: 432 - 8/4 8/2 

Also these are >= 676 however move the high roll first:

- 687: 687 - 24/18 13/9   
- 692: 692 - 24/18 8/4    
- 694: 694 - 24/18 6/2

**Comment by lanctot** [comment]
Oops, possibly the comment I pointed you to is just wrong in this case? (i.e. the first 676 numbers are low roll first, the next are high roll first)

For the function to expost it: it already exists in the code, we just need to expose it. I'll keep you posted.

**Comment by lanctot** [comment]
Oh wait something definitely looks incorrect there because they are all 6 apart, but the roll is 46. I suspect it's a bug in the string representation functions.

If you find such a state, can you send me the list of actions (that you can get with State::History()) so I can reproduce the same state?

**Comment by RjVicks** [comment]
Sorry, I am not sure what you mean by such a state

**Comment by lanctot** [comment]
The one in your most recent screenshot. 

Am I understanding correctly that all the moves showing 6 spaces apart as if you rolled 66 rather than 46?

**Comment by lanctot** [comment]
Oh wait no some of them indeed are only 4 apart, sorry.

**Comment by lanctot** [comment]
Hi @RjVicks,

Ok, I have a few answers for you.

1. The comment I pointed you to originally in the header is correct. The first 676 numbers are for when the low roll moves first.
2. It's the `BackgammonState::ActionToString` function that manipulates the order, that's why you are seeing the low roll first (and why it appears that 297 and 973 are equivalent), see here: https://github.com/deepmind/open_spiel/blob/b298e9f8b1e36fc3adbc36902181d565ce01f7d4/open_spiel/games/backgammon.cc#L179
3. The two functions I mentioned are already exposed: `BackgammonState::CheckerMovesToSpielMove` and `BackgammonState::SpielMoveToCheckerMoves`. Are these what you are looking for? Do you need them from Python?

Note that I think the ordering in the string is not the right thing to do, because there are situations where the order matters. I will fix that, thanks for pointing it out.

**Comment by lanctot** [comment]
> Note that I think the ordering in the string is not the right thing to do, because there are situations where the order matters. I will fix that, thanks for pointing it out.

After looking at the `ActionToString` function: I take this back -- it is making sure to handle the ordering when it makes a difference, and this ordering does indeed seem to be the convention among Backgammon players / bots. It's important to know that OpenSpiel is storing them as two separate moves internally, only getting printed out the same.

Let me know if those two functions I mentioned are helpful.

**Comment by RjVicks** [comment]
Hi Lanctot

Thanks for clearing all that up. Your explanation at the start was super helpful also.

Yes! Those functions do look like what I am looking for. I'll try them out shortly... 

I am using python.

**Comment by lanctot** [comment]
Ok these functions need to be exposed to python. I will add them and they should be available in today's github update.

**Comment by lanctot** [comment]
Ok @RjVicks they are now accessible from Python. For some examples, see here: https://github.com/deepmind/open_spiel/blob/b8c2ff8e9a4f5dad9b179217f740ddb0df967f7c/open_spiel/python/tests/games_sim_test.py#L251

You can add more too if you want by editing python/pybind11/games_backgammon.{h,cc}
