### ISSUE TITLE
Makefile:113: recipe for target 'all' failed

### ISSUE THREAD

**Issue by dylanqyuan** [deepmind/open_spiel#462]
Thanks for your attention!
when I run the following code to build from source:
`./open_spiel/scripts/build_and_run_tests.sh`

the following error ocurred:
`CMakeFiles/Makefile2:1022: recipe for target 'CMakeFiles/open_spiel_core.dir/all' failed
make[1]: *** [CMakeFiles/open_spiel_core.dir/all] Error 2
make[1]: *** ....
[ 16%] Linking CXX static library libabsl_malloc_internal.a
[ 16%] Built target absl_malloc_internal
[ 17%] Linking CXX static library libabsl_strings.a
[ 17%] Built target absl_strings
Makefile:113: recipe for target 'all' failed
make: *** [all] Error 2
Exiting virtualenv
`

**Comment by lanctot** [comment]
Hi @dylanqyuan , hmm do you have more information, like more of the error? That only says that the build failed but not why. The error should be some place earlier in the output. 

Did you make sure to run `./install.sh` before this to get the dependencies?

**Comment by dylanqyuan** [comment]
> 
> 
> Hi @dylanqyuan , hmm do you have more information, like more of the error? That only says that the build failed but not why. The error should be some place earlier in the output.
> 
> Did you make sure to run `./install.sh` before this to get the dependencies?

@lanctot Thanks for your kindful help! When I move from Ubuntu 16.04 to 18.04, the issue has been solved.

**Comment by lanctot** [comment]
Great!
