### ISSUE TITLE
How to get player's personal history?

### ISSUE THREAD

**Issue by dvstter** [deepmind/open_spiel#469]
The leduc_poker's history returns all the histories. Is there any method to part of the history visible only by himself?

**Comment by lanctot** [comment]
You can iterate over each item `FullHistory()` and check the item.player == CurrentPlayer(). Is this what you are looking for?

Is this C++ or Python? Generally all the information known by a player is encoded in `InformationStateString`.

**Comment by dvstter** [comment]
> You can iterate over each item `FullHistory()` and check the item.player == CurrentPlayer(). Is this what you are looking for?
> 
> Is this C++ or Python? Generally all the information known by a player is encoded in `InformationStateString`.

Yes, I figure this out before your reply. Thank you for your efforts on this project!!! I think this whole project's API design is very simple and self-explanatory.

**Comment by lanctot** [comment]
Perfect. Thanks for the kind words. Have a happy new year!
