### ISSUE TITLE
How to interpret TimeStep contents

### ISSUE THREAD

**Issue by 18jeffreyma** [deepmind/open_spiel#473]
I'm interested in running a custom algorithm on the Markov Soccer game, and wanted to use the `rl_environment` API provided, something along the lines of the following code:

```
from open_spiel.python import rl_environment

env = rl_environment.Environment('markov_soccer')
time_step = env.reset()

for row in time_step.observations['info_state']:
    print(len(row), row)
```

However, I get this as output, and I'm not quite sure how to interpret this `'info_state'` element, as each player has a 120 element observation list, when the board is only 5x4. Could I get some clarification (or direction to documentation) how this 'info_state' parameter should be interpreted correctly? For reference, the output is the following:

```
120 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
120 [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 1.0, 1.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]
```

**Comment by lanctot** [comment]
Yes that is an encoding of the game's observation tensor (or information state tensor, if one is defined).

In the case of MarkovSoccer it is five planes of 5x4, described here: https://github.com/deepmind/open_spiel/blob/b8c2ff8e9a4f5dad9b179217f740ddb0df967f7c/open_spiel/games/markov_soccer.cc#L349

See the function above this one to see which plane corresponds to which item on the field.

**Comment by 18jeffreyma** [comment]
Gotcha, thats very helpful! For some followup, is the difference between plane `a` and `A` when that respective player acquires the ball, or is there some other explanation of the plane?

**Comment by lanctot** [comment]
Yep that's it, `A` means its the first player carrying the ball, `a` is the first player not carrying the ball, and similarly for `b` and `B`. 

That info is buried in `markov_soccerr.cc`.. definitely not easy to find, we should explain the meanings of those in comments at the top of the file. So please leave this issue open as a reminder for me to fix it.

**Comment by 18jeffreyma** [comment]
Will do, thanks again for the prompt replies!
