### ISSUE TITLE
state.observation_tensor() fails when state is terminal

### ISSUE THREAD

**Issue by goshawk22** [deepmind/open_spiel#474]
Whenever I try to get the observation of a terminal state, it fails with the error:
`pyspiel.SpielError: /open_spiel/spiel.cc:699 player >= 0`
`player = -4, 0 = 0`

It looks like the problem is that the player is -4, which doesn't really make sense in a 2-player game.
I've tried with both Chess and TicTacToe, but both have the same result.

**Comment by lanctot** [comment]
That is odd, I thought we had a test for this in our simulation testd. -4 is `kTerminalId`, a special player id reserved for terminals, but still it should be possible to get obs tensors at terminals, so this sounds like it could be a bug. I will look further into it when I am back at work (jan 4th)

**Comment by lanctot** [comment]
Oh I have a suspicion as to the cause: I think at terminals you need to call the overloaded method with a specific player number. I think the rl_environment did that, I guess you are using the python API directly?

**Comment by goshawk22** [comment]
Yep this works - thanks for the help!
