### ISSUE TITLE
Request: documentation of instructions for adding a python game, parallel to the c++ instructions

### ISSUE THREAD

**Issue by ebaillie** [deepmind/open_spiel#479]
Apologies if this isn't the right place for requests.

I understand that the preferred method for adding new games to open_spiel is to code them in c++

However, is it possible to add instructions to the documentation for adding and playing a new python game, similar to what already exists for a new c++ game, including a rundown of what features of the package can and can't be accessed by new python games?

For instance, it isn't clear to someone unfamiliar to the code (ie, me) whether there's a mechanism for including python games among the list of registered games so that they can be loaded by pyspiel.load_game, and the python implementation of tic tac toe currently available can't be added to the python integration tests, because it's not in the registered games list

**Comment by elkhrt** [comment]
Thanks for the suggestion!
There isn't currently a mechanism to register and load Python games, but we
could add one. I'll give it some thought; and also add some documentation.

**Comment by elkhrt** [comment]
Quick update - I now have Python games working internally (registration, load_game, passing to C++ algorithms) - this should be in the next release.

**Comment by lanctot** [comment]
These changes are now in @ebaillie, see the commits on Jan 31. Can you pull the changes and try again?

It should be now straight-forward to add games, as it is quite similar to the C++ way. @elkhrt also added a python implementation of Kuhn poker for demonstration. 

We can eventually add one for simultaneous move games. It would be great to have separate specific documentation for adding python games, but it's not clear when we will be able to get to this. It would make a nice contribution if you are up to it!

**Comment by michalsustr** [comment]
Nice! :) How can games implemented in python be loaded in c++? I found there is https://pybind11.readthedocs.io/en/stable/reference.html?highlight=import%20file#_CPPv4N7module_6importEPKc so is it enough to just import the python file and then call `LoadGame("python_kuhn_poker")` ?

**Comment by elkhrt** [comment]
Yes, just import the Python module containing the game and then do
`load_game`.
https://github.com/deepmind/open_spiel/blob/1a28440960e1cbb168bc7bd9dade0ef3eac98f2b/open_spiel/python/games/kuhn_poker_test.py

lines 25 and 34
