### ISSUE TITLE
Problem running mcts example with a python game

### ISSUE THREAD

**Issue by ebaillie** [deepmind/open_spiel#480]
(this may also be an issue with other agents - mcts is the one that I've tried)

The situation: I experimentally modified mcts.py from python/examples to test it on the Python version of tic_tac_toe

imported tic_tac_toe.py and loaded the game directly rather than with pyspiel.load_game

code fails with error message:

>     bot.inform_action(state, current_player, action)
> TypeError: inform_action(): incompatible function arguments. The following argument types are supported:
>     1. (self: pyspiel.Bot, arg0: pyspiel.State, arg1: int, arg2: int) -> None
> 

This appears to be fixable by making TicTacToeState explicitly inherit from pyspiel.State, but I then had to hack the clone function also to copy all the class attributes individually rather than by using copy.deepcopy()

Since the TicTacToe code explicitly says "not inheriting from pyspiel.State because of problems with pickle" I assume that this is a non-workable solution in general - I hope there's a better one.

**Comment by lanctot** [comment]
Hi @ebaillie, yeah unfortunately this might keep happening for you. 

We haven't had much demand so far nor many use cases for the python-only games, so we have not put much effort into proper support for them. The python-only Tic-Tac-Toe was mostly just to show that it *can* be done but it's certainly not fully-supported and not tested (as you're discovering).. this is one of the main reasons we don't really mention it in the documentation and put a big warning in the tic-tac-toe example. 

I can't think of a clean fix and the fact that you had to hack the clone is a concern. I'll bring it up with the team.

It would be great to have better support for python-only games, so please keep posting issues when you find them. We'll just have to track them and fix each one-by-one. So it might take some effort before it is smooth.

**Comment by michalsustr** [comment]
Out of curiosity I just had a look, and I think this could be easy and done via some special wrapper, such as subclasses `PythonGame` and `PythonState` which would receive a pybind's `py::object` in a constructor and call appropriate `.attr` methods on it: https://pybind11.readthedocs.io/en/stable/advanced/pycpp/object.html#calling-python-methods
The `PythonGame(py::object impl_in_python)` would call the appropriate registration methods to make these games available also in C++, effectively gaining bidirectional support.

**Comment by michalsustr** [comment]
Hmm I think `PythonGame` should also receive `PythonGame(py::object game_impl_in_python, py::object state_impl_in_python, py::object observer_impl_in_python)`

**Comment by elkhrt** [comment]
Shouldn't the general pybind mechanism work?
(as used in
https://github.com/deepmind/open_spiel/blob/master/open_spiel/python/pybind11/bots.cc
)

**Comment by michalsustr** [comment]
Oh yeah, that looks good! Does it work also with `NewInitialState()` and `MakeObserver()` ?

**Comment by elkhrt** [comment]
I'm going to give it a go

**Comment by Helveg** [comment]
Can I pile on here for request for Python only games? I think this library would thrive very well in Python's ML ecosystem if the API for defining games would be available and clarified for Python games.

**Comment by elkhrt** [comment]
Support for Python games will be in the next release.

**Comment by elkhrt** [comment]
The update has landed - I'm interested to hear how people get on.
If adding new games, for the time being I recommend the state implementation be pure Python, i.e. not calling C++ methods (e.g. `current_player()`, `is_chance_node()`) from the Python implementation of the State / Observer APIs.

**Comment by lanctot** [comment]
These changes are now in @ebaillie, see the commits on Jan 31. Can you pull the changes and try again?

**Comment by ebaillie** [comment]
I'm having a bit of trouble with it, in fact.

The two things I tested out were the ability to call 

`pyspiel.load_game("python_tic_tac_toe")`
 
which was what I was expecting the change to make possible, and then after that, (since I see the tic_tac_toe.py file has had a reorganisation), to just do

```
import tic_tac_toe
ttt=tic_tac_toe.TicTacToeGame()
```

which is the way I was creating python games in the absence of 'load'

The first way informs me that python_tic_tac_toe is an unknown game name, and the second has an AttributeError involving pyspiel.GameInfo

I suspected that both of my problems might be solvable by running build_and_run_tests.sh but at the moment that's failing for me at the 99% mark with this error:

[ 99%] Linking CXX executable functional_test
/home/ubuntu/AIStrat/open_spiel/open_spiel/python/pybind11/python_games.cc:142:16: error: no viable conversion from 'pybind11::detail::str_attr_accessor' (aka 'accessor<accessor_policies::str_attr>') to 'py::function'
  py::function f = py_handle_.attr("new_initial_state");


(in a totally unrelated remark, however ... thanks for making a python kuhn_poker - it's very helpful to be able to have a game involving chance nodes as one of the examples)

**Comment by lanctot** [comment]
Ah yes - the change was quite involved, we had to increase the version of pybind11 we depend on. So you will have to re-install from scratch (so that install.sh pulls in the new version). My first guess is that you are still using the older pybind11.

**Comment by ebaillie** [comment]
I have now done that and everything now works perfectly.

Thanks!

And I see that I was wrong to assume that load_game was necessarily going to work now, since that was the other issue I opened and not this one - but it does, in fact, now work! So thanks for that one too

**Comment by lanctot** [comment]
Great!
