### ISSUE TITLE
Bidding rules in Liar's Dice differ from Wikipedia's description

### ISSUE THREAD

**Issue by gabrfarina** [deepmind/open_spiel#487]
Wikipedia mentions that in the game of Liar's Dice

>  common bidding variants, given a previous bid of an arbitrary quantity and face value, include:
> - the player may bid a higher quantity of any particular face, or the same quantity of a higher face (allowing a player to "re-assert" a face value they believe prevalent if another player increased the face value on their bid);
> - the player may bid a higher quantity of the same face, or any particular quantity of a higher face (allowing a player to "reset" the quantity);
> - the player may bid a higher quantity of the same face or the same quantity of a higher face (the most restrictive; a reduction in either face value or quantity is usually not allowed).

However, after comparing differing results on our internal implementation of Liar's Dice and OpenSpiel's, I now think that OpenSpiel implements a different bidding variant, which can be summarized as

> the player may bid the same quantity of a higher face, or a higher quantity of any face (allowing a player to "reset" the face).

I think that can be seen in the implementation of the game, here:

https://github.com/deepmind/open_spiel/blob/244d1b55eb3f9de2ab4a0e06341ff2847afea466/open_spiel/games/liars_dice.cc#L446-L461

By encoding bids with the bid quantity occupying the higher bits, you end up concluding that a bid is higher if the quantity is higher (no matter the face), or the quantity is the same but the face is the same.

I think this is potentially problematic because face 6 is considered the "catch-all" face. So, if a player does not bid face 6, under the implemented rules the opponent should bid the same quantity of face 6, and be guaranteed to be safe. This ruins the strategy of the game.

Given that the class-level documentation of the game simply points to Wikipedia without comments, I think that if we wanted to stick to the currently implemented bidding rules, we should at least document this quirk. Alternatively, I'm very happy to fix the implementation to align the bidding rules to what Wikipedia says.

**Comment by gabrfarina** [comment]
Actually, I went ahead and opened a PR to change the bidding rules and re-align them to what is written on Wikipedia, since I'm now pretty convinced that the game as implemented now is not particularly interesting in terms of strategy.

I have also made the number of faces per die configurable, so that I could compare with our internal generator more easily. If for some reason you want to keep the number of faces configurable but don't want to switch to the new bidding rules, let me know and I can decouple the two features 🙂

**Comment by lanctot** [comment]
Thanks @gabrfarina. 

I think the one you point out in our implementation is equivalent to the first variant cited from Wikipedia. Even though it is awkwardly-worded, what is included in the parentheses is the same as "resetting the face". If not, then it would have been worded "the player may bid a higher quantity of the same face," like the wording in the second and third ones you cited.

I agree it is problematic when 6 is chosen as the wild, but had not realized that before. So what rules does your PR go with, then? The one where you can only increase the quantity xor face (every move having branching factor of 2?), making the 1's wild, or something else? It'd be good to keep this bidding variant as a possible choice and making the 1's wild, for backward compatibility reasons.. I know at least one other researcher who has published results with this variant, so I think it's common.

**Comment by lanctot** [comment]
I based this on Bluff, whose board is here: 
![image](https://user-images.githubusercontent.com/3929263/105521743-dd356780-5cb6-11eb-8b32-0f9fb897c697.png)

I've always played that the bid must just go further on the outside track, but looking at the rules [on this site](http://www.diceagegame.com/bluff/) they describe the 2-action game (increase one of {quantity, face} but not both).

**Comment by gabrfarina** [comment]
Actually, thinking about it more, I believe that my point about face 6 was wrong. A cast 6 matches any bid, but not the other way around: if I bid "at least 2 dice are a 6", the only roll that match that is "6-6".

You are right about the first bidding rule, I had missed the subtlety you pointed out.

Our own generator uses the second 2, instead of rule number 1. I wonder at this point if it makes sense to have the bidding rule used be a parameter to the game, defaulting to your original implementation? I'm happy to amend the PR.

**Comment by lanctot** [comment]
Oh, right, of course.. that makes sense, I misunderstood as well. :) 

As far as I can tell, the rule number 2 seems to be the one described as the standard one of Bluff. I would be delighted to support both via a flag, and happy to default to the current one (more so as a preference toward backward-compatibility).

Thanks for generalizing the number of faces! I would also like to finally implement the full / larger game and extend it to multiple players (if it's only 2p at the moment..)

**Comment by gabrfarina** [comment]
Great, I think it would be nice for OpenSpiel to support the second bidding rule, so that over time we can phase out our generator, or at least have a second source of truth to debug.

I have amended the PR to support both bidding rules. Our generator supports multiple players (and we have used it as a benchmark game for team collusion), but unfortunately it does not support multiple rounds. Do you think the multi-round version has the potential to be an interesting benchmark game? If so I don't mind carving out some time to hack around that feature.

**Comment by lanctot** [comment]
That's perfect, thanks @gabrfarina !

I think it's an interesting game because it's Markovian between subgames, as in, each one can be solved independently and then bootstrapped and it's a real game played by people. At one point I wanted to get to the full game (5 dice per player), which I think it completely possible now (via some form of function approximation or imperfect recall abstractions for the really large ones) since the subgames (2,2), (2,1), (1,1), are solvable exactly. The reason I never went for it is because I don't think it's a very popular game so maybe nobody would be interested, and it's just redoing what was done on poker so there wasn't enough "research incentive".

So maybe not a high priority, but it'd still be nice for our implementation to support it so someone can go for it eventually. So it's a nice-to-have feature in the same sense as Backgammon should also implement doubling cube and multi-round game too (and when we add Crib it'll be similar: start with the one-round game and add the multi-round game eventually).

**Comment by lanctot** [comment]
The PR has now been merged: https://github.com/deepmind/open_spiel/pull/488

Thanks @gabrfarina !
