### ISSUE TITLE
Complicated turn orders in boardgames

### ISSUE THREAD

**Issue by Helveg** [deepmind/open_spiel#492]
I'm looking to create agents for complicated boardgames such as [Puerto Rico](https://boardgamegeek.com/boardgame/3076/puerto-rico), [New Frontiers](https://boardgamegeek.com/boardgame/255692/new-frontiers), [Clans of Caledonia](https://boardgamegeek.com/boardgame/216132/clans-caledonia) and other resource management type games. A prominent feature of most of these games is a complicated turn based system. In Puerto Rico & New Frontiers there is an order to the players that can change, and the active player picks a shared phase where then again the turn order specifies in which order players can play out this phase. In Clans of Caledonia a player can keep playing until they pass or run out of options.

I'm just exploring whether OpenSpiel is a good fit for my use case so I'd like to know:

* Can OpenSpiel games deal with dynamic turn orders?
* Is support for Python games coming soon? (see #480, #479) I think there are a lot of people playing around with ML in Python that don't know C++ but could still contribute an endless variety of games.

**Comment by lanctot** [comment]
Hi @Helveg,

First of all, it is awesome to hear about interest in more complex board games. I quite like the worker placement genre myself, and am a big fan of Stone Age and Egizia.

Yes OpenSpiel can handle arbitrary turn orders. It is all controlled by the ApplyAction function. 

One of the core devs is currently working on better support for python-only games, so I would assume so, yes. @elkhrt wdyt?

**Comment by lanctot** [comment]
Btw contributing copyrighted games is tricky.

We had someone contribute a wrapper to an implementation of Catan, and we decided not to accept the PR because it was too risky. Ideally we would get permissions from the copyright holders, and we have done that before (see the Hanabi Challenge paper) but it takes time, and it's not guaranteed to work.

Failing that people would have to host the games in their own repos or just work on them privately.

**Comment by Helveg** [comment]
I was considering the copyright issues as well and am thinking of working together with a lawyer friend to write up a template license specifying in big lines something like this:

* 3 parties: 
  * The OpenSource community (& all non-commercial users)
  * The developers (contributors to the source code that game)
  * The holders of the intellectual property on the boardgame
* Only the IP holders can use the game engine and the agents for commercial-use, but non-commercial use is allowed.
* Room to specify how the IP holders and developers wish to divide the proceeds of any commercial-use with default 10% for an OpenSource ML fund (good candidates? Is there an OpenSpiel fund? :p)

I think boardgame engines and agents are very licensable products as many online boardgame websites exist, so the hope is that with some existing legal framework it will become rather straightforward to develop engines in private, so the contributors aren't infringing on any IP and then contact the gameboard devs to see if they want to make some free money, in the process allowing the OpenSource community to play around with it non-commercially.

**Comment by michalsustr** [comment]
@Helveg this sounds awesome! If there was a streamlined way how handle these situations that would be extremely helpful. You also might be interested in some comments here, as it has come up in the past already: https://github.com/deepmind/open_spiel/issues/459

**Comment by lanctot** [comment]
Hi @Helveg, we have now added proper support for Python games, see the commits on Jan 31st.

This is an interesting discussion. I will talk to our legal team to see what is possible and what our options could look like going forward.

**Comment by Helveg** [comment]
Ok, I'm nearing a point in the development of the first boardgame where I could start playing around with the Python games. I'll try to use the C++ docs and open a PR with some Python docs as I tinker along.

**Comment by DictumMortuum** [comment]
@Helveg I didn't know how to reach out to you except maybe make a comment here. I'm looking to do something similar with more hobby boardgames and was researching if there's something that has already been done. Have you made any progress with this?

**Comment by Helveg** [comment]
No, I didn't find a suitable library for my needs and never got very far.

**Comment by lanctot** [comment]
Just a quick note that OpenSpiel now has much better support for python games than it had in 2021. 

Also, it has always supported arbitrary turn orders and has several examples of games with them.

Is there anything that was missing that you needed 
That you could not find in particular?

**Comment by Helveg** [comment]
It was a hobby project endeavour of 3 years ago that I can't remember that well anymore, I have no feedback, sorry! :)
