### ISSUE TITLE
Acme now has an OpenSpiel interface!

### ISSUE THREAD

**Issue by lanctot** [deepmind/open_spiel#493]
Acme is a research framework for reinforcement learning:

- [github](https://github.com/deepmind/acme)
- [paper](https://arxiv.org/abs/2006.00979)

It now supports [integration with OpenSpiel](https://github.com/deepmind/acme/commit/7fa9b804e47fd1b1fbb20ed5e62275d822607c8b), thanks to @jhtschultz! Thanks also to help and support from the Acme team (@fastturtle @mwhoffman @bshahr).

I'm quite happy to see this cross-project collaboration driven by external contributions. The hope is that this will facilitate large-scale RL in games.

Enjoy!

**Comment by jhtschultz** [comment]
Very excited about this project! Thanks again to the Acme team for all their support. Acme is a powerful and flexible framework for Deep RL with an extensive collection of reference implementations. Can only imagine that integration with OpenSpiel will result in good things :)

**Comment by mwhoffman** [comment]
Thanks for all the great work! We're also quite happy to see this kind of collaboration go forward! Kudos!
