### ISSUE TITLE
Problem with Julia API when installed in /usr/local

### ISSUE THREAD

**Issue by lanctot** [deepmind/open_spiel#497]
Hi @findmyway, we had to move our CI away from Travis and to Github Actions this week. The problem is that the Julia tests are now failing again, see here: https://github.com/jblespiau/open_spiel-1/runs/1595264912?check_suite_focus=true

The problem is similar to https://github.com/deepmind/open_spiel/issues/201 except the command I used before no longer works because I copied the library to the $HOME/packages/julias/julia-1.3.1. See here: https://github.com/deepmind/open_spiel/blob/32a3d303e0ce710f2ef70a3214d26640cde97bf7/open_spiel/scripts/install.sh#L197

Now the machines have Julia installed in /usr/local/julia1.5.3, and this might generally happen on the user side. So we'll probably need to do a sudo to copy the file. I think we can do this in our install script as long as we echo something like why we requiring sudo... but even if that works, it does not feel like an elegant solution. Do you have a better idea about how to fix this?

**Comment by findmyway** [comment]
Hi @lanctot ,

I think we don't need to copy the library with Julia (and CxxWrap) of the latest version. The required change should be minor but I need to verify it first. (My response may be slow due to the Chinese New Year 😃 )

**Comment by lanctot** [comment]
Great. Happy Chinese New Year!

No rush on this. We have disabled the Julia API in all of our tests until we can figure it out.
