### ISSUE TITLE
Cool work. Do you plan to support large games, such as Texas Hold'em?

### ISSUE THREAD

**Issue by lihuiknight** [deepmind/open_spiel#5]
FYI

**Comment by lihuiknight** [comment]
wow, that's great. I plan to use this toolbox and do some experiments.

Writing Texas Hold'em solver in pure C/C++ needs a lot of effort. Looking forward.

**Comment by lihuiknight** [comment]
Yes, Noam Brown implemented Texas Hold'em solver in pure C/C++.  I meet him in IJCAI 2019.

It can imagine there are a lot of codes in his solver.  Reimplementation of such difficult game needs a lot time.

**Comment by Kailianghu** [comment]
Cool work ！The ACPC code ([http://www.computerpokercompetition.org/downloads/code/competition_server/project_acpc_server_v1.0.42.tar.bz2]) is pretty good for poker engine

**Comment by saeta** [comment]
Hey all!

Thank you very much for your interest in OpenSpiel. I lead the [Swift for TensorFlow](https://github.com/tensorflow/swift) project in Google Brain and collaborated with @lanctot and many others across both Brain and DeepMind to help make OpenSpiel. When I saw the recent research results coming out using Texas Hold'em, I built a game implementation for OpenSpiel. Unfortunately, I had some edge cases in the game engine that we discovered late, so we held it back from the initial release. Earlier this week, I fixed it up and so @lanctot has now open sourced it at https://github.com/deepmind/open_spiel/blob/master/swift/Sources/OpenSpiel/TexasHoldem.swift (I also spent some time last night and [optimized the game engine a bit](https://github.com/deepmind/open_spiel/commit/6a99c8bbb523a129c4739c25042be5673f2653b9), dropping the time to play a round from 8.4 usec down to 4.7 usec.) :-) 

I and others will be discussing the design of the Swift OpenSpiel port at the [Swift for TensorFlow Open Design Review](https://twitter.com/bsaeta/status/1166382453897871360) _this Friday (tomorrow)_. Please do join if you're able and ask us questions! (A recording will be made and posted later.) To get the invite, join [`swift@tensorflow.org`](https://groups.google.com/a/tensorflow.org/forum/#!forum/swift).

All the best,
-Brennan

**Comment by dennisjay** [comment]
Hi all!

I have an implementation of a Poker gameengine based on the ACPC-Server with a very similar API to open_spiel.

I think I'll be able to contribute it as a pull request.

Are there any style guidelines and rules for contribution? How can I contact you in case of questions?

Geetings,
DJ

**Comment by dennisjay** [comment]
Now implemeted an adapter for my previous code and made everything compile. Game unit tests are running, but no observations and information sets. 

Code is incubating here
https://github.com/dennisjay/open_spiel/tree/feature/universal_poker_game

Feedback and contributions welcome :-)
