### ISSUE TITLE
Automatic tests of games

### ISSUE THREAD

**Issue by michalsustr** [deepmind/open_spiel#50]
I think it would be nice to have a general test suite for all games which makes these kinds of generic tests, like action-infoset consistency, zero-sumness if the game claims so, etc., it would be beneficial for game developers. I didn't notice such a thing in the lib. The kinds of tests we've done in GTLib are:
- isDomainZeroSum
- domainMaxUtility
- domainMaxDepth
- isNumPlayersCountActionsConsistentInState
- isActionGenerationAndAOHConsistent

It's not much, but catches bunch of bugs fast.

**Comment by lanctot** [comment]
We have these already. See tests/basic_tests.cc (these are simulation tests done by all games) and integration_tests/api_test.py.
