### ISSUE TITLE
Install from source on Ubuntu: internal compiler error: Segmentation fault case RankType::k2... RankType::kK: {

### ISSUE THREAD

**Issue by BEMPscience** [deepmind/open_spiel#501]
Hello,

  I am trying to install open_spiel from source (after several failed attempts using pip directly). 
Ubuntu 20.04.2 LTS

cmake version 3.16.3

clang version 10.0.0-4ubuntu1 
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

Everything runs fine per the installation instructions until 
./open_spiel/scripts/build_and_run_tests.sh

```
[ 57%] Building CXX object games/CMakeFiles/games.dir/stones_and_gems.cc.o
/home/awinter/Documents/open_spiel-master/open_spiel/games/solitaire.cc: In member function 'std::vector<open_spiel::solitaire::Card> open_spiel::solitaire::Card::LegalChildren() const':
/home/awinter/Documents/open_spiel-master/open_spiel/games/solitaire.cc:394:42: internal compiler error: Segmentation fault
           case RankType::k2... RankType::kK: {
                                          ^~
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://gcc.gnu.org/bugs/> for instructions.
make[2]: *** [games/CMakeFiles/games.dir/build.make:752: games/CMakeFiles/games.dir/solitaire.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:7445: games/CMakeFiles/games.dir/all] Error 2
make: *** [Makefile:95: all] Error 2
```

This is a bit beyond my skill set to try and solve. I was wondering if anyone had an idea on how to fix this. 

Thanks!

**Comment by BEMPscience** [comment]
Digging through more of the output from the builf script I found this too

```
[ 36%] Linking CXX executable matrix_example
/home/awinter/anaconda3/bin/../lib/gcc/x86_64-conda_cos6-linux-gnu/7.3.0/../../../../x86_64-conda_cos6-linux-gnu/bin/ld: ../CMakeFiles/open_spiel_core.dir/spiel.cc.o: in function `open_spiel::Game::ToString[abi:cxx11]() const':
spiel.cc:(.text._ZNK10open_spiel4Game8ToStringB5cxx11Ev+0x3d2): undefined reference to `open_spiel::GameParametersToString(std::map<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, open_spiel::GameParameter, std::less<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, std::allocator<std::pair<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const, open_spiel::GameParameter> > > const&)'
collect2: error: ld returned 1 exit status
make[2]: *** [examples/CMakeFiles/matrix_example.dir/build.make:160: examples/matrix_example] Error 1
make[1]: *** [CMakeFiles/Makefile2:5319: examples/CMakeFiles/matrix_example.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 36%] Building CXX object games/CMakeFiles/bridge_double_dummy_solver.dir/bridge/double_dummy_solver/src/dump.cpp.o

```

**Comment by lanctot** [comment]
Seems like g++ is being used. Is clang++ in your path? Can you try prepending the build script command with `CXX=clang++ `?

**Comment by BEMPscience** [comment]
Ok thanks! I tried what you said and got this error, which is really weird
```
./open_spiel/scripts/build_and_run_tests.sh
clang++ not found (the clang C++ compiler is needed to compile OpenSpiel). Exiting...
```

but I have clang installed.

**Comment by lanctot** [comment]
Can you run the following and report the output:

```
clang++ --version
which clang++
```

**Comment by BEMPscience** [comment]
_clang++ --version_
clang version 10.0.0-4ubuntu1 
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

_which clang++_
/usr/bin/clang++

Also thank you for the help over the weekend.

**Comment by lanctot** [comment]
No problem, problems like these are usually easy.

Can you now run
```
rm -rf build venv
CXX=/usr/bin/clang++ ./open_spiel/scripts/build_and_run_tests
```

**Comment by BEMPscience** [comment]
Same error
_rm -rf build venv_

_CXX=/usr/bin/clang++ ./open_spiel/scripts/build_and_run_tests.sh_
clang++ not found (the clang C++ compiler is needed to compile OpenSpiel). Exiting..

**Comment by lanctot** [comment]
Can you try editing the build script and just commenting out that check? Should be near the top of the file.

**Comment by BEMPscience** [comment]
So that works to a point and then the whole system hangs up during the test phase and doesn't recover. 
![crashy_crash](https://user-images.githubusercontent.com/59931962/107863106-b1695580-6e0e-11eb-986a-293e7dcb5159.jpg)

I have to do a hard shutdown. Not sure where the log would be at to see what's going wring.

**Comment by BEMPscience** [comment]
But this runs _examples/example --game=tic_tac_toe_ just fine in the build directory.

**Comment by BEMPscience** [comment]
But trying this outside of the build dir

_python3 open_spiel/python/examples/example.py --game=breakthrough_

Traceback (most recent call last):
  File "open_spiel/python/examples/example.py", line 26, in <module>
    import pyspiel
ImportError: /home/awinter/Documents/open_spiel-master/build/python/pyspiel.so: undefined symbol: PyThread_tss_set

**Comment by BEMPscience** [comment]
Tried again and it gives me the those weird green bars, locks up everything but after 3 mins everything is fine again. Ran the example from build and then went up one dir and ran the python3 ... examples. 

Looks like we are good to go. Thanks!

**Comment by lanctot** [comment]
Great, enjoy!
