### ISSUE TITLE
pyspiel not found error

### ISSUE THREAD

**Issue by kausik1998** [deepmind/open_spiel#504]
Hi,
I installed everything in a separate virtual environment. Please see the attached screenshot.
![opsp](https://user-images.githubusercontent.com/56243488/108264825-ff939700-7135-11eb-8bb1-d85aa7878b52.jpg)

**Comment by lanctot** [comment]
Hi @kausik1998, 

If you're installing from source, you will need to add some directories to your PYTHONPATH environment variable. See step 4 of https://github.com/deepmind/open_spiel/blob/master/docs/install.md.

If you want to install from pip, the name of the package is open_spiel (not pyspiel). Also note that the pip installation builds from source and requires some specific build tools (with minimal versions) be installed on your system. See the instructions at the above link to check that you have them all before installing from pip.

**Comment by kausik1998** [comment]
> Hi @kausik1998,
> 
> If you're installing from source, you will need to add some directories to your PYTHONPATH environment variable. See step 4 under https://github.com/deepmind/open_spiel/blob/master/docs/install.md#summary.
> 
> If you want to install from pip, the name of the package is open_spiel (not pyspiel). Also note that the pip installation builds from source and requires some specific build tools (with minimal versions) be installed on your system. See the instructions at this [link](https://github.com/deepmind/open_spiel/blob/master/docs/install.md#python-only-installation-via-pip) to check that you have them all before installing from pip.

Thank you for your response! I will try that.

**Comment by kausik1998** [comment]
Hi,

I followed these instructions [https://github.com/deepmind/open_spiel/blob/master/docs/windows.md](url) and was able to make it work. Thank you. Closing this issue now.

**Comment by lanctot** [comment]
Great!
