### ISSUE TITLE
What's the correct usage of GameParameter in python?

### ISSUE THREAD

**Issue by ebaillie** [deepmind/open_spiel#510]
This is a request for advice, because I can't figure this out from inspecting the code.

I see that the intended format for parameterising a game is 

`game = MyGame({"myparam": pyspiel.GameParameter(2)})`

or

`game = pyspiel.load_game("game_short_name(myparam=2)")`

My first question: how are we intended to then invoke the parameter value? I have tried

`self._myparam=params['myparam']`

but this gives me a GameParameter object, when I want an integer

My second question is more of a comment - I can't get the load_game method using the syntax above to work with an actual parameter. Fails with the message  

`Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyspiel.SpielError: Unknown parameter 'myparam'. Available parameters are:
`  

I do have a default for the specific parameter set when creating the class, as in:

```
class MyGame(pyspiel.Game):

    def __init__(self,params={"myparam":pyspiel.GameParameter(4)}):
        super().__init__(self, _GAME_TYPE, _GAME_INFO, params or dict())
        self._myparam=params["myparam"]

```

Thanks in advance

**Comment by lanctot** [comment]
Tagging @elkhrt who worked on this recently.

As far as I can tell, you can't ... yet! :) Looks like we will need to expose the appropriate value functions to python here: https://github.com/deepmind/open_spiel/blob/13c81e5a7c3ac9ee8ea04ecbdc5f66d69a5863fd/open_spiel/python/pybind11/pyspiel.cc#L103  (you can add them yourself locally until we fix this: they are int_value, double_value, etc. based on the accessor functions in game_parameters.h). Then you should be able to do `self._myparam=params['myparam'].int_value()`. 

We can probably add a helper function on the python side like `parameter_value` so you don't have to call the specific type_value() functions. And yeah we should add a parameterized game as an example too.

**Comment by lanctot** [comment]
Actually if you do that, can you add the has_value functions too and submit a PR? Maybe we can also add a helper utils module in python/games that exposes a general param_value that check each type and returns the one held by the game parameter. Or hmm, maybe this ought to be in the python Game class actually.

**Comment by ebaillie** [comment]
Thanks, I appreciate the help

**Comment by elkhrt** [comment]
I've added a `.value()` method to `GameParameter` in Python - it will be available in the next push to github.
That should enable Python games with parameters - it would be great if you could add an example.

**Comment by elkhrt** [comment]
I realize I failed to address the `load_game` question. You need to populate `parameter_specification` in the `_GAME_TYPE` constant, for example:
```
    parameter_specification={"myparam": pyspiel.GameParameter(1.234)}
````
Where the supplied GameParameter object specifies the required type and provides a default value.
There's also another one-line patch needed - will push this today.

**Comment by elkhrt** [comment]
One final(?) comment on this. It is currently not completely safe to call the C++ `State` API from the Python implementation. For example, do not call `self.History()` inside the Python `do_apply_action`. It will usually work, but to get it 100% working needs some `pybind11` enhancements, so this is best avoided for now.
