### ISSUE TITLE
OpenSpiel 0.3.1 is now available!

### ISSUE THREAD

**Issue by lanctot** [deepmind/open_spiel#512]
For details see, https://github.com/deepmind/open_spiel/releases/tag/v0.3.1.

**Comment by lanctot** [comment]
I mistakenly forgot to include the optional dependencies, so universal_poker and hanabi are not available from colab. Will fix in a few hours. Reopening https://github.com/deepmind/open_spiel/issues/512

**Comment by michalsustr** [comment]
Yay! Thanks everyone involved! And especially @lanctot for the precious care :) 

Looking forward to Python games. I might use OpenSpiel in an AI intro course at the uni and make some example game like tic-tac-toe in python for the students :)

**Comment by lanctot** [comment]
> I mistakenly forgot to include the optional dependencies, so universal_poker and hanabi are not available from colab. Will fix in a few hours. Reopening #189

Ok pip package is now at version 0.3.1 and has `hanabi` and `universal_poker` back in them. Will issue another release, should fix colab.

**Comment by lanctot** [comment]
... did I say 0.3.0? I meant 0.3.1 :)

https://github.com/deepmind/open_spiel/releases/tag/v0.3.1
