### ISSUE TITLE
Observation Tensor vs Information state

### ISSUE THREAD

**Issue by willmcgowan** [deepmind/open_spiel#515]
I’ve looked through several of the python MARL algorithms(rcfr, deep cfr, nfsp, and psro) and it seems that they all use information states. Are there any MARL algorithms that can use observation tensors instead of information states?

**Comment by lanctot** [comment]
Yeah several of the ones you mention there are designed for partially observable games so will default to using information states.

The ones that use the RL environment (e.g. NFSP) are easy enough to change, you can hard-code it here: https://github.com/deepmind/open_spiel/blob/a961d89273b6ae93e47755cfe3adb54ecb880966/open_spiel/python/rl_environment.py#L193. Or set the `provides_information_state_tensor` to false in each game you are running on.

For the others you would have to change all the calls... or just change the underlying games you are running on to reroute the calls in InformationStateTensor to ObservationTensor and InformationStateTensorShape to ObservationTensorShape (two lines per game).

Note that many of those algorithms may not act as expected using observations over information states but I would be super curious if recurrent nets with observations can recover the performance of full information states with MLPs.

Hope this helps.

**Comment by willmcgowan** [comment]
This helps a lot. Thank you for answering my question.
