### ISSUE TITLE
Generate playthroughs != Regenerate playthroughs

### ISSUE THREAD

**Issue by michalsustr** [deepmind/open_spiel#516]
I generated playthroughs with `./open_spiel/scripts/generate_new_playthrough.sh "dark_chess(board_size=4)"`  (soon to be merged)

The resulting file did not include observation tensors. When I ran `./scripts/regenerate_playthroughs.sh` it was updated with the observation tensors (and stays unchanged on further calls). Maybe the `generate_new_playthrough` does not work well with Observer API?

If you want, I can take a closer look for more details.

**Comment by lanctot** [comment]
@elkhrt , can you take a look into this?

**Comment by elkhrt** [comment]
I had a quick look, and the code seems okay.
Can you reproduce the problem?

**Comment by michalsustr** [comment]
Hmm now I can't reproduce it. :) 

In the meantime I discovered there was some bug in the DC implementation I fixed, that could be related to this. So closing. 

Sorry for the non-issue.
