### ISSUE TITLE
A potential bug in minimax

### ISSUE THREAD

**Issue by findmyway** [deepmind/open_spiel#521]
From the doc, it says that:

```
value_function: An optional function mapping a Spiel `State` to a numerical
      value, to be used as the value of the maximizing player for a node when we
      reach `maximum_depth` and the node is not terminal.
```

However, the `maximizing_player_id` is not considered here.

https://github.com/deepmind/open_spiel/blob/a961d89273b6ae93e47755cfe3adb54ecb880966/open_spiel/algorithms/minimax.cc#L62

https://github.com/deepmind/open_spiel/blob/a961d89273b6ae93e47755cfe3adb54ecb880966/open_spiel/python/algorithms/minimax.py#L178

**Comment by lanctot** [comment]
Hi @findmyway, this should be ok? The doc says value function is always supposed to always been in view of the maximizing player. So you should not need the maximizing_player_id at those points -- it is used in the other parts of the function to when looking whose turn it is to play to decide whether to use min or max, e.g. lines 66 and 92 of minimax.cc.

**Comment by findmyway** [comment]
> The doc says value function is always supposed to always been in view of the maximizing player.

Sorry I may missed something. But how could one know the current maximizing player without passing it to the value function? With `state` only e all we know is the current player.

By the way, the only test case I can find with value function is a lambda function which always returns 0.

**Comment by lanctot** [comment]
The idea is that you design the function before you start the search (when you know the maximizing player) and then pass it to the search. I'll make an example.

**Comment by findmyway** [comment]
Thanks for your explanation. Now I see. So the value function has to enclose the maximizing player into it here.

**Comment by lanctot** [comment]
Well, you didn't find a bug in minimax. But..... you inadvertently found a bug in Breakthrough! My minimax example was not looking right, turns out Breakthrough::Undo was incorrect. Whoops!  So... yeah... thanks! ;-)
