### ISSUE TITLE
install.sh does not install git

### ISSUE THREAD

**Issue by vofak** [deepmind/open_spiel#523]
Shell is not my kind of thing but I believe this code in install.sh is not doing what it's supposed to:
```
set -e  # exit when any command fails

# ... some other code

git --version 2>&1 >/dev/null
GIT_IS_AVAILABLE=$?
if [ $GIT_IS_AVAILABLE -ne 0 ]; then #...
  # ... install git
fi
```
The ```$GIT_IS_AVAILABLE``` is supposed to have a non-zero value if git is not installed, because then ```git --version``` returns a non-zero value. But because of the ```set -e```, the script exits instead of setting the variable and installing git.
I propose this:
```
GIT_IS_AVAILABLE=0
git --version 2>&1 >/dev/null || GIT_IS_AVAILABLE=1
# ...
```

Could anyone check if I'm right?

**Comment by lanctot** [comment]
Hmm, yes I think you are right. 

We should just check if hit is available just like we check everything else so we don't have to run a command and have it fail.
