### ISSUE TITLE
Problems building openspiel from source.

### ISSUE THREAD

**Issue by Josef-Vonasek** [deepmind/open_spiel#532]
I have built openspiel from source, but I have trouble testing it.

- running `open_spiel/scripts/global_variables.sh` I get python 50% errors caused by missing module `absl`. Despite the fact that I installed `absl` trough pip3 (and I can import it in python3 repl)
- running `open_spiel/scripts/global_variables.sh` with `BUILD_WITH_JULIA=ON` and `test_only=julia_test` I get `make: *** No rule to make target 'spieljl'.  Stop.`

I have up to date pip, python 3.8 and julia 1.6.

**Comment by findmyway** [comment]
> running open_spiel/scripts/global_variables.sh with BUILD_WITH_JULIA=ON and test_only=julia_test I get make: *** No rule to make target 'spieljl'. Stop.

My best guess is this step failed before `make`:

https://github.com/deepmind/open_spiel/blob/f7c562588389b75dd0076fe10c26ce1a57063d5a/open_spiel/scripts/build_and_run_tests.sh#L192-L196

Could you find any other error messages except for `` make: *** No rule to make target 'spieljl' `` ?

**Comment by lanctot** [comment]
Hi @Josef-Vonasek,

If you're getting missing absl errors, then you likely didn't get abseil. You need to run `./install.sh`.

Once you've installed the dependencies, you can do the following to test Julia:

```
BUILD_WITH_JULIA=ON ./open_spiel/scripts/build_and_run_tests.sh --test_only=julia_test
```

(Setting it in the global_variables.sh is a good way to keep the settings persistent.)

**Comment by Josef-Vonasek** [comment]
Ah, that's obvious in retrospect. Thank you!
