### ISSUE TITLE
raising error when illegal action is applied: inconsistency between games

### ISSUE THREAD

**Issue by VitamintK** [deepmind/open_spiel#533]
Not a huge issue, but I figured I'd log it here since I noticed:

in Kuhn poker and universal poker, picking an illegal action for a deal does not raise an error (i.e., dealing the same card twice).  
in Leduc poker, doing so raises a `SpielError`.   
Seems like they should probably all exhibit the Leduc poker behavior?

```
>>> game = pyspiel.load_game("kuhn_poker")
>>> game.new_initial_state().child(0).child(0).child(1).child(1)
0 0 bb
>>> game.new_initial_state().child(0).child(0).child(1).child(1).returns()
[-2.0, 2.0]
```

```
>>> game = pyspiel.load_game("leduc_poker")
>>> game.new_initial_state().child(0).child(0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
pyspiel.SpielError: [...]/open_spiel/games/leduc_poker.cc:312 deck_[move] != kInvalidCard
```

**Comment by findmyway** [comment]
I experienced this issue some time ago when working with the Julia API (in Julia the index of Array starts from 1). It really took me a while to figure out that an illegal action was taken accidentally 😪

**Comment by michalsustr** [comment]
I encountered the same issue a number of times :-)) I believe the search through legal actions before ApplyAction() is not done due to performance?

**Comment by VitamintK** [comment]
> I believe the search through legal actions before ApplyAction() is not done due to performance?

Ah, I hadn't considered that.  Well, it shouldn't be much of a performance hit as long as the total number of dealt cards is low.  Alternatively, at least raising an error at some point -- perhaps when checking `returns()` at a terminal state -- should be better than nothing.

**Comment by lanctot** [comment]
@VitamintK @michalsustr yes that's the reason. It _can_ be a significant performance hit in general -- really depends on the game implementation. Some games have a lot of legal moves and they are costly to generate.

My advice: always do a check that the move is legal before calling ApplyAction. We will do is add a flag to the RL environments that will allow/enable check in the `step` method. I know it doesn't help if you're using the pure python API, but we can also add another helper function `apply_action_with_legality_check` to help as well.
