### ISSUE TITLE
Question: where is supported game list?

### ISSUE THREAD

**Issue by Hidetomi** [deepmind/open_spiel#54]
Is this a list of supported games?

> CMakeLists.txt

I wanted to see a simpler list if possible.

Thank you.

**Comment by lanctot** [comment]
Hi @Hidetomi, you can see it in the this page linked from the README (  https://github.com/deepmind/open_spiel/blob/master/docs/games.md ) or in the paper https://arxiv.org/abs/1908.09453 (Table 1, page 4).

**Comment by Hidetomi** [comment]
Hi! @lanctot, I will read it. Thank you!
