### ISSUE TITLE
Specific call for contribution: C++ DQN

### ISSUE THREAD

**Issue by lanctot** [deepmind/open_spiel#542]
Hi all, 

This is a spin-off thread from a conversation in the Amazons PR: https://github.com/deepmind/open_spiel/pull/537.

@selfsim was asking about doing RL in C++. Amazingly, we have very few RL algorithms implemented in C++. We have AlphaZero that uses the TF and PyTorch C++ interfaces, but we only two traditional ones are Q-learning and Sarsa which were recently added by @satyaki3794. I've been discussing some basic RL and algorithms with Satyaki as well, who is now interested in understanding DQN, so I thought I would suggest it as a potential collaboration with @selfsim.

So I thought.. why not also have a C++ implementation of DQN, just like we have C++ AlphaZero? I think it would be quite a fun and unique addition to the library. I don't know of any pure C++ implementations, could make a nice reference. 

I think it might be possible to almost directly port the PyTorch DQN to C++ using the PyTorch C++ API. I suggest PyTorch only because it seems to be easier to install and use the C++ interface; we've had a number of unresolved issues with connecting to TF from C++, compiling it from source is non-trivial. 

Anyway, I'm tagging also @Asugawara, who contributed several of our PyTorch algorithms, and @jhtschultz who might also be interested, and @christianjans who contributed the PyTorch C++ AlphaZero. I'm curious what you all think about this. Some part of me just wants to see it happen because we _can_ do it. And, go on.. just admit it.. it'd be pretty neat..  ;-)

**Comment by michalsustr** [comment]
+1 for PyTorch :) I think bunch of the code from the AZ implementation could be reused (refactored).

**Comment by jhtschultz** [comment]
Pretty neat indeed. Having attempted some TF C++ a while back I’d also recommend the PyTorch route. Happy to assist :)

**Comment by satyaki3794** [comment]
Yeah, I'm definitely interested in this as well. I think this will be a lot of fun. :)

**Comment by Asugawara** [comment]
That's sounds good! +1!
I'm interested in that.
If there is no other person who wants to do it, could I give it a try?

**Comment by christianjans** [comment]
This would be great! I'd be happy to help wherever I can. :)

**Comment by selfsim** [comment]
I am also interested in this!

**Comment by lanctot** [comment]
@Asugawara just submitted a PR!! https://github.com/deepmind/open_spiel/pull/575

![image](https://user-images.githubusercontent.com/3929263/117008183-048fcd80-acc5-11eb-934c-6a2ba8eab5ba.png)
