### ISSUE TITLE
Will you add the code of PSRO paper in this repo

### ISSUE THREAD

**Issue by GoingMyWay** [deepmind/open_spiel#544]
Dear @lanctot,

Thanks to you and your team for developing such good repo. Will you share the code of the PSRO's paper: _A Unified Game-Theoretic Approach to Multiagent Reinforcement Learning_ in this repo as good learning examples for other researchers?

Thank you for your attention.

**Comment by lanctot** [comment]
Hi @GoingMyWay,

Thanks for kind words. You can find an implementation of PSRO here: https://github.com/deepmind/open_spiel/tree/master/open_spiel/python/algorithms/psro_v2

There is an example to help get started:

**Comment by jordancurve** [comment]
Is there an implementation of online outcome sampling? (http://www.mlanctot.info/files/papers/aamas15-iioos.pdf)

**Comment by lanctot** [comment]
Yes, see here for example uses: https://github.com/deepmind/open_spiel/blob/master/open_spiel/algorithms/oos_test.cc

**Comment by jordancurve** [comment]
Thank you!

**Comment by GoingMyWay** [comment]
Thank you.
