### ISSUE TITLE
Feature: complex game parameters

### ISSUE THREAD

**Issue by michalsustr** [deepmind/open_spiel#545]
Hi, here is a crazy idea I was thinking about for a while and I wanted to ask your opinion about it. 

In a number of games I encountered things like "write comma/space separated values to encode arrays", game-transformations that take nested expressions, aliasing of common game strings (for goofspiel/poker), etc. 
Additionally I think it would be pretty cool to have some new powerful game transformations in place where you could just specify things like "fix this player as a chance node", "factorize actions in this game to have a maximum branching factor", "create a specific subgame",  "after each action of the player, add a chance node in this specific way", and so on, and possibly compose any of them together as well. Then you can simply reuse the same algorithms on the game as you would normally, without having to modify the algorithms!

IMHO all of this starts to look like a domain specific language over the possible games, with a C++ backend. These features can be added incrementally as they evolve, leading to hard-to-compose / hard-to-maintain code, or alternatively, they could be designed up-front. There is arguably no better language for DSLs than Lisp, and  [implementing a tiny Lisp is very easy](http://howtowriteaprogram.blogspot.com/2010/11/lisp-interpreter-in-90-lines-of-c.html). Some functions would be directly binded to C++, and there would a small number of predefined functions / macros.

Is it too crazy of an idea? :)

**Comment by lanctot** [comment]
Yeah I would like to keep these simple as they are now and discourage complex cases, or rather, in those cases specify a config file and load the settings from a file.

**Comment by michalsustr** [comment]
Yeah, I thought so :) like I said just some crazy idea. :)
