### ISSUE TITLE
Question: Is there any information that can be used to identify Open Spiel supports?

### ISSUE THREAD

**Issue by Hidetomi** [deepmind/open_spiel#55]
I am not familiar with game classification.

For example, I want to add tetris.
But I don't know if Tetris applies to the classification described in [Open Spiel supports](https://github.com/Hidetomi/open_spiel/blob/master/docs/intro.md#what-is-openspiel). Is there any information that can be used to identify it?

Thank you.

**Comment by lanctot** [comment]
Hi @Hidetomi , yes! The best place to read further on the formalisms that OpenSpiel uses (linked from that page) is the [OpenSpiel paper](https://arxiv.org/abs/1908.09453). 

Tetris is an interesting one! It can be modeled as a single-player extensive-form game (with chance eventsm required to determine the next block). I would recommend looking at the catch game, which is the closest to Tetris we currently have.

The only tricky thing is that there is no notion of a time-limit or any real-time execution / constraints in the game itself. So the game as implemented in OpenSpiel would be turn-based (like catch) and any real-time elements (such as time-limits imposed on an agent's decision, and default no-op moves if the agent doesn't respond in time) would need to be handled externally in a simulator between agent and environment.

Feel free to ask any questions if this is not clear!

**Comment by Hidetomi** [comment]
Hi @lanctot , Thank you!

> The only tricky thing is that there is no notion of a time-limit or any real-time execution / constraints in the game implementations themselves. So in OpenSpiel, the game would be turn-based (like catch) and any real-time elements (such as time-limits imposed on an agent's decision, and default no-op moves if the agent doesn't respond in time) would need to be handled externally in a a main loop between agent and environment, which would be fairly straight-forward.

I am very happy to know that. First read a paper and try to understand open_spiel.
