### ISSUE TITLE
GPU not being utilized while using LIBTORCH Alphazero

### ISSUE THREAD

**Issue by SwiftGodDev** [deepmind/open_spiel#553]
I successfully built openspiel with `BUILD_WITH_LIBTORCH=ON`. I have cuda 11.2 installed on my system. But when I start training it does not seem to utilize gpu.

**Comment by christianjans** [comment]
Hi @SwiftGodDev, thanks for reaching out. What command are your running? There is an argument for `alpha_zero_torch_example.cc` that lets you set the devices you want to use: https://github.com/deepmind/open_spiel/blob/1381619f24317fec2cdf3724fb19505e4bbfeb1d/open_spiel/examples/alpha_zero_torch_example.cc#L58-L61 It defaults to using the CPU, but let me know if you are already specifying GPU (CUDA) devices and we can take a closer look.

**Comment by SwiftGodDev** [comment]
Hi @christianjans, after reading your comment I ran this command `./alpha_zero_torch_example --devices=/cuda:0`. But it gave this error.

Logging directory: /notebooks/data/chess/
Overwriting existing model: /notebooks/data/chess//vpnet.pb
Playing game: chess
terminate called after throwing an instance of 'c10::Error'
  what():  Cannot initialize CUDA without ATen_cuda library. PyTorch splits its backend into two shared libraries: a CPU library and a CUDA library; this error has occurred because you are trying to use some CUDA functionality, but the CUDA library has not been loaded by the dynamic linker for some reason.  The CUDA library MUST be loaded, EVEN IF you don't directly use any symbols from the CUDA library! One common culprit is a lack of -Wl,--no-as-needed in your link arguments; many dynamic linkers will delete dynamic library dependencies if you don't depend on any of their symbols.  You can check if this has occurred by using ldd on your binary to see if there is a dependency on *_cuda.so library. (initCUDA at ../aten/src/ATen/detail/CUDAHooksInterface.h:63)
frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x6a (0x7f81f1550aaa in /notebooks/open_spiel/open_spiel/libtorch/libtorch/lib/libc10.so)
frame #1: <unknown function> + 0xa939e7 (0x7f81e30879e7 in /notebooks/open_spiel/open_spiel/libtorch/libtorch/lib/libtorch_cpu.so)
frame #2: void std::__once_call_impl<std::_Bind_simple<at::Context::lazyInitCUDA()::{lambda()#1} ()> >() + 0x39 (0x7f81e303dde9 in /notebooks/open_spiel/open_spiel/libtorch/libtorch/lib/libtorch_cpu.so)
frame #3: <unknown function> + 0x1247f (0x7f81e25e347f in /usr/lib/x86_64-linux-gnu/libpthread.so.0)
frame #4: <unknown function> + 0xa4a647 (0x7f81e303e647 in /notebooks/open_spiel/open_spiel/libtorch/libtorch/lib/libtorch_cpu.so)
frame #5: <unknown function> + 0x1247f (0x7f81e25e347f in /usr/lib/x86_64-linux-gnu/libpthread.so.0)
frame #6: <unknown function> + 0xe9fbff (0x7f81e3493bff in /notebooks/open_spiel/open_spiel/libtorch/libtorch/lib/libtorch_cpu.so)
frame #7: <unknown function> + 0xea19c7 (0x7f81e34959c7 in /notebooks/open_spiel/open_spiel/libtorch/libtorch/lib/libtorch_cpu.so)
frame #8: at::native::to(at::Tensor const&, c10::TensorOptions const&, bool, bool, c10::optional<c10::MemoryFormat>) + 0x7e9 (0x7f81e34969c9 in /notebooks/open_spiel/open_spiel/libtorch/libtorch/lib/libtorch_cpu.so)
frame #9: <unknown function> + 0x12236d6 (0x7f81e38176d6 in /notebooks/open_spiel/open_spiel/libtorch/libtorch/lib/libtorch_cpu.so)
frame #10: <unknown function> + 0x2ced027 (0x7f81e52e1027 in /notebooks/open_spiel/open_spiel/libtorch/libtorch/lib/libtorch_cpu.so)
frame #11: <unknown function> + 0x113f61c (0x7f81e373361c in /notebooks/open_spiel/open_spiel/libtorch/libtorch/lib/libtorch_cpu.so)
frame #12: void torch::nn::Module::to_impl<c10::Device&, bool&>(c10::Device&, bool&) + 0x2ab (0x7f81e5972c1b in /notebooks/open_spiel/open_spiel/libtorch/libtorch/lib/libtorch_cpu.so)
frame #13: void torch::nn::Module::to_impl<c10::Device&, bool&>(c10::Device&, bool&) + 0xa2 (0x7f81e5972a12 in /notebooks/open_spiel/open_spiel/libtorch/libtorch/lib/libtorch_cpu.so)
frame #14: void torch::nn::Module::to_impl<c10::Device&, bool&>(c10::Device&, bool&) + 0xa2 (0x7f81e5972a12 in /notebooks/open_spiel/open_spiel/libtorch/libtorch/lib/libtorch_cpu.so)
frame #15: void torch::nn::Module::to_impl<c10::Device&, bool&>(c10::Device&, bool&) + 0xa2 (0x7f81e5972a12 in /notebooks/open_spiel/open_spiel/libtorch/libtorch/lib/libtorch_cpu.so)
frame #16: torch::nn::Module::to(c10::Device, bool) + 0x18 (0x7f81e596da08 in /notebooks/open_spiel/open_spiel/libtorch/libtorch/lib/libtorch_cpu.so)
frame #17: ./alpha_zero_torch_example() [0x98f242]
frame #18: ./alpha_zero_torch_example() [0x9266ac]
frame #19: ./alpha_zero_torch_example() [0x43c407]
frame #20: __libc_start_main + 0xf3 (0x7f81e20b90b3 in /usr/lib/x86_64-linux-gnu/libc.so.6)
frame #21: ./alpha_zero_torch_example() [0x43bd1e]

Aborted (core dumped)

**Comment by SwiftGodDev** [comment]
I tried changing cuda versions(10.2, 11.0, 11.1) but had no luck.

**Comment by christianjans** [comment]
Thanks for the information @SwiftGodDev. Sorry, I forgot to mention that one other thing to ensure is that you are installing the correct Libtorch version. In `open_spiel/scripts/install.sh`, ensure that you have the correct Libtorch download commented-out for the version of CUDA you are using: https://github.com/deepmind/open_spiel/blob/1381619f24317fec2cdf3724fb19505e4bbfeb1d/open_spiel/scripts/install.sh#L133-L151 The default download is for CPU only, but the other downloads support CUDA. Let me know how this goes or if you already tried this.

**Comment by selfsim** [comment]
@christianjans I am currently also trying to configure my system to use a GPU. 

I'm initially trying with CUDA 11.2 and cudnn >8

Have you seen this before?

Running ./open_spiel/scripts/build_and_run_tests.sh from /home/jonas/Documents/open_spiel
Reusing virtualenv from ./venv.
Skipping installation of requirements.txt.
Building and testing in /home/jonas/Documents/open_spiel/build using 'python' (version 3.8.5).
Current build type is: Testing
BUILD_WITH_ACPC: OFF 
BUILD_WITH_EIGEN: OFF 
BUILD_WITH_HANABI: OFF 
BUILD_WITH_JULIA: OFF 
BUILD_WITH_LIBTORCH: ON 
BUILD_WITH_TENSORFLOW_CC: OFF 
BUILD_WITH_PUBLIC_STATES: OFF 
BUILD_WITH_PYTHON: ON 
BUILD_WITH_XINXIN: OFF 
BUILD_WITH_ROSHAMBO: OFF 
BUILD_WITH_GAMUT: OFF 
BUILD_WITH_ORTOOLS: OFF 
-- Caffe2: CUDA detected: 10.1
-- Caffe2: CUDA nvcc is: /usr/bin/nvcc
-- Caffe2: CUDA toolkit directory: /usr
-- Caffe2: Header version is: 10.1
-- **Found cuDNN: v?  (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)**
CMake Error at libtorch/libtorch/share/cmake/Caffe2/public/cuda.cmake:170 (message):
  PyTorch requires cuDNN 7 and above.
Call Stack (most recent call first):
  libtorch/libtorch/share/cmake/Caffe2/Caffe2Config.cmake:88 (include)
  libtorch/libtorch/share/cmake/Torch/TorchConfig.cmake:40 (find_package)
  CMakeLists.txt:230 (find_package)

seems like its not checking for the cudnn_version.h file which has the `CUDNN_MAJOR 8` definition.

I am going to try adjusting the download URL for CUDA 11.2, and if that does not work, I'll try scaling back to 10.2.

**Comment by SwiftGodDev** [comment]
I am getting the same error as well. I have cudnn>8.

**Comment by selfsim** [comment]
Hi @christianjans, @SwiftGodDev, I've made some progress here.

cudNN version:
> 8.1.1.33

nvcc --version:
> nvcc: NVIDIA (R) Cuda compiler driver
> Copyright (c) 2005-2021 NVIDIA Corporation
> Built on Sun_Feb_14_21:12:58_PST_2021
> Cuda compilation tools, release 11.2, V11.2.152
> Build cuda_11.2.r11.2/compiler.29618528_0

nvidia-smi:

> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 460.67       Driver Version: 460.67       CUDA Version: 11.2     |
> |-------------------------------+----------------------+----------------------+


The issue is that `libtorch/libtorch/share/cmake/Caffe2/public/cuda.cmake` is not set up for versions of cudNN >= 8. They made some changes to where the version appears.

I replaced the line `file(READ ${CUDNN_INCLUDE_PATH}/cudnn.h CUDNN_HEADER_CONTENTS)` with `file(READ ${CUDNN_INCLUDE_PATH}/cudnn_version.h CUDNN_HEADER_CONTENTS)`, this allows cmake to correctly read the cudNN version.

Then I created an empty `CMakeLists.txt` in `libtorch` to satisfy cmake, in order to try and build again.

This leads to some potential other issues, when running `build_and_run_tests.sh` with BUILD_WITH_LIBTORCH="ON", I get:

> -- Caffe2: CUDA detected: 10.1
> -- Caffe2: CUDA nvcc is: /usr/bin/nvcc
> -- Caffe2: CUDA toolkit directory: /usr
> -- Caffe2: Header version is: 10.1
> -- Found cuDNN: v8.1.1  (include: /usr/local/cuda/include, library: /usr/local/cuda/lib64/libcudnn.so)
> -- Autodetected CUDA architecture(s):  5.2
> -- Added CUDA NVCC flags for: -gencode;arch=compute_52,code=sm_52
> Python include dirs: /usr/include/python3.8
> -- Configuring done
> CMake Warning at algorithms/alpha_zero_torch/CMakeLists.txt:20 (add_executable):
>   Cannot generate a safe runtime search path for target torch_vpnet_test
>   because files in some directories may conflict with libraries in implicit
>   directories:
> 
>     runtime library [libnvToolsExt.so.1] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
>       /usr/local/cuda/lib64
>     runtime library [libcufft.so.10] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
>       /usr/local/cuda/lib64
>     runtime library [libcurand.so.10] in /usr/lib/x86_64-linux-gnu may be hidden by files in:
>       /usr/local/cuda/lib64
> 
>   Some of these libraries may not be found correctly.

However the build finishes with only warnings, and all tests pass, which is nice.

Running `alpha_zero_torch_example` with --devices="/cpu:0, cuda:0" crashes with:

> ./alpha_zero_torch_example --devices="/cpu:0, cuda:0"
> Logging directory: /tmp/az
> Overwriting existing model: /tmp/az/vpnet.pb
> Playing game: amazons
> terminate called after throwing an instance of 'c10::Error'
>   what():  Expected one of cpu, cuda, mkldnn, opengl, opencl, ideep, hip, msnpu device type at start of device string:  cuda (parse_type at ../c10/core/Device.cpp:37)
> frame #0: c10::Error::Error(c10::SourceLocation, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x6a (0x7f62ffb11aaa in /home/jonas/Documents/open_spiel/open_spiel/libtorch/libtorch/lib/libc10.so)
> frame #1: <unknown function> + 0x150fa (0x7f62ffaf80fa in /home/jonas/Documents/open_spiel/open_spiel/libtorch/libtorch/lib/libc10.so)
> frame #2: c10::Device::Device(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) + 0x14a (0x7f62ffaf83ba in /home/jonas/Documents/open_spiel/open_spiel/libtorch/libtorch/lib/libc10.so)
> frame #3: ./alpha_zero_torch_example() [0x943313]
> frame #4: ./alpha_zero_torch_example() [0x994791]
> frame #5: ./alpha_zero_torch_example() [0x992f28]
> frame #6: ./alpha_zero_torch_example() [0x98ef13]
> frame #7: ./alpha_zero_torch_example() [0x92674c]
> frame #8: ./alpha_zero_torch_example() [0x43fa77]
> frame #9: __libc_start_main + 0xf3 (0x7f62aed9b0b3 in /lib/x86_64-linux-gnu/libc.so.6)
> frame #10: ./alpha_zero_torch_example() [0x43f38e]
> 
> Aborted (core dumped)

However, running `alpha_zero_torch_example` with --devices="cuda:0" runs nicely, with full GPU usage.

@christianjans - do you know why its not liking the comma separated list?

**Comment by SwiftGodDev** [comment]
Thank you @selfsim, your method worked.

**Comment by SwiftGodDev** [comment]
@christianjans Can you please add an option for loading a checkpoint?

**Comment by christianjans** [comment]
Great work! Glad this was resolved. And yes, @SwiftGodDev, I will be working on including functionality to restart Libtorch AZ training from checkpoints. Additionally, there is already a branch that allows one to test their trained Libtorch AZ model against a random or MCTS player, see #319 for more information.

**Comment by SwiftGodDev** [comment]
Thank You @christianjans for the update. I will close this issue now as the problem has been resolved.
