### ISSUE TITLE
Next release planning

### ISSUE THREAD

**Issue by lanctot** [deepmind/open_spiel#555]
Hello everyone,

We are planning a release in the coming months, so I am starting a thread to discuss it and give updates.

I am currently looking into how we can get fully into PyPI, as a bdist_wheel so you don’t have to compile from source when installing via pip. Luckily we mostly already have what is necessary, and a great project like https://github.com/joerick/cibuildwheel will help automate this for various platforms and Python versions.

I have hit a few snags, mostly in an attempt to support Python 3.9, which comes as default in MacOS 10.15 (and Ubuntu 21.04). It seems like TF 2.5 has Python 3.9 support, and I was able to compile OpenSpiel and run most tests under Python 3.9 with TF 2.5, which recently issued its first release candidate. The rest seem minor and fixable, so I don’t anticipate any major problems.

Anyway it seems like a good opportunity to line up with the TF/Ubuntu releases and official Python 3.9 support, so it won’t be any earlier than May.. maybe more like June.

**Comment by michalsustr** [comment]
This is awesome! We're using OpenSpiel in a basic AI course (things like minimax/alphabeta/mcts) since it has a number of game implementations. The precompiled binaries are the number one thing that would be useful, because right now starting up a colab means you have to wait for up to 15min before everything compiles. Thanks a lot!

**Comment by lanctot** [comment]
Ok I have spent a bit of time looking into this. Here's a quick update.

### Python 3.9

I was able to get OpenSpiel compiled and running in Python 3.9, with TF 2.5.0rc0

- neurd_test is either crashing (when run wheels.yml using the build_and_run_scripts.sh directly in my fork) or hanging (on my personal desktop / MacOS CI). It is clearly related to Tensorflow because when run on the CI after an hour it crashed with a TF error about building a graph. We will have to rerun with TF verbosity flag enabled and follow up with the TF team.
- the current dm_tree release does not support Python 3.9, so we can either wait or just remove the dm-haiku + optax dependencies and (temporarily) disable the single affected test until dm_tree is release. I will coordinate with @superbobry.

### Binary bdist_wheel

- I have been trying to get cibuildwheel working, and have had a lot of help from the team. I discovered that the manylinux docker images don't have clang++ (https://github.com/joerick/cibuildwheel/issues/638), which is fine because the g++ build still works. Maybe @michalsustr will be happy to hear that we'd have to officially support it again. Maybe an opportunity to fix all those compilation warnings :) Another small change is required to the python CMakeLists when running in cibuildwheel, details here:https://github.com/joerick/cibuildwheel/issues/639

The wheels are currently not building in my fork despite the fixes because it seems some of our code cannot compile under old compilers (installed in the docker images required to support wide use of systems and python versions). We can go a fix all these but I'm slightly worried about the maintenance burden this imposes, and especially if it makes it harder for new contributions. Imagine PRs not passing tests because an outdated distribution/toolchain can't compile the code which compiles perfectly fine on a modern system. The tree project currently uses GitHub Actions directly and it's wonderfully simple: https://github.com/deepmind/tree/blob/master/.github/workflows/ci.yml, the only problem is that it requires the manylinux_2_24 docker image which is very new and so might not work on older systems. Also, there'd always still be the current solution of building manually from source.

Anyway, there are some trade-offs to consider here. I would love to hear from @elkhrt @superbobry and/or anybody with experience on this.

**Comment by lanctot** [comment]
Quick update: 

We decided to remove a lot of official python dependencies (#563), making the python installation a lot less bulky. Of course this doesn't quite solve the weird issue with Python 3.9 and `python_neurd_test` but it would at least allow a wheel to be built and the main API to be used-- which is Python 3.9-compatible-- without the TF release. It will also make installing the pip for use of the core API much easier, and let users install only what they need/use.

I seem to have fixed the last of the C++ issues with older compilers (in my fork), but now running into some other issues with cibuildwheel and docker that I will follow-up on.

**Comment by lanctot** [comment]
Another update: I fixed the one problematic C++ compilation problem on older g++ and we successfully built our first official bdist wheel using cibuildwheel today (targeting Python 3.6 on the manylinux2014 image). This is great because any other issues with different Python versions should be simple to solve (modulo the pending TF issue). Will pursue fixing the code for MacOS compilers on the manylinux images, but this is good. We are on track for a May / June release.

**Comment by lanctot** [comment]
I managed to build our first set of bdist wheels built with cibuildwheel, and installed it externally (on my Mac laptop and personal Ubuntu desktop). It installed in about 3 seconds, and worked. :slightly_smiling_face:

**Comment by michalsustr** [comment]
> Anyway it seems like a good opportunity to line up with the TF/Ubuntu releases and official Python 3.9 support, so it won’t be any earlier than May.. maybe more like June.

This would be a perfect timeline also for the competition as we could have the games as easily available as just with `pip install open_spiel` :) I will try to get everything in before well implemented and tested. Currently there is missing RBC and Gin Rummy updates, and a mechanism for not revealing perfect information in the game. I think the last could be done via communication with a referee that will only supply requested information (i.e. something like exposing Observer API via standard input/output).

**Comment by lanctot** [comment]
Sounds good @michalsustr . Also, keep in mind we can do minor releases after the big one (and update the wheel each time) so there's no rush to get all that finished for this first release of the bdist wheel.

**Comment by lanctot** [comment]
Quick update the the problem with neurd_test has been resolved as of TF 2.5.0rc2, and https://github.com/deepmind/open_spiel/pull/572 moves our supported versions up to Python3.9.

Everything is looking good now, the last thing we need to do add test for the installed wheel, and we'll be good to go.

**Comment by lanctot** [comment]
Just a quick heads-up that there is just too much to do before the release, so this will be getting pushed to the summer. Hopefully July but possibly further. It might be big enough for 1.0, still discussing that with the team.

**Comment by lanctot** [comment]
Ok, the bdist_wheel PR has been merged: https://github.com/deepmind/open_spiel/pull/583

Thanks especially to @henryiii who had many helpful suggestions for use of cibuildwheel with CMake.

Release coming this or next week..! Will now close this thread and open a new one when it's live.
