### ISSUE TITLE
Observation tensor shape mismatch in Tic-Tac-Toe

### ISSUE THREAD

**Issue by uduse** [deepmind/open_spiel#558]
```python
game = pyspiel.load_game('tic_tac_toe')
state = game.new_initial_state()
obs = state.observation_tensor(state.current_player())
print(np.asarray(obs).shape)
print(game.observation_tensor_shape())
```
This prints:
```
(27,)
[3, 3, 3]
```
Is this an intended behavior?

**Comment by lanctot** [comment]
Hi @uduse,

Intended might be a strong word ... :) This is _expected_ behavior in the sense that it is not a bug: observation_tensor has always returned the flattened data (as a vector or floats) that you then have to reshape when storing into numpy arrays. It is not ideal, and we should probably have a function exposed that returns the observation with its appropriate shape.

@locked made some changes to the observations last summer with the intention of getting them to be better integrated with numpy, but I'm not sure if we ever actually went the extra step after that. If not, it should be quite easy and it'd be a welcome addition to the library. The data is already is represented in the correct way internally, so I don't think there is any need for copying, and there's a few examples of numpy buffers used in the TensorGame wrapping.

**Comment by elkhrt** [comment]
Yes, this is intended - our original API just returns a flat vector. But as Marc says there is a new & improved method.
```
import pyspiel
from open_spiel.python.observation import make_observation

game = pyspiel.load_game('tic_tac_toe')
obs = make_observation(game)
state = game.new_initial_state()
obs.set_from(state, player=0)
print({k: v.shape for k, v in obs.dict.items()})
```
Prints:
```
{'observation': (3, 3, 3)}
```
As well as getting the shape right, this also allows reuse of the same numpy array, so avoids a bunch of allocations. Furthermore, for non board games, the observation can be reported in multiple pieces, e.g. the above code for kuhn_poker produces:
```
{'player': (2,), 'private_card': (6,), 'community_card': (6,), 'pot_contribution': (2,)}
```

**Comment by uduse** [comment]
@lanctot  @elkhrt Thank you for your answers! It makes sense to me now. 🙏 😄
