### ISSUE TITLE
Inconsistent documentation in case no possible actions

### ISSUE THREAD

**Issue by TheoCabannes** [deepmind/open_spiel#588]
In case a player has no possible actions, the documentation is not clear.

ApplyActions states that the player should have the action kInvalidAction: https://github.com/deepmind/open_spiel/blob/53eeb6127578f91e88a6c0451983d10e3509446d/open_spiel/spiel.h#L557.
Generate_playthrough.py seems to work when the player has kInvalidAction as action.

LegalActions seems to say that the player should have a empty list: https://github.com/deepmind/open_spiel/blob/53eeb6127578f91e88a6c0451983d10e3509446d/open_spiel/spiel.h#L229
spiel.cc returns an error in case kInvalidAction is used https://github.com/deepmind/open_spiel/blob/53eeb6127578f91e88a6c0451983d10e3509446d/open_spiel/spiel.cc#L317
This makes CFR not working on a game I am developing in my own fork: https://github.com/TheoCabannes/open_spiel/issues/7

Can you help me? Is what I am saying true?
Can CFR works with games where some players do not have valid actions?

**Comment by lanctot** [comment]
Hi @TheoCabannes,

Sure we can help but I have to understand your use case first.

Is it a simultanrous move game? If so are you loading it as a sequential game using turn_based_simultaneous_game?

Sounds you are indeed hitting some uncovered use cases of our API.

**Comment by TheoCabannes** [comment]
Indeed, I am creating a simultaneous move game and I am loading it as a sequential game using turn_based_simultaneous_game. I am also currently writing it with python.

I am currently hitting several issues, so I will probably create a small use case in order to enable debugging my current issues.
Hopefully, the small use case can later be converted in a test.

Thank you a lot for your help!

**Comment by lanctot** [comment]
If a simultaneous game, are you saying you have nodes where some players have actions and others don't have any?

Can we clearly exclude the case that it is a player's turn and they have zero legal moves?

**Comment by lanctot** [comment]
Absolutely we will definitely make sure it is properly handled and covered in a test afterward. Thanks a lot for your help in following up.

**Comment by TheoCabannes** [comment]
Yes, in some nodes some players have actions and other not.
When converting into turn based it created nodes where there is no legal moves.
Currently, one fix is to use kInvalidAction in this case and comment the line https://github.com/deepmind/open_spiel/blob/53eeb6127578f91e88a6c0451983d10e3509446d/open_spiel/spiel.cc#L317

For more context, I am working on a research project based on the implementation of dynamic routing game very similar to this game http://www.professeurs.polymtl.ca/jerome.le-ny/docs/proceedings/2018_CDC_MFGrouteChoice_Salhab.pdf. I am in contact with Julien Perolat who is helping me.

**Comment by lanctot** [comment]
Yeah absolutely not surprised that the code does not handle this case (nor that the docs are inconsistent). This should indeed be fixed and covered by tests. Should be an easy fix, will try to have it dobe by next sync github sync (Monday). Will update this thread as we progress.

This is great timing too, catching these before the release.

Dynamic routing games are definitely something I would love to see in OpenSpiel. Thanks for the context.

**Comment by TheoCabannes** [comment]
I created a PR to show my current issues: https://github.com/deepmind/open_spiel/pull/589

**Comment by lanctot** [comment]
Ok @TheoCabannes, I have looked into this and have some updates.

First of all, I would like to separate two things that are being mixed up currently:

1. Proper support for simultaneous move games where some players have no legal actions (along with clear documentation on how these are to be supported)
2. Implementation of a simultaneous move games in Python, and how they can be converted to sequential games to run CFR.

I will not talk at all about (2) because it unnecessarily complicates explaining of (1), which IMO needs to be handled first. @elkhrt  is looking into (2) right now and I believe will have a fix soon.

On (1), it turns out we had most of the functionality already there, but there were bugs. I have just managed to fix those and to make a test that runs CFR on a game of this form. It will be merged in the next sync (Monday) and linked to this thread so you can see it. The fixes were entirely on the C++ side, and CFR running in C++.

Regarding documentation:

- `LegalActions(player)` should indeed return an empty list if player has no legal actions
- `ApplyActions(const std::vector<Action>& actions)` has to have length equal to number of players, so _something_ needs to be passed for every player, even if they have no legal moves. kInvalidAction actually doesn't work because it can't properly be converted from the mapping of flat joint action to vector of actions. So I have updated the docs to clearly explain this, and recommend using 0 for those cases.

The turn_based_simultaneous_game actually skips over the players without any legal moves. This was the intention all along, but it was buggy. My fix should address that. So when you convert to a turn-based game, CFR will never see those states because the converter skips over them, and hence does not need to have a policy defined for them (nor stores any info about them).

**Comment by TheoCabannes** [comment]
Thank you a lot @lanctot.
Two questions/remarks on the point (1).
1. In case LegalActions returns a empty list for player without actions and ApplyActions needs an argument so it takes as argument a list of length equal to the number of player, should generate_playthrough be changed? Also in this case, then the example [here](https://github.com/deepmind/open_spiel/blob/master/docs/concepts.md#playing-a-trajectory) is not correct anymore.
2. On your suggestion to pass 0 as action of players without legal actions (instead of kInvalidActions). This seems to me a little bit weird because 0 can model an action which is not legal for the players without legal actions. Should we create a new variable (for example kNoLegalActions) with value num_actions() and consider that their are num_actions()+1 legal actions? It seems that in any case [this documentation line](https://github.com/deepmind/open_spiel/blob/53eeb6127578f91e88a6c0451983d10e3509446d/open_spiel/spiel.h#L557) should be changed

**Comment by lanctot** [comment]
Yes generate_playthrough shoukd be changed. I don't see why the example is mot correct. Can you explain why you think so.

Yes the doc line has been change. You will only see the change when we apply the sync of our internal repo with github, which happens on Mondays.

**Comment by TheoCabannes** [comment]
Sorry, the example is still correct. But it only applies to sequential games, as simultaneous games use state.legal_actions().

For simultaneous game this will be incorrect:
```python3
legal_actions = state.legal_actions()
actions = random.choice(legal_actions)
state.apply_action(actions)
```

**Comment by lanctot** [comment]
Actually that should still work too, but I will add a test to be sure.

There is an inherited version of ApplyAction that converts a flat action into its equivalent joint action (see simultaneous_move_game.h).

**Comment by TheoCabannes** [comment]
I see. For a simultaneous python game my example fails. But this is due to the issue raised in https://github.com/deepmind/open_spiel/pull/587:
LegalActions bindings does not cover LegalActions(player p) due to potentially some issue with overloading in python.

**Comment by TheoCabannes** [comment]
I will try it with C++ code

**Comment by lanctot** [comment]
> I will try it with C++ code

It will fail. :) You have to wait until Monday. :-p

I also caught a few more things as a result of your last messages, and fixed them too. I don't have the python side of if tested, but I'll try to get it in there too.

@elkhrt also got an example simultaneous game implemented and working too, so it will be a big update.

**Comment by lanctot** [comment]
> Thank you a lot. Looking forward for the fix on Monday. For the python tests, I have done [this PR](https://github.com/deepmind/open_spiel/pull/589) that creates test for python implementation of a simultaneous game.

Great! Once all this new code is live, it should be as easy as just pulling changes from master and should work from then on.

> On the previous questions: should we create a new variable (for example kNoLegalActions) with value num_actions() and consider that they are num_actions()+1 legal actions? This will enable avoiding using 0 to encode no legal possible actions and the action 0.

I think it's too much. This is a rare case... I think it's fine to just keep the lists empty and submit 0 in the simultaneous move case. And actually, I believe it has to be 0 for the flat action to joint action converter to work properly. I don't think it's so bad to overload -- you can pass anything as the actions for those players because they should get ignored, but 0 makes sense to ensure the flat action -> joint action converter still works (would be good to add a test for that!) 

@elkhrt wdyt?

**Comment by elkhrt** [comment]
Agree passing action=0 makes sense for nodes without actions.
We could alternatively make it a vector<optional<Action>> or a map<Player, Action>

**Comment by lanctot** [comment]
Yeah and I prefer the 0 option than map (too heavy) and optionals (not supported fully through pybind11 without an additional dependency).

**Comment by TheoCabannes** [comment]
Thank you for the fix (and the python iterated_prisoners_dilemma).
However the inconsistencies have not been fully solved.
It seems from the discussion that legal_actions() should return [0] and not an empty list when there is no action possible.
In the [docs](https://github.com/deepmind/open_spiel/blob/cb327b1d662e3552416c9e10af61cf994ae6a746/open_spiel/spiel.h#L231), it still says that legal_actions(Player player) should return an empty list.

In case an empty list is returned then example is failing:
![Screen Shot 2021-05-17 at 4 23 19 PM](https://user-images.githubusercontent.com/23631115/118506033-3e34ef80-b72d-11eb-9ea9-e2a82eb46436.png)
The error is raised from [here](https://github.com/deepmind/open_spiel/blob/cb327b1d662e3552416c9e10af61cf994ae6a746/open_spiel/python/examples/example.py#L85).

I am not sure if there is any test for this. I would suggest to change documentation of legal_actions(Player player) and create another example similar to [this dynamic routing game](https://github.com/deepmind/open_spiel/pull/599) to test these cases. Current in my dynamic routing game PR, I do not pass empty list when no actions is legal for a player.
The python iterated_prisoners_dilemma does not test when:
1. A player does not have any legal actions. And here, 0 does not correspond to no legal actions but to the action cooperate.
2. the two players have different actions.

Can the issue be re-open?

**Comment by TheoCabannes** [comment]
This issue should also be raised in:
https://github.com/deepmind/open_spiel/blob/cb327b1d662e3552416c9e10af61cf994ae6a746/open_spiel/examples/example.cc#L120
and 
https://github.com/deepmind/open_spiel/blob/cb327b1d662e3552416c9e10af61cf994ae6a746/open_spiel/examples/benchmark_game.cc#L84

**Comment by lanctot** [comment]
Hi @TheoCabannes, 

I think there was a misunderstanding:

1. LegalActions(player) should return an empty list when player does not have any legal actions.
2. When calling ApplyActions(std::vector<Action> actions), a 0 should be passed into the index for any players that do not have legal actions.

That was solved in this commit: https://github.com/deepmind/open_spiel/commit/8d38f58f907330002b7885acf28d9c343257fc75

**Comment by lanctot** [comment]
Whoops, I think I missed example.py. We did add it in the tests (see that commit above), we just have to apply a similar fix to example.py.

**Comment by TheoCabannes** [comment]
Hi @lanctot,
Then in this case, the following lines needs to be changed:
https://github.com/deepmind/open_spiel/blob/cb327b1d662e3552416c9e10af61cf994ae6a746/open_spiel/python/examples/example.py#L85
https://github.com/deepmind/open_spiel/blob/cb327b1d662e3552416c9e10af61cf994ae6a746/open_spiel/examples/benchmark_game.cc#L84
https://github.com/deepmind/open_spiel/blob/cb327b1d662e3552416c9e10af61cf994ae6a746/open_spiel/examples/example.cc#L119
Because they will throw IndexError in python and (I guess) segmentation fault in C++.
Please see the screenshot below:
![Screen Shot 2021-05-17 at 4 23 19 PM](https://user-images.githubusercontent.com/23631115/118508285-573ea000-b72f-11eb-897c-7c4b449c8651.png)

**Comment by lanctot** [comment]
Yes you're right. Can you submit another PR (you can fix them all in one PR)?

**Comment by lanctot** [comment]
Oh sorry, the change I described was in a different commit, this one: https://github.com/deepmind/open_spiel/commit/96bd3e1e65d2c36947b4e45a7033bf775b8bbbe7

See the changes I made in generate_playthrough.py, games_sim_test.py, and basic_tests.py.

It does not matter that 0 encodes a legal action: it's only being used as a placeholder value when the agent has no legal actions. @elkhrt was talking about have a special action for it and then just changing the mapping from flat actions to joint actions, so maybe you can wait for him to do it? Or he and I can guide you through it if you want to do it?

**Comment by TheoCabannes** [comment]
I created this PR https://github.com/deepmind/open_spiel/pull/601

**Comment by elkhrt** [comment]
Using 0 seems reasonable to me. We could alternatively require kInvalidAction (-1) for cases where the player has no legal action, but this would require a few other changes. Let me know if you fancy doing that and I can provide some guidance.
