### ISSUE TITLE
Julia test failing

### ISSUE THREAD

**Issue by lanctot** [deepmind/open_spiel#606]
Hi @findmyway, seems like there are still some problems with the Julia test so I've disabled it again. See: https://github.com/deepmind/open_spiel/runs/2613878461?check_suite_focus=true.

I _think_ currently the line with the copy of the libstdc++.so is only triggered when julia is installed manually. On Github Actions, Julia 1.6.1 is installed in /usr/local/julia. So I wonder if there's a similar patch for this issue in that case?

**Comment by findmyway** [comment]
> I _think_ currently the line with the copy of the libstdc++.so is only triggered when julia is installed manually. On Github Actions, Julia 1.6.1 is installed in /usr/local/julia. So I wonder if there's a similar patch for this issue in that case?

That explains it!
I was wondering why the v1.6.1 was installed 🤣

**Comment by lanctot** [comment]
Fixed by https://github.com/deepmind/open_spiel/commit/1cb359c8d2b9f83283c5d6f6b53bd1ba2109eeb9
