### ISSUE TITLE
az_path Unicode Decode Error

### ISSUE THREAD

**Issue by fzh6762788** [deepmind/open_spiel#607]
Hi everyone, 

I wanted to use the following line to start a game between the az-trained model and me. 

python3 open_spiel/python/examples/mcts.py --game=connect_four --player1=az --player2=human --az_path=/mnt/d/Windows_to_Ubuntu/connect_four/checkpoint-240.pt

However, I ran into the following issue. I am using Ubuntu 20.04 LTS on my Windows 10. It passed 100% of the tests after I installed everything based on the instructions for Windows users. Also, I installed libtorch based on my colleague's suggestion. Unfortunately, this is still an issue. I hope someone could give me some suggestions. Thank you for your time and help in advance. 

2021-05-18 19:01:49.871135: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2021-05-18 19:01:49.873442: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "open_spiel/python/examples/mcts.py", line 223, in <module>
    app.run(main)
  File "/home/fengzhihao/.local/lib/python3.8/site-packages/absl/app.py", line 303, in run
    _run_main(main, args)
  File "/home/fengzhihao/.local/lib/python3.8/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "open_spiel/python/examples/mcts.py", line 197, in main
    _init_bot(FLAGS.player1, game, 0),
  File "open_spiel/python/examples/mcts.py", line 96, in _init_bot
    model = az_model.Model.from_checkpoint(FLAGS.az_path)
  File "/home/fengzhihao/open_spiel/open_spiel/python/algorithms/alpha_zero/model.py", line 202, in from_checkpoint
    model = cls.from_graph(checkpoint, path)
  File "/home/fengzhihao/open_spiel/open_spiel/python/algorithms/alpha_zero/model.py", line 215, in from_graph
    saver = tf.train.import_meta_graph(metagraph)
  File "/home/fengzhihao/.local/lib/python3.8/site-packages/tensorflow/python/training/saver.py", line 1465, in import_meta_graph
    return _import_meta_graph_with_return_elements(meta_graph_or_file,
  File "/home/fengzhihao/.local/lib/python3.8/site-packages/tensorflow/python/training/saver.py", line 1481, in _import_meta_graph_with_return_elements
    meta_graph_def = meta_graph.read_meta_graph_file(meta_graph_or_file)
  File "/home/fengzhihao/.local/lib/python3.8/site-packages/tensorflow/python/framework/meta_graph.py", line 643, in read_meta_graph_file
    text_format.Merge(file_content.decode("utf-8"), meta_graph_def)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 70: invalid start byte

**Comment by lanctot** [comment]
Hi @fzh6762788,

What produced `checkpoint-240.pt` ? The Python (TF-based) AlphaZero, or the Libtorch (C++-based) AlphaZero?

I believe that playing against a checkpoint in `examples/mcts.py` in your message was designed for the former. So if you're sending it LibTorch-generated checkpoints, that would certainly explain things.  I'm not 100% sure if we have something that can play against the torch-based checkpoints, but I know the original author is working on something related currently.

@tewalds, @christianjans can you weigh in on this?

**Comment by fzh6762788** [comment]
Hi Lanctot,

Thank you so much for your response. That explains a lot. Yes, our az model was based on Libtorch. We thought that we could solve this by installing Libtorch. We are looking forward to receiving any updates on this matter.

**Comment by lanctot** [comment]
I just remembered that @christianjans did add this recently: https://github.com/deepmind/open_spiel/pull/557

Specifically there is a C++ example that you can run called alpha_zero_game_example, here:

**Comment by christianjans** [comment]
Hi @fzh6762788 and @lanctot, yes, to play a LibTorch model, run the `alpha_zero_torch_game_example`. The flags are slightly different than in `examples/mcts.py`, but hopefully they are clear. Please don't hesitate to ask if you have any questions!

And regarding the documentation for LibTorch AlphaZero, I have updated (and will continue update if things are unclear or need clarification) the `alpha_zero_torch/README.md` in #581 to show how to train, continue training, and play a saved model.

**Comment by fzh6762788** [comment]
Hi @christianjans, this is a naive question. Do I still need to download or install something in my Ubuntu terminal? I am a little confused. Thank you so much for your time and help.

**Comment by lanctot** [comment]
Do you see it in build/examples? i.e. can you run `ls -l ./build/examples`?

If not, you can try building it:
```
cd build
make alpha_zero_torch_game_example
```

If it doesn't work, can you paste the exact error?

**Comment by fzh6762788** [comment]
@lanctot Thank you for your reply. I did not see that under /open_spiel/build/examples file. So I tried to build it under /open_spiel/build. It returned me "no rule to make target" as follows:

fengzhihao@Feng:~/open_spiel/build/examples$ ls
CMakeFiles           Makefile        cfr_example                   cmake_install.cmake  example  imperfect_recall_mccfr  mcts_example                                                                      policy_iteration_example    tabular_sarsa_example
CTestTestfile.cmake  benchmark_game  cfr_multi_equilibria_example  count_all_states     gtp      matrix_example         minimax_example  tabular_q_learning_example  value_iteration_example
fengzhihao@Feng:~/open_spiel/build/examples$ cd ..
fengzhihao@Feng:~/open_spiel/build$ make alpha_zero_torch_game_example
make: *** No rule to make target 'alpha_zero_torch_game_example'.  Stop.
fengzhihao@Feng:~/open_spiel/build$

Please let me know I made any mistakes.

**Comment by christianjans** [comment]
Hi @fzh6762788, no worries, but yeah that is strange.

The updated README for LibTorch AlphaZero (https://github.com/deepmind/open_spiel/blob/49bfd9cb044316d58624bfd7a4436aab381322de/open_spiel/algorithms/alpha_zero_torch/README.md) may help. It has instructions on how to install, build, run training, and play a trained model for LibTorch AlphaZero. Did your setup process of LibTorch AlphaZero look similar to what this README is outlining?

Also, I'm wondering, the `alpha_zero_torch_game_example.cc` is a relatively new addition to OpenSpiel, if you run `ls open_spiel/examples/` does `alpha_zero_torch_game_example.cc` show up?

**Comment by fzh6762788** [comment]
@christianjans 
Yes, I followed the instructions by running the following lines under the /open_spiel file, 

export OPEN_SPIEL_BUILD_WITH_LIBTORCH="${OPEN_SPIEL_BUILD_WITH_LIBTORCH:-"ON"}"
and 
export OPEN_SPIEL_BUILD_WITH_LIBTORCH_DOWNLOAD_URL="${OPEN_SPIEL_BUILD_WITH_LIBTORCH_DOWNLOAD_URL:-"https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-1.5.1%2Bcpu.zip"}"
and
./install.sh
 
Then, I got "command not found". Should I run those lines under another directory? 

However, I saw alpha_zero_torch_game_example.cc under open_spiel/examples/. 

Please let me know if it is solvable. Thank you for your help

**Comment by christianjans** [comment]
Okay great @fzh6762788, glad you have `alpha_zero_torch_game_example.cc` 👍

And the commands look right. What command led to the "command not found" error? Did you also run `./open_spiel/scripts/build_and_run_tests.sh` after running `./install.sh`?

**Comment by fzh6762788** [comment]
Thank you for your response. Here is what I got after I ran ./open_spiel/scripts/build_and_run_tests.sh under /open_spiel directory. Please let me know where I can improve.

fengzhihao@Feng:~/open_spiel$ ./open_spiel/scripts/build_and_run_tests.sh
Running ./open_spiel/scripts/build_and_run_tests.sh from /home/fengzhihao/open_spiel
Reusing virtualenv from ./venv.
Skipping installation of requirements.txt.
Building and testing in /home/fengzhihao/open_spiel/build using 'python' (version 3.8.5).
Current build type is: Testing
OPEN_SPIEL_BUILD_WITH_ACPC: OFF
OPEN_SPIEL_BUILD_WITH_EIGEN: OFF
OPEN_SPIEL_BUILD_WITH_GO: OFF
OPEN_SPIEL_BUILD_WITH_HANABI: OFF
OPEN_SPIEL_BUILD_WITH_JULIA: OFF
OPEN_SPIEL_BUILD_WITH_LIBTORCH: ON
OPEN_SPIEL_BUILD_WITH_TENSORFLOW_CC: OFF
OPEN_SPIEL_BUILD_WITH_PYTHON: ON
OPEN_SPIEL_BUILD_WITH_XINXIN: OFF
OPEN_SPIEL_BUILD_WITH_ROSHAMBO: OFF
OPEN_SPIEL_BUILD_WITH_GAMUT: OFF
OPEN_SPIEL_BUILD_WITH_ORTOOLS: OFF
OPEN_SPIEL_ENABLE_JAX: AUTO
OPEN_SPIEL_ENABLE_PYTORCH: AUTO
OPEN_SPIEL_ENABLE_TENSORFLOW: AUTO
OPEN_SPIEL_ENABLE_PYTHON_MISC: OFF
CMake Error at CMakeLists.txt:224 (find_package):
  By not providing "FindTorch.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Torch", but
  CMake did not find one.

  Could not find a package configuration file provided by "Torch" with any of
  the following names:

    TorchConfig.cmake
    torch-config.cmake

  Add the installation prefix of "Torch" to CMAKE_PREFIX_PATH or set
  "Torch_DIR" to a directory containing one of the above files.  If "Torch"
  provides a separate development package or SDK, be sure it has been
  installed.


-- Configuring incomplete, errors occurred!
See also "/home/fengzhihao/open_spiel/build/CMakeFiles/CMakeOutput.log".
See also "/home/fengzhihao/open_spiel/build/CMakeFiles/CMakeError.log".
Exiting virtualenv

**Comment by fzh6762788** [comment]
Hi @lanctot @christianjans,

My colleague helped me fix the issue above earlier. It turns out that it was a small issue that had nothing to do with open_spiel. This issue was because Unzip did not come with Ubuntu's installation. I never knew it had to be installed in the subsystem. After we installed Unzip and ran the open_spiel installation again, the AZ model with Pytorch worked! Thank you so much for your time and help.

**Comment by christianjans** [comment]
Oh great to hear @fzh6762788! Glad this has been resolved, good find!
