### ISSUE TITLE
Requirements missing

### ISSUE THREAD

**Issue by VojtaKovarik** [deepmind/open_spiel#609]
When installing openspiel on windows, I followed the steps listed in documentation. Afterwards, 36 tests failed. It seems the issue was that some (many?) requirements were missing. Eg, numpy didn't get installed. The file requirements.txt only contained three items, so it could have something to do with that.

**Comment by lanctot** [comment]
Yeah many of them are now not officially "required" and have become optional as of this commit: https://github.com/deepmind/open_spiel/commit/146c76158344f76bee6ad2bfd71e852c9ccd6504. Those tests now only get included if the additional packages are detected as installed, which works properly on MacOS and Linux -- probably the windows instructions need to be updated.

They have been moved to this file: https://github.com/deepmind/open_spiel/blob/master/open_spiel/scripts/python_extra_deps.sh. For now, You can see how we install them in here: https://github.com/deepmind/open_spiel/blob/master/open_spiel/scripts/travis_script.sh:

```
source ./open_spiel/scripts/python_extra_deps.sh
pip3 install --upgrade $OPEN_SPIEL_PYTHON_JAX_DEPS $OPEN_SPIEL_PYTHON_PYTORCH_DEPS $OPEN_SPIEL_PYTHON_TENSORFLOW_DEPS $OPEN_SPIEL_PYTHON_MISC_DEPS
```

**Comment by lanctot** [comment]
Just took a look at the Windows instructions -- CMake should be auto-detecting the things you need just like on Linux and MacOS.

Are you using CMake to build via Step 7 on this page? https://github.com/deepmind/open_spiel/blob/master/docs/windows.md. If so, it should not run those extra tests that depend on the things that you don't have installed.

Before installing anything, can you try this and send me the output:
```
rm -rf build
mkdir build
CXX=clang++ cmake -DPython3_EXECUTABLE=$(which python3) -DCMAKE_CXX_COMPILER=clang++ ../open_spiel
```

**Comment by lanctot** [comment]
Oh wait numpy specifically that is something from `requirements.txt`. Much of our code just assumes it's installed (even outside of those extra deps above), we should really add it to `requirements.txt`. Can you try doing that and see how many of those 36 tests pass after rerunning the `pip3 install -r requirements.txt` ?

**Comment by VojtaKovarik** [comment]
I dirty-fixed it in the meantime by using an old requirements.txt file, after which it worked.

But sure, let me try reinstalling it in the way you mentioned, s.t. we can fix it for future people :-).

**Comment by lanctot** [comment]
Thanks I appreciate that, when you get it working can you submit a PR? :)

**Comment by VojtaKovarik** [comment]
When I add `numpy >= 1.16` to requirements.txt, two out of the 155 tests still fail:
> 116 - python_policy_gradient_test
> 150 - run_python_test
Not sure what is still missing. I will have to leave this unresolved for now though, because of certain upcoming deadlines :-).

**Comment by VojtaKovarik** [comment]
> Are you using CMake to build via Step 7 on this page? https://github.com/deepmind/open_spiel/blob/master/docs/windows.md. If so, it should not run those extra tests that depend on the things that you don't have installed.
> 
> Before installing anything, can you try this and send me the output:
> 
> ```
> rm -rf build
> mkdir build
> cd build
> CXX=clang++ cmake -DPython3_EXECUTABLE=$(which python3) -DCMAKE_CXX_COMPILER=clang++ ../open_spiel
> ```

When doing a fresh instal in a virtual environment, I got the following after running `CXX=clang++ cmake -DPython3_EXECUTABLE=$(which python3) -DCMAKE_CXX_COMPILER=clang++ ../open_spiel`:

`-- The C compiler identification is GNU 9.3.0
-- The CXX compiler identification is Clang 10.0.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
Current build type is: Testing
OPEN_SPIEL_BUILD_WITH_ACPC not set. Defaults to OFF
OPEN_SPIEL_BUILD_WITH_ACPC: OFF
OPEN_SPIEL_BUILD_WITH_EIGEN not set. Defaults to OFF
OPEN_SPIEL_BUILD_WITH_EIGEN: OFF
OPEN_SPIEL_BUILD_WITH_GO not set. Defaults to OFF
OPEN_SPIEL_BUILD_WITH_GO: OFF
OPEN_SPIEL_BUILD_WITH_HANABI not set. Defaults to OFF
OPEN_SPIEL_BUILD_WITH_HANABI: OFF
OPEN_SPIEL_BUILD_WITH_JULIA not set. Defaults to OFF
OPEN_SPIEL_BUILD_WITH_JULIA: OFF
OPEN_SPIEL_BUILD_WITH_LIBTORCH not set. Defaults to OFF
OPEN_SPIEL_BUILD_WITH_LIBTORCH: OFF
OPEN_SPIEL_BUILD_WITH_TENSORFLOW_CC not set. Defaults to OFF
OPEN_SPIEL_BUILD_WITH_TENSORFLOW_CC: OFF
OPEN_SPIEL_BUILD_WITH_PYTHON not set. Defaults to ON
OPEN_SPIEL_BUILD_WITH_PYTHON: ON
OPEN_SPIEL_BUILD_WITH_XINXIN not set. Defaults to OFF
OPEN_SPIEL_BUILD_WITH_XINXIN: OFF
OPEN_SPIEL_BUILD_WITH_ROSHAMBO not set. Defaults to OFF
OPEN_SPIEL_BUILD_WITH_ROSHAMBO: OFF
OPEN_SPIEL_BUILD_WITH_GAMUT not set. Defaults to OFF
OPEN_SPIEL_BUILD_WITH_GAMUT: OFF
OPEN_SPIEL_BUILD_WITH_ORTOOLS not set. Defaults to OFF
OPEN_SPIEL_BUILD_WITH_ORTOOLS: OFF
OPEN_SPIEL_ENABLE_JAX not set. Defaults to AUTO
OPEN_SPIEL_ENABLE_JAX: AUTO
OPEN_SPIEL_ENABLE_PYTORCH not set. Defaults to AUTO
OPEN_SPIEL_ENABLE_PYTORCH: AUTO
OPEN_SPIEL_ENABLE_TENSORFLOW not set. Defaults to AUTO
OPEN_SPIEL_ENABLE_TENSORFLOW: AUTO
OPEN_SPIEL_ENABLE_PYTHON_MISC not set. Defaults to OFF
OPEN_SPIEL_ENABLE_PYTHON_MISC: OFF
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found Python3: /home/vojta/open_spiel_test/env/bin/python3 (found version "3.8.5") found components: Interpreter Development
Python executable: /home/vojta/open_spiel_test/env/bin/python3
Python include dirs: /usr/include/python3.8
OPEN_SPIEL_ENABLE_JAX set to AUTO. Detecting Jax...
Not found. Enable printing errors in python/CMakeLists.txt to see output.
OPEN_SPIEL_ENABLE_PYTORCH set to AUTO. Detecting PyTorch...
Not found. Enable printing errors in python/CMakeLists.txt to see output.
OPEN_SPIEL_ENABLE_TENSORFLOW set to AUTO. Detecting Tensorflow...
Not found. Enable printing errors in python/CMakeLists.txt to see output.
-- Configuring done
-- Generating done
-- Build files have been written to: /home/vojta/open_spiel_test/open_spiel/build`

**Comment by lanctot** [comment]
No problem I can tske over and fix the rest, thanks!

**Comment by lanctot** [comment]
Many thanks @VojtaKovarik for reporting.

This should fix them all: https://github.com/deepmind/open_spiel/pull/611
