### ISSUE TITLE
Hanabi

### ISSUE THREAD

**Issue by griprox** [deepmind/open_spiel#61]
It would be great if we could use this repo with Hanabi. Probably adding some kind of wrapper would  be enough.

**Comment by lanctot** [comment]
Welcome @griprox . I'm glad you asked! :) It's in the [Call for Contributions](https://github.com/deepmind/open_spiel/blob/master/docs/contributing.md). We have an internal version and I just managed to get it working recently. 

Should be added in the next update actually, and it will close this issue when it's pushed.

**Comment by lanctot** [comment]
@griprox it's in now. it's an optional game so to enable it you need to follow instructions here: https://github.com/deepmind/open_spiel/blob/e39f9c2950f990c8c974e4bab4968c8ed6ef0638/open_spiel/games/hanabi.h#L28

If you run DQN and/or A2C can you post here or the reddit thread? I'm curious how well they do on Hanabi.
