### ISSUE TITLE
Restoring nfsp agent in leduc poker

### ISSUE THREAD

**Issue by zhotaios** [deepmind/open_spiel#626]
I hope this is the right place to ask questions: 

I trained the nfsp agents for leduc poker provided in the example files and for testing purposes I saved the agents at half of the total iterations as well. Now I wanted to restore both the half trained agents and the fully trained agents and test them against eachother to see how much they have improved in the last half of the iterations. However while restoring only the fully trained or only the half trained agents works fine, when I try to load the fully trained and its respective half trained agent I get an error: 

![Loading error](https://user-images.githubusercontent.com/60020481/121493777-7223cd80-c9d8-11eb-9a11-46d0b8c8888d.jpg)

I was wondering why that is? Because as I said, loading only the fully trained agents or the half trained agents works fine on its own. Should I also post my code of restoring the agents?

**Comment by finbarrtimbers** [comment]
If you post your code I'm happy to take a look. 

The answer is that in tensorflow, restoring works magically as long as you're restoring the exact same graph that you were originally checkpointing. However, once you start doing anything slightly different, you have to change how you do things to explicitly manipulate the graph. 

Specifically- now, your graph is different from the checkpoint. What you need to do is figure out what the networks are being mapped to in the restored version, as it's not the same as the original version. One way to do that is to print out all the variable names and inspect them manually (that's how I've done it in the past, I'm sure there's a smarter way). 

For instance, I had similar code that was doing a similar thing (restoring multiple copies of the same agent). In my case, the weights were being created in the original script looking like `linear_2/w:0` but the restored copies looked like `linear_2/w_1:0`, so to correctly map the original, checkpointed variables to the new ones, I had to do this:

```
  sync_ops = []
  for var in tf.global_variables():
    sync_ops.append(
        tf.assign(
            var,
            tf.get_default_graph().get_tensor_by_name(lambda var: var.name[:-2] + '_1:0')))
  session.run(sync_ops)
```

**Comment by lanctot** [comment]
Thanks @finbarrtimbers !

@zhotaios: does it make sense? Did this resolve your issue?
