### ISSUE TITLE
make freezes on Google Compute instance (Ubuntu 19.04) at 100%

### ISSUE THREAD

**Issue by witaly-iwanow** [deepmind/open_spiel#63]
So it just freezes forever at the final make step (install.sh, venv, etc. run without a glitch):
[ 97%] Built target matrix_games_test
[ 97%] Built target turn_based_simultaneous_game_test
[ 98%] Built target misere_test
[ 99%] Built target spiel_test
[100%] Building CXX object python/CMakeFiles/pyspiel.dir/pybind11/pyspiel.cc.o

**Comment by jblespiau** [comment]
Hi. Thank you for your report. Did you find how to fix this?

Reproducing it on our side would be very time consuming, so I assume it won't be fixed by us. However, if other people are confronted to it, this bug can be useful to gather several users having the same issue.

**Comment by lanctot** [comment]
@witaly-iwanow , any updates for us on this? Did it manage to work eventually?

**Comment by witaly-iwanow** [comment]
No, not really, I tried to clean up and restart the build process a few
times, but it just froze at the same point no matter what. I just built it
on my machine locally, and it went fine. I agree it's hard to repro, if
there are no more complaints, it can be closed eventually
