### ISSUE TITLE
I can't install openspiel

### ISSUE THREAD

**Issue by menglinjian** [deepmind/open_spiel#640]
when I was installing openspiel，some errors raise：
ERROR: Command errored out with exit status 1: /home/mlj/venv/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-wfyikrao/open-spiel_27b15f01be044bb49384b9b6a08727a8/setup.py'"'"'; __file__='"'"'/tmp/pip-install-wfyikrao/open-spiel_27b15f01be044bb49384b9b6a08727a8/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-wqmxrk1f/install-record.txt --single-version-externally-managed --compile --install-headers /home/mlj/venv/include/site/python3.8/open-spiel Check the logs for full command output.

**Comment by lanctot** [comment]
Are you installing via pip?

**Comment by lanctot** [comment]
Did you follow the instructions here? https://github.com/deepmind/open_spiel/blob/master/docs/install.md#python-only-installation-via-pip

If so can you please show the versions of cmake and clang++ by running the commands in the installation instructions and post them here?

**Comment by menglinjian** [comment]
> Did you follow the instructions here? https://github.com/deepmind/open_spiel/blob/master/docs/install.md#python-only-installation-via-pip
> 
> If so can you please show the versions of cmake and clang++ by running the commands in the installation instructions and post them here?

Yes，I follow the instruction. 
camke=3.12.2
clang++=10.0.0
ubuntu=18.04.2 
python=3.8.9

**Comment by lanctot** [comment]
You have the python dev files? Does `python3-config --help` run for you?

If so, maybe try outside of the virtual environment? i.e. try skipping these two lines:
```
virtualenv -p python3 venv
source venv/bin/activate
```

**Comment by menglinjian** [comment]
> You have the python dev files? Does `python3-config --help` run for you?
> 
> If so, maybe try outside of the virtual environment? i.e. try skipping these two lines:
> 
> ```
> virtualenv -p python3 venv
> source venv/bin/activate
> ```
> 
> Edit: you ran the install/upgrade to setuptools command, right?


Thank you, lanctot. I have solved this problem by updating clang7 to clang10 then following the instructions again.

**Comment by lanctot** [comment]
Great!
