### ISSUE TITLE
Gamut library

### ISSUE THREAD

**Issue by michalsustr** [deepmind/open_spiel#65]
I just came across Gamut library: http://gamut.stanford.edu/ 

I thought it might be an interesting addition for generating normal-form games and wanted to let you know about it, in case you didn't. It's written in Java, so maybe it would be possible to write a "bridge" for it? Maybe it can be added to the list of call for contributions?

**Comment by lanctot** [comment]
Yep I know about GAMUT. Interesting, I was not aware that is was still active/supported. Have you tried it? Last update was 2004.

I see that a jar file is provided and the user guide gives usage examples. I guess we could interact with it via JNI as in the Ludii wrapper (see https://github.com/deepmind/open_spiel/issues/39).

Feel free to add it to the Call for Contributions!

**Comment by lanctot** [comment]
Hi @michalsustr , do you plan to add this to the Call for Contributions? If not, I will close it.

**Comment by michalsustr** [comment]
Yes, I made the PR.

**Comment by lanctot** [comment]
We have added this now: https://github.com/deepmind/open_spiel/commit/e73a69ce76d70791ef42f493a4f1721750d13b7d

Disabled by default, requires changing `BUILD_WITH_GAMUT` in `scripts/global_variables.sh`.
