### ISSUE TITLE
 research_dqn_pytorch.ipynb  uses TensorFlow, not pytorch

### ISSUE THREAD

**Issue by balloch** [deepmind/open_spiel#653]
The title is pretty straightforward, was looking for a DQN example with PyTorch, and the notebook ` research_dqn_pytorch.ipynb ` in fact uses TensorFlow. i didn't see a file in `open_spiel/python/examples` either that met this criteria. do you have any suggestions? Or could this be modified to used pytorch?

**Comment by lanctot** [comment]
Thanks, we will fix that. Best place to start is https://github.com/deepmind/open_spiel/blob/master/open_spiel/python/pytorch/dqn_pytorch_test.py. @Asugawara, what do you think about adding a simple example to python/examples that shows it solving catch?

**Comment by Asugawara** [comment]
I think research_dqn_pytorch.ipynb uses Pytorch. dqn_pt defined on cell 1 and used on cell 4.
Is there something wrong??
ref:https://github.com/deepmind/open_spiel/blob/master/open_spiel/colabs/research_dqn_pytorch.ipynb

>what do you think about adding a simple example to python/examples that shows it solving catch?

It's a nice idea!
I think it would be good to make one based on　python/examples/subgle_agent_catch.py.

**Comment by lanctot** [comment]
Oops I did not actually check. @balloch can you help us understand? Thanks.

**Comment by balloch** [comment]
Ah, I see my mistake. It has Pytorch, but it also has Tensorflow (`tf_main`, I presume so that the person running the notebook can compare the results from the two frameworks?). I understand now. Thanks!
