### ISSUE TITLE
Tests are failing on my computer

### ISSUE THREAD

**Issue by TheoCabannes** [deepmind/open_spiel#657]
When I am running the OpenSpiel tests on my computer some are failing due to `RuntimeError: Tried to call pure virtual function "Game::new_initial_state"` and `AttributeError: 'pyspiel.State' object has no attribute '__dict__'`

Here are my logs: 
[logs.txt](https://github.com/deepmind/open_spiel/files/6765521/logs.txt)

When trying to debug the errors, I found that rolling back GitHub to https://github.com/deepmind/open_spiel/commit/2af781c5d364b64fcb7d6831faa423ee45d39a1a solve the issue.

I have a dependency error when rolling back to https://github.com/deepmind/open_spiel/commit/b0e4da6175aeee899448798600d8e1a8f3564f3d

I also have the tests failing (for the same reasons) when rolling back GitHub to https://github.com/deepmind/open_spiel/commit/373669f3ff177885899ac3c386b09523fda7bfcc

Here is the result of `conda list`:
[conda_list.txt](https://github.com/deepmind/open_spiel/files/6765563/conda_list.txt)

**Comment by TheoCabannes** [comment]
I run tests with `sh open_spiel/scripts/build_and_run_tests.sh`

**Comment by lanctot** [comment]
Yes you need to pull changes from pybind11. You are probably using the one you downloaded before and a recent commit require some new features. If you run `git pull` in the pybind11 top-level dir I think that should be enough.

**Comment by TheoCabannes** [comment]
Thank you so much. Can this be added to the install script?

**Comment by lanctot** [comment]
There is no changes to make in the install script, because it's checking out a fresh copy of pybind11. It's only happening to you because you're using a cached copy.

**Comment by TheoCabannes** [comment]
I see. My problem is solved now. Thanks! Is there a way to check the cached copy of pybind11 in build_and_run_tests script and update it if needed? (I do not know a lot of bash/shell scripts)

**Comment by TheoCabannes** [comment]
@lanctot can't this line be changed for example: https://github.com/deepmind/open_spiel/blob/9e4f6d219244dcd3deddf1ca75ab1113580bc73c/open_spiel/scripts/install.sh#L98

**Comment by lanctot** [comment]
Well, in this case it was that a checked out branch was just behind master, and we had a change that depended on new features. That's a very rare occurrence. We normally prefer _not_ to depend on the master branch, because it is always moving and can cause problems, so we fix them to release versions or specific checkouts. In the case of pybind11, we are working with that team and using advanced features (i.e. smart-holder). Maybe we should still fix the commit numbers and update as we go, though. I'll talk to @elkhrt.

**Comment by elkhrt** [comment]
Perhaps a simpler option is to use `git pull` to update the local copy to the latest version. This should be reasonably quick in the common case that not much has changed.
