### ISSUE TITLE
Running the game logic on GPU

### ISSUE THREAD

**Issue by StochasticEntropy** [deepmind/open_spiel#669]
Is there a way to run the game logic on GPUs? Currently the games all run on the CPU because of the C++ bindings as far as I know. This results in a lot of data movement from GPU memory to CPU memory and back for an algorithm that trains better on a GPU. 

I'm wondering if it would be possible to implement a game in such a way that all the data can be kept on the GPU. 

I'm thinking maybe JAX might be a good library to use for that, but I'm not sure if it's designed for these use cases where there would be a lot of control flows. 

Just mentioning @mattjj here, because you never know, he might know ...

If we wrote all the ifs as jax where clauses, could we even vmap it?
And would that be efficient for a GPU?

**Comment by michalsustr** [comment]
I'm afraid that won't be easy to do, is there something specific you have in mind, or just the ability to do state.apply_action() in parallel? (or something like that)

**Comment by michalsustr** [comment]
If you prebuild the game trees in advance, and then run algorithms on those trees on the GPU that can be done efficiently. For example, there is a GPU version of CFR that one student made but we didn't have time to integrate it into OpenSpiel. Would this be something of interest?

**Comment by StochasticEntropy** [comment]
The main problem is that I have to have my exproration steps running on the CPU due to the C++ implementation. Don't get me wrong, I'm grateful for the open spiel environment, I'm just wondering if it would make sense to implement some games on a GPU to scale them up. I understand that the notion is a bit weird, but given that our facebook and google friends were able to do it, maybe @mattjj and the jax team can do better ;)
