### ISSUE TITLE
coordinated_mp does not inherit from NormalForm* nor Matrix*

### ISSUE THREAD

**Issue by lanctot** [deepmind/open_spiel#671]
Unlike `matching_pennies_3p` and `blotto`, `coordinated_mp` does not inherit from NormalFormGame/State nor MatrixGame/State. @michalsustr, is there a reason for this? It might be good to change them to make them consistent with the rest (there are some free helpful functions that get inherited).

**Comment by michalsustr** [comment]
>  Is there a reason for this?

Yes, while the game is quite simple, it cannot be represented with just NormalFormGame/State nor MatrixGame/State, as after action of the first player there is a stochastic public outcome (top/bottom) for the two infostates of the second player. Did this come up as an issue in some code refactor?

**Comment by lanctot** [comment]
Ahh, makes sense! Yes please take a look at the commit I linked on the C++ DQN PR.
