### ISSUE TITLE
is the efficiency of CFR tied to the efficiency of state.child()?

### ISSUE THREAD

**Issue by VitamintK** [deepmind/open_spiel#672]
From [the comments introducing Python games](https://github.com/deepmind/open_spiel/blob/ead53908dd109180ce68e8240e8ae157927c7ddf/open_spiel/python/games/kuhn_poker.py):
> Python games are significantly slower than C++, but it may still be suitable
for prototyping or for small games.
> 
> It is possible to run C++ algorithms on Python implemented games, This is likely
to have good performance if the algorithm simply extracts a game tree and then
works with that (e.g. CFR algorithms). It is likely to be poor if the algorithm
relies on processing and updating states as it goes, e.g. MCTS.

My interpretation of this is that if CFR extracts a game tree and works with that, then any slowness in `state.apply_action()` or `state.clone()` won't matter at all once we're done extracting the game tree, which makes sense and sounds great!

My question is: do the openspiel implementations of CFR actually "simply extract a game tree and then
work with that"?  From skimming the source of `open_spiel/algorithms/cfr.cc`, it looks like each call to `EvaluateAndUpdatePolicy()` traverses the game tree with the recursive `ComputeCounterFactualRegretForActionProbs()`, which looks like it calls `state.Child(action)`.  So each call to `EvaluateAndUpdatePolicy()` calls `state.Child(action)` for each (state, action) pair in the game.

Is the comment wrong, did I misinterpret the comment, or did I misunderstand the CFR code?

**Comment by VitamintK** [comment]
tagging @elkhrt because I think you wrote the comment

**Comment by lanctot** [comment]
> My interpretation of this is that if CFR extracts a game tree and works with that, then any slowness in `state.apply_action()` or `state.clone()` won't matter at all once we're done extracting the game tree, which makes sense and sounds great!
> My question is: do the openspiel implementations of CFR actually "simply extract a game tree and then
> work with that"? 

No, our CFR implementations don't do this. They walk the game tree procedurally on every iteration via states, applying actions, getting the next children states, and looking up information states from the keys from those states.

I know @michalsustr talked about making a CFR based on `algorithms/info_state_trees`, but I can't seem to find it now -- maybe it was never submitted?

**Comment by VitamintK** [comment]
Gotcha, thanks for the answer!  Should I close this now, or leave it open to track the comment update?

**Comment by michalsustr** [comment]
> I know @michalsustr talked about making a CFR of the form you're describing.. based on algorithms/infostate_trees, but I can't seem to find it now -- maybe it was never submitted?

Yes, I have a version that prebuilds the infostate trees, computes full gradients on the sequence form and propagates it through the individual trees. It's a bit of code, I didn't get to publishing it yet, but maybe now I can in the coming weeks.

**Comment by lanctot** [comment]
Cool, thanks guys. Yes @VitamintK, leave it open as a reminder to update the comment, thanks!
