### ISSUE TITLE
phantom tic-tac-toe: InformationStateString gives num attempted turns even when obstype is `reveal-nothing`

### ISSUE THREAD

**Issue by VitamintK** [deepmind/open_spiel#676]
Is this correct?  Phantom Tic-Tac-Toe's `InformationStateString` gives `absl::StrAppend(&str, history_.size(), "\n");` even when obstype is `reveal-nothing` instead of `reveal-numturns`.

**Comment by lanctot** [comment]
That is indeed a bug! Good find, thanks. I will fix it this week.

**Comment by lanctot** [comment]
Actually could you submit a PR? It'd be good for you to get the credit for it.

**Comment by lanctot** [comment]
> Actually could you submit a PR? It'd be good for you to get the credit for it.

Forgot I wrote that and fixed it today, so please disregard :)
