### ISSUE TITLE
Converting from observations to string representations

### ISSUE THREAD

**Issue by uduse** [deepmind/open_spiel#678]
It would be helpful if some games implement `ObservationToString`, a function that pretty prints an observation tensor.

Here are two scenarios:
 - The user has no direct control over the environment interaction process (e.g., using libraries like Acme that wraps open_spiel) and only sees observations as inputs.
 - The observations are stored somewhere (e.g., in a replay buffer) while the full game states are not stored.

In both cases, it would be helpful for the user to visualize what's going on by printing observation tensors.

**Comment by elkhrt** [comment]
Yes, this would be great. We could perhaps then change the existing ObservationString implementations to use this functionality, to reduce duplication. What games do you have in mind?

**Comment by uduse** [comment]
> Yes, this would be great. We could perhaps then change the existing ObservationString implementations to use this functionality, to reduce duplication. What games do you have in mind?

Right now I'm only using `Catch` for prototyping my project.
