### ISSUE TITLE
TARGET_OBJECTS:human_bot not found

### ISSUE THREAD

**Issue by michalsustr** [deepmind/open_spiel#682]
The [alpha_zero_torch_game_example](https://github.com/deepmind/open_spiel/blob/master/open_spiel/examples/CMakeLists.txt#L54) uses `TARGET_OBJECTS:human_bot`, but this target does not exist. This shows up if `OPEN_SPIEL_BUILD_WITH_LIBTORCH` is enabled.

**Comment by lanctot** [comment]
Whoops, I removed that in the UCIBot PR. You can replace it with `TARGET_OBJECTS:bots`. I'll fix it, thanks!
