### ISSUE TITLE
Saving trained tabular qlearner

### ISSUE THREAD

**Issue by EmmaUnimelb** [deepmind/open_spiel#685]
Is there a method implemented in openSpiel for saving a trained tabular qlearner and restoring it for later use? The existence of a lambda seems to stop it from pickling at the moment

**Comment by EmmaUnimelb** [comment]
Yes, I believe that's the one.

The error is:
AttributeError: Can't pickle local object 'QLearner.__init__.<locals>.<lambda>'

**Comment by EmmaUnimelb** [comment]
I tried your suggestion and it worked - thanks

**Comment by lanctot** [comment]
Great! Would you like to submit a fix?

**Comment by EmmaUnimelb** [comment]
Sure.
I have sent a pull request. Github is having a little trouble showing me the CLA for the right email though

**Comment by lanctot** [comment]
> Sure.
> I have sent a pull request. Github is having a little trouble showing me the CLA for the right email though

Ah yes I think you probably have to logout of your current account or access github while signed into your account associated with your github account.

**Comment by lanctot** [comment]
Solved by https://github.com/deepmind/open_spiel/pull/690, thanks!
