### ISSUE TITLE
bridge and double dummy solver

### ISSUE THREAD

**Issue by rysios** [deepmind/open_spiel#686]
DDS colors are spades = 0,hearts = 1,diamonds = 2, clubs =3
bridge.h :
enum Denomination { kClubs = 0, kDiamonds, kHearts, kSpades, kNoTrump };

It's nothing wrong with it, until you try to calculate par result

**Comment by lanctot** [comment]
@elkhrt can you take a look?

**Comment by elkhrt** [comment]
This is intriguing! Are you attempting to use the par score as a baseline of some sort?

Feel free to add a mapping from open spiel suits to DDS suits if that would be helpful for you.
I think you'd need to change the line that populates the deal here:

https://github.com/deepmind/open_spiel/blob/ba9220ecd0225ba558f79853b0c3a877bcd7ce10/open_spiel/games/bridge.cc#L458

Plus every access of the values in `double_dummy_results_` (probably simplest to introduce a helper member function to do this access).

**Comment by rysios** [comment]
Thanks for answer. 
Yes I'm trying to use (real score - par score) as reward in RL.
You are wright, mentioned line should be:  
 dd_table_deal.cards[player][3 - suit] += 1 << (2 + rank); 
and every occurrence of 
double_dummy_results_->resTable[trumps]
should be replaced with
double_dummy_results_->resTable[trumps == 4 ? trumps : 3 - trumps]

**Comment by elkhrt** [comment]
If you'd like to submit a PR, that would be great.
I'd recommend you create a member function for the second change, rather than have `trumps == 4 ? trumps : 3 - trumps` repeated multiple times.

**Comment by lanctot** [comment]
Closing now as this is out-of-date. @rysios, please re-open if you want to continue discussion, but a PR would be welcome!
