### ISSUE TITLE
Questions about different CFR variants

### ISSUE THREAD

**Issue by ai-gamer** [deepmind/open_spiel#69]
Thanks a lot for open sourcing the repository. It's quite helpful.

I see there are many variants of CFR algorithm implemented. I would like to ask if there are someone already working on the VR-MCCFR and if the discounted regret minimisation algorithm also on the list to be done.

If I want to try this two tasks, are there some suggestions to make the code more suitable for the repository?

**Comment by michalsustr** [comment]
I have an implementation similar to VR-MCCFR, with baseline over individual histories (not public states) that I'm porting over to open spiel. I'm just currently distracted with other university duties, but I'd expect to have it done in a few weeks. Adding public state baseline shouldn't be too difficult in a domain-specific way.

**Comment by lanctot** [comment]
I got two requests for VR-MCCFR in two days ;-) The baselines are in the [Call for Contributions](https://github.com/deepmind/open_spiel/blob/master/docs/contributing.md) but also discounted CFR would be great.

I plan to also submit an implementation of outcome sampling (in C++) in the next few weeks, so I will keep my mind on including support for the baselines as well if we don't already have it by then (mine also would only be history / infostate baselines)

**Comment by ai-gamer** [comment]
Good to know.
