### ISSUE TITLE
Pytorch Deep CFR example uses wrong value for Policy Network layers

### ISSUE THREAD

**Issue by newmanne** [deepmind/open_spiel#694]
The policy network seems to be created using the advantage network parameters and the policy network layer parameters appear to be unused. 

https://github.com/deepmind/open_spiel/blob/1506d1c7b14c0f7dfcc091c41824c5a0dbe1971e/open_spiel/python/pytorch/deep_cfr.py#L269

**Comment by lanctot** [comment]
Good catch, thanks! I've fixed it, will get merged in next update (Monday).
