### ISSUE TITLE
rbc repetition draws?

### ISSUE THREAD

**Issue by VitamintK** [deepmind/open_spiel#695]
The rules for recon blind chess [here](https://reconchess.readthedocs.io/en/latest/rules.html) state that "all rules associated with stalemates or automatic draw conditions are eliminated."

The OpenSpiel implementation doesn't currently match:

```
>>> game = pyspiel.load_game('rbc')
>>> game.new_initial_state().child(0).child(0).child(0).child(0).child(0).child(0).child(0).child(0).is_terminal()
True
```

Should this be changed, or does the implementation intentionally differ?

**Comment by lanctot** [comment]
Hi @michalsustr, can you take a look?

**Comment by michalsustr** [comment]
Ah, I was basing the implementation on [these rules](https://rbc.jhuapl.edu/gameRules) which are slightly different. I will take a closer look at the differences. Regarding the automatic draw specifically, I think it's preferrable to make sure the game is finite and terminates after some number of (possibly nonsensical) moves.

**Comment by VitamintK** [comment]
> Regarding the automatic draw specifically, I think it's preferrable to make sure the game is finite and terminates after some number of (possibly nonsensical) moves.

That sounds reasonable to me -- would it be worth it to add the automatic draw thresholds as parameters to the game?

Also-- unrelated, but I just noticed: the rbc rules from jhuapl also say that "If a player captures a piece, she is informed that she made a capture (but she is not informed about what she captured)" but from skimming the observation tensor and observation string code in open_spiel, I couldn't find this in there.  Is this missing?

**Comment by VitamintK** [comment]
Ah, now I see that captures are in `WritePublicInfoTensor`, so they are in the observation tensors at least.

I do have some other questions though: 
1. isn't `state.move_captured_` always true?  It's set by `move_captured_ = Board().at(move.from).color != Board().at(move.to).color`, and since the color of the destination square is either the opponent or empty, it will always be unequal to the piece's color, no?  If true, this could be fixed by using `OppColor` instead of `!=`
2. `illegal_move_attempted_` is in the public info tensor, but it doesn't seem like it should be common knowledge if my opponent attempted an illegal move (if things like failed pawn captures or forward moves are considered illegal moves)

**Comment by michalsustr** [comment]
>  Would it be worth it to add the automatic draw thresholds as parameters to the game?

Right now the draws are controlled via `kNumRepetitionsToDraw` constant, when the board hashvalue occurs more than 3 (kNumRepetitionsToDraw) times. https://github.com/deepmind/open_spiel/blob/master/open_spiel/games/rbc.cc#L419
I think this is a reasonable default, but if you have a particular use-case in mind when you'd need to change that feel free to make a PR, I can make a review for it. 

Thanks for pointing out these issues!

**Comment by lanctot** [comment]
I believe this was fixed by https://github.com/deepmind/open_spiel/pull/704. If there are any outstanding problems on this issue, please re-open.
