### ISSUE TITLE
higc referee_test fails: No module named 'numpy'

### ISSUE THREAD

**Issue by VitamintK** [deepmind/open_spiel#715]
When attempting to install latest master open_spiel, I ran into the following failed test:
```
Starting players.
Bot#0: /Users/kevin/github/open_spiel_fork/open_spiel/higc/bots/random_bot_py.sh
Bot#1: /Users/kevin/github/open_spiel_fork/open_spiel/higc/bots/test_bot_start.sh
Bot#0: Traceback (most recent call last):
  File "/Users/kevin/github/open_spiel_fork/open_spiel/higc/bots/random_bot.py", line 19, in <module>
    import numpy as np
ModuleNotFoundError: No module named 'numpy'
Bot#0 did not respond 'ready'
Bot#0 response was: ''
Bot#0 also timed out.
Bot#1 ready ok.
Could not start all players correctly, cannot play the tournament.
Spiel Fatal Error: /Users/kevin/github/open_spiel_fork/open_spiel/higc/referee_test.cc:131 results->num_matches() == 1
results->num_matches() = 0, 1 = 1
```

I followed the steps
> ./install.sh
> pip3 install -r requirements.txt
> ./open_spiel/scripts/build_and_run_tests.sh

I have numpy installed on the `python` I'm using, as well as my system's python, so I'm not sure why this is happening.

I can disable the test to move forward, but I'm filing this issue here in case anyone else experiences this or knows how to fix it.

cc: @michalsustr

**Comment by lanctot** [comment]
Another quick update: this is now causing the Hithub Actions wheels test to fail on MacOS X, so I'm disabling the higc_referee_test until we fix it, see https://github.com/deepmind/open_spiel/pull/719 for details.

I think we should fix this ASAP. @michalsustr, have you been able to reproduce it from a fresh checkout of master?

@VitamintK can you let me know what your environment is? It only started showing up for me after upgrading my Ubuntu to 21.10 and only on the wheels test yesterday (e.g. they were working fine last week).

**Comment by VitamintK** [comment]
I'm using Mac OS with a conda (not venv) environment.

`import numpy` works both with the conda environment's `python` and `/usr/bin/python`.

**Comment by VitamintK** [comment]
ah, but the tests were running with `open_spiel/venv/bin/python`, which I wasn't using, and which doesn't have `numpy`.  (Found the python directory by putting `print(os.path.dirname(sys.executable), file=sys.stderr)` in `random_bot.py`.)

When I run installation with `--virtualenv=false`, the issue seems to be fixed.

**Comment by lanctot** [comment]
> When I run `./open_spiel/scripts/build_and_run_tests.sh` with `--virtualenv=false`, the issue seems to be fixed.

Ok, so, yes same with me. 

With a fresh checkout from the latest master, when I re-enable both HIGC tests (in `higc/CMakeLists.txt` and `python/CMakeLists.txt`):

- When I run the build and test script with no arguments, both `referee_text` and `python/higc_referee_test.py` fail. Log here: https://pastebin.com/FnxkibtT
- When I run with `--virtualenv=false` all the tests pass.

**Comment by VitamintK** [comment]
> The CI failures vary, but AFAICT they are not related to timeouts.
> Here's one. https://github.com/deepmind/open_spiel/runs/3919551061?check_suite_focus=true

You're right, that one indeed looks unrelated to timeouts:

```
Bot#0:   File "/Users/runner/work/open_spiel/open_spiel/open_spiel/python/tests/../bots/higc_random_bot_test.py", line 60
    public_buf, private_buf, *legal_actions = message.split(" ")
                                             ^
SyntaxError: invalid syntax
```

It looks like that operator ([extended iterable unpacking](Extended Iterable Unpacking)) was introduced in python 3.0, so this must mean the python interpreter being used is python 2.x -- probably mac OS's system python.

**Comment by michalsustr** [comment]
I will take a look now as well. The tests assumed the default installation of virtualenv, because the python files needed both numpy and pyspiel.

**Comment by lanctot** [comment]
Unfortunately they seemed to get deleted.. they definitely happened, though. The logs were similar to the one I linked above here: https://github.com/deepmind/open_spiel/issues/715#issuecomment-946063027

Didn't you say that you could reproduce the problem locally?

**Comment by lanctot** [comment]
Yes that looks like one of them! I feel like there might have been another too but I am not 100% sure :) either way, good find, thanks!
