### ISSUE TITLE
Limiting number of actions in the domains

### ISSUE THREAD

**Issue by michalsustr** [deepmind/open_spiel#73]
As pointed out in #51 domains can factorize their actions if there's too many of them per node. 

Would you like to impose a limit on that, for example having at most 256 actions per node? The reason why this would practically useful is because pretty much all the algorithms work with some notion of saving a value per action.

**Comment by jblespiau** [comment]
I do not think preventing games to do that would be beneficial. However, if for some specific work or algorithm, we need to factorize the actions, then it's a good thing to make sure this can be done.

This could be done using an argument to the game, or maybe using a wrapper is there is a good way of doing it. Adding the functions `long LegalActionsCount` and `LegalActionAt(long index)` you suggested can also be doable.

If you have a specific need, and found a good way of implementing it for your research/experiments/work, feel free to share it and this can also be included in OpenSpiel.
