### ISSUE TITLE
Sampling of actor in NeuRD

### ISSUE THREAD

**Issue by chiraguic** [deepmind/open_spiel#737]
Hi, I am interested in implementing NeuRD in my actor-critic RL model. I think the version in the NeuRD paper samples actions only for the critic and not for the actor and so I wanted to know how can I implement it for the sampled version? Can I just include 1/pi in the update like you have explained before the equation (5) of the paper?

**Comment by lanctot** [comment]
Hi @chiraguic !

See the discussions of it here: https://github.com/deepmind/open_spiel/issues/148 and here: https://github.com/deepmind/open_spiel/issues/316, where one of the original authors posted the code for the thresholding and the policy gradient loss. You should be able to adapt it from that and the policy gradient code. 

We've had a number of requests for an implementation of sample-based NeuRD. It'd be great if you would contribute it if you get it working.  :)

**Comment by lanctot** [comment]
@chiraguic , just checking if you have an update on this? If not, I'm inclined to close the issue. Let me know what you think.
