### ISSUE TITLE
How can I solve this on pycharm of Windows: We recommend: Clang version >= 7.0.0. 

### ISSUE THREAD

**Issue by lmh-leo** [deepmind/open_spiel#744]
After pip install open_spiel ,there is an error:
`RuntimeError: A C++ compiler that supports c++17 must be installed to build the following extensions: pyspiel. We recommend: Clang version >= 7.0.0.`
thanks.

**Comment by lmh-leo** [comment]
But there is a python library clang which version is 11.0;

**Comment by xj886** [comment]
Hello, I also encountered this problem, how did you solve it?
