### ISSUE TITLE
[FR] Parametrize Tic-Tac-Toe to accept an arbitrary sized board and win patterns

### ISSUE THREAD

**Issue by NightMachinary** [deepmind/open_spiel#749]
E.g., we might want a 10x10 board with the win conditions being 

```
X
X
X
XXX
```

(up to any number of 90 degree rotations.).

PS: If you’re too busy, would a PR of this feature be accepted?

**Comment by lanctot** [comment]
I don't see why we wouldn't accept a PR implementation. I would recommend leaving Tic-Tac-Toe implemented as is and make a new game. 

I'm curious, though: is it because you'd use this game for a research project?

**Comment by NightMachinary** [comment]
I am learning RL, so I am not doing research yet; but I like Tic-Tac-Toe's simplicity. It's easier for me to analyze the game, rather than, say, chess. But the classic version is too useless.

I also really like big Tic-Tac-Toe games ;)

**Comment by lanctot** [comment]
You might also be interested in Ultimate Tic-Tac-Toe. I saw a recent applicate of AlphaZero to it: https://www.reddit.com/r/MachineLearning/comments/rdb1uw/p_utttai_alphazerolike_solution_for_playing/?utm_medium=android_app&utm_source=share

I have always liked this game, would be great to have it in OpenSpiel.

**Comment by lanctot** [comment]
Hi @NightMachinary, we have now added an implementation of Ultimate Tic-Tac-Toe: https://github.com/deepmind/open_spiel/commit/fa7b6af395a0d80ac62513d4edfeb4f9a0092957

**Comment by NightMachinary** [comment]
Thanks, that game is also interesting!
