### ISSUE TITLE
Best way to parallelize env rollout

### ISSUE THREAD

**Issue by MachengShen** [deepmind/open_spiel#756]
I'm wondering what would be the best way to parallelize the env steps? For gym envs, we have the SubProcessEnv wrapper, is there anything equivalent in open_spiel? I would like to avoid passing policy networks to subprocess. Please instruct, thanks!

**Comment by lanctot** [comment]
By paralellize do you mostly mean batching? As in are you looking for a way to execute say n steps on n independent environments in one step?

We don't have anything like that currently, but it would be a nice addition, so we would welcome a PR that adds this (a batched environment).

I am not sure what you mean by passing policy nets to the subprocess. Can you elaborate? I am not familiar with SubProcessEnv from gym.. the thing I have in mind would just be a batched environment.. the agents would still be responsible for choosing submitting actions.

**Comment by MachengShen** [comment]
Yes, i mean batched environment. Can you suggest an implementation for the python version without changing the cpp code? I appreciate it.

**Comment by lanctot** [comment]
Hmm, not sure what to recommend without knowing more about your use case, other than the basic one of having an object with multiple environments, that sequentially applies step to all of them and returns a batch of observations.

But I can see this a fast/performant one done on the C++ side ​(i.e. where the cost of going from Python to C++ and back is paid only once per step) being generally useful for scalability and I would be happy to start/sketch one that we can then build into a batched RL env.
