### ISSUE TITLE
how to exchange the private cards in leduc poker?

### ISSUE THREAD

**Issue by Jzhou0** [deepmind/open_spiel#757]
Hi @lanctot , there's a little question. I'm wondering how to exchange the private cards in leduc poker?  I want to use duplicate tables to remove some of the randomness of the cards.  However  the definition of the class _state_  is  unclear, where the _state_  show as follows:
`game = pyspiel.load_game("leduc_poker")
state=game.new_initial_state()
`
when exchange the private cards, I could not assignment a collection  hand of saved  cards to  the corresponding  variable in _state_.
Please instruct, thanks!

**Comment by lanctot** [comment]
Hi @Jzhou0,

The state is a Python-wrapped C++ object described in `spiel.h`. In the case of leduc poker, it is a LeducState object defined in games/leduc_poker.h. The python API for these classes and objects are in `python/pybind11`.

There are two potential solutions: (i) add a method to LeducState to modify the cards and expose it to Python, (ii) write a Python function that builds a new state from scratch, by looking at `state.history()` of the old state, and changes the outcomes at each chance node.

I recommend (i), but it involves changing and writing some C++. It's quite a simple one so I'd be happy to write a version of it for you if you describe precisely what function you'd need.

**Comment by Jzhou0** [comment]
I  am trying  to  follow (i).  Coincidentally, I find a  more simple  solution in `python/example/example.py`,  I could use the method ` game.deserialize_state(state_string)` to  construction a special state with saved `state_string` , and the whole process is easy:
`flags.DEFINE_string("load_state", None, "A file containing a string to load a specific state")`
`with open(FLAGS.load_state, encoding="utf-8") as input_file:`
     `for line in input_file:`
           `state_string += line`
`state_string = state_string.rstrip()`
`state = game.deserialize_state(state_string)`

But there is another  problem,  that is what the loading state file should be?
I load a file like this :
```
Round: 1
Player: -1
Pot: 2
Money (p1 p2 ...): 99 99
Cards (public p1 p2 ...): -10000 -10000 -10000
Round 1 sequence:
Round 2 sequence:
```
an error occurs :
```
state = game.deserialize_state(state_string)
ValueError: stol
```
Any feedback/insight would be much appreciated!

**Comment by lanctot** [comment]
Ah yes but there is no need to read or writing to a file, and that's not what the serialized state looks like. You can see what a serialized state looks like by printing `state.serialize()`. This solution would be similar to my history-based one. Probably best to do it the right way.

Take a look at python/pybind11/games_backgammon.cc and the associated methods in games/backgammon.h. You can see how these are used in python/games_sim_test.py. The best solution would be to create the methods you need for Leduc and expose them to python (similar to the backgammon example). As I said, I am happy to help you with this if you tell me what you want to do with the state. Is it e.g. just something to replace the private cards?

**Comment by Jzhou0** [comment]
Yeah, only replace the private cards.  
For example,  in the first game of Leduc poker,  cards for p1 and p2 are Ks and Qs respectively. And  I want to set p1's and p2's private card to Qs and Ks respectively in the second game.  But is there any method implementation for this assigning operator in Python? 
I could try to write a function in C++,  but I wonder how to expose them to python?

**Comment by lanctot** [comment]
To add the methods on the C++ side, modify LeducState in games/leduc_poker.h and games/leduc_poker.cc. 

To expose them to python, see the second paragraph of my previous response. (We will add documentation for this soon.)

**Comment by lanctot** [comment]
Hi @Jzhou0, I have this implemented and tested internally now. We will use it as an example for documentation on how to provide games-specific functionality and expose it to python.

The code has to go through a short review and will be available on the next sync to github, which might be tomorrow or the next day (this thread will be updated when the code is in master).

**Comment by lanctot** [comment]
We have now added documentation on this at the bottom of [the developer guide page](https://github.com/deepmind/open_spiel/blob/master/docs/developer_guide.md).
