### ISSUE TITLE
Building with BUILD_WITH_XINXIN="ON" is broken (missing hearts/Algorithm.cpp)

### ISSUE THREAD

**Issue by jeremysalwen** [deepmind/open_spiel#769]
Attempted to build with XINXIN support (export BUILD_WITH_XINXIN="ON").  Cmake fails, it appears there are some missing files that are not checked into the git?

```
-- Configuring done
CMake Error at games/hearts/CMakeLists.txt:1 (add_library):
  Cannot find source file:

    hearts/Algorithm.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
  .hpp .hxx .in .txx


CMake Error at games/hearts/CMakeLists.txt:1 (add_library):
  No SOURCES given to target: xinxin


CMake Generate step failed.  Build files cannot be regenerated correctly.
```

`find . -name Algorithm.cpp` finds nothing.

**Comment by lanctot** [comment]
Hi @jeremysalwen,

You also need to have the variable set when you run `./install.sh` which will clone the xinxin repo, which is what you are missing. 

You can check out scripts/install.sh for the git clone command.

**Comment by jeremysalwen** [comment]
Thanks @lanctot, that solves it. Might I suggest updating https://github.com/deepmind/open_spiel/blob/master/docs/install.md to note that you need to set the configuration variables before install.sh?

**Comment by lanctot** [comment]
Actually, great idea. Can you submit a PR to fix the docs?
