### ISSUE TITLE
Large memory usage even after abstraction

### ISSUE THREAD

**Issue by Henry-E** [deepmind/open_spiel#775]
Following along with the suggestions on card abstraction [here](https://github.com/deepmind/open_spiel/issues/243), I removed suits from the ACPC poker implementation.

This greatly reduced the number of information sets needed for the toy game I was training. However, despite there only being ~2,000 information sets, when I run `cfr.CFRSolver(custom_universal_poker_game)` the solver object still takes up 12GB ram!?! I'm at a loss for how to debug this or to reduce the memory usage as I had thought reducing the number of information sets was the way to go for reducing memory usage.

EDIT: My current best guess at a solution is to update `ChanceOutcomes` and `LegalActions` in such a way that they will also reflect the suit-less card abstraction.

**Comment by lanctot** [comment]
Hi @Henry-E, can you first clarify whether you're using the Python CFR impl or the C++ CFR impl?

**Comment by lanctot** [comment]
How did you get the 2k information set count? Did you double-check that this is the size of the CFR table, not from some analysis on the resulting game? E.g. can you confirm that CFR's table is size 2000?

Can you compute the average branching factor.. e.g. for all info states, sum |LegalActions(s)| and divide by number of info state.

**Comment by Henry-E** [comment]
```
Hi @Henry-E, can you first clarify whether you're using the Python CFR impl or the C++ CFR impl?
```

Ah, this is a good point. It's the Python CFR implementation. I didn't realise the example Universal Poker colab was using the python cfr algorithm. Switching over to the C++ implementation of CFR on pyspiel drops the RAM usage to 1.5GB. Great improvement!

```
How did you get the 2k information set count? Did you double-check that this is the size of the CFR table, not from some analysis on the resulting game? E.g. can you confirm that CFR's table is size 2000?
```

It was from counting up the entries in the private variable `._info_state_nodes`
`cfr_trained._info_state_nodes` -> 2,280
For comparison here's the count of all the states
`get_all_states.get_all_states(this_game)` -> 8,725,180 states

```
Can you compute the average branching factor.. e.g. for all info states, sum |LegalActions(s)| and divide by number of info state.
```
I'll give it a shot. The c++ variables are bit harder to interact in python with but I'm sure there's some examples of it in the python examples folder.

Thanks for the help!

**Comment by lanctot** [comment]
Great!

I think we might have a tool that does it already: https://github.com/deepmind/open_spiel/blob/master/open_spiel/examples/count_all_states.cc

(Or if it doesn't, we should modify it so that it does.. should be fairly easy)

**Comment by Henry-E** [comment]
Thanks for the link, it gives the same numbers as above

```
Game: universal_poker(betting=limit,numPlayers=2,numRounds=2,blind=5 10,raiseSize=10 10 20,maxRaises=2 2 3,firstPlayer=2 1,numSuits=4,numRanks=5,numHoleCards=1,numBoardCards=0 2 1), 
num_histories: 8761301, 
num_terminal_histories: 5234500, 
num_chance_nodes: 36121, 
num_nonterminal_states: 2280, 
num_terminal_states: 28250
```
`8761301 histories - 36121 chance = 8,725,180 states` as above
It still gets up to 25GB of RAM though while counting all the states.

I think I'm going to experiment tomorrow with having the functions `ChanceOutcomes` and `LegalActions` output values that are consistent with the card abstraction. That should reduce the number of histories to something more in line with the information states. 

Being able to do the CFR with 1.5GB RAM is definitely better, though I imagine that's still quite a large amount of memory for only 2,280 info states?

**Comment by lanctot** [comment]
I agree it is still large for that number of info state, but what I want to know is the average branching factor. CFR's memory requirements are linear in number of infostate time actions, so I am curious how many legsl actions the game has on average. You can get this by summing the size of the legal actions over all the states and then dividing by number of states (a small change to the example I pointed you to above.)

I have a sudpicion as to the potential cause but I want to know the average branching factor before I say more.

**Comment by Henry-E** [comment]
Ah ok, sorry I missed that. 

Not super familiar with C++ but I tried this 

```
      case StateType::kDecision:
        if (game->GetType().information ==
            GameType::Information::kPerfectInformation)
        {
          nonterminal_states.insert(state->ToString());
          int legal_actions = state->LegalActions().size();
          num_legal_actions += legal_actions;
        }
        else
        {
          nonterminal_states.insert(state->InformationStateString());
          int legal_actions = state->LegalActions().size();
          num_legal_actions += legal_actions;
        }
  ```
  It gets the size of the legal actions array at every non terminal node. This is what you were looking for I think?
  
  ```
  num_histories: 8761301, 
  num_terminal_histories: 5234500, 
  num_chance_nodes: 36121, 
  num_nonterminal_states: 2280, 
  num_terminal_states: 28250, 
  num_legal_actions: 8145300
  ```
  So `8145300/2280=3572.5`

**Comment by lanctot** [comment]
Ok perfect, but you should be dividing by the number of histories because the loops is over histories, so you have: `8145300/5234500 = 1.556`. That's quite low, so I'm guessing you're using limited betting... ah! I just noticed now that you're doing limit, so this makes perfect sense.

Ok this is progress. I just noticed this example does not include the information states, but I think we can trust the one from the python side. So that's 2280 * 1.5 = ~O(3550) values and keys that you need to store... 1.5GB still seems like a fair bit for that.

Here are some potential causes:

-  It you are running a best response computation anywhere in the code, you might be using one that requires memory linear in the number of histories. If so, this is almost surely the problem. Can you verify? Are you running a best response at any point? If so, which one?

-  I just noticed recently that the map we chose for our CFR implementations was `std::unordered_map`. This was because we were not using abseil at that time, but now we are. I think this data structure be me less memory-inefficient than e.g. `absl::flat_hash_map`. We should make that change. Off the top of my head I'm not sure how much better it could be, but it's an easy change to make.

I'm happy to help figure this out. 2280 info states really should not take up 1.5GB of RAM.

**Comment by Henry-E** [comment]
Checking out the problem this morning it looks like I was wrong that it's taking up 1.5GB. Because it's a remote server I had assumed RAM usage outside of openspiel was negligible but I forgot that VS code is a RAM hog and it's actually taking up most of the 1.5GB. Looking closely at htop, the kernel of the jupyter notebook appears to be more like 100mb.

```
If you are running a best response computation anywhere in the code, you might be using one that requires memory linear in the number of histories. If so, this is almost surely the problem. Can you verify? Are you running a best response at any point? If so, which one?
```
I did try a few of these and they definitely blow out the memory when the history size is super large, up to like 25GB for the `count_all_states` scripts.

```
I just noticed recently that the map we chose for our CFR implementations was std::unordered_map. This was because we were not using abseil at that time, but now we are. I think this data structure be me less memory-inefficient than e.g. absl::flat_hash_map. 
```
Just for the sake of it I tried adding this anyway. It's hard to judge without proper testing but it didn't seem to make a noticeable difference.

Separately I also updated `LegalActions` to be in line with the information state abstraction. This made a huge difference to speed and the number of histories.

```
Game: universal_poker(betting=limit,numPlayers=2,numRounds=2,blind=5 10,raiseSize=10 10 20,maxRaises=2 2 3,firstPlayer=2 1,numSuits=4,numRanks=5,numHoleCards=1,numBoardCards=0 2 1), 
num_histories: 47906, 
num_terminal_histories: 28250, 
num_chance_nodes: 756, 
num_nonterminal_states: 2280, 
num_terminal_states: 28250, 
num_legal_actions: 44125
```
8,761,301 down to 47,906 histories.

One comment about the average policy object returned by CFR solver object in python, it's not iterable so it's quite to get the number of information states without having to traverse the entire history. 

Thanks again for the help!
