### ISSUE TITLE
Implementation of discounted cfr and linear cfr

### ISSUE THREAD

**Issue by ai-gamer** [deepmind/open_spiel#78]
I try to implement discounted cfr by writing a subclass of _CFRSolver class. I overwrite the _compute_counterfactual_regret_for_player function. Since linear CFR is just a special case of discounted cfr, so it is also implemented. I am not sure if I implement it in a nice way.

I test it by running on goofspiel4, it gets decent results. Will the implementation be helpful? Should I pull it?

**Comment by lanctot** [comment]
That's awesome!! That sounds like a great way to do it. Yes, please, would love if you turned this into a pull request.

**Comment by ai-gamer** [comment]
I turned it into a pull request. Please check if it works when you get time. Thanks!
