### ISSUE TITLE
Game serialize/deserialize

### ISSUE THREAD

**Issue by tuero** [deepmind/open_spiel#784]
Forenote: I previously wrote the `stones_n_gems` game.

## Problem 
The `stones_n_gems` game uses a string containing commas to represent the map being used, which clashes with how the `GameParametersFromString` function parses serialized Games.

## Description / Explanation
The `stones_n_gems` game allows for various input maps to play. Maps are used in the game initialization process through the GameParameter `grid`  string, which is a string containing newlines/commas to represent each item in the underlying map. I've been trying to use the game in python code which pickles the game/state, and have been getting errors about `Unknown parameter` during the deserializing process.

I've looked into how the pyspiel state python objects are pickled, and it appears that both the game/state are pickled. I've narrowed down the issue to what I believe is the `GameParametersFromString` function.  For this particular game, it receives as input the following (note that the commas/newlines are part of the string):
```
stones_and_gems(grid=12,12,999999,1
18,18,18,18,18,18,18,18,18,18,18,18
18,02,02,02,02,02,02,02,02,02,02,18
18,02,02,02,02,02,04,02,02,02,02,18
18,02,02,02,02,02,02,02,02,02,02,18
18,02,02,02,02,02,01,02,02,02,02,18
18,02,02,02,00,02,01,02,02,02,02,18
18,02,02,02,02,02,01,02,02,02,02,18
18,02,02,02,02,02,01,02,02,02,02,18
18,02,02,02,02,02,02,02,02,02,02,18
18,02,02,02,02,02,02,02,02,02,02,18
18,02,02,02,02,02,02,02,02,02,08,18
18,18,18,18,18,18,18,18,18,18,18,18,obs_show_ids=True)
```
During the inner loop which reads each game parameter, I see the following when debug printing `game_string.substr(equals + 1, i - equals - 1)`:
```
12
---
stones_and_gems(grid=12,12
---
stones_and_gems(grid=12,12,999999
---
stones_and_gems(grid=12,12,999999,1
18
---
stones_and_gems(grid=12,12,999999,1
18,18
---
stones_and_gems(grid=12,12,999999,1
18,18,18
---
stones_and_gems(grid=12,12,999999,1
18,18,18,18
---
stones_and_gems(grid=12,12,999999,1
18,18,18,18,18
---
stones_and_gems(grid=12,12,999999,1
18,18,18,18,18,18
---
stones_and_gems(grid=12,12,999999,1
18,18,18,18,18,18,18
---
stones_and_gems(grid=12,12,999999,1
18,18,18,18,18,18,18,18
---
stones_and_gems(grid=12,12,999999,1
18,18,18,18,18,18,18,18,18
---
stones_and_gems(grid=12,12,999999,1
18,18,18,18,18,18,18,18,18,18
---
stones_and_gems(grid=12,12,999999,1
18,18,18,18,18,18,18,18,18,18,18
---
stones_and_gems(grid=12,12,999999,1
18,18,18,18,18,18,18,18,18,18,18,18
18

```
etc.

## Solution
I believe the solution to this is to change the commas in the `grid` parameter to be another symbol (say `|` as an example). This is an easy fix on my end, but will break compatibility for anyone who has existing code which uses this game.

Let me know if I should go ahead with a PR on this.

**Comment by lanctot** [comment]
Hi Jake, yes this is a problem with the simple default way that everything is serialized (and passed as strings). As a result some games are just not serializable with nondefault params (see this thread too: https://github.com/deepmind/open_spiel/issues/778).

The larger fix is to allow games and state serialization to be overridden (not just states) which we plan to get around to eventually. But that is likely not any time soon, so I like your suggested fix which should work in the short term.

**Comment by lanctot** [comment]
I don't know anyone using this game but also I think it is ok to have backward-incompatible changes on the master branch (since there are other options for greatet stability like using a release branch and forking)

**Comment by tuero** [comment]
Thanks for the feedback Marc!
