### ISSUE TITLE
NFSP with CNN

### ISSUE THREAD

**Issue by BedirT** [deepmind/open_spiel#789]
Do we have NFSP implementation using a CNN rather than a linear network? I can't seem to locate it, I would appreciate it if someone could direct me (if it exists).

**Comment by lanctot** [comment]
Hi Bedir,

We do not. Most of the imperfect information games have single dimensional info set tensors. 

Extending NFSP to support CNNs (with e.g. an example on Dark Hex) would make a nice contribution!

**Comment by BedirT** [comment]
Yeah I will work on that :ok_hand:

**Comment by BedirT** [comment]
@lanctot 

I have a couple of questions (All on the DarkHex version, but it is probably the same for some other phantom games):
- The game implements the info-states as one-hot encoding which I don't think would capture the spatial connection I aim to have with CNN implementation. If that sounds fine I will change the game itself. Let me know if there is a better way.
- Is it fine if I used tf2 & default layering system with Functional API, or should I write custom layers?

**Comment by lanctot** [comment]
>     * The game implements the info-states as one-hot encoding which I don't think would capture the spatial connection I aim to have with CNN implementation. If that sounds fine I will change the game itself. Let me know if there is a better way.

If you're planning to train it only on the current "view" (losing all historical information) then I suggest you use the ImperfectRecallDarkHex and override the information state tensor to be just the spatialized view. 

To see how to organize the tensor for use by CNNs, see some of the perfect information games which lay them out in planes (e.g. Tic-Tac-Toe, Breakthrough) which can then be reshaped on the python size. The AlphaZero implementations use CNNs if you want to see how those observations get used in CNN training. 

>     * Is it fine if I used tf2 & default layering system with Functional API, or should I write custom layers?

For extending NFSP? I don't have a preference as long as the basic NFSP we have now still works as before (i.e. make CNNs optional and disabled by default, or copy the file and make it a new NFSP specifically for CNNs).

**Comment by BedirT** [comment]
I am pretty much done, except that I cannot figure out some c++ related stuff :) 

When I implement a non-one-hot version of the `information_state` and `observation_state`, I can run the game, but I get weird shapes from `InformationStateTensorShape` and `ObservationTensorShape`... I couldn't find a proper way to handle the issue.

Here is an example from the playthrough;
```bash
NumDistinctActions() = 12
PolicyTensorShape() = [12]
MaxChanceOutcomes() = 0
GetParameters() = {board_size=3,gameversion=cdh,num_cols=4,num_rows=3,obstype=reveal-nothing}
NumPlayers() = 2
MinUtility() = -1.0
MaxUtility() = 1.0
UtilitySum() = 0.0
ObservationTensorShape() = [55531744]
ObservationTensorLayout() = TensorLayout.CHW
ObservationTensorSize() = 55531744
MaxGameLength() = 23
ToString() = "dark_hex_ir(num_cols=4,num_rows=3)"
```
I did realize the problem is coming from `spiel.h` as the function `InformationStateTensorSize` uses bitwise ops, but my c++ knowledge is limited to knowing how can I bypass the virtual function call (or a better solution, maybe)

**Comment by lanctot** [comment]
`Game::StateInformationStateTensorSize` is simply a product of the values in InformationStateTensorShape, see here: https://github.com/deepmind/open_spiel/blob/5eaf401f7d08d68285fe214ab5cf5a741807ea6e/open_spiel/spiel.h#L824. Similarly for `ObservationTensorSize`.

I don't see and `InformationStateTensorSize` above, only `ObservationTensorSize`, and your `ObservationTensorShape` does not look right -- it should be multi-dimensional (like, e.g. [3, 4, 3]).

I'm not sure where you're seeing bitwise operations.... I think you've possibly misunderstood something. Can you submit a PR so we can see the code?

**Comment by BedirT** [comment]
Here #791

**Comment by lanctot** [comment]
Ok right those tensor shapes are single-dimensional. Why? They should be planar for CNNs: one plane for white stones, one for black stones, one for empty (or "unknown").

Please take a look at Breakthrough or Tic-Tac-Toe for examples on multi-dimensional observations tensors (including their shape functions). You can mostly copy what was done in those games, but in your case your shape should be [num_planes, num_rows, num_cols].
