### ISSUE TITLE
Help with Python game implementation: MCTS reaches state with no legal actions remain

### ISSUE THREAD

**Issue by aaronsnoswell** [deepmind/open_spiel#799]
Hi OpenSpiel team!

I'm working on understanding how OpenSpiel works, and I've been implementing the card game [Battle Line](https://boardgamegeek.com/boardgame/760/battle-line) (in Python) to learn about the game and state objects OpenSpiel uses.

I've gotten my implementation to a point that I believe the game logic is correct: I can sample random actions manually and rollout an entire game trajectory, but when I try testing my game implementation with the MCTS bot, I get an error from `open_spiel/python/algorithms/mcts.py:69`

```ValueError                                Traceback (most recent call last)
<ipython-input-12-0f348d9ccb6f> in <module>()
     50         # Decision node: sample action for the single current player
     51         bot = bots[current_player]
---> 52         action = bot.step(state)
     53         action_str = state.action_to_string(current_player, action)
     54         print("Player {} sampled action: {}".format(current_player, action_str))

3 frames
/usr/local/lib/python3.7/dist-packages/open_spiel/python/algorithms/mcts.py in step(self, state)
    292 
    293   def step(self, state):
--> 294     return self.step_with_policy(state)[1]
    295 
    296   def _apply_tree_policy(self, root, state):

/usr/local/lib/python3.7/dist-packages/open_spiel/python/algorithms/mcts.py in step_with_policy(self, state)
    266     """Returns bot's policy and action at given state."""
    267     t1 = time.time()
--> 268     root = self.mcts_search(state)
    269 
    270     best = root.best_child()

/usr/local/lib/python3.7/dist-packages/open_spiel/python/algorithms/mcts.py in mcts_search(self, state)
    409         solved = self.solve
    410       else:
--> 411         returns = self.evaluator.evaluate(working_state)
    412         solved = False
    413 

/usr/local/lib/python3.7/dist-packages/open_spiel/python/algorithms/mcts.py in evaluate(self, state)
     67           action = self._random_state.choice(action_list, p=prob_list)
     68         else:
---> 69           action = self._random_state.choice(working_state.legal_actions())
     70         working_state.apply_action(action)
     71       returns = np.array(working_state.returns())

mtrand.pyx in numpy.random.mtrand.RandomState.choice()

ValueError: 'a' cannot be empty unless no samples are taken
```

It seems that when doing a lookahead rollout, the MCTS bot reaches a point where it tries to sample actions, but there are no legal actions to be found - which *should* mean the game has terminated, but apparently, it hasn't. I'm guessing I've missed something small in my implementation of the Python state interface, but I can't see my mistake.

My code [is in a collab notebook](https://colab.research.google.com/drive/1RjT9UBDFEiMNckOmvlsNUovqZ7w7wUUh#scrollTo=aWXlOH3vu3QQ) - I would greatly appreciate if anyone more familiar with the project had time to take a peek and let me know if you can see the problem with my game implementation.

If I can get this working, I'd be happy to contribute this implementation as an unofficial demo of the python API.

Thank you,

**Comment by lanctot** [comment]
Hi @aaronsnoswell, 

The best way to debug this is to insert an if statement on the offending line that checks if the legal_actions are empty. When it is, print out the `state.to_string()` and `state.history()`. 

Then, separately, construct a new program that plays through that history, printing out ever state and every action (you can use `state.action_to_string` to get the action's string representation). 

Then manually inspect what's happening and whether it makes sense. This should find where the logic went wrong or a case that is not being covered.

**Comment by lanctot** [comment]
Actually, this is such a common case for debugging that I'll add a helper that does this (one that can take the history string and game string and just play it out (but will only be in the next few weeks). There are a few options that would be good too, like the ability to make it an interactive session walk through the game.

**Comment by lanctot** [comment]
Hi @aaronsnoswell, just touching base -- were you able to find the problem?

**Comment by aaronsnoswell** [comment]
Hi @lanctot! Thank you for following up! I have been busy and haven't had a chance to review this yet :D Please feel free to close and I'll report back if there is any actual issue here (other than my own incompetence :D)
