### ISSUE TITLE
Implement Xiangqi game

### ISSUE THREAD

**Issue by huynq55** [deepmind/open_spiel#802]
Hello, I want to implement the Xiangqi game. I'm referring the Chess game implementation as an example for Xiangqi. For chess, there is chess folder which has files like chess_board, chess-common. I want to create the same xiangqi folder with same files (my programming skill is not so good, so i'm just mimicking Chess). Will the files be recognized by the compiler when I run `build_and_run_tests.sh`? How can I make sure that my implementation will be merged into open_spiel? Thanks!

**Comment by lanctot** [comment]
Hi @huynq55,

Great!

The best place to start is the "Adding a game" section of the developer guide: https://github.com/deepmind/open_spiel/blob/master/docs/developer_guide.md

The files will be found if they are added to the appropriate CMakeLists.txt files. I recommend copying what is done in chess there as well.

Once you are happy with the implementation and all the tests pass, please submit a pull request. Then we will review it and probably ask you to change a few things and then once the fixes are all done we will import it and it gets merged after that.

**Comment by lanctot** [comment]
I've added this game to Call for New Games thread, so closing this one for now until anybody volunteers to work on it. Thanks for the suggestion!
