### ISSUE TITLE
Any plans for MCTS Solver?

### ISSUE THREAD

**Issue by jdermont** [deepmind/open_spiel#81]
Are there any plans to implement mcts solver into mcts? I see in code there is just simple back-propagation of the values, regardless wether they come from interior node or terminal node. Mcts solver is when we encounter terminal node, we can apply something like inf/-inf value to the node, but also back-propagate the terminals as far as we can, by using logic that if terminal node is a win for a player, then it's obviously loss for its parent (opponent). Similarly if all siblings are loss, then it's a win for the parent and again loss for grandparent.

**Comment by lanctot** [comment]
@tewalds and I have discussed some some general improvements to MCTS. I'm not sure if that would include [MCTS Solver](https://dke.maastrichtuniversity.nl/m.winands/documents/uctloa.pdf) but it would be a really nice thing to have. 

It would also (eventually) be good to have [implicit minimax backus](http://mlanctot.info/files/papers/cig14-immcts.pdf) which is kind of a heuristic version that you can use everywhere in the game if you have an evaluation function that was inspired by MCTS-Solver.

Supporting too many options in the base algorithm would probably be a mistake, actuallu. I think the solver is fairly obvious and should always be on by default, whereas we can keep copies that add the other things (unless we can do it in a modular enough way that doesn't make the basic MCTS too complex.

Feel free to add these to the [Call for Contributions](https://github.com/deepmind/open_spiel/blob/master/docs/contributing.md) so we (and others) can see it!

**Comment by jdermont** [comment]
Plain mcts solver looks simple and is very general enhancement to mcts. Even if the playing strength of the game doesn't benefit from it, it doesn't hurt and near endgames it may return desired move almost immediately, instead of making useless simulations. This can be seen especially in ai vs ai battles as the last moves are printed very quickly.

Can I just edit the Call for Contributions and pull request it?

**Comment by locked-deepmind** [comment]
Yes, please feel free to do a PR either to add the call for contributors or
to add the functionality itself.

For context, we want the algorithms in OpenSpiel to be clear
implementations of standard approaches - easy to understand, and easy for
people to use as a basis for research, by extending them with their own new
ideas. We are not aiming to build the strongest solvers possible.

MCTS solver definitely does qualify as the sort of thing that we want, but
game-specific heuristics would definitely not.

**Comment by lanctot** [comment]
And just to clarify that last point: we want the main the main implementation of MCTS to be free of game-specific heuristics (and not have too many options), i.e. be fairly clean. 

We expect to have several variants separate from the main ones which might use heuristic information (via outside evaluators like the minimax search does now) -- but we want to avoid any hard-coded game-specific heuristics in the algorithm implementations themselves.

**Comment by tewalds** [comment]
I was planning to add this. I found it was a large performance boost in Havannah, and presumably any game where there are threats to win on short paths from the current position.

**Comment by lanctot** [comment]
@jdermont , @tewalds added MCTS-Solver in Python. Feel free to re-open if you wanted it also on the C++ side. I think we'll add it there too eventually.
