### ISSUE TITLE
Replicator dynamics (quiver) not showing

### ISSUE THREAD

**Issue by GitMew** [deepmind/open_spiel#812]
I've been trying to write an OpenSpiel example that illustrates how to plot replicator dynamics. However, even with the minimal code below, nothing seems to show up. Perhaps I'm missing something, perhaps something is broken.
```python3
import pyspiel
import open_spiel.python.egt.visualization as v
import open_spiel.python.egt.dynamics as d
import open_spiel.python.egt.utils as u

import matplotlib.pyplot as plt

def example():
    game = pyspiel.load_matrix_game("matrix_rps")

    # Figure setup
    fig = plt.figure()  # Alternatively, fig, main_ax = plt.subplots()
    rect = [0, 0, 100, 100]  # [left, bottom, width, height]
    ax = v.Dynamics3x3Axes(fig, rect)

    # Arrow plot setup
    payoffs  = u.game_payoffs_array(game)
    dynamics = d.replicator  # Two alternatives: d.qpg and d.boltzmannq
    popdyn   = d.SinglePopulationDynamics(payoffs, dynamics)
    ax.quiver(popdyn)

    plt.show()  # Shows a window, but it's an empty figure :(

if __name__ == "__main__":
    example()
```

**Comment by dhennes** [comment]
Hi @GitMew you need to set the projection of the subplot. In your example, the axis object `ax` is not linked to the figure `fig`. This should work:
```
# Figure setup
fig = plt.figure()
ax = fig.add_subplot(111, projection='3x3')
```

**Comment by GitMew** [comment]
> In your example, the axis object `ax` is not linked to the figure `fig`. This should work:
> 
> ```
> # Figure setup
> fig = plt.figure()
> ax = fig.add_subplot(111, projection='3x3')
> ```
@dhennes Aha, now something is showing up. If you don't mind me asking: why are we forgoing `Dynamics3x3Axes` altogether? It's a subclass of `matplotlib.Axes`, but surely not the same at all?

**Comment by dhennes** [comment]
`Dynamics3x3Axes` is actually the projection class [registered](https://github.com/deepmind/open_spiel/blob/master/open_spiel/python/egt/visualization.py#L609) under the name `3x3`. The argument `projection='3x3'` tells Matplotlib to create an instance of this class and adds it to the figure. You can find more info on how projections work in Matplotlib [here](https://matplotlib.org/stable/api/projections_api.html).
