### ISSUE TITLE
State string in tabular policies for mean field games.

### ISSUE THREAD

**Issue by wyz2368** [deepmind/open_spiel#813]
Dear authors,

I noticed there might be an indexing issue when using tabular policy for mean field games. In the example code below, I first created a MFG and a uniform policy that is transformed to a tabular policy using `to_tabular()`. For a tabular policy, we can use `policy.state_lookup` (a dictionary) to look up the index of the state by inputting the state string (keys). However, the keys of `policy.state_lookup` are `dict_keys(['0', '0, 0, 2', '1', '0, 1, 2', '2', '0, 2, 2', '3', '0, 0, 0', '4', '0, 0, 1'])`. I think the correct keys should be `['0, 0', '0, 2', '1, 0', '1, 2', '2, 0', ...]`.  This is because in MFGs a state string `'0, 0'` represents the state 0 at time step 0. The `policy.state_lookup` seems to group these numbers (keys) in a wrong way. Any thoughts on this would be very helpful. Thanks.

```
import pyspiel
from open_spiel.python import policy as policy_std

game = pyspiel.load_game("mfg_crowd_modelling", {"size": 5, "horizon": 2})
policy = policy_std.UniformRandomPolicy(game).to_tabular()
print(policy.state_lookup)
{'0': 0, '0, 0, 2': 1, '1': 2, '0, 1, 2': 3, '2': 4, '0, 2, 2': 5, '3': 6, '0, 0, 0': 7, '4': 8, '0, 0, 1': 9}
```

**Comment by lanctot** [comment]
Thanks @wyz2368, 

@sgirgin @RaphaelMarinier @perolat , any idea what's going on here?

**Comment by lanctot** [comment]
@TheoCabannes too, maybe...?

**Comment by sgirgin** [comment]
Hi @wyz2368 ! When a game provides the information state string, the tabular policy uses that as the keys. This is documented in the class description:

https://github.com/deepmind/open_spiel/blob/master/open_spiel/python/policy.py#L192

(impementation: https://github.com/deepmind/open_spiel/blob/master/open_spiel/python/policy.py#L291)

In this particular case (crowd modelling game), they are the history strings.

**Comment by wyz2368** [comment]
This is very helpful. Thank you so much!
