### ISSUE TITLE
Unable to use C++ shared library in CMAKE project

### ISSUE THREAD

**Issue by sardanian** [deepmind/open_spiel#814]
I am trying to use the C++ shared library in a CMAKE project. I am trying to do something simple which is basically to be able to run a game by also include another library, such as libtorch. I understand libtorch is already built into the current alphazero lbtorch example but I am trying to use it on its own.

I understand that in the C++ useage instructions that you can use a shared library for open_spiel and this is what I am trying to do but via a CMAKE project. I see that there is a way to compile a file for open_spiel in the shared_library_example with clang++ but I want to make this via CMAKE so I can also incorporate libtorch or other libraries in my project.

I am new to using C++ libraries having done most things in python.

My current errors are that when I try to include the shared library and include the headers, etc. when I run something as simple as this: there is the error I am getting in my CMAKE build.

tester.cpp:
```
#include <torch/torch.h>
#include <iostream>
#include "open_spiel/spiel.h"
#include "open_spiel/spiel_utils.h"

int main() {
    torch::Tensor tensor = torch::rand({2, 3});
    std::cout << tensor << std::endl;

    // Print out registered games.
    std::cerr << "Registered games:" << std::endl;
//    std::shared_ptr<const open_spiel::Game> game = open_spiel::LoadGame("chess");
    std::vector<std::string> names = open_spiel::RegisteredGames();
    for (const std::string& name : names) {
        std::cerr << name << std::endl;
    }
}

```
my CmakeList.txt file:
```
cmake_minimum_required(VERSION 3.21)

set(CMAKE_CUDA_COMPILER /usr/local/cuda/bin/nvcc)
project(tester)
SET(BUILD_SHARED_LIBS ON)
SET(LD_LIBRARY_PATH ${HOME}/open_spiel/build)

set(CMAKE_CXX_STANDARD 17)

set (CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wno-everything")
set (CMAKE_POSITION_INDEPENDENT_CODE ON)

include_directories("${PROJECT_SOURCE_DIR}")

include_directories(open_spiel)
include_directories(open_spiel/build)
include_directories(open_spiel/open_spiel)
include_directories(open_spiel/open_spiel/abseil-cpp)
include_directories(open_spiel/open_spiel/abseil-cpp/absl)
include_directories(open_spiel/open_spiel/abseil-cpp/absl/random)
include_directories(open_spiel/open_spiel/abseil-cpp/absl/base)

find_package(PythonInterp REQUIRED)
find_package(Torch REQUIRED)
#find_package(open_spiel REQUIRED)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${TORCH_CXX_FLAGS} -v")
add_executable(tester tester.cpp)

target_link_libraries(tester "${TORCH_LIBRARIES}" open_spiel)
target_link_libraries(tester open_spiel)
set_property(TARGET tester PROPERTY CXX_STANDARD 17)
```

I have open_spiel repository downloaded into my $HOME/open_spiel directory

The error I am getting is in tester.cpp is:
undefined reference to `open_spiel::RegisteredGames()'

I am using CLION and it recognizes the open_spiel namespace and I can thus use Intellisense so it looks like to me that the shared library is being recognized, but it isn't!

I have tried also adding this before the add_executable:
`add_library(open_spiel SHARED ${HOME}/open_spiel/build/libopen_spiel.so)`

and then this after add_executable:
`target_link_libraries(tester open_spiel)`

hoping this would help.

I also tried adding this:
`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${TORCH_CXX_FLAGS} -v -I${HOME}/ -I${HOME}/open_spiel/open_spiel/abseil-cpp -L${HOME}/open_spiel/build -lopen_spiel -std=c++17")`

to basically recreate the C++ clang++ compile code and still I get the same error of undefined reference.

I try to include the library and have access to the headers 

I cannot figure it out though. I have read that there is a need for a Open_spielConfig.Cmake (or some sort of config.cmake) file to be able to use find_package() in a CMAKE file, howver there doesn't seem to be any kind of Config.Cmake file getting generated.

I have spent hours on this and feel it is a simple thing I am missing out but just can't seem to figure it out. I am hoping someone can help me with this.

Thank you.

**Comment by lanctot** [comment]
Hi @sardanian,

We don't have OpenSpiel setup for this at the moment, we would have to write the necessary CMake meta-files (as you're suggesting) to have find_package work properly. This would be a welcome addition to OpenSpiel. 

In the mean time:

- Will you need to modify the OpenSpiel code at all? If not, then I suggest you build it at as a dynamically-linked library by following the instructions [here](https://github.com/deepmind/open_spiel/blob/master/docs/library.md). Then all you would need to do in your project is setup the include paths and dynamically link to OpenSpiel, which is fairly easy.
- If you need to modify OpenSpiel code but not LibTorch then you can instead do the opposite: compile OpenSpiel to link to the LibTorch library (see [here](https://github.com/deepmind/open_spiel/tree/master/open_spiel/algorithms/alpha_zero_torch) for how to do that).

Hope this helps!

**Comment by sardanian** [comment]
Thank you for this.

I do not need to modify OpenSpiel code at all. However, "[Using OpenSpiel as a C++ Library](https://github.com/deepmind/open_spiel/blob/master/docs/library.md)" requires that I compile via clang++. I do not believe there is a way to compile libtorch with clang++ (at least I have not been able to find the appropriate method to do that). Libtorch documentations and tutorials show it being integrated via a cmake process (similar to how OpenSpiel implements libtorch via cmake). Thus I am unable to do this. If there is a way that I am missing, I would love to do this. Ideally I could use cmake to include two libraries (OpenSpiel and Libtorch) and include them as a part of my program.

I can recompile Openspiel with libtorch every time as you suggested in your [second option](https://github.com/deepmind/open_spiel/tree/master/open_spiel/algorithms/alpha_zero_torch), but I felt there should be a way for me to have a torch library and a openspiel library and integrate both of those into my new program. If this is not possible I could recompile openspiel with libtorch each time, but it just seemed the wrong way to go about it.

Thank you.

**Comment by sardanian** [comment]
Actually, upon further testing, recompiling Openspiel with libtorch doesn't seem the right approach or I can't seem to figure it out. I would like to use CLION and debug my program and so would like to be able to build and add an executable of my file and then debug it. Ideally I can have an OpenSpiel library and a torch library called by the same program via CMAKE. Then I can build via cmake and easily debug as well.

**Comment by lanctot** [comment]
If you do not need to modify the OpenSpiel code, then you can compile it as a shared library. It should not matter whether you produce that shared library with clang++ or g++ (replace all the instances of clang++ with g++ on that page and it will still work), because it's binary/machine code that gets dynamically loaded at run-time. You compile the OpenSpiel shared library once via the instructions above and and then link against separately it in your code. You can still use CLION to debug your programs. But: before continuing, I strongly suggest you read a tutorial on dynamic linking/libraries. Here's an overview: https://www.learncpp.com/cpp-tutorial/a1-static-and-dynamic-libraries/. To see how to setup CMake for dynamic linking against a shared library, you can see our example of using OR-Tools (an external optimization library) for linear programming [here](https://github.com/deepmind/open_spiel/blob/0c265fbaa56c418788333fdf3bd373ff12620d14/open_spiel/CMakeLists.txt#L269) and [here](https://github.com/deepmind/open_spiel/blob/master/open_spiel/algorithms/ortools/CMakeLists.txt).

As for the second option, there is a working example: our LibTorch AlphaZero code does exactly what you'd want to do. Take a look at the the LibTorch AlphaZero CMakeLists.txt [here](https://github.com/deepmind/open_spiel/blob/master/open_spiel/algorithms/alpha_zero_torch/CMakeLists.txt), the definitions for Torch library [here](https://github.com/deepmind/open_spiel/blob/0c265fbaa56c418788333fdf3bd373ff12620d14/open_spiel/CMakeLists.txt#L258). The path is for LibTorch was chosen by us [here](https://github.com/deepmind/open_spiel/blob/0c265fbaa56c418788333fdf3bd373ff12620d14/open_spiel/scripts/install.sh#L165).

Hope this helps!

**Comment by sardanian** [comment]
Thank you. I was able to get this resolved. I went through your points and it seems that there was an issue with LibTorch, not OpenSpiel. I had implemented LibTorch first, but for some reason when combined with OpenSpiel it was causing some issues. I eventually got a cmake file working for both of them through your direction. Thank you.

**Comment by lanctot** [comment]
Great! Glad we could help.
