### ISSUE TITLE
What is the difference between an information state and an observation?

### ISSUE THREAD

**Issue by hhlei** [deepmind/open_spiel#815]
I don't understand the purpose of the Observer class in making a game. Isn't there already a function InformationStateTensor(player, values) to generate observations? Also, what exactly should go into values?

**Comment by hhlei** [comment]
Kind of related question: how do I write the informationStateTensor for non homogenous players (ie different observation/action spaces)? I have to define a priori an informationStateTensorShape in the game class, but it doesn't differentiate between players.

**Comment by lanctot** [comment]
Hi @hhlei, see the docs in spiel.h for the difference, also explained in the OpenSpiel paper.

For different observations / infoststes the common way is to make it a constant size equal to the maximum across players and then just store different information in them (see the Sheriff game as an example).

**Comment by lanctot** [comment]
Hi @hhlei, did this clarify things for you?
