### ISSUE TITLE
Minor discussions about pathfinding games

### ISSUE THREAD

**Issue by rezunli96** [deepmind/open_spiel#822]
Hello there. I am currently working on pathfinding games and found the implementation here really helpful!

Some minor questions about the implementation. According to the reference [here](https://www.jmlr.org/papers/volume4/hu03a/hu03a.pdf) there maybe several mechanics that are missing: (1) when an agent hits an obstacle, actually there could be a probability to pass through the block. (2) when two agents contest they may also incur a penalty (3) two agents may share the same destination. According to my understanding, they are not currently supported?

**Comment by lanctot** [comment]
Hi @rezunli96, I did not model the pathfinding games on any existing descriptions, I just designed the rules myself. Not sure I fully understand each one of the points yet so I will look at the reference and get  back to you soon.
