### ISSUE TITLE
Dependency errror: LogUsage function is used in core (spiel.cc) but defined in utils

### ISSUE THREAD

**Issue by phcerdan** [deepmind/open_spiel#825]
Changed in commit: https://github.com/deepmind/open_spiel/commit/f3fee781cc9936d9ba3f33582a2ea77846225756

Faulty line:  https://github.com/deepmind/open_spiel/blob/master/open_spiel/spiel.cc#L238

Solution: Move usage_logging.{h.cc} from utils to core (or remove LogUsage from spiel.cc)

**Comment by lanctot** [comment]
Sorry, I don't understand-- under what circumstances does this cause an error and can you give an example?

**Comment by phcerdan** [comment]
I am refactoring a bit CMake files to simplify the library for my usage.

If you compile the files at core: https://github.com/deepmind/open_spiel/blob/0c265fbaa56c418788333fdf3bd373ff12620d14/open_spiel/CMakeLists.txt#L165-L190

 without `/utils`, it fails at that line. If you remove the line, it compiles ok.

I thought utils was an optional extra, but you need it to compile `spiels.cc`. Closing.

**Comment by lanctot** [comment]
Ok, makes sense. We need to keep that call to `LogUtil` for internal purposes.
