### ISSUE TITLE
Hyperscan Error in make ...collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by muhammadnaeemshahzad** [deepmind/open_spiel#83]
I am getting below error message in make of hyperscan...I'm trying to build Hyperscan latest version as of today.
cmake verison : 3.15.3
 
Error Details
Scanning dependencies of target hsbench
[ 95%] Building CXX object tools/hsbench/CMakeFiles/hsbench.dir/data_corpus.cpp.o
[ 95%] Building CXX object tools/hsbench/CMakeFiles/hsbench.dir/engine.cpp.o
[ 95%] Building CXX object tools/hsbench/CMakeFiles/hsbench.dir/engine_hyperscan.cpp.o
[ 96%] Building CXX object tools/hsbench/CMakeFiles/hsbench.dir/heapstats.cpp.o
[ 96%] Building CXX object tools/hsbench/CMakeFiles/hsbench.dir/huge.cpp.o
[ 96%] Building CXX object tools/hsbench/CMakeFiles/hsbench.dir/main.cpp.o
[ 96%] Building CXX object tools/hsbench/CMakeFiles/hsbench.dir/sqldb.cpp.o
[ 97%] Linking CXX executable ../../bin/hsbench
CMakeFiles/hsbench.dir/engine_hyperscan.cpp.o: In function `buildEngineHyperscan(std::map<unsigned int, std::string, std::less<unsigned int>, std::allocator<std::pair<unsigned int const, std::string> > > const&, ScanMode, std::string const&, std::string const&, ue2::Grey const&)':
/root/NAEEM/hyperscan/tools/hsbench/engine_hyperscan.cpp:427: undefined reference to `ue2::hs_compile_lit_multi_int(char const* const*, unsigned int const*, unsigned int const*, hs_expr_ext const* const*, unsigned long const*, unsigned int, unsigned int, hs_platform_info const*, hs_database**, hs_compile_error**, ue2::Grey const&)'
/root/NAEEM/**hyperscan/tools/hsbench/engine_hyperscan.cpp:434: undefined reference to `ue2::hs_compile_multi_int(char const* const*, unsigned int const*, unsigned int const*, hs_expr_ext const* const*, unsigned int, unsigned int, hs_platform_info const*, hs_database**, hs_compile_error**, ue2::Grey const&)'
collect2: error: ld returned 1 exit status**
make[2]: *** [bin/hsbench] Error 1
make[1]: *** [tools/hsbench/CMakeFiles/hsbench.dir/all] Error 2
make: *** [all] Error 2
[root@howler hyperscan]# ^C
[root@howler hyperscan]#

**Comment by lanctot** [comment]
Wrong repos?
