### ISSUE TITLE
Dynamics3x3Axes subplot is smaller than others

### ISSUE THREAD

**Issue by GitMew** [deepmind/open_spiel#839]
I'm plotting 2x2 and 3x3 dynamics besides each other. You'd expect the top and bottom edges of the square 2x2 plot to be reasonably close to the level of the triangular 3x3 plot's base and tip, but the 3x3 plot seems shrunk down. I've looked in many places, and there doesn't seem to be a way in matplotlib to scale up just one of the subplots manually.

On the topic of scaling in 3x3 plots: I've been trying to make it so that the dynamics arrows show smaller magnitude not by retracting their tail into a fixed-size arrow head, but instead scale down the arrows as a whole (see e.g. figure 4 in https://jair.org/index.php/jair/article/view/10952/26090). Is there an easy way to cause this behaviour?

Here's an MWE and its result:
```python
from open_spiel.python.egt.utils import game_payoffs_array
from open_spiel.python.egt.dynamics import MultiPopulationDynamics, SinglePopulationDynamics, replicator
from open_spiel.python.egt.visualization import Dynamics2x2Axes, Dynamics3x3Axes
from pyspiel import load_matrix_game
import matplotlib.pyplot as plt
pd  = load_matrix_game("matrix_pd")
rps = load_matrix_game("matrix_rps")

fig = plt.figure()
ax1: Dynamics2x2Axes = fig.add_subplot(1,2,1, projection="2x2")
ax2: Dynamics3x3Axes = fig.add_subplot(1,2,2, projection="3x3")

popdyn1 = MultiPopulationDynamics(game_payoffs_array(pd), replicator)
popdyn2 = SinglePopulationDynamics(game_payoffs_array(rps), replicator)

ax1.quiver(popdyn1)
ax2.quiver(popdyn2)

plt.show()
```
![bad_alignment_openspiel](https://user-images.githubusercontent.com/37484463/169419320-1b835738-72af-4860-a7fc-1e042478667e.png)

**Comment by lanctot** [comment]
@dhennes, any idea?

**Comment by dhennes** [comment]
Hi @GitMew, sorry for the delay. You could try this to manually set the bounds of you subplots:
```
ax2.set_xlim(0, 1)  # no vertex labels, so we can set xlim tighter
ax1.set_position([0, 0.05, 0.45, 0.9])  # left, bottom, width, height
ax2.set_position([0.5, 0, 0.5, 1])
```
