### ISSUE TITLE
Information State Tensor Format

### ISSUE THREAD

**Issue by nikhilweee** [deepmind/open_spiel#854]
I am running Leduc Poker and I am having a hard time figuring out the format for the Information State Tensor. Where can I find more information on how the following Information State String is translated to the corresponding Information State Tensor?
```
[Observer: 0][Private: 1][Round 2][Player: 0][Pot: 14][Money: 95 91][Public: 3][Round1: 1 1][Round2: 2 2]
[1.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 1.0, 0.0, 0.0, 0.0, 0.0]
```

**Comment by lanctot** [comment]
Hi @nikhilweee, 

You can find the function that fills the tensor here: https://github.com/deepmind/open_spiel/blob/da774f602fb4a390e66b979a67210498fd0d8919/open_spiel/games/leduc_poker.cc#L176

The bits include: one-hot encoded observing player, one-hot encoded private card, one-hot encoded public card, then the betting sequence of one-hot encoded actions (call or raise).

Also described in the comment here: https://github.com/deepmind/open_spiel/blob/da774f602fb4a390e66b979a67210498fd0d8919/open_spiel/games/leduc_poker.cc#L811

Hope this helps!

**Comment by nikhilweee** [comment]
I see, this was very helpful. Thank you so much!

**Comment by lanctot** [comment]
No problem!
