### ISSUE TITLE
Use of designated initializer not allowed in C++17

### ISSUE THREAD

**Issue by yclicc** [deepmind/open_spiel#864]
https://github.com/deepmind/open_spiel/blob/0ffd9584c8be560f4e0f659b3ad93933d9078b48/open_spiel/games/mfg/dynamic_routing.cc#L95-L102

Use of designated initializers is a C++20 feature and the supported version of C++ is C++17. This led to a compile error when building on Windows 10. I'm not an expert on C++ so not sure how this should best be rewritten, but I was able to make open_spiel compile by commenting out these lines (but presumably breaking the Mean Field Game).

@lanctot

**Comment by lanctot** [comment]
Hi @yclicc, 

Thanks for reporting. I will try submitting a PR to fix and link you the fix to try on your side.

**Comment by lanctot** [comment]
Ok can you try making the changes describe here: https://github.com/deepmind/open_spiel/pull/865/files

(Please confirm if it works as a result.)

**Comment by yclicc** [comment]
Yep, thanks, that compiles now! I can't comment on whether the mean field games still work as intended though as I haven't used that part of the package and can't find an example script for it.
