### ISSUE TITLE
TypeError: can't pickle pyspiel.Game objects

### ISSUE THREAD

**Issue by tcfuji** [deepmind/open_spiel#88]
Hi,

I'm trying to speed up the training of the openspiel rl agents. I've tried both python's multiprocessing package and [ray](https://ray.readthedocs.io/en/latest/index.html) but in both cases I get the same error: 
`TypeError: can't pickle pyspiel.Game objects`

If there is no way around this, can anyone suggest other methods of parallel/distributed training of agents playing openspiel games?

Thank you.

**Comment by lanctot** [comment]
Hmmm... yeah I guess the C++ wrapped objects are not serializeable by default through pybind11. 

I would be very surprised if it's not possible-- we probably just have to add a few methods. The nice thing is that we already have game and state serialization supported in C++ so I suspect we just have to add something to get pickle support.

I will look into it and report back when I know more.

**Comment by lanctot** [comment]
Yep as I suspected: https://pybind11.readthedocs.io/en/stable/advanced/classes.html#pickling-support

Feel free to look into adding support for this. Otherwise, I will take a look at some point in the next few weeks.

**Comment by lanctot** [comment]
Turns out it will be a bit of a big change but I think it's an important one to make. So I will look into it and update the thread when we have some news.

**Comment by lanctot** [comment]
Alright I managed to get pickle working on games and states (added a test to games_sim_test.py). It will be pushed to github on the next update (Thursday). Please leave the issue open, and the commit on the update will automatically close it. Thanks for catching this!

**Comment by tcfuji** [comment]
Thank you!
