### ISSUE TITLE
Do we need also to store data from RL policy in the RL buffer in NFSP?

### ISSUE THREAD

**Issue by rezunli96** [deepmind/open_spiel#886]
Hello, one minor question about the current implementation of NFSP. According to the [original paper](https://arxiv.org/pdf/1603.01121.pdf), data generated by either SL or RL policy are all stored in M_{RL} for learning RL best response. However according to the current implementation:

https://github.com/deepmind/open_spiel/blob/4924f3de48bf88421259eddc1454f7a1f37d0dc8/open_spiel/python/algorithms/nfsp.py#L188-L203

It stores data in M_{RL} only when it is the SL network is acting. Is it because DQN is an off-policy algorithm so there is no difference here...?

**Comment by lanctot** [comment]
Hi @rezunli96,

The transitions are always stored in the RL buffer, but in one case it happens within the DQN agent's step function (line 189).

**Comment by rezunli96** [comment]
I see, thanks!
