### ISSUE TITLE
Convolutional networks

### ISSUE THREAD

**Issue by jamesdfrost** [deepmind/open_spiel#89]
I'm playing around with a basic DQN working with backgammon, and having got this working with a FF network, would like to try this using a convolutional network instead. So far I've:

- created a copy of the dqn.py algorithm called dqn_conv.py, which implements a simple conv network using Sonnet
- created a version of breakthrough_dqn.py file, which points at backgammon instead, and the above dqn_conv algorithm instead of dqn

this currently fails (which I'd expect it to) as the backgammon state is output as (None, 198) of rank 2 which doesn't match the input I need for the conv net.

I'm presuming that I need to modify BackgammonState::InformationStateAsNormalizedVector in backgammon.cc to output the right tensor, but any advice on doing this in the right way would be appreciated. 

I'm currently thinking I should add a game option which defines which output format the game returns, from the current one (default), perhaps a 1D conv format (as backgammon is essentially a 1D game) and a 2D conv format.

Does this make sense, and any issues with doing this?

**Comment by lanctot** [comment]
Hi @jamesdfrost , ah yes, good point.

 If you take a look at the formats of the breakthrough and tic_tac_toe `InformationStateAsNormalizedVector` (or `ObservationAsNormalizedVector`), they are flattened in a way that be reshaped to the appropriate size in numpy (3x3x3 for Tic-Tac-Toe, 3x8x8 for Breakthrough). 

I had convnets working a long time ago using numpy.reshape but that code did not make it into OpenSpiel, and it is is gone now. But you're on the right track -- you basically need to reformat how the data is stored (by writing out channel/plane one after the other, each in row-major order). But it has not been tested for quite some time.

It would be great to have an example of running DQN or A2C self-play on, e.g. Breakthrough or Connect Four, that people could use as a reference... maybe you can start by trying that?

**Comment by jamesdfrost** [comment]
I'm happy to start with either Breakthrough or Connect4 if you think they are better general examples - I'll have a look at Connect4 first.

**Comment by jblespiau** [comment]
If I remember correctly, it can also be done with tf.reshape (providing the tensor of InformationStateAsNormalizedVector() and the shape as InformationStateAsNormalizedVectorShape().

**Comment by jamesdfrost** [comment]
@jblespiau - thanks for that tip, that helped me get this over the line. PR now submitted for a simple ConvNet example using Connect_Four.

One issue I had was I tried to stick to Sonnet for defining the network - as far as I can tell you can only have 2 layer Conv2d networks (https://sonnet.readthedocs.io/en/latest/api.html#conv2d), certainly couldn't get it to work with 1 or 3 layers.

The other issue as far as I can see with Sonnet is it doesn't currently support running on PC - would there be any objections to using Keras to define networks in future?

**Comment by jamesdfrost** [comment]
One other thought I had on this, is you may have games with additional information being passed as well as the board information. For example in backgammon you might have the board position, along with the current match score for P1 / P2, and whether the position is the first move in a double. This wouldn't then map directly to a 2D format.

e.g. the current backgammon board state is encoded in 4 * kNumPoints * kNumPlayers (kBoardEncodingSize) with an additional 3 * kNumPlayers making up kStateEncodingSize.

In this case I'd suggest that within the DQN_Conv example the board state is split into a 2D convolutional vector, with any additional information (if any) values being split into a separate 1D vector. The first part would feed into the convolutional network, whilst the second part would feed in after the flatten operation.

Will aim to update the example to take this into account.
