### ISSUE TITLE
Cmake version requirements

### ISSUE THREAD

**Issue by BedirT** [deepmind/open_spiel#895]
I get this error with CMake 3.16.3

> CMake 3.17 or higher is required.  You are running version 3.16.3

In the installation guide, it still says 3.12

https://github.com/deepmind/open_spiel/blob/ae9371a1c92a6bfb2312e8315882bfe7d3e69a1a/docs/install.md?plain=1#L28

**Comment by lanctot** [comment]
Ah yes that was updated a while ago and we forgot to update the docs. In fact I recently skimmed through our documentation and there's several things out-of-date or inaccurate. We'll fix it in the coming weeks before the next release, and I'll be sure to include this too. Thanks!
