### ISSUE TITLE
Why do ACPC and Hanabi env variables default to ON?

### ISSUE THREAD

**Issue by VitamintK** [deepmind/open_spiel#901]
https://github.com/deepmind/open_spiel/blob/master/setup.py#L86

On a fresh computer, `$OPEN_SPIEL_BUILD_WITH_ACPC` and `$OPEN_SPIEL_BUILD_WITH_HANABI` default to "ON" which means that if not manually turned to "OFF", the installation errors.

Just wondering if they should both default to "OFF" to make the initial installation experience smoother?

**Comment by lanctot** [comment]
Hmm, that's because we use the setup script mostly to test and distribute the wheels. I did not think people would use setup.py to build OpenSpiel, but I guess it should be an option. I will look into this in the coming weeks.

**Comment by VitamintK** [comment]
Yeah, I install by doing `pip install -e .` as mentioned in `install.md`, step 4.

**Comment by lanctot** [comment]
They are now removed: https://github.com/deepmind/open_spiel/commit/b847dc0c34ba6e62d2720411d973914ee88294c8
