### ISSUE TITLE
Train an AlphaZero Agent on Nim game

### ISSUE THREAD

**Issue by sagebei** [deepmind/open_spiel#906]
Hi,

As the Nim game and AlphaZero algorithms are implemented in the OpenSpiel, I wonder if it is possible to train an AlphaZero agent on Nim game using the library. Is there an instruction page on how to do it?

**Comment by lanctot** [comment]
Hi @sagebei , yes the best place to start is here: https://github.com/deepmind/open_spiel/blob/master/docs/alpha_zero.md.

**Comment by sagebei** [comment]
Thank you!
