### ISSUE TITLE
error installing on windows

### ISSUE THREAD

**Issue by 87a** [deepmind/open_spiel#908]
I'm installing open_spiel on windows using vs2019, and it gave me errors.

Cannot open include file: 'pybind11_abseil/absl_casters.h': No such file or directory	

I guess it's due to pybind11_abseil is not installed.

**Comment by lanctot** [comment]
Hi @87a , yes actually there are some lines missing from the documentation that will be added in the next github sync (Monday). This should be included in the set of commands run when installing dependencies:

```
git clone -b 'master' https://github.com/pybind/pybind11_abseil.git open_spiel\pybind11_abseil
cd open_spiel\pybind11_abseil
git checkout '73992b5'
cd ..\..
```

Can you try it and let me know if it works?

**Comment by 87a** [comment]
thanks, it works.

**Comment by lanctot** [comment]
Documentation has now been updated in: https://github.com/deepmind/open_spiel/commit/7a1a2ee9b54006ab981770cbf3c03e36538ae7c6

Thanks for catching this and letting us know!
