### ISSUE TITLE
How to use a specific game state in C++?

### ISSUE THREAD

**Issue by 87a** [deepmind/open_spiel#909]
In C++, game and state can be created by
`std::string game_name = "bridge";
open_spiel::GameParameters params;
std::shared_ptr<const open_spiel::Game> game = open_spiel::LoadGame(game_name, params);
std::unique_ptr<open_spiel::State> state = game->NewInitialState();`

But the state only has methods which was written in spiel.h class State, How do I create a bridge state which has special methods for bridge game, like CurrentPhase()?

I've tried like this
`open_spiel::bridge::BridgeGame bridge_game = open_spiel::bridge::BridgeGame(params);
open_spiel::bridge::BridgeState bridge_state = open_spiel::bridge::BridgeState(game, false, false, false);`

But the bridge_state cannot give observation_tensor,it needs 
`Player player, absl::Span<float> values`
However the state can correctly work with ObservationTensor().
Are there any examples to show how to use BridgeGame and BridgeState?

**Comment by lanctot** [comment]
Hi @87a,

You must still use the `LoadGame` method and then down cast it to the specific state:

```
std::shared_ptr<const Game> game = LoadGame("bridge");
std::unique_ptr<State> state = game->NewInitialState();                        // generic state
BridgeState* bridge_state = down_cast<BridgeState*>(state.get());     // specific state
```

**Comment by lanctot** [comment]
No problem!
