### ISSUE TITLE
Incorrect docstring in policy_gradient.py

### ISSUE THREAD

**Issue by maayanorner** [deepmind/open_spiel#912]
https://github.com/deepmind/open_spiel/blob/f4ae28033cc1f92ca4cc9f8bc87477ba9c8c4237/open_spiel/python/algorithms/policy_gradient.py

Hi,
The docstring states the critic learning rate is 0.001, but it really defaults to 0.01.
It has the same issue in PPO, etc., I guess it's related to some copy-pasting or something similar :)

Thanks

**Comment by lanctot** [comment]
Thanks, good find! Can you submit a PR to fix the instances you found?

**Comment by maayanorner** [comment]
Sure,
I will work on it as soon as I can.

**Comment by Warlord-K** [comment]
@lanctot I have made the appropriate changes and made a PR for that, Please Merge it if this is correct, otherwise let me know if any modifications need to be made.

**Comment by lanctot** [comment]
Perfect thanks. Should be merged on Monday.
