### ISSUE TITLE
non-marginal strategy selectors in psro_v2

### ISSUE THREAD

**Issue by rezunli96** [deepmind/open_spiel#922]
Hello. In the current implementation of psro_v2, right before it is going to do best response, it will first select a subset of strategies from the current strategy pool and then decided how to do BR using these selected strategies:
https://github.com/deepmind/open_spiel/blob/0e0ae2f1827f24dafe82372d1bf4ea1729cb9566/open_spiel/python/algorithms/psro_v2/psro_v2.py#L293-L313

However here is one thing that is unclear to me. When we are considering non-marginal/joint strategy, according to line 310-313 it seems that currently_used_policies should be a list of joint strategies, while current_indexes should be a "num_player"-sized list each recording a list of policy indexes for each player. This design looks strange to me. 

And I doubled checked in psro_v2/strategy_selector.py, there were non-marginal selector implemented. For example,
https://github.com/deepmind/open_spiel/blob/0e0ae2f1827f24dafe82372d1bf4ea1729cb9566/open_spiel/python/algorithms/psro_v2/strategy_selectors.py#L356-L376

However the interface is not consistent with line 293 in psro_v2.py. Does that mean we need to write a customized strategy selector based on these? If so, is there a easy way we get used_indexes? Thanks.

**Comment by lanctot** [comment]
@PaulFMMuller can you take a look?
