### ISSUE TITLE
tf.Session problems while training two RL agents

### ISSUE THREAD

**Issue by tcfuji** [deepmind/open_spiel#93]
Hi,

I'm doing an experiment that involves training a slightly modified version of `open_spiel/python/algorithms/dqn.py` from scratch against an unmodified trained version of `open_spiel/python/algorithms/dqn.py`. I'm not adept at Tensorflow so I guessed that I would need two different tf.Sessions (one for each agent) so that the untrained agent does not have the same weights as the trained agent. To restore the trained agent, I used 
```
saver= tf.train.Saver()
saver.restore(sess_trained_agent, tf.train.latest_checkpoint('./tmp'))
```

The rest follows the same logic as `open_spiel/python/examples/breakthrough.py`

However, I get a list of errors such as the following:
```
Traceback (most recent call last):
W1014 10:33:49.109382 4537161152 deprecation.py:323] From ~/anaconda3/envs/openspiel/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.
  File "~/anaconda3/envs/openspiel/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1356, in _do_call
    return fn(*args)
  File "~/anaconda3/envs/openspiel/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1341, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "~/anaconda3/envs/openspiel/lib/python3.7/site-packages/tensorflow/python/client/session.py", line 1429, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.FailedPreconditionError: Attempting to use uninitialized value mlp_2/linear_4/b
	 [[{{node mlp_2/linear_4/b/read}}]]
```

Any assistance on having an untrained agent train against a trained agent would be appreciated.

**Comment by jamesdfrost** [comment]
@tcfuji - I'm still learning this framework, and still trying to get my head around most of it, but have been playing a bit with the breakthrough code. It already has the concept of having two different agents which with a little modification can be defined separately - just change the following code:
`
    agents = [
        dqn.DQN(
            session=sess,
            player_id=idx,
            state_representation_size=info_state_size,
            num_actions=num_actions,
            hidden_layers_sizes=hidden_layers_sizes,
            replay_buffer_capacity=FLAGS.replay_buffer_capacity,
            batch_size=FLAGS.batch_size) for idx in range(num_players)
    ]
`

with the following:

`
    agents = [
        dqn.DQN(
            session=sess,
            player_id=0,
            state_representation_size=info_state_size,
            num_actions=num_actions,
            hidden_layers_sizes=hidden_layers_sizes,
            replay_buffer_capacity=FLAGS.replay_buffer_capacity,
            batch_size=FLAGS.batch_size) 
        ,
        dqn2.DQN(
            session=sess,
            player_id=1,
            state_representation_size=info_state_size,
            num_actions=num_actions,
            hidden_layers_sizes=hidden_layers_sizes,
            replay_buffer_capacity=FLAGS.replay_buffer_capacity,
            batch_size=FLAGS.batch_size) 
    ]
`

you need to then copy dqn.py as dqn2.py and make any modifications (and don't forget to include it at the top of the breakthrough file)

It should be possible to load the weights into one network separately than the other, although to be honest I've not worked out how to save / load trained models yet!

**Comment by fzvinicius** [comment]
Hi @tcfuji, 

@jamesdfrost's suggestion is the way to go here. Note that a single TF session hold all weights and variables. In your case, it might be easier to pass `var_list` to `tf.train.Saver`, providing only the dqn2 variables.

Note that you may need to run tf.global_variables_initializer op in the session before restoring the checkpoint.

Perhaps the following links will help you: 
- https://stackoverflow.com/questions/41621071/restore-subset-of-variables-in-tensorflow
- https://stackoverflow.com/questions/33759623/tensorflow-how-to-save-restore-a-model
