### ISSUE TITLE
Can I use open_spiel as a shared library on windows?

### ISSUE THREAD

**Issue by 87a** [deepmind/open_spiel#933]
[library.md](https://github.com/deepmind/open_spiel/blob/master/docs/library.md) only provides this on linux and macos, so are there any methods to do this on windows? or it only supports linux and macos?

**Comment by lanctot** [comment]
We've never tested it, but I would be surprised if it didn't work. 

You just have to have the `BUILD_SHARED_LIB` environment variable set to `ON`, or you can manually set it on line 335 of CMakeLists.txt here: https://github.com/deepmind/open_spiel/blob/7f9a27cbca89f412802fb0d5283de8acaa19c4e2/open_spiel/CMakeLists.txt#L335

```
set (BUILD_SHARED_LIB ON)
```

On Windows, the extension would be `.dll`, but everything else should be the same. Let us know if it works!

**Comment by 87a** [comment]
Thanks, by doing it I can see `open_spiel.lib` and `open_spiel.dll` in the `out/build/x64-Debug` folder, and can you provide an example of how to use it in cmakelist.txt?

**Comment by lanctot** [comment]
Once you have OpenSpiel as a shared library, you probably can set it up via its own (separate) project in Visual Studio. You'd need to setup the project to link against that library and set the include paths.  That is probably the easiest way to do it. See [here](https://stackoverflow.com/questions/7845886/linking-dll-in-visual-studio) and [here](https://stackoverflow.com/questions/2676417/how-do-include-paths-work-in-visual-studio).

You can do it as a separate CMake project too, if you want (see this tutorial for basic usage: https://cmake.org/cmake/help/latest/guide/tutorial/index.html), but the main CMakeLists.txt it would look something like this:

```
cmake_minimum_required(VERSION 3.10)

# set the project name
project(87a_project)

# This has to point to the root of OpenSpiel so you can using #include in the same way as the OpenSpiel headers
include_directories(open_spiel)

# This tells the compiler where to find the library
link_directories(out/build/x64-Debug)

# This adds the link command when building
link_libraries(open_spiel)

# add the executable
add_executable(87a_main 87a_main.cc)
```

Hope this helps!
