### ISSUE TITLE
Possible contribution: LOLA 

### ISSUE THREAD

**Issue by axelbr** [deepmind/open_spiel#934]
Hi, 
I am planning to contribute a JAX implementation of [Learning with Opponent-Learning Awareness" (Foerster et al.)](https://arxiv.org/abs/1709.04326) if no one currently works on it and if it is still appreciated (I noticed it was mentioned in your call for contributions list).

I just wanted to check before starting to implement it :slightly_smiling_face:

**Comment by lanctot** [comment]
Nice!! Absolutely welcome, would love to see it. 

Nobody is currently working on it to the best of our knowledge.

**Comment by lanctot** [comment]
@axelbr this is very cool!!

Yes, please do make a PR and we can have more discussion there. In the post, please also include these graphs as well. Thanks.. this will make a wonderful addition to OpenSpiel!

**Comment by lanctot** [comment]
Closing this thread as the PR is mow submitted. Thanks!
