### ISSUE TITLE
Shared library in Windows?

### ISSUE THREAD

**Issue by roblim1** [deepmind/open_spiel#942]
Referencing #933, I am trying to build open_spiel as a shared library in Windows in MS Visual Studio 2019, but get the following error:

`Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2019	unresolved external symbol "void __cdecl open_spiel::LogUsage(void)" (?LogUsage@open_spiel@@YAXXZ) referenced in function "class std::shared_ptr<class open_spiel::Game const > __cdecl open_spiel::LoadGame(class std::map<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> >,class open_spiel::GameParameter,struct std::less<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > >,class std::allocator<struct std::pair<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const ,class open_spiel::GameParameter> > >)" (?LoadGame@open_spiel@@YA?AV?$shared_ptr@$$CBVGame@open_spiel@@@std@@V?$map@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VGameParameter@open_spiel@@U?$less@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@2@V?$allocator@U?$pair@$$CBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@VGameParameter@open_spiel@@@std@@@2@@3@@Z)	C:\Users\user\apps\spiel_win\open_spiel\open_spiel\out\build\x64-Debug\open_spiel	C:\Users\user\apps\spiel_win\open_spiel\open_spiel\out\build\x64-Debug\spiel.cc.obj	1	
`

The build produces an open_spiel.dll file, but when I add that file as a shared library in my project, I get this error:

`Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK1107	invalid or corrupt file: cannot read at 0x370	some_project	C:\some_project\dependencies\open_spiel\lib\open_spiel.dll	1`

I can build open_spiel without the shared library option without any problems.  

Any suggestions on how to get the shared library to build correctly?

**Comment by roblim1** [comment]
Looks like I am able to build a shared library in Windows properly, per Issue #825.

**Comment by lanctot** [comment]
@roblim1 ok but did you have to move utils/usage_logging.h and .cc to the core?

**Comment by roblim1** [comment]
@lanctot, yes exactly what I did.

**Comment by lanctot** [comment]
Ok this has bitten us a few times, can I ask you to submit a PR with your changes?

**Comment by roblim1** [comment]
Sure, I can do that!
