### ISSUE TITLE
Optimal pricing policy in the game between the entrepreneur and the environment in a B2B setting

### ISSUE THREAD

**Issue by PrashantPD** [deepmind/open_spiel#944]
Hi,

I find it interesting to model prices from the point of view of marketing in an entrepreneurial setting. This is relevant because the product is sold on the basis of the entrepreneur's characteristics too along with the product and consumer economics. 

So, the environment comprises of consumers that adopt the new product (Bass, 1969 (https://pdodds.w3.uvm.edu/files/papers/others/everything/bass1969a.pdf)). Adoption is driven by their innovativeness which is relative in that an individual has either more or less of it than others in a social system (Rogers & Shoemaker, 1971).

For B2B products, early adopters are interested in adopting the product early and using it in their supply chain. Innovators are interested in trying the product and take risks and can also buy products that eventually do not succeed in the marketplace. And then there is a segment of customers that are price conscious.

Do you want me to take a deeper look into this game between the entrepreneur and the environment. This may be important to understand from the technology point of view as IP creation may be involved and the game may have serious cascading implications for the entire supply chain.

**Comment by lanctot** [comment]
Hi @PrashantPD, my first reaction is I'm not sure how OpenSpiel would help with your research goals you outline here.

Can you help me understand? Is this game formalizable as an extensive-form game? If so, what are the states, observations, actions, rewards/utilities?  Then, are there algorithms you'd like to run on the game from the OpenSpiel suite, or you'd implement your own?

**Comment by PrashantPD** [comment]
> Hi @PrashantPD, my first reaction is I'm not sure how OpenSpiel would help with your research goals you outline here.
> 
> Can you help me understand? Is this game formalizable as an extensive-form game? If so, what are the states, observations, actions, rewards/utilities? (If there are any examples from game theory texts or otherwise, can you point to that could help.)
> 
> Then, are there algorithms you'd like to run on the game from the OpenSpiel suite, or you'd implement your own?

Hi @lanctot, Absolutely - on it - will provide a formal extensive-form structure by Sunday. I would love to implement my own algorithm from the marketing literature. So parameters like for instance organizational scale may determine whether the consumer can still make the annual interest payments on its debt after they have bought the entrepreneur's product.

**Comment by PrashantPD** [comment]
Hi @lanctot, The entrepreneur may be more market leaning whereas the late adopter and the laggard consumer in a B2B setting is more product leaning (Bass, 1969-https://pdodds.w3.uvm.edu/files/papers/others/everything/bass1969a.pdf). The framework agrees with the product-market fit (Davidsson, 2021-https://eprints.qut.edu.au/210484/1/84641557.pdf) literature. But in so far as there is no such ethereal concept of a perfect product-market fit I think it is important to understand what are the possible determinants of such a fit.

States: There will be two states for both the entrepreneur as well as the consumer - either product or market driven. The presence of a syndicate (https://corporatefinanceinstitute.com/resources/knowledge/deals/syndicate/) or the absence of it for the consumer indicates whether the consumer is product driven as he wants to sell it or goes by the market: is market driven. The entrepreneur in the absence of a consumer syndicate is market driven whereas in the presence of it is product driven.

Observation and Action: There will be an observation on the syndicate price in the presence of a syndicate and the wholesaler price and comparison of which one is lower. The wholesaler may say there is no general downward pressure on the price but a segment of customer has refused to buy in which case the entrepreneur doesn't sell to the syndicate because the entrepreneur has the wholesaler channel. In the presence of a downward pressure on the price as well as the presence of a consumer syndicate the entrepreneur sells to the syndicate. There is an action available to the consumer on whether to form a syndicate or not in order to drive the price down. This is done primarily because the consumer faces prohibitive costs and is not able to sell the product and not because they want to compete with the entrepreneur's wholesaler.

Reward: The reward is the profit that both the entrepreneur and the consumer make as a result of the price of the entrepreneur's product.

This will purely be my research based on the Bass (1969) diffusion model wherein only the late adopters and the laggards form the syndicate as they are price conscious and the innovators and the early adopters are not and are known to assume risks of product adoption. I would like to implement the algorithm in C++.

**Comment by PrashantPD** [comment]
Hi @lanctot, In a game without equilibrium what the player desires is a competitive advantage. In its absence the game basically is a pursuit of this elusive/evasive reward. What each player in the game has is agency in setting up his states in the game. Since the previous states lead to a game without equilibrium the player has to devise a state/set of states which will lead to an equilibrium in his favor.   

States: The company that is more open to receiving outside counseling has multiple bandit arms to sample out of that is the company has multiple states and the company that takes decisions in-house sets the distribution of its states.

Observation and Action: The observation by the company that receives a recommendation in the game is the reward in each round of the game. As part of the sampling that bandit arm is selected after a certain rounds of sampling whose mean is maximum amongst those that are as large as plausibly possible (https://tor-lattimore.com/downloads/book/book.pdf). The company that takes decisions in-house observes the arm that is chosen by the competitor after certain rounds of sampling and selects the probability distribution of the states.

Rewards: The reward for both the companies is the profit that they receive.

But this game of pursuit-evasion can be endless especially when there are economies of scale and scope involved. So for instance, if the company that receives a recommendation loses its competitive advantage the company adds an additional arm whereas the company that selects the distribution of its states can add an additional distribution when it loses its competitive advantage.

**Comment by lanctot** [comment]
I am sorry @PrashantPD, I never got around to looking back at this. Was OpenSpiel helpful for what you were hoping to do?
