### ISSUE TITLE
Multistep simultaneous move game and visualizatoin

### ISSUE THREAD

**Issue by chiraguic** [deepmind/open_spiel#957]
I am looking for a zero-sum or fully cooperative multistep simultaneous move games (SMG) that are used as standard benchmarks for evaluation (especially where I can control the size of game)? I am also looking for a way to use and visualize SMG as imperfect information extensive form game. I am assuming I will have to use `convert_to_turn_based` method to convert the SMG to imperfect information extensive form game but I am not sure how to visualize it?

**Comment by lanctot** [comment]
Hi @chiraguic, 

There's `markov_soccer` and `coop_box_pushing` that have been used in a few papers (maybe the latter more than the former). There's also `laser_tag` which has been used more recently. There are also `coin_game` and `pathfinding` but I think they are general-sum. 

We have some basic visualization tools for the EFGs in `python/visualizations` (see the OpenSpiel paper for what the resulting game looks like) but unless you make them very small it may not not look very user-friendly. You may want to check out [SpielViz](https://github.com/michalsustr/spielviz) which has visualized some of the games too.

Lastly you have the option of exporting any game to .efg format which can then be loaded by Gambit / Game Theory Explorer.

It would be nice to have better visualization capabilities, so if you work on anything that's worth contributing, it would be very welcome :) 

Hope this helps!

**Comment by lanctot** [comment]
Closing this for now but please re-open if you'd like to follow-up.
