### ISSUE TITLE
Uninterpretable bug with legal_actions check

### ISSUE THREAD

**Issue by jjshoots** [deepmind/open_spiel#958]
Hi there, I'm trying to use Openspiel in a project where all games share a common API with PettingZoo, and due to the architecture of the system, the stepping of  the environment looks something like so (modified from the [first example code](https://openspiel.readthedocs.io/en/latest/concepts.html#playing-a-trajectory)):

P/S: This bug only occurs on `backgammon` AFAICT.

```python
import random
import pyspiel
import numpy as np

game = pyspiel.load_game("backgammon")
state = game.new_initial_state()
while not state.is_terminal():
    legal_actions = state.legal_actions()

    if state.is_chance_node():
        # Sample a chance event outcome.
        outcomes_with_probs = state.chance_outcomes()
        action_list, prob_list = zip(*outcomes_with_probs)
        action = np.random.choice(action_list, p=prob_list)
        state.apply_action(action)

        for i in range(game.num_players()):
            print("----------")
            print(i)
            print(state.legal_actions(i)) # FAILS HERE

    if not state.is_chance_node():
        # The algorithm can pick an action based on an observation (fully observable
        # games) or an information state (information available for that player)
        # We arbitrarily select the first available action as an example.
        action = legal_actions[0]
        state.apply_action(action)

        for i in range(game.num_players()):
            print("----------")
            print(i)
            print(state.legal_actions(i))

```

For some reason, when trying to get legal_actions after executing any and all possible chance nodes, the following stack trace is raised:

```
OpenSpiel exception: /project/open_spiel/games/backgammon.cc:848 board_[player][i] >=
board_[player][i] = -2, 0 = 0
Traceback (most recent call last):
  File "/home/jet/Sandboxes/Shimmy/src/bugfinder.py", line 20, in <module>
    print(state.legal_actions(i))
pyspiel.SpielError: /project/open_spiel/games/backgammon.cc:848 board_[player][i] >= 0
board_[player][i] = -2, 0 = 0
```

Following this trace leads me to this section of the code in `/open_spiel/open_spiel/games/backgammon.cc`:

```c
int BackgammonState::CountTotalCheckers(int player) const {
  int total = 0;
  for (int i = 0; i < 24; ++i) {
    SPIEL_CHECK_GE(board_[player][i], 0); // THIS LINE
    total += board_[player][i];
  }
  SPIEL_CHECK_GE(bar_[player], 0);
  total += bar_[player];
  SPIEL_CHECK_GE(scores_[player], 0);
  total += scores_[player];
  return total;
}
```

I have further tried browsing around the code to see what that `SPIEL_CHECK_GE` actually does, but cannot seem to find its definition.

So my question is, what is that error and why is it not possible to get legal actions after executing chance nodes?

**Comment by lanctot** [comment]
Could be terminal, maybe? Hard to tell without seeing the state. 

Chances are PettingZoo and OpenSpiel are implementing the game differently. 

Can you add a try/catch around that line that fails, and print the output of `pyspiel.serialize_game_and_state(game, state)` ? Then we can try to reload the state to inspect it.

**Comment by lanctot** [comment]
(Might actually be easier to just print the state and the action you're taking each time.)

```
print(state)
print(f"Taking action {state.action_to_string(player, action)}")
```

**Comment by lanctot** [comment]
Wait:

```
        for i in range(game.num_players()):
            print("----------")
            print(i)
            print(state.legal_actions(i)) # FAILS HERE
```

You're calling legal actions on all the players... why? That might be your answer. Backgammon is turn-based, there's only one player playing at any given turn (including chance).

**Comment by lanctot** [comment]
Ok I've reproduced it in colab. Hmm... yeah.. something is fishy here; definitely seems like a bug (oddly our simulations tests are not catching it).

**Comment by jjshoots** [comment]
Thanks for the quick reply! The repo where we are doing the work is [here](https://github.com/Farama-Foundation/Shimmy/pull/3), I've confirmed that this bug only occurs on backgammon.

**Comment by lanctot** [comment]
Ok yeah I see the problem: it appears to be with the script you have above, not in the game (which explains why our simulation tests are not running into it).  

It is taking illegal moves and then getting the state into a bad state. Excerpt with fix below:

```python
    #  .
    #  .
    #  . 
    if not state.is_chance_node():
        # The algorithm can pick an action based on an observation (fully observable
        # games) or an information state (information available for that player)
        # We arbitrarily select the first available action as an example.
        # action = legal_actions[0]   # PROBLEM WAS HERE -- legal_actions list has not been updated since the last state.apply_action, so the first element in this list can be illegal
        # Fix is to comment the line above, and replace it with:
        action =  state.legal_actions()[0]
        state.apply_action(action)

    # .
    # .
    # .
```

**Comment by lanctot** [comment]
BTW we added a flag to the RL environment to check for legality of the moves submitted by the agent: https://github.com/deepmind/open_spiel/blob/97a199a3276ef35b932f39dc01786855aa36545f/open_spiel/python/rl_environment.py#L152. 

I would recommend enabling this while debugging as it will catch some problems without the mysterious opaque crash in the game state at some other point. (We disable it by default for performance reasons.)

**Comment by jjshoots** [comment]
Thanks for the help! Just updating here that the solution above worked. :)
