### ISSUE TITLE
How to get observations from states?

### ISSUE THREAD

**Issue by jjshoots** [deepmind/open_spiel#959]
According to my testing thus far, it seems that not all games have the same method of accessing player observations, and there are four separate ways to get the current game state:

```python
state.observation_state_string(Optional[player])
state.observation_state_tensor(Optional[player])
state.information_state_string(Optional[player])
state.information_state_tensor(Optional[player])
```

Without having to do a bunch of try/excepts, is there a place that documents which games have which methods implemented, or is there a possibility that I'm not seeing a section of documentation that pertains to this?

Just some code example of what I'm doing to find out what's implemented:

```python
import pyspiel
import numpy as np

game = pyspiel.load_game("tarok")
state = game.new_initial_state()
while not state.is_terminal():

    while state.is_chance_node():
        outcomes_with_probs = state.chance_outcomes()
        action_list, prob_list = zip(*outcomes_with_probs)
        action = np.random.choice(action_list, p=prob_list)
        state.apply_action(action)

    legal_actions = state.legal_actions()
    action = legal_actions[0]
    state.apply_action(action)

    try:
        try:
            try:
                print(state.observation_string())
            except:
                print(state.observation_string(state.current_player()))
        except:
            try:
                print(state.observation_tensor())
            except:
                print(state.observation_tensor(state.current_player()))
    except:
        try:
            try:
                print(state.information_state_tensor())
            except:
                print(state.information_state_tensor(state.current_player()))
        except:
            try:
                raise Exception
                print(state.information_state_string())
            except:
                print(state.information_state_string(state.current_player()))
```

**Comment by lanctot** [comment]
Hi @jjshoots, 

Easiest thing is to just check the game type. Each game type object has two fields `provides_information_state_tensor` and `provides_observation_tensor`. 

Here's an example of how the RL environment does it:

https://github.com/deepmind/open_spiel/blob/97a199a3276ef35b932f39dc01786855aa36545f/open_spiel/python/rl_environment.py#L198

This is not a general rule, but roughly true: all perfect information games will have observation defined, all imperfect info games will have information state defined, but some have both defined (some have none defined, but they are rare).

**Comment by jjshoots** [comment]
Ah, gotcha, thank you!

**Comment by jjshoots** [comment]
Reopening this to hitchhike with an adjacent question, what about string-based observation/information states, is there a flag to check for that? AFAICT, not all games have tensor based observations and only have string-based, e.g. battleship.

**Comment by lanctot** [comment]
Yes there are similar properties for the string versions, see the GameType struct here:  https://github.com/deepmind/open_spiel/blob/97a199a3276ef35b932f39dc01786855aa36545f/open_spiel/spiel.h#L120

The strings are used mostly for tabular methods, e.g. as unique identifiers for keys that index into a table, or for optimization methods (e.g. CFR, sequence-form linear programming). 

Which ones are included per game depends on who implemented them and how they've being used. Battleship was a contribution and the contributor didn't implement the tensor functions because they did not use the game for RL. We recently added the infoset tensor function to it (because it's an imperfect information game), but not the observation one.
