### ISSUE TITLE
A question about R-NaD

### ISSUE THREAD

**Issue by TadaoYamaoka** [deepmind/open_spiel#965]
state.returns() at line 955 of rnad.py is always [0, 0] because the terminal state is changed in the following code.
```
    if state.is_terminal():
      state = self._ex_state
```
is this intentional?

**Comment by lanctot** [comment]
@perolat can you take a look?

**Comment by lanctot** [comment]
Thanks, this indeed was a bug introduced by a recent refactor. We'll fix it and merge the fix in the next day or two.
