### ISSUE TITLE
Choice of entropy step R-NAD

### ISSUE THREAD

**Issue by spktrm** [deepmind/open_spiel#978]
How does the choice of entropy schedule influence how the algorithm progresses? Is there an ablation provided anywhere? Could the authors perhaps comment from their testing?

**Comment by lanctot** [comment]
@perolat @bartdevylder

**Comment by perolat** [comment]
Hi,

Thanks for the question!

Not for R-NaD but for a method that is very close. See :
https://arxiv.org/pdf/2002.08456.pdf

In short:
- If eta is small the algorithm can be unstable,
- If eta is high the algorithm is slow.

**Comment by spktrm** [comment]
Thanks for the response! I am not talking about eta, but rather the influence of delta m - the number of steps to update the networks that generate the regularisation policy.

**Comment by perolat** [comment]
Looks like I missed part of the question :)

The idea for delta m is to be long enough to get close enough to the next fixed point. Typically it tend to be short at the beginning of the training (to get rough and inexpensive approximations of the fixed point one should converge to at the end of stage m) and then longer (So those fixed points are of better "quality").

No ablation was provided and the choice made was empirically guided.

**Comment by spktrm** [comment]
Thank you for your response. The notion of the fixed point is kinda abstract imo. Are we close to the fixed point once loss approaches 0? Then would be a good time to update?

**Comment by spktrm** [comment]
Hypothetically, what would be expected if the entropy size was smaller e.g 50-100

**Comment by perolat** [comment]
Unfortunately I don't know any way to check how close to a fixed point we are. We usually use delta m that is large enough to be on the safe side.

If delta_m was too small 50-100 the algorithm could be unstable but there is no existing theory there to guide us in that regime. So not sure..
