### ISSUE TITLE
Question about how to run CFR on Matrix game

### ISSUE THREAD

**Issue by szrlee** [deepmind/open_spiel#98]
I noticed that there is a c++ API to transform normal form games to turn-based one.
But how to do it in python.
Is there an example to do it?
E.g. doing CFR on matrix game.

**Comment by lanctot** [comment]
Hi @szrlee, you need to load it as a turn-based game. You can use the python function `load_game_as_turn_based`, you can also just specify it via the name, here is an example:

https://github.com/deepmind/open_spiel/blob/b46c34cc94111fca1f6bb7b943e0200ca61c72ab/open_spiel/integration_tests/api_test.py#L46
