### ISSUE TITLE
Both C++ and Python implementation of games necessary for some algorithms?

### ISSUE THREAD

**Issue by regenbogenfrosch** [deepmind/open_spiel#981]
### Discussed in https://github.com/deepmind/open_spiel/discussions/975

<div type='discussions-op-text'>

<sup>Originally posted by **regenbogenfrosch** December 10, 2022</sup>
Hello all open_spiel developers

Thank you very much for releasing this wonderful project!

I am just new to RL and open_spiel in general and have some questions that might sound easy for you:
I am currently using open_spiel in my university work, and trying to understand RL for my project.
I have rewritten the "Tower Of Hanoi" problem as a k-general sum single player game in the C++ code part of open_spiel as described in the tutorial. And it works. Random plays run very well until the TerminalState is reached, at least for small problem sizes.
I also managed successfully to run the Q-Learning and SARSA learning algorithm (from one of the examples file adapted) and those algorithms also converge to the solution.

Now I want to test the "real" RL algorithms, as DQN, A2C and EVA. Unfortunately, I have found examples for using these algorithms only in the python directory of open_spiel.
Now, my silly question: does this mean, I have to rewrite my "myHanoi.cc" Code for my game completely new (and identical) in python (for example: myHanoi.py)? Or is it possible to use my written game and just load it from the C++ code directory somehow?
Sorry, for the silly sounding question, but I missed that somehow in the documentation.

Anyways, this is a cool framework, thanks again.

Best Regards
Frank
</div>

**Comment by jblespiau** [comment]
I answered there, closing this. Thanks for raising it again here.
