### ISSUE TITLE
Comments contradict the code logic - LegalActions vs. ChanceOutcomes

### ISSUE THREAD

**Issue by Henry-E** [deepmind/open_spiel#992]
Just checking if I'm correct in my interpretation of this
https://github.com/deepmind/open_spiel/blob/e75bdf114de32c2211edf36443703a6e8846a3cb/open_spiel/spiel.h#L263-L270
This comment above the `LegalActions()` function seems incorrect, since the `LegalActions(Player)` function checks for whether it's a chance node or not.
https://github.com/deepmind/open_spiel/blob/e75bdf114de32c2211edf36443703a6e8846a3cb/open_spiel/spiel.h#L255-L257
And instead it collects the actions from `ChanceOutcomes()` as would be sensible and much less effort for people implementing games (don't need to re-include the logic of ChanceOutcomes in LegalActions).
https://github.com/deepmind/open_spiel/blob/e75bdf114de32c2211edf36443703a6e8846a3cb/open_spiel/spiel.h#L622-L628

**Comment by lanctot** [comment]
Sorry, you will have to clarify because I don't understand. 

What is your precise question? Are to you saying that the `All games should implement this function` is misleading, since in games with chance events, you just end up implementing `ChanceOutcomes` for the chance events?

Can you elaborate and be more specific about what you're claiming is incorrect in the comment?

**Comment by lanctot** [comment]
> And instead it collects the actions from `ChanceOutcomes()` as would be sensible and much less effort for people implementing games (don't need to re-include the logic of ChanceOutcomes in LegalActions).

Exactly, this is what most (almost all) of the games with chance events do.

Maybe you can suggest a rewording of the comment to "correct" it (or at least help me understand)?

**Comment by lanctot** [comment]
Maybe this will help: not all calls to get the legal actions will be done via `LegalActions(Player player)`. It is often the case that `LegalActions()` is called directly.

**Comment by lanctot** [comment]
Here is an example: https://github.com/deepmind/open_spiel/blob/e75bdf114de32c2211edf36443703a6e8846a3cb/open_spiel/games/pig.cc#L207. 

Note the first few lines: the function checks if it's a chance node, if so, returns `LegalChanceOutcomes` which calls `ChanceOutcomes`.

**Comment by Henry-E** [comment]
Ok if this is the case: ` not all calls to get the legal actions will be done via LegalActions(Player player).` then i guess it's reasonable that you would have to return the list of chance outcomes. Just going by the header it seemed redundant to include the chance outcome logic in `LegalActions`. Manually returning `LegalChanceOutcomes()` from inside `LegalActions` seems like a nice shortcut though, I'll do that. I was looking at the Liar's dice example and had duplicate logic in `ChanceOutcomes` and `LegalActions`.

**Comment by lanctot** [comment]
>I was looking at the Liar's dice example and it had duplicate logic in `ChanceOutcomes` and `LegalActions`.

Oh that's bad -- I think it's leftover from when we changed the basic API years back (before the initial release). If you're so inclined, could you submit a PR to fix that?

**Comment by Henry-E** [comment]
Sure, done!
