### ISSUE TITLE
About state_space

### ISSUE THREAD

**Issue by masoumian** [deepmind/open_spiel#998]
Hi,
I wanted to use the sample_episode(self, policies, num_episodes) function separately with an arbitrary list of input policies, but I get an error when it wants to define state_policy = policies[player]**(state)** in sample_spisode(state, policies).
It's because the policies are not callable (and I believe it's true), but we use (state). So I'm confused with this calling and the state input of the policies.

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/31691417/213606895-2e67cba3-a304-4dc3-8d12-76ac1997d734.png">

I would be thankful if you can explain it so that I can modify my policy input.

Sorry if it's so in detail and many thanks for this valuable work.

**Comment by lanctot** [comment]
Tagging @PaulFMMuller as he is the author of that code. 

Is this the line you're referring to? https://github.com/deepmind/open_spiel/blob/453ab85f9dc94be8e2a3a01b12cf5821edfed141/open_spiel/python/algorithms/psro_v2/abstract_meta_trainer.py#L85

My guess is that those are policy objects described in [this file](https://github.com/deepmind/open_spiel/blob/master/open_spiel/python/policy.py), which means they'd be calling the function on line 145 of `policy.py`. 

In what form is your policy? Can it be wrapped into a python policy object? Why would your policies not be a function of the state?

**Comment by masoumian** [comment]
Thanks for your reply. It got resolved.
The file you mentioned helped me. Yes, I was using the python policy object but a simple mistake using the list of policies made me confused! Now it's okay.
Thanks again.
